# -*- coding: utf-8 -*-
# İlişki (es_sevgili) ve Bireysel Natal modları için Arap Noktaları ve Asteroit sözlükleri.
# engine.py arap_noktasi_hesapla/arap_noktasi_sinastri_analizi tarafından yüklenir.

ARAP_NOKTALARI_ILISKI = {
    "Şans Noktası":     {"nokta1": "Ay",     "nokta2": "Güneş",  "kisa": "SANS", "aciklama": "Kaderin size sunduğu doğal fırsat ve bereket kapısı"},
    "Ruh Noktası":      {"nokta1": "Güneş",  "nokta2": "Ay",     "kisa": "RUH",  "aciklama": "İçsel amacınız, manevi yolculuğunuz ve ruhsal rehberlik"},
    "Evlilik Noktası":  {"nokta1": "Venüs",  "nokta2": "Satürn", "kisa": "EVLİ", "aciklama": "Bağlılık, evlilik kaderi ve uzun vadeli ortaklık enerjisi"},
    "Aşk Noktası":      {"nokta1": "Venüs",  "nokta2": "Mars",   "kisa": "AŞK",  "aciklama": "Aşk diliniz, çekim gücünüz ve kalbinizin yönü"},
    "Tutku Noktası":    {"nokta1": "Mars",   "nokta2": "Venüs",  "kisa": "TUTK", "aciklama": "Arzu yoğunluğunuz, iç ateşiniz ve kaderinizi harekete geçiren güç"},
    "Para Noktası":     {"nokta1": "Merkür", "nokta2": "Güneş",  "kisa": "PARA", "aciklama": "Maddi kazanç, bolluk ve refahın size açıldığı kanal"},
}

ARAP_NOKTA_BURC_YORUMLARI = {
    ("Şans Noktası", "Koç"): "Şans enerjiniz cesur ve öncüdür; hayatın kapıları inisiyatif aldığınız anda açılır. Kader, sizi ilk adımı atmaya çağırır.",
    ("Şans Noktası", "Boğa"): "Şansınız sabır ve istikrarda gizlidir; en büyük fırsatlar somut, adım adım ilerleyen çalışmalarla gelir. Kader size kalıcı değerler sunar.",
    ("Şans Noktası", "İkizler"): "Şansınız iletişimde parlar; doğru kelimeyi söylediğiniz an kapılar açılır. Bilgi ve bağlantılar, kaderin size uzattığı anahtarlardır.",
    ("Şans Noktası", "Yengeç"): "Şansınız aile ve duygusal güvenlikte; sevdikleriniz ve yuvanız size beklenmedik fırsatlar getirir. Kader, kalbinizi takip ettiğinizde güler.",
    ("Şans Noktası", "Aslan"): "Şansınız yaratıcılık ve kendini ifadede; sahneye çıktığınız an kader sizi ödüllendirir. Cesaretiniz, bereketin kapısıdır.",
    ("Şans Noktası", "Başak"): "Şansınız detaylarda ve hizmettedir; titizliğiniz size görünmez fırsatlar kazandırır. Kader, düzeni sevenleri ödüllendirir.",
    ("Şans Noktası", "Terazi"): "Şansınız uyum ve ilişkilerde; denge kurduğunuzda hayat size gülümser. Doğru bağlantılar, kaderin size armağanıdır.",
    ("Şans Noktası", "Akrep"): "Şansınız dönüşümde saklıdır; krizlerden güçlenerek çıktığınızda kader size yeni kapılar açar. Derinlik, bereketin kaynağıdır.",
    ("Şans Noktası", "Yay"): "Şansınız ufukta ve keşifte; maceraya atıldığınızda beklenmedik kazanımlar sizi bulur. Kader, geniş düşünenleri sever.",
    ("Şans Noktası", "Oğlak"): "Şansınız disiplin ve uzun vadeli planda; sabırla yükseldiğinizde zirvede taçlanırsınız. Kader, emeğinize sadıktır.",
    ("Şans Noktası", "Kova"): "Şansınız özgünlükte; farklı düşündüğünüzde evren sizi ödüllendirir. Sıra dışı fikirleriniz, bereketin anahtarıdır.",
    ("Şans Noktası", "Balık"): "Şansınız sezgi ve maneviyatta; iç sesinize güvendiğinizde sihir gerçekleşir. Kader, inananların yanındadır.",

    ("Ruh Noktası", "Koç"): "Ruhunuzun arayışı bağımsızlıkta; kendi yolunuzu çizdikçe iç huzura kavuşursunuz. Ruhsal tekamülünüz cesaretle örülür.",
    ("Ruh Noktası", "Boğa"): "Ruhunuz toprak ve kalıcılıkla beslenir; kendinize değer verdikçe ruhsal olarak zenginleşirsiniz. Tekamülünüz sükunetle akar.",
    ("Ruh Noktası", "İkizler"): "Ruhunuz bilgi ve iletişimle beslenir; öğrenme ve paylaşma, ruhsal yolculuğunuzun taşlarıdır. Zihniniz, ruhunuzun aynasıdır.",
    ("Ruh Noktası", "Yengeç"): "Ruhunuz duygusal derinlik ve aidiyetle yoğrulur; kökleriniz ve aileniz ruhsal besin kaynağınızdır. İç dünyanız, kutsal sığınağınızdır.",
    ("Ruh Noktası", "Aslan"): "Ruhunuz yaratıcılık ve ışımayla yükselir; kendi ışığınızı gördükçe ruhsal olarak parlaklaşırsınız. Kalbinizin cömertliği, ruhunuzun imzasıdır.",
    ("Ruh Noktası", "Başak"): "Ruhunuz hizmet ve arınmayla beslenir; başkalarına faydalı oldukça ruhunuz dinginleşir. Mükemmellik arayışınız, ruhsal disiplininizdir.",
    ("Ruh Noktası", "Terazi"): "Ruhunuz denge ve uyumla beslenir; iç barışı buldukça ruhsal olarak olgunlaşırsınız. Güzellik ve adalet, ruhunuzun dilidir.",
    ("Ruh Noktası", "Akrep"): "Ruhunuz dönüşümle yoğrulur; karanlıklarınızla yüzleştikçe ruhsal olarak dirilirsiniz. Derin arınma, tekamülünüzün merkezidir.",
    ("Ruh Noktası", "Yay"): "Ruhunuz özgürlük ve bilgelikle yükselir; ufkunuzu genişlettikçe ruhsal olarak büyürsünüz. Hakikat arayışı, ruhunuzun pusulasıdır.",
    ("Ruh Noktası", "Oğlak"): "Ruhunuz yapı ve sorumlulukla olgunlaşır; hayat derslerini sabırla öğrendikçe ruhsal otoriteniz güçlenir. Tekamülünüz, disiplinli bir yükseliştir.",
    ("Ruh Noktası", "Kova"): "Ruhunuz özgürlük ve insanlık sevgisiyle yükselir; evrensel bilince açıldıkça ruhsal olarak aydınlanırsınız. Farklılık, ruhunuzun zenginliğidir.",
    ("Ruh Noktası", "Balık"): "Ruhunuz sezgi ve şefkatle yoğrulur; evrenle bir olmayı öğrendikçe ruhsal olarak derinleşirsiniz. İçsel akışınız, ilahi rehberliğinizdir.",

    ("Evlilik Noktası", "Koç"): "Bağlılık kaderiniz cesur ve net; evliliğinizde inisiyatif sizden gelir. Kadersel eşinizle güçlü bir yürüyüşünüz olacaktır.",
    ("Evlilik Noktası", "Boğa"): "Bağlılık kaderiniz toprak gibi sağlamdır; evliliğiniz güven ve istikrar üzerine kurulur. Kadersel bağınız, zamanla daha da güçlenir.",
    ("Evlilik Noktası", "İkizler"): "Bağlılık kaderiniz iletişim ve zihinsel uyumla dokunur; evliliğiniz konuşarak, paylaşarak büyür. Kadersel eşiniz, ruh ikiziniz gibidir.",
    ("Evlilik Noktası", "Yengeç"): "Bağlılık kaderiniz duygusal beslenme üzerine kuruludur; evliliğiniz yuva ve aile değerleriyle derinleşir. Kadersel bağınız, kalbinizin sığınağıdır.",
    ("Evlilik Noktası", "Aslan"): "Bağlılık kaderiniz onur ve cömertlikle örülür; evliliğiniz birlikte parlamak üzerine kuruludur. Kadersel eşinizle sahnenin ışıklarını paylaşırsınız.",
    ("Evlilik Noktası", "Başak"): "Bağlılık kaderiniz hizmet ve titizlikle işler; evliliğiniz karşılıklı özenle olgunlaşır. Kadersel bağınız, detaylardaki sevgide saklıdır.",
    ("Evlilik Noktası", "Terazi"): "Bağlılık kaderiniz denge ve adaletle kurulur; evliliğiniz eşitlik üzerine yükselir. Kadersel eşiniz, hayatınızın tamamlayıcı yarısıdır.",
    ("Evlilik Noktası", "Akrep"): "Bağlılık kaderiniz derin ve dönüştürücüdür; evliliğiniz ruhsal bir kontrat gibidir. Kadersel bağınız, hiçbir fırtınayla yıkılmaz.",
    ("Evlilik Noktası", "Yay"): "Bağlılık kaderiniz özgürlük ve macera ile beslenir; evliliğiniz birlikte keşfetmek üzerine kuruludur. Kadersel eşinizle ufuklara yol alırsınız.",
    ("Evlilik Noktası", "Oğlak"): "Bağlılık kaderiniz sorumluluk ve yapı üzerine kuruludur; evliliğiniz uzun vadeli ve sağlamdır. Kadersel bağınız, hayat boyu sürecek bir kontrattır.",
    ("Evlilik Noktası", "Kova"): "Bağlılık kaderiniz özgün ve sıra dışıdır; evliliğiniz kalıpları yıkarak kurulur. Kadersel eşiniz, en iyi dostunuzdur.",
    ("Evlilik Noktası", "Balık"): "Bağlılık kaderiniz koşulsuz sevgiyle dokunur; evliliğiniz manevi bir birlikteliktir. Kadersel bağınız, ruhların kutsal birleşmesidir.",

    ("Aşk Noktası", "Koç"): "Aşk diliniz cesur ve doğrudandır; kalbinizin önünde engel tanımaz. Aşk kaderiniz, tutkuyla başlar ve zaferle taçlanır.",
    ("Aşk Noktası", "Boğa"): "Aşk diliniz duyusal ve sadıktır; sevginizi dokunuş ve güvenle ifade edersiniz. Aşk kaderiniz, kalıcı ve besleyicidir.",
    ("Aşk Noktası", "İkizler"): "Aşk diliniz kelimeler ve zihinsel oyundur; kalbiniz merakla atar. Aşk kaderiniz, sohbetle filizlenir ve bilgiyle büyür.",
    ("Aşk Noktası", "Yengeç"): "Aşk diliniz şefkat ve duygusal güvenliktir; kalbiniz kucak açmayı sever. Aşk kaderiniz, derin ve koruyucudur.",
    ("Aşk Noktası", "Aslan"): "Aşk diliniz cömertlik ve tutkulu ilgidir; kalbiniz sahne ışıklarıyla yanar. Aşk kaderiniz, görkemli ve onurlandırıcıdır.",
    ("Aşk Noktası", "Başak"): "Aşk diliniz hizmet ve inceliktir; sevginizi pratik şefkatle gösterirsiniz. Aşk kaderiniz, titiz ve sadıktır.",
    ("Aşk Noktası", "Terazi"): "Aşk diliniz zarafet ve uyumdur; kalbiniz estetikten beslenir. Aşk kaderiniz, dengeli ve adildir.",
    ("Aşk Noktası", "Akrep"): "Aşk diliniz yoğun ve dönüştürücüdür; kalbiniz ruhun derinliklerinde atar. Aşk kaderiniz, ölümcül bir bağlılıktır.",
    ("Aşk Noktası", "Yay"): "Aşk diliniz macera ve coşkudur; kalbiniz ufuklara doğru kanatlanır. Aşk kaderiniz, neşeli ve genişleyicidir.",
    ("Aşk Noktası", "Oğlak"): "Aşk diliniz ciddi ve sorumludur; kalbiniz emekle güçlenir. Aşk kaderiniz, sadakat üzerine inşa edilir.",
    ("Aşk Noktası", "Kova"): "Aşk diliniz özgün ve arkadaşçadır; kalbiniz özgürlükten beslenir. Aşk kaderiniz, sıra dışı ve özgürdür.",
    ("Aşk Noktası", "Balık"): "Aşk diliniz romantik ve koşulsuzdur; kalbiniz hayal ve şefkatle dolar. Aşk kaderiniz, ruhsal ve masalsıdır.",

    ("Tutku Noktası", "Koç"): "İç ateşiniz ani ve güçlüdür; arzularınız doğrudan eyleme dönüşür. Tutkunuz, kaderinizi cesurca yazdırır.",
    ("Tutku Noktası", "Boğa"): "İç ateşiniz derin ve sabit yanar; arzularınız duyusal ve kalıcıdır. Tutkunuz, kaderinizi azimle inşa eder.",
    ("Tutku Noktası", "İkizler"): "İç ateşiniz zihinsel ve kıvrak yanar; arzularınız merakla beslenir. Tutkunuz, kaderinizi keşifle örer.",
    ("Tutku Noktası", "Yengeç"): "İç ateşiniz duygusal ve korumacı yanar; arzularınız aile ve güvenlikle bağlıdır. Tutkunuz, kaderinizi şefkatle yönlendirir.",
    ("Tutku Noktası", "Aslan"): "İç ateşiniz görkemli ve yaratıcı yanar; arzularınız takdir ve ışımayla güçlenir. Tutkunuz, kaderinizi parlaklıkla taçlandırır.",
    ("Tutku Noktası", "Başak"): "İç ateşiniz titiz ve düzenli yanar; arzularınız hizmet ve kusursuzlukla yoğrulur. Tutkunuz, kaderinizi incelikle işler.",
    ("Tutku Noktası", "Terazi"): "İç ateşiniz zarif ve uyumlu yanar; arzularınız güzellik ve dengeyle beslenir. Tutkunuz, kaderinizi estetikle yönlendirir.",
    ("Tutku Noktası", "Akrep"): "İç ateşiniz yoğun ve sönmez yanar; arzularınız derinlik ve kontrolle güçlenir. Tutkunuz, kaderinizi dönüştürerek yazar.",
    ("Tutku Noktası", "Yay"): "İç ateşiniz genişleyici ve coşkulu yanar; arzularınız özgürlük ve ideallerle beslenir. Tutkunuz, kaderinizi ufka doğru taşır.",
    ("Tutku Noktası", "Oğlak"): "İç ateşiniz disiplinli ve kararlı yanar; arzularınız başarı ve statüyle beslenir. Tutkunuz, kaderinizi zirveye çıkarır.",
    ("Tutku Noktası", "Kova"): "İç ateşiniz özgün ve devrimci yanar; arzularınız özgürlük ve ideallerle beslenir. Tutkunuz, kaderinizi sıra dışı bir yola sokar.",
    ("Tutku Noktası", "Balık"): "İç ateşiniz sezgisel ve akışkan yanar; arzularınız hayal ve maneviyatla beslenir. Tutkunuz, kaderinizi ilhamla yönlendirir.",

    ("Para Noktası", "Koç"): "Para kaderiniz girişimcilikle açılır; ilk adımı cesaretle attığınızda bolluk sizi bulur. Maddi fırsatlar, öncü olduğunuzda gelir.",
    ("Para Noktası", "Boğa"): "Para kaderiniz toprak ve istikrarla örülür; düzenli birikimleriniz bereket getirir. Maddi bolluk, sabırlı emeğinizin karşılığıdır.",
    ("Para Noktası", "İkizler"): "Para kaderiniz iletişim ve ticaretle açılır; bilginiz ve bağlantılarınız kazanç getirir. Maddi fırsatlar, paylaştıkça büyür.",
    ("Para Noktası", "Yengeç"): "Para kaderiniz güvenlik ve evle bağlantılıdır; ailenize değer katan işler bereket getirir. Maddi bolluk, duygusal güvenlikle beslenir.",
    ("Para Noktası", "Aslan"): "Para kaderiniz yaratıcılık ve vitrinle açılır; yeteneklerinizi sergiledikçe kazanç artar. Maddi bolluk, cömertliğinizi besleyerek gelir.",
    ("Para Noktası", "Başak"): "Para kaderiniz hizmet ve analizle örülür; titizlikle yönetilen kaynaklar çoğalır. Maddi bolluk, düzenli sistemlerle gelir.",
    ("Para Noktası", "Terazi"): "Para kaderiniz ortaklık ve uyumla açılır; işbirlikleri ve estetik zevkiniz kazanç getirir. Maddi bolluk, dengeli paylaşımla artar.",
    ("Para Noktası", "Akrep"): "Para kaderiniz dönüşüm ve derinlikle örülür; kaynak yönetimi gücünüz yüksektir. Maddi bolluk, yeniden yapılandırma ile gelir.",
    ("Para Noktası", "Yay"): "Para kaderiniz genişleme ve fırsatlarla açılır; yabancı bağlantılar ve keşifler kazanç getirir. Maddi bolluk, geniş vizyonla gelir.",
    ("Para Noktası", "Oğlak"): "Para kaderiniz disiplin ve stratejiyle örülür; uzun vadeli hedefler kazancınızı büyütür. Maddi bolluk, sabırlı yükselişin sonucudur.",
    ("Para Noktası", "Kova"): "Para kaderiniz yenilik ve teknolojiyle açılır; sıra dışı fikirleriniz kazanç getirir. Maddi bolluk, özgün girişimlerle gelir.",
    ("Para Noktası", "Balık"): "Para kaderiniz sezgi ve ilhamla örülür; sanatsal ve manevi alanlar size fırsat sunar. Maddi bolluk, akışa güvendikçe gelir.",
}

ARAP_NOKTA_EV_YORUMLARI = {
    ("Şans Noktası", 1): "Şans enerjiniz kimliğinizde taçlanır; fırsatlar sizi ilk adımınızda bulur.",
    ("Şans Noktası", 2): "Şans enerjiniz maddi değerlerle beslenir; fırsatlar özgüveninizle çoğalır.",
    ("Şans Noktası", 3): "Şans enerjiniz iletişimde parlar; fırsatlar çevreniz ve bilginizle gelir.",
    ("Şans Noktası", 4): "Şans enerjiniz köklerinizde saklıdır; aile ve yuva size fırsat kapısı açar.",
    ("Şans Noktası", 5): "Şans enerjiniz yaratıcılıkta parlar; fırsatlar oyun ve sanat yoluyla gelir.",
    ("Şans Noktası", 6): "Şans enerjiniz günlük düzende işler; fırsatlar hizmet ve titizlikle gelir.",
    ("Şans Noktası", 7): "Şans enerjiniz ortaklıklarda yükselir; fırsatlar ilişkilerinizle gelir.",
    ("Şans Noktası", 8): "Şans enerjiniz dönüşümde güçlenir; fırsatlar miras ve derin bağlarla gelir.",
    ("Şans Noktası", 9): "Şans enerjiniz ufukta parlar; fırsatlar seyahat ve bilgelikle gelir.",
    ("Şans Noktası", 10): "Şans enerjiniz kariyerde taçlanır; fırsatlar hedeflerinizle gelir.",
    ("Şans Noktası", 11): "Şans enerjiniz dostluklarda yükselir; fırsatlar topluluklarınızla gelir.",
    ("Şans Noktası", 12): "Şans enerjiniz maneviyatta derinleşir; fırsatlar sezginizle gelir.",

    ("Ruh Noktası", 1): "Ruhsal amacınız kimliğinizle iç içedir; kendiniz olarak ruhunuzu yaşarsınız.",
    ("Ruh Noktası", 2): "Ruhsal amacınız değerlerinizle beslenir; özgüveniniz ruhunuzun aynasıdır.",
    ("Ruh Noktası", 3): "Ruhsal amacınız öğrenme ve paylaşmada; kelimeler ruhunuzun köprüsüdür.",
    ("Ruh Noktası", 4): "Ruhsal amacınız köklerinizde saklıdır; aile bağlarınız ruhunuzu besler.",
    ("Ruh Noktası", 5): "Ruhsal amacınız yaratıcılıkta parlar; ifadeniz ruhunuzun neşesidir.",
    ("Ruh Noktası", 6): "Ruhsal amacınız hizmette işler; faydalı olmak ruhunuzu arındırır.",
    ("Ruh Noktası", 7): "Ruhsal amacınız ilişkilerde aynalanır; bağlarınız ruhunuzu olgunlaştırır.",
    ("Ruh Noktası", 8): "Ruhsal amacınız dönüşümde derinleşir; arınma ruhunuzun şifasıdır.",
    ("Ruh Noktası", 9): "Ruhsal amacınız hakikatte yükselir; inancınız ruhunuzun ışığıdır.",
    ("Ruh Noktası", 10): "Ruhsal amacınız sorumlulukta taçlanır; misyonunuz ruhunuzun yoludur.",
    ("Ruh Noktası", 11): "Ruhsal amacınız insanlık sevgisinde parlar; topluluğunuz ruhunuzu besler.",
    ("Ruh Noktası", 12): "Ruhsal amacınız maneviyatta derinleşir; içsel akışınız ilahi rehberinizdir.",

    ("Evlilik Noktası", 1): "Evlilik kaderiniz kimliğinizle bağlantılıdır; bağlılık, benliğinizin temelidir.",
    ("Evlilik Noktası", 2): "Evlilik kaderiniz güven ve değerlerle beslenir; ortaklığınız maddi temele dayanır.",
    ("Evlilik Noktası", 3): "Evlilik kaderiniz iletişimle güçlenir; birlikteliğiniz sohbetle büyür.",
    ("Evlilik Noktası", 4): "Evlilik kaderiniz yuva hayatında taçlanır; aile kurmak kaderinizin merkezidir.",
    ("Evlilik Noktası", 5): "Evlilik kaderiniz neşe ve yaratıcılıkla beslenir; birlikteliğiniz coşkuyla doludur.",
    ("Evlilik Noktası", 6): "Evlilik kaderiniz günlük hizmetle işler; ortaklığınız özenle güçlenir.",
    ("Evlilik Noktası", 7): "Evlilik kaderiniz bir numaralı ev alanıdır; eşiniz hayatınızın aynasıdır.",
    ("Evlilik Noktası", 8): "Evlilik kaderiniz derin bağlarla örülür; birlikteliğiniz ruhsal bir kontrattır.",
    ("Evlilik Noktası", 9): "Evlilik kaderiniz ortak ideallerle yükselir; birlikte genişlersiniz.",
    ("Evlilik Noktası", 10): "Evlilik kaderiniz toplumsal rolde taçlanır; eşinizle birlikte hedeflere yürürsünüz.",
    ("Evlilik Noktası", 11): "Evlilik kaderiniz dostlukla beslenir; eşiniz en yakın arkadaşınızdır.",
    ("Evlilik Noktası", 12): "Evlilik kaderiniz maneviyatta derinleşir; birlikteliğiniz ruhsal bir birleşmedir.",

    ("Aşk Noktası", 1): "Aşk kaderiniz kimliğinizle parlar; sevginiz, benliğinizin ışığıdır.",
    ("Aşk Noktası", 2): "Aşk kaderiniz özdeğerle beslenir; kendinizi sevdikçe sevgi çekersiniz.",
    ("Aşk Noktası", 3): "Aşk kaderiniz iletişimde filizlenir; kalbiniz kelimelerle konuşur.",
    ("Aşk Noktası", 4): "Aşk kaderiniz duygusal güvenlikte yeşerir; kalbiniz yuva arar.",
    ("Aşk Noktası", 5): "Aşk kaderiniz romantizmle parlar; kalbiniz oyun ve neşeyle yanar.",
    ("Aşk Noktası", 6): "Aşk kaderiniz hizmet ve özenle beslenir; sevginiz pratik şefkatle büyür.",
    ("Aşk Noktası", 7): "Aşk kaderiniz ilişkilerde aynalanır; sevgi, hayatınızın ana temelidir.",
    ("Aşk Noktası", 8): "Aşk kaderiniz derinlikte yoğrulur; kalbiniz ruhsal bağlarla atar.",
    ("Aşk Noktası", 9): "Aşk kaderiniz macerayla parlar; kalbiniz uzak diyarlara yol alır.",
    ("Aşk Noktası", 10): "Aşk kaderiniz toplumsal rolle güçlenir; sevginiz saygıyla beslenir.",
    ("Aşk Noktası", 11): "Aşk kaderiniz dostlukta yeşerir; kalbiniz topluluk içinde atar.",
    ("Aşk Noktası", 12): "Aşk kaderiniz maneviyatta derinleşir; kalbiniz ilahi sevgiyle yanar.",

    ("Tutku Noktası", 1): "Tutkunuz kimliğinizden fışkırır; ateşiniz benliğinizi harekete geçirir.",
    ("Tutku Noktası", 2): "Tutkunuz değerlerinizle beslenir; arzularınız kazanca dönüşür.",
    ("Tutku Noktası", 3): "Tutkunuz zihninizde parlar; arzularınız fikirlerle güçlenir.",
    ("Tutku Noktası", 4): "Tutkunuz köklerinizde yanar; aileniz ateşinizi besler.",
    ("Tutku Noktası", 5): "Tutkunuz yaratıcılıkta alevlenir; arzularınız sanatta parlar.",
    ("Tutku Noktası", 6): "Tutkunuz hizmette işler; arzularınız günlük işlerde güç bulur.",
    ("Tutku Noktası", 7): "Tutkunuz ilişkilerde yanar; arzularınız bağlarla güçlenir.",
    ("Tutku Noktası", 8): "Tutkunuz derinlikte alevlenir; arzularınız dönüşümle beslenir.",
    ("Tutku Noktası", 9): "Tutkunuz ufukta parlar; arzularınız keşifle büyür.",
    ("Tutku Noktası", 10): "Tutkunuz kariyerde taçlanır; arzularınız hedeflerle yükselir.",
    ("Tutku Noktası", 11): "Tutkunuz dostlukta yanar; arzularınız ideallerle güçlenir.",
    ("Tutku Noktası", 12): "Tutkunuz maneviyatta derinleşir; arzularınız ilhamla beslenir.",

    ("Para Noktası", 1): "Para kaderiniz kimliğinizle bağlantılıdır; kazancınız girişiminizle büyür.",
    ("Para Noktası", 2): "Para kaderiniz doğal ev alanıdır; bolluk, buradan taşar.",
    ("Para Noktası", 3): "Para kaderiniz ticaret ve iletişimle işler; bilginiz kazanca dönüşür.",
    ("Para Noktası", 4): "Para kaderiniz aile ve gayrimenkulde; kökleriniz size kazanç getirir.",
    ("Para Noktası", 5): "Para kaderiniz yaratıcılıkla parlar; yetenekleriniz kazanca dönüşür.",
    ("Para Noktası", 6): "Para kaderiniz hizmetle işler; titiz emeğiniz bereket getirir.",
    ("Para Noktası", 7): "Para kaderiniz ortaklıklarda yükselir; işbirlikleri kazanç getirir.",
    ("Para Noktası", 8): "Para kaderiniz derin kaynaklarda; yatırım ve miras size fırsat sunar.",
    ("Para Noktası", 9): "Para kaderiniz genişlemede parlar; yabancı bağlar kazancınızı artırır.",
    ("Para Noktası", 10): "Para kaderiniz kariyerde taçlanır; mesleğiniz bolluk getirir.",
    ("Para Noktası", 11): "Para kaderiniz ağlarla beslenir; topluluğunuz kazancınızı büyütür.",
    ("Para Noktası", 12): "Para kaderiniz maneviyatta işler; sezginiz fırsatları sezdirir.",
}

ARAP_EV_KISAYORUMLARI = {
    1: "Kimlik ve benlik alanında kadersel bir etki yaratır.",
    2: "Değerler ve maddi kaynaklar alanında kadersel bir etki yaratır.",
    3: "İletişim ve yakın çevre alanında kadersel bir etki yaratır.",
    4: "Aile kökleri ve yuva alanında kadersel bir etki yaratır.",
    5: "Yaratıcılık ve aşk hayatı alanında kadersel bir etki yaratır.",
    6: "Günlük düzen ve sağlık alanında kadersel bir etki yaratır.",
    7: "Ortaklıklar ve ilişkiler alanında kadersel bir etki yaratır.",
    8: "Dönüşüm ve derin bağlar alanında kadersel bir etki yaratır.",
    9: "İnanç ve genişleme alanında kadersel bir etki yaratır.",
    10: "Kariyer ve toplumsal rol alanında kadersel bir etki yaratır.",
    11: "Dostluklar ve topluluklar alanında kadersel bir etki yaratır.",
    12: "Bilinçaltı ve maneviyat alanında kadersel bir etki yaratır.",
}

ARAP_NOKTA_SINASTRI_YORUMLARI = {
    ("Şans Noktası", "Şans Noktası"): "Şans noktalarınız kaderin aynı titreşiminde; birlikte şanslı bir yolculuk sizi bekliyor.",
    ("Şans Noktası", "Ruh Noktası"): "Birinin şansı diğerinin ruhsal yolunu aydınlatıyor; kaderiniz birbirinizi besliyor.",
    ("Şans Noktası", "Evlilik Noktası"): "Şansınız bağlılığınızı güçlendiriyor; birlikteyken fırsatlar açılıyor.",
    ("Şans Noktası", "Aşk Noktası"): "Şans ve aşk enerjiniz iç içe; birlikteliğiniz kaderin lütfuyla besleniyor.",
    ("Şans Noktası", "Tutku Noktası"): "Şansınız tutkunuzu harekete geçiriyor; birlikteyken cesur adımlar atıyorsunuz.",
    ("Şans Noktası", "Para Noktası"): "Şans ve bolluk enerjiniz birleşiyor; birlikteyken maddi fırsatlar açılıyor.",
    ("Ruh Noktası", "Ruh Noktası"): "Ruh noktalarınız aynı frekansta; aranızda ruhsal bir anlaşma var.",
    ("Ruh Noktası", "Evlilik Noktası"): "Ruhsal yolunuz bağlılık kaderinizle kesişiyor; birlikteliğiniz manevi bir amaç taşıyor.",
    ("Ruh Noktası", "Aşk Noktası"): "Ruhunuz ve kalbiniz birlikte atıyor; aşkınız ruhsal bir derinlik taşıyor.",
    ("Ruh Noktası", "Tutku Noktası"): "Ruhsal amacınız ve tutkunuz birleşiyor; birlikteyken iç ateşiniz güçleniyor.",
    ("Ruh Noktası", "Para Noktası"): "Ruhsal yolunuz maddi araçlarla destekleniyor; birlikte denge buluyorsunuz.",
    ("Evlilik Noktası", "Evlilik Noktası"): "Evlilik noktalarınız aynı titreşimde; kadersel bir bağlılık kontratı aranızda.",
    ("Evlilik Noktası", "Aşk Noktası"): "Aşk ve bağlılık kaderiniz birleşiyor; birlikteliğiniz kalıcı ve tutkulu.",
    ("Evlilik Noktası", "Tutku Noktası"): "Bağlılık ve tutku enerjiniz iç içe; birlikteliğiniz ateşli ama sağlam.",
    ("Evlilik Noktası", "Para Noktası"): "Bağlılık ve bolluk enerjiniz birleşiyor; birlikte sağlam bir gelecek kuruyorsunuz.",
    ("Aşk Noktası", "Aşk Noktası"): "Aşk noktalarınız aynı frekansta; kalpleriniz aynı ritimde atıyor.",
    ("Aşk Noktası", "Tutku Noktası"): "Aşk ve tutku enerjiniz mükemmel uyumda; birlikteliğiniz romantik ve ateşli.",
    ("Aşk Noktası", "Para Noktası"): "Aşk ve bolluk enerjiniz birleşiyor; birlikteyken hem sevgi hem bereket akıyor.",
    ("Tutku Noktası", "Tutku Noktası"): "Tutku noktalarınız aynı titreşimde; birlikteyken enerjiniz katlanarak artıyor.",
    ("Tutku Noktası", "Para Noktası"): "Tutku ve bolluk enerjiniz birleşiyor; cesaretiniz maddi fırsatlar yaratıyor.",
    ("Para Noktası", "Para Noktası"): "Para noktalarınız aynı frekansta; birlikteyken bolluk enerjiniz güçleniyor.",
}

ARAP_NOKTA_GEZEGEN_SINASTRI = {
    ("Şans Noktası", "Güneş"): "Şans noktanız karşı tarafın Güneş'iyle kavuşuyor; varlığınız onun hayatına fırsat getiriyor.",
    ("Şans Noktası", "Ay"): "Şans noktanız karşı tarafın Ay'ıyla kavuşuyor; onun duyguları sizinle birlikte şans buluyor.",
    ("Şans Noktası", "Venüs"): "Şans noktanız karşı tarafın Venüs'üyle kavuşuyor; birlikteyken güzellik ve fırsat iç içe.",
    ("Şans Noktası", "Mars"): "Şans noktanız karşı tarafın Mars'ıyla kavuşuyor; birlikteyken cesur adımlar bereket getiriyor.",
    ("Şans Noktası", "Jüpiter"): "Şans noktanız karşı tarafın Jüpiter'iyle kavuşuyor; genişleme ve bolluk birlikte akıyor.",
    ("Şans Noktası", "Satürn"): "Şans noktanız karşı tarafın Satürn'üyle kavuşuyor; birlikteyken fırsatlar sorumlulukla geliyor.",
    ("Ruh Noktası", "Güneş"): "Ruh noktanız karşı tarafın Güneş'iyle kavuşuyor; onun varlığı ruhsal yolunuzu aydınlatıyor.",
    ("Ruh Noktası", "Ay"): "Ruh noktanız karşı tarafın Ay'ıyla kavuşuyor; ruhlarınız duygusal bir derinlikte buluşuyor.",
    ("Ruh Noktası", "Venüs"): "Ruh noktanız karşı tarafın Venüs'üyle kavuşuyor; ruhsal bağınız sevgiyle dokunuyor.",
    ("Ruh Noktası", "Mars"): "Ruh noktanız karşı tarafın Mars'ıyla kavuşuyor; ruhsal yolunuz birlikte cesurca ilerliyor.",
    ("Ruh Noktası", "Jüpiter"): "Ruh noktanız karşı tarafın Jüpiter'iyle kavuşuyor; birlikte manevi olarak genişliyorsunuz.",
    ("Ruh Noktası", "Satürn"): "Ruh noktanız karşı tarafın Satürn'üyle kavuşuyor; ruhsal bağınız kaderin işidir.",
    ("Evlilik Noktası", "Güneş"): "Evlilik noktanız karşı tarafın Güneş'iyle kavuşuyor; onun kimliği bağlılık kaderinizi tamamlıyor.",
    ("Evlilik Noktası", "Ay"): "Evlilik noktanız karşı tarafın Ay'ıyla kavuşuyor; duygusal bağınız bağlılıkla besleniyor.",
    ("Evlilik Noktası", "Venüs"): "Evlilik noktanız karşı tarafın Venüs'üyle kavuşuyor; aşk ve bağlılık kaderiniz birleşiyor.",
    ("Evlilik Noktası", "Mars"): "Evlilik noktanız karşı tarafın Mars'ıyla kavuşuyor; birlikteliğiniz ateşli ve bağlı.",
    ("Evlilik Noktası", "Jüpiter"): "Evlilik noktanız karşı tarafın Jüpiter'iyle kavuşuyor; bağlılığınız bollukla besleniyor.",
    ("Evlilik Noktası", "Satürn"): "Evlilik noktanız karşı tarafın Satürn'üyle kavuşuyor; bağınız kaderin en sağlam imzası.",
    ("Aşk Noktası", "Güneş"): "Aşk noktanız karşı tarafın Güneş'iyle kavuşuyor; onun varlığı kalbinizi ısıtıyor.",
    ("Aşk Noktası", "Ay"): "Aşk noktanız karşı tarafın Ay'ıyla kavuşuyor; kalbiniz onun duygularıyla atıyor.",
    ("Aşk Noktası", "Venüs"): "Aşk noktanız karşı tarafın Venüs'üyle kavuşuyor; aşk enerjiniz mükemmel uyumda.",
    ("Aşk Noktası", "Mars"): "Aşk noktanız karşı tarafın Mars'ıyla kavuşuyor; çekiminiz güçlü ve tutkulu.",
    ("Aşk Noktası", "Jüpiter"): "Aşk noktanız karşı tarafın Jüpiter'iyle kavuşuyor; sevginiz birlikte büyüyor.",
    ("Aşk Noktası", "Satürn"): "Aşk noktanız karşı tarafın Satürn'üyle kavuşuyor; sevginiz zamana meydan okuyor.",
    ("Tutku Noktası", "Güneş"): "Tutku noktanız karşı tarafın Güneş'iyle kavuşuyor; onun varlığı iç ateşinizi körüklüyor.",
    ("Tutku Noktası", "Ay"): "Tutku noktanız karşı tarafın Ay'ıyla kavuşuyor; duygularınız birlikte alevleniyor.",
    ("Tutku Noktası", "Venüs"): "Tutku noktanız karşı tarafın Venüs'üyle kavuşuyor; arzu ve sevgi iç içe geçiyor.",
    ("Tutku Noktası", "Mars"): "Tutku noktanız karşı tarafın Mars'ıyla kavuşuyor; enerjiniz birlikte ikiye katlanıyor.",
    ("Tutku Noktası", "Jüpiter"): "Tutku noktanız karşı tarafın Jüpiter'iyle kavuşuyor; birlikteyken coşkunuz büyüyor.",
    ("Tutku Noktası", "Satürn"): "Tutku noktanız karşı tarafın Satürn'üyle kavuşuyor; arzunuz disiplinle güçleniyor.",
    ("Para Noktası", "Güneş"): "Para noktanız karşı tarafın Güneş'iyle kavuşuyor; onun varlığı kazancınızı artırıyor.",
    ("Para Noktası", "Ay"): "Para noktanız karşı tarafın Ay'ıyla kavuşuyor; birlikteyken maddi güvenlik artıyor.",
    ("Para Noktası", "Venüs"): "Para noktanız karşı tarafın Venüs'üyle kavuşuyor; bolluk ve güzellik birlikte akıyor.",
    ("Para Noktası", "Mars"): "Para noktanız karşı tarafın Mars'ıyla kavuşuyor; birlikteyken kazanç için cesurca çalışıyorsunuz.",
    ("Para Noktası", "Jüpiter"): "Para noktanız karşı tarafın Jüpiter'iyle kavuşuyor; birlikteyken bolluk katlanıyor.",
    ("Para Noktası", "Satürn"): "Para noktanız karşı tarafın Satürn'üyle kavuşuyor; birlikte sağlam bir servet kuruyorsunuz.",
}

ASTEROID_ISIMLERI = {
    "Juno": {"etki": "Evlilik, sadakat, taahhüt ve ortaklık enerjisi"},
    "Ceres": {"etki": "Beslenme, şefkat, annelik ve koruma içgüdüsü"},
    "Pallas": {"etki": "Stratejik zeka, yaratıcı çözüm ve bilgelik"},
    "Vesta": {"etki": "Kutsal odak, adanmışlık ve içsel ateş"},
    "Eros": {"etki": "Tutku, arzu yoğunluğu ve cinsel çekim"},
    "Psyche": {"etki": "Ruhsal derinlik, kırılganlık ve bilinçdışı bağ"},
    "Sappho": {"etki": "Romantizm, estetik tutku ve duygusal derinlik"},
    "Amor": {"etki": "Koşulsuz sevgi, kabul ve kalp bağlanması"},
}

ASTEROID_SINASTRI_YORUMLARI = {
    ("Juno", "Güneş"): "Juno'nuz Güneş'iyle kavuşuyor; bağlılığınız onun kimliğiyle bütünleşiyor, sadakat kaderinizin merkezine oturuyor.",
    ("Juno", "Ay"): "Juno'nuz Ay'ıyla kavuşuyor; duygusal güvenlik ve sadakat iç içe, bağınız şefkatle besleniyor.",
    ("Juno", "Venüs"): "Juno'nuz Venüs'üyle kavuşuyor; evlilik ve aşk enerjisi birleşiyor, birlikteliğiniz sevgiyle mühürleniyor.",
    ("Juno", "Mars"): "Juno'nuz Mars'ıyla kavuşuyor; bağlılığınız tutkuyla ateşleniyor, aranızdaki çekim güçlü.",
    ("Juno", "Jüpiter"): "Juno'nuz Jüpiter'iyle kavuşuyor; birlikteliğiniz bolluk ve genişlemeyle besleniyor.",
    ("Juno", "Satürn"): "Juno'nuz Satürn'üyle kavuşuyor; bağlılığınız kadersel ve kalıcı, evlilik kontratı güçlü.",
    ("Ceres", "Ay"): "Ceres'iniz Ay'ıyla kavuşuyor; karşılıklı beslenme ve şefkat bağınızın temeli oluyor.",
    ("Ceres", "Venüs"): "Ceres'iniz Venüs'üyle kavuşuyor; sevginiz besleyici ve şefkatli, birlikteliğiniz huzur dolu.",
    ("Ceres", "Güneş"): "Ceres'iniz Güneş'iyle kavuşuyor; onun varlığı sizi besliyor, aranızda annelik enerjisi akıyor.",
    ("Ceres", "Mars"): "Ceres'iniz Mars'ıyla kavuşuyor; koruma içgüdünüz güçlü, birlikte zorlukları aşıyorsunuz.",
    ("Ceres", "Jüpiter"): "Ceres'iniz Jüpiter'iyle kavuşuyor; birlikteyken şefkat ve bolluk iç içe akıyor.",
    ("Ceres", "Satürn"): "Ceres'iniz Satürn'üyle kavuşuyor; sorumlu bir bakım ve güven bağı kuruyorsunuz.",
    ("Pallas", "Merkür"): "Pallas'ınız Merkür'üyle kavuşuyor; zihinsel uyumunuz yüksek, birlikte akıllıca çözümler buluyorsunuz.",
    ("Pallas", "Güneş"): "Pallas'ınız Güneş'iyle kavuşuyor; stratejik bilgeliğiniz onun kimliğini güçlendiriyor.",
    ("Pallas", "Ay"): "Pallas'ınız Ay'ıyla kavuşuyor; duygusal zekanız yüksek, sezgisel çözümlerle bağ kuruyorsunuz.",
    ("Pallas", "Venüs"): "Pallas'ınız Venüs'üyle kavuşuyor; zarafet ve strateji birleşiyor, birlikteliğiniz incelikli.",
    ("Pallas", "Mars"): "Pallas'ınız Mars'ıyla kavuşuyor; akıllıca savaşan bir ekip oluyorsunuz.",
    ("Vesta", "Güneş"): "Vesta'nız Güneş'iyle kavuşuyor; birlikteyken odaklanmanız artıyor, ortak hedeflerinize adanıyorsunuz.",
    ("Vesta", "Ay"): "Vesta'nız Ay'ıyla kavuşuyor; duygusal adanmışlığınız güçlü, bağınız içsel ateşle besleniyor.",
    ("Vesta", "Mars"): "Vesta'nız Mars'ıyla kavuşuyor; ortak enerjiniz disiplinli ve hedef odaklı.",
    ("Vesta", "Satürn"): "Vesta'nız Satürn'üyle kavuşuyor; birlikteliğiniz kutsal bir görev gibi, adanmışlığınız sağlam.",
    ("Eros", "Venüs"): "Eros'unuz Venüs'üyle kavuşuyor; tutku ve sevgi iç içe, çekiminiz karşı konulmaz.",
    ("Eros", "Mars"): "Eros'unuz Mars'ıyla kavuşuyor; aranızdaki çekim yoğun ve ateşli, arzu kaderinizi yönlendiriyor.",
    ("Eros", "Ay"): "Eros'unuz Ay'ıyla kavuşuyor; duygusal bağınız tutkuyla yoğruluyor.",
    ("Eros", "Güneş"): "Eros'unuz Güneş'iyle kavuşuyor; onun varlığı arzularınızı alevlendiriyor.",
    ("Psyche", "Ay"): "Psyche'niz Ay'ıyla kavuşuyor; ruhlarınız duygusal derinlikte buluşuyor, telepatik bir bağ kuruyorsunuz.",
    ("Psyche", "Venüs"): "Psyche'niz Venüs'üyle kavuşuyor; ruhsal ve romantik sevgi birleşiyor, bağınız masalsı.",
    ("Psyche", "Güneş"): "Psyche'niz Güneş'iyle kavuşuyor; ruhunuz onun kimliğiyle derinden bağ kuruyor.",
    ("Psyche", "Neptün"): "Psyche'niz Neptün'üyle kavuşuyor; ruhsal bağınız ilahi boyutlara ulaşıyor.",
    ("Sappho", "Venüs"): "Sappho'nuz Venüs'üyle kavuşuyor; romantizminiz dorukta, aşkınız estetik ve derin.",
    ("Sappho", "Ay"): "Sappho'nuz Ay'ıyla kavuşuyor; duygusal bağınız şairane ve hassas.",
    ("Sappho", "Mars"): "Sappho'nuz Mars'ıyla kavuşuyor; tutkulu romantizm aranızda akıyor.",
    ("Sappho", "Güneş"): "Sappho'nuz Güneş'iyle kavuşuyor; onun varlığı romantik duygularınızı parlıyor.",
    ("Amor", "Venüs"): "Amor'unuz Venüs'üyle kavuşuyor; koşulsuz sevgi ve aşk birleşiyor, bağınız kutsal.",
    ("Amor", "Ay"): "Amor'unuz Ay'ıyla kavuşuyor; sevginiz koşulsuz ve şefkatli, duygusal bağınız derin.",
    ("Amor", "Güneş"): "Amor'unuz Güneş'iyle kavuşuyor; sevginiz onun varlığını tamamlıyor.",
    ("Amor", "Mars"): "Amor'unuz Mars'ıyla kavuşuyor; koşulsuz sevginiz tutkuyla güçleniyor.",
}
