# -*- coding: utf-8 -*-
"""Sinastri hesaplama modulunun TR/EN/ES metin sozlukleri.

Uretim: TR degerleri app.py icindeki Turkce sabitlerden birebir alindi;
EN/ES degerleri elle yazildi. Sozluk anahtarlari Turkce kalir (ic donem)
ve cikti metinleri i18n.pdf_label() ile gecirilir.
"""

TR = {
    'acilar': {
        0: {
            'isim': 'Kavuşum',
            'etki': 'Güçlü Birleşme',
            'puan': 10,
        },
        180: {
            'isim': 'Karşıt',
            'etki': 'Farkındalık/Gerilim',
            'puan': -5,
        },
        90: {
            'isim': 'Kare',
            'etki': 'Mücadele/Dinamizm',
            'puan': -8,
        },
        120: {
            'isim': 'Üçgen',
            'etki': 'Doğal Akış/Şans',
            'puan': 8,
        },
        60: {
            'isim': 'Sekstil',
            'etki': 'Fırsat/Uyum',
            'puan': 5,
        },
    },
    'gezegen': {
        'ebeveyn': {
            'Güneş': 'kimlik, benlik gelişimi ve hayati güç',
            'Ay': 'duygusal dünya, beslenme ihtiyacı ve içgüdü',
            'Merkür': 'iletişim, öğrenme süreci ve zihinsel gelişim',
            'Venüs': 'değerler, sevgi dili ve estetik algı',
            'Mars': 'eylem cesareti, bağımsızlık enerjisi ve öfke yönetimi',
            'Jüpiter': 'genişleme, bolluk ve bilgelik arayışı',
            'Satürn': 'yapı, sorumluluk ve disiplin ihtiyacı',
            'Uranüs': 'özgürlük arzusu, yenilik ve isyan enerjisi',
            'Neptün': 'hayal gücü, maneviyat ve kırılganlık',
            'Plüton': 'dönüşüm, güç yapiylari ve yeniden doğum',
            'KAD': 'kader misyonu, ruhsal yön ve hayat dersi',
            'GAD': 'gerçek benlik, içsel rehberlik ve Potansiyel',
            'Chiron': 'şifa, yara bilgeliği ve merhamet',
            'Juno': 'bağlanma tarzı, taahhüt ve güven ihtiyacı',
            'Ceres': 'beslenme, koruma içgüdüsü ve annelik enerjisi',
            'Pallas': 'stratejik zeka, yaratıcı çözüm ve vizyon',
            'Vesta': 'içsel odak, kutsal bağlılık ve kararlılık',
            'Eros': 'tutku, arzu yoğunluğu ve eylem enerjisi',
            'Psyche': 'ruhsal derinlik, kırılganlık ve bilinçdışı',
            'Sappho': 'hassasiyet, estetik algı ve duygusal derinlik',
            'Amor': 'koşulsuz sevgi, kabul ve kalp bağlanması',
        },
        'normal': {
            'Güneş': 'öz-bilinç, kimlik ve hayati güç',
            'Ay': 'duygusal dünya, içgüdü ve beslenme',
            'Merkür': 'iletişim, zihinsel alışveriş ve merak',
            'Venüs': 'sevgi dili, estetik ve değerler',
            'Mars': 'tutku, eylem cesareti ve fiziksel çekim',
            'Jüpiter': 'genişleme, bolluk ve ruhsal büyüme',
            'Satürn': 'yapı, sorumluluk ve kalıcı bağlılık',
            'Uranüs': 'özgürlük, yenilik ve ani değişimler',
            'Neptün': 'maneviyat, hayal gücü ve koşulsuz sevgi',
            'Plüton': 'dönüşüm, güç ve ruhsal yeniden doğum',
            'KAD': 'kader düğümü, ruhsal misyon ve karmik bağ',
            'GAD': 'gerçek benlik, ruhsal rehberlik ve içsel ışık',
            'Chiron': 'şifa, kırılganlık ve merhamet',
            'Juno': 'evlilik sadakati, ortaklık ve taahhüt',
            'Ceres': 'besleme, koruma ve annelik enerjisi',
            'Pallas': 'stratejik zeka, yaratıcı çözüm ve vizyon',
            'Vesta': 'adhara, kutsal odak ve içsel ateş',
            'Eros': 'arfzunun derinliği, cinsel çekim ve tutku',
            'Psyche': 'ruhsal derinlik, kırılganlık ve bilinçdışı bağ',
            'Sappho': 'şiirsel hassasiyet, estetik tutku ve duygusal derinlik',
            'Amor': 'koşulsuz sevgi, romantik kader ve kalp bağlanması',
        },
    },
    'dinamik': {
        'ebeveyn': {
            0: {
                'baslik': 'Bu iki enerji birleşerek ortak bir gelişim alanı yaratıyor',
                'aciklama': "Bu kavuşumda, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi aynı noktada birleşmiş. Bu birleşme, ebeveyn-çocuk bağında {konu} alanında güçlü bir etki yaratıyor. Birbirinizin bu alandaki güçlü ve zayıf yönlerini tamamlıyorsunuz.",
                'konu_map': {
                    'Güneş': 'kimlik ve benlik gelişimi',
                    'Ay': 'duygusal bağ ve beslenme',
                    'Merkür': 'iletişim ve öğrenme',
                    'Venüs': 'değerler ve sevgi dili',
                    'Mars': 'bağımsızlık ve eylem',
                    'Jüpiter': 'genişleme ve bilgelik',
                    'Satürn': 'yapı ve disiplin',
                    'Uranüs': 'özgürlük ve yenilik',
                    'Neptün': 'hayal gücü ve maneviyat',
                    'Plüton': 'dönüşüm ve güç',
                },
            },
            60: {
                'baslik': 'Bu iki enerji arasında yapıcı bir fırsat bağı var',
                'aciklama': "Bu sekstilde, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi arasında yapıcı bir fırsat ve destek bağı var. Bu uyum, ebeveyn-çocuk bağında {konu} alanında yeni kapılar açıyor. Bu fırsatı değerlendirmek için birlikte adım atmanız yeterli.",
                'konu_map': {
                    'Güneş': 'benlik ve ifade',
                    'Ay': 'duygusal destek ve beslenme',
                    'Merkür': 'iletişim ve öğrenme',
                    'Venüs': 'değerler ve güzellik',
                    'Mars': 'bağımsızlık ve cesaret',
                    'Jüpiter': 'büyüme ve bolluk',
                    'Satürn': 'yapı ve disiplin',
                    'Uranüs': 'yenilik ve özgürlük',
                    'Neptün': 'ilham ve maneviyat',
                    'Plüton': 'dönüşüm ve güçlenme',
                },
            },
            90: {
                'baslik': 'Bu iki enerji arasında yapıcı bir mücadele var',
                'aciklama': "Bu kare açıda, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi arasında sürekli bir gerilim ve itme-çekme dinamiği var. Bu mücadele, ebeveyn-çocuk bağında {konu} alanında büyütücü bir baskı yaratıyor. Bu enerjiyi kanalize etmek için ortak bir hedef belirlemek en sağlıklı yoldur.",
                'konu_map': {
                    'Güneş': 'ego ve benlik',
                    'Ay': 'duygusal güvenlik',
                    'Merkür': 'anlama ve anlaşma',
                    'Venüs': 'değer ve kabul',
                    'Mars': 'bağımsızlık ve eylem',
                    'Jüpiter': 'inanç ve genişleme',
                    'Satürn': 'sorumluluk ve yapı',
                    'Uranüs': 'özgürlük ve rutin',
                    'Neptün': 'gerçeklik ve hayal',
                    'Plüton': 'güç ve kontrol',
                },
            },
            120: {
                'baslik': 'Bu iki enerji arasında doğal bir uyum akışı var',
                'aciklama': "Bu üçgende, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi arasında doğal bir uyum ve akış var. Bu trio, ebeveyn-çocuk bağında {konu} alanında şans ve kolaylık yaratıyor. Birbirinizin bu alandaki güçlü yönlerini destekliyorsunuz.",
                'konu_map': {
                    'Güneş': 'benlik ifadesi ve güç',
                    'Ay': 'duygusal akış ve beslenme',
                    'Merkür': 'iletişim ve zihinsel uyum',
                    'Venüs': 'değerler ve estetik',
                    'Mars': 'bağımsızlık ve eylem uyumu',
                    'Jüpiter': 'büyüme ve neşe',
                    'Satürn': 'yapı ve destek',
                    'Uranüs': 'özgürlük ve yenilik',
                    'Neptün': 'maneviyat ve ilham',
                    'Plüton': 'dönüşüm ve derinlik',
                },
            },
            180: {
                'baslik': 'Bu iki enerji zıt kutuplarda birbirini tamamlıyor',
                'aciklama': "Bu karşıtlıkta, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi zıt kutuplarda duruyor. Bu zıtlık, ebeveyn-çocuk bağında {konu} alanında sürekli bir gerilim ve farkındalık yaratıyor. Zıt yönlerinizi kabul etmek, bu enerjiyi yapıcıya dönüştürmenin anahtarıdır.",
                'konu_map': {
                    'Güneş': 'kimlik ve benlik',
                    'Ay': 'duygusal ihtiyaçlar',
                    'Merkür': 'iletişim ve düşünce tarzı',
                    'Venüs': 'değer algısı',
                    'Mars': 'bağımsızlık ve eylem',
                    'Jüpiter': 'genişleme ve inanç',
                    'Satürn': 'yapı ve sorumluluk',
                    'Uranüs': 'özgürlük ve değişim',
                    'Neptün': 'gerçek ve hayal',
                    'Plüton': 'güç ve kontrol',
                },
            },
        },
        'normal': {
            0: {
                'baslik': 'Bu iki enerji birleşerek ortak bir güç yaratıyor',
                'aciklama': "Bu kavuşumda, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi aynı noktada birleşmiş. Bu birleşme, ilişkinizde {konu} alanında güçlü bir etki yaratıyor. Birbirinizin bu alandaki güçlü ve zayıf yönlerini tamamlıyorsunuz.",
                'konu_map': {
                    'Güneş': 'öz-bilinç ve ifade',
                    'Ay': 'duygusal bağ ve beslenme',
                    'Merkür': 'iletişim ve anlama',
                    'Venüs': 'sevgi ve değerler',
                    'Mars': 'tutku ve eylem',
                    'Jüpiter': 'büyüme ve bolluk',
                    'Satürn': 'yapı ve taahhüt',
                    'Uranüs': 'özgürlük ve yenilik',
                    'Neptün': 'maneviyat ve hayaller',
                    'Plüton': 'dönüşüm ve güç',
                },
            },
            60: {
                'baslik': 'Bu iki enerji arasında yapıcı bir fırsat bağı var',
                'aciklama': "Bu sekstilde, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi arasında yapıcı bir fırsat ve destek bağı var. Bu uyum, ilişkinizde {konu} alanında yeni kapılar açıyor. Bu fırsatı değerlendirmek için birlikte adım atmanız yeterli.",
                'konu_map': {
                    'Güneş': 'öz-güç ve ifade',
                    'Ay': 'duygusal destek ve beslenme',
                    'Merkür': 'iletişim ve öğrenme',
                    'Venüs': 'sevgi ve güzellik',
                    'Mars': 'tutku ve cesaret',
                    'Jüpiter': 'büyüme ve bolluk',
                    'Satürn': 'yapı ve disiplin',
                    'Uranüs': 'yenilik ve özgürlük',
                    'Neptün': 'ilham ve maneviyat',
                    'Plüton': 'dönüşüm ve güçlenme',
                },
            },
            90: {
                'baslik': 'Bu iki enerji arasında yapıcı bir mücadele var',
                'aciklama': "Bu kare açıda, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi arasında sürekli bir Gerilim ve itme-çekme dinamiği var. Bu mücadele, ilişkinizde {konu} alanında büyütücü bir baskı yaratıyor. Bu enerjiyi kanalize etmek için ortak bir hedef belirlemek en sağlıklı yoldur.",
                'konu_map': {
                    'Güneş': 'ego ve benlik',
                    'Ay': 'duygusal güvenlik',
                    'Merkür': 'anlama ve anlaşma',
                    'Venüs': 'sevgi ve değer',
                    'Mars': 'eylem ve tutku',
                    'Jüpiter': 'inanç ve genişleme',
                    'Satürn': 'sorumluluk ve yapı',
                    'Uranüs': 'özgürlük ve rutin',
                    'Neptün': 'gerçeklik ve hayal',
                    'Plüton': 'güç ve kontrol',
                },
            },
            120: {
                'baslik': 'Bu iki enerji arasında doğal bir uyum akışı var',
                'aciklama': "Bu üçgende, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi arasında doğal bir uyum ve akış var. Bu trio, ilişkinizde {konu} alanında şans ve kolaylık yaratıyor. Birbirinizin bu alandaki güçlü yönlerini destekliyorsunuz.",
                'konu_map': {
                    'Güneş': 'öz-ifade ve güç',
                    'Ay': 'duygusal akış ve beslenme',
                    'Merkür': 'iletişim ve zihinsel uyum',
                    'Venüs': 'sevgi ve estetik',
                    'Mars': 'tutku ve eylem uyumu',
                    'Jüpiter': 'büyüme ve neşe',
                    'Satürn': 'yapı ve destek',
                    'Uranüs': 'özgürlük ve yenilik',
                    'Neptün': 'maneviyat ve ilham',
                    'Plüton': 'dönüşüm ve derinlik',
                },
            },
            180: {
                'baslik': 'Bu iki enerji zıt kutuplarda birbirini tamamlıyor',
                'aciklama': "Bu karşıtlıkta, {p1}'in {anlam1} enerjisi ile {p2}'in {anlam2} enerjisi zıt kutuplarda duruyor. Bu zıtlık, ilişkinizde {konu} alanında sürekli bir gerilim ve farkındalık yaratıyor. Zıt yönlerinizi kabul etmek, bu enerjiyi yapıcıya dönüştürmenin anahtarıdır.",
                'konu_map': {
                    'Güneş': 'öz-benlik ve ifade tarzı',
                    'Ay': 'duygusal ihtiyaçlar',
                    'Merkür': 'iletişim ve düşünce tarzı',
                    'Venüs': 'sevgi ve değer algısı',
                    'Mars': 'eylem ve tutku dili',
                    'Jüpiter': 'genişleme ve inanç',
                    'Satürn': 'yapı ve sorumluluk',
                    'Uranüs': 'özgürlük ve değişim',
                    'Neptün': 'gerçek ve hayal',
                    'Plüton': 'güç ve kontrol',
                },
            },
        },
    },
    'ders': 'Dersi',
    'muhur': 'Mührü',
    'temas': 'Teması',
    'sifa': 'Şifası',
    'baslik_dersler': '💊 KADERSEL DERSLER VE ŞİFA ÖNERİLERİ',
    'baslik_receteler': '💊 KADERSEL ŞİFA REÇETELERİ',
    'baslik_planet_etkilesimleri': 'GEZEGEN ETKİLEŞİMLERİ',
    'bos_mesaj': 'Majör bir sinastri etkileşimi saptanmadı.',
    'recete_yok': 'Mevcut kadersel temaslarınız akut bir şifa reçetesi gerektirmemektedir. Doğal akışınızda kalın.',
    'fallback_ebeveyn': 'ebeveyn-çocuk bağının temel yapıları',
    'fallback_normal': 'ilişkinin temel yapıları',
    'fallback_enerji': 'enerji',
    'aktivite': 'Ortak bir aktivite belirleyin ve bu gerilimli enerjiyi yapıcı bir alana kanalize edin.',
    'hobi': 'Ortak bir hobi edinin ve bu gerilimli enerjiyi yapıcı bir alana kanalize edin.',
}

EN = {
    'acilar': {
        0: {
            'isim': 'Conjunction',
            'etki': 'Powerful Union',
            'puan': 10,
        },
        180: {
            'isim': 'Opposition',
            'etki': 'Awareness / Tension',
            'puan': -5,
        },
        90: {
            'isim': 'Square',
            'etki': 'Struggle / Dynamism',
            'puan': -8,
        },
        120: {
            'isim': 'Trine',
            'etki': 'Natural Flow / Luck',
            'puan': 8,
        },
        60: {
            'isim': 'Sextile',
            'etki': 'Opportunity / Harmony',
            'puan': 5,
        },
    },
    'gezegen': {
        'ebeveyn': {
            'Güneş': 'identity, personality development and vital strength',
            'Ay': 'the emotional world, need for nourishment and instinct',
            'Merkür': 'communication, the learning process and mental development',
            'Venüs': 'values, love language and aesthetic sense',
            'Mars': 'courage to act, independence energy and anger management',
            'Jüpiter': 'expansion, abundance and the search for wisdom',
            'Satürn': 'structure, responsibility and the need for discipline',
            'Uranüs': 'desire for freedom, novelty and rebellion energy',
            'Neptün': 'imagination, spirituality and vulnerability',
            'Plüton': 'transformation, power structures and rebirth',
            'KAD': 'karmic mission, spiritual direction and the lesson of life',
            'GAD': 'the true self, inner guidance and Potential',
            'Chiron': 'healing, the wisdom of wounds and compassion',
            'Juno': 'attachment style, commitment and the need for security',
            'Ceres': 'nourishment, the protective instinct and motherhood energy',
            'Pallas': 'strategic mind, creative solutions and vision',
            'Vesta': 'inner focus, sacred devotion and perseverance',
            'Eros': 'passion, intensity of desire and action energy',
            'Psyche': 'psychic depth, vulnerability and the unconscious',
            'Sappho': 'sensitivity, aesthetic sense and emotional depth',
            'Amor': 'unconditional love, acceptance and the bond of the heart',
        },
        'normal': {
            'Güneş': 'self-awareness, identity and vital strength',
            'Ay': 'the emotional world, instinct and nourishment',
            'Merkür': 'communication, mental exchange and curiosity',
            'Venüs': 'love language, aesthetics and values',
            'Mars': 'passion, courage to act and physical attraction',
            'Jüpiter': 'expansion, abundance and spiritual growth',
            'Satürn': 'structure, responsibility and lasting commitment',
            'Uranüs': 'freedom, novelty and sudden changes',
            'Neptün': 'spirituality, imagination and unconditional love',
            'Plüton': 'transformation, power and spiritual rebirth',
            'KAD': 'the karmic node, spiritual mission and karmic bond',
            'GAD': 'the true self, spiritual guidance and the inner light',
            'Chiron': 'healing, vulnerability and compassion',
            'Juno': 'marital loyalty, partnership and commitment',
            'Ceres': 'nourishment, protection and motherhood energy',
            'Pallas': 'strategic mind, creative solutions and vision',
            'Vesta': 'adhara, sacred focus and the inner fire',
            'Eros': 'depth of desire, sexual attraction and passion',
            'Psyche': 'psychic depth, vulnerability and the unconscious bond',
            'Sappho': 'poetic sensitivity, aesthetic passion and emotional depth',
            'Amor': 'unconditional love, romantic fate and the bond of the heart',
        },
    },
    'dinamik': {
        'ebeveyn': {
            0: {
                'baslik': 'These two energies merge and create a shared field of growth',
                'aciklama': "In this conjunction, {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2} meet at the very same point. This union has a strong effect on {konu} within the parent-child bond. You complete each other's strengths and weaknesses in this area.",
                'konu_map': {
                    'Güneş': 'identity and personality development',
                    'Ay': 'emotional bond and nourishment',
                    'Merkür': 'communication and learning',
                    'Venüs': 'values and love language',
                    'Mars': 'independence and action',
                    'Jüpiter': 'expansion and wisdom',
                    'Satürn': 'structure and discipline',
                    'Uranüs': 'freedom and novelty',
                    'Neptün': 'imagination and spirituality',
                    'Plüton': 'transformation and power',
                },
            },
            60: {
                'baslik': 'There is a constructive bond of opportunity between these two energies',
                'aciklama': "In this sextile, there is a constructive bond of opportunity and support between {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2}. This harmony opens new doors to {konu} within the parent-child bond. All it takes to make use of this opportunity is to take a step together.",
                'konu_map': {
                    'Güneş': 'self and expression',
                    'Ay': 'emotional support and nourishment',
                    'Merkür': 'communication and learning',
                    'Venüs': 'values and beauty',
                    'Mars': 'independence and courage',
                    'Jüpiter': 'growth and abundance',
                    'Satürn': 'structure and discipline',
                    'Uranüs': 'novelty and freedom',
                    'Neptün': 'inspiration and spirituality',
                    'Plüton': 'transformation and strengthening',
                },
            },
            90: {
                'baslik': 'There is a constructive struggle between these two energies',
                'aciklama': "In this square, there is a constant tension and a push-pull dynamic between {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2}. This struggle creates a formative pressure on {konu} within the parent-child bond. The healthiest way to channel this energy is to set a shared goal.",
                'konu_map': {
                    'Güneş': 'ego and self',
                    'Ay': 'emotional security',
                    'Merkür': 'comprehension and understanding',
                    'Venüs': 'value and acceptance',
                    'Mars': 'independence and action',
                    'Jüpiter': 'faith and expansion',
                    'Satürn': 'responsibility and structure',
                    'Uranüs': 'freedom and routine',
                    'Neptün': 'reality and imagination',
                    'Plüton': 'power and control',
                },
            },
            120: {
                'baslik': 'There is a natural harmony flowing between these two energies',
                'aciklama': "In this trine, there is a natural harmony and flow between {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2}. This trio brings luck and ease to {konu} within the parent-child bond. You support each other's strengths in this area.",
                'konu_map': {
                    'Güneş': 'self-expression and strength',
                    'Ay': 'emotional flow and nourishment',
                    'Merkür': 'communication and mental harmony',
                    'Venüs': 'values and aesthetics',
                    'Mars': 'independence and action in tune',
                    'Jüpiter': 'growth and joy',
                    'Satürn': 'structure and support',
                    'Uranüs': 'freedom and novelty',
                    'Neptün': 'spirituality and inspiration',
                    'Plüton': 'transformation and depth',
                },
            },
            180: {
                'baslik': 'These two energies on opposite poles complete each other',
                'aciklama': "In this opposition, {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2} stand on opposite poles. This opposition constantly creates tension and awareness around {konu} within the parent-child bond. Accepting your opposite sides is the key to turning this energy into something constructive.",
                'konu_map': {
                    'Güneş': 'identity and self',
                    'Ay': 'emotional needs',
                    'Merkür': 'communication and thinking style',
                    'Venüs': 'sense of values',
                    'Mars': 'independence and action',
                    'Jüpiter': 'expansion and faith',
                    'Satürn': 'structure and responsibility',
                    'Uranüs': 'freedom and change',
                    'Neptün': 'reality and imagination',
                    'Plüton': 'power and control',
                },
            },
        },
        'normal': {
            0: {
                'baslik': 'These two energies merge and create a shared force',
                'aciklama': "In this conjunction, {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2} meet at the very same point. This union has a strong effect on {konu} within your relationship. You complete each other's strengths and weaknesses in this area.",
                'konu_map': {
                    'Güneş': 'self-awareness and expression',
                    'Ay': 'emotional bond and nourishment',
                    'Merkür': 'communication and comprehension',
                    'Venüs': 'love and values',
                    'Mars': 'passion and action',
                    'Jüpiter': 'growth and abundance',
                    'Satürn': 'structure and commitment',
                    'Uranüs': 'freedom and novelty',
                    'Neptün': 'spirituality and dreams',
                    'Plüton': 'transformation and power',
                },
            },
            60: {
                'baslik': 'There is a constructive bond of opportunity between these two energies',
                'aciklama': "In this sextile, there is a constructive bond of opportunity and support between {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2}. This harmony opens new doors to {konu} within your relationship. All it takes to make use of this opportunity is to take a step together.",
                'konu_map': {
                    'Güneş': 'personal power and expression',
                    'Ay': 'emotional support and nourishment',
                    'Merkür': 'communication and learning',
                    'Venüs': 'love and beauty',
                    'Mars': 'passion and courage',
                    'Jüpiter': 'growth and abundance',
                    'Satürn': 'structure and discipline',
                    'Uranüs': 'novelty and freedom',
                    'Neptün': 'inspiration and spirituality',
                    'Plüton': 'transformation and strengthening',
                },
            },
            90: {
                'baslik': 'There is a constructive struggle between these two energies',
                'aciklama': "In this square, there is a constant tension and a push-pull dynamic between {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2}. This struggle creates a formative pressure on {konu} within your relationship. The healthiest way to channel this energy is to set a shared goal.",
                'konu_map': {
                    'Güneş': 'ego and self',
                    'Ay': 'emotional security',
                    'Merkür': 'comprehension and understanding',
                    'Venüs': 'value and acceptance',
                    'Mars': 'action and passion',
                    'Jüpiter': 'faith and expansion',
                    'Satürn': 'responsibility and structure',
                    'Uranüs': 'freedom and routine',
                    'Neptün': 'reality and imagination',
                    'Plüton': 'power and control',
                },
            },
            120: {
                'baslik': 'There is a natural harmony flowing between these two energies',
                'aciklama': "In this trine, there is a natural harmony and flow between {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2}. This trio brings luck and ease to {konu} within your relationship. You support each other's strengths in this area.",
                'konu_map': {
                    'Güneş': 'self-expression and strength',
                    'Ay': 'emotional flow and nourishment',
                    'Merkür': 'communication and mental harmony',
                    'Venüs': 'values and aesthetics',
                    'Mars': 'passion and action in tune',
                    'Jüpiter': 'growth and joy',
                    'Satürn': 'structure and support',
                    'Uranüs': 'freedom and novelty',
                    'Neptün': 'spirituality and inspiration',
                    'Plüton': 'transformation and depth',
                },
            },
            180: {
                'baslik': 'These two energies on opposite poles complete each other',
                'aciklama': "In this opposition, {p1}'s energy of {anlam1} and {p2}'s energy of {anlam2} stand on opposite poles. This opposition constantly creates tension and awareness around {konu} within your relationship. Accepting your opposite sides is the key to turning this energy into something constructive.",
                'konu_map': {
                    'Güneş': 'self and style of expression',
                    'Ay': 'emotional needs',
                    'Merkür': 'communication and thinking style',
                    'Venüs': 'love and sense of values',
                    'Mars': 'action and language of passion',
                    'Jüpiter': 'expansion and faith',
                    'Satürn': 'structure and responsibility',
                    'Uranüs': 'freedom and change',
                    'Neptün': 'reality and imagination',
                    'Plüton': 'power and control',
                },
            },
        },
    },
    'ders': 'Lesson',
    'muhur': 'Seal',
    'temas': 'Contact Theme',
    'sifa': 'Remedy',
    'baslik_dersler': '💊 KARMIC LESSONS AND HEALING SUGGESTIONS',
    'baslik_receteler': '💊 KARMIC HEALING RECIPES',
    'baslik_planet_etkilesimleri': 'PLANETARY INTERACTIONS',
    'bos_mesaj': 'No major synastry interaction was detected.',
    'recete_yok': 'Your current karmic contacts do not require an urgent healing recipe. Stay in your natural flow.',
    'fallback_ebeveyn': 'the basic structures of the parent-child bond',
    'fallback_normal': 'the basic structures of your relationship',
    'fallback_enerji': 'energy',
    'aktivite': 'Choose a shared activity and channel this tense energy into a constructive field.',
    'hobi': 'Adopt a shared hobby and channel this tense energy into a constructive field.',
}

ES = {
    'acilar': {
        0: {
            'isim': 'Conjunción',
            'etki': 'Unión Potente',
            'puan': 10,
        },
        180: {
            'isim': 'Oposición',
            'etki': 'Conciencia / Tensión',
            'puan': -5,
        },
        90: {
            'isim': 'Cuadratura',
            'etki': 'Esfuerzo / Dinamismo',
            'puan': -8,
        },
        120: {
            'isim': 'Trígono',
            'etki': 'Flujo Natural / Suerte',
            'puan': 8,
        },
        60: {
            'isim': 'Sextil',
            'etki': 'Oportunidad / Armonía',
            'puan': 5,
        },
    },
    'gezegen': {
        'ebeveyn': {
            'Güneş': 'identidad, desarrollo de la personalidad y fuerza vital',
            'Ay': 'el mundo emocional, la necesidad de nutrición y el instinto',
            'Merkür': 'comunicación, el proceso de aprendizaje y el desarrollo mental',
            'Venüs': 'valores, lenguaje del amor y sentido estético',
            'Mars': 'valor para actuar, energía de independencia y gestión de la ira',
            'Jüpiter': 'expansión, abundancia y búsqueda de sabiduría',
            'Satürn': 'estructura, responsabilidad y necesidad de disciplina',
            'Uranüs': 'deseo de libertad, novedad y energía de rebeldía',
            'Neptün': 'imaginación, espiritualidad y vulnerabilidad',
            'Plüton': 'transformación, estructuras de poder y renacimiento',
            'KAD': 'misión kármica, dirección espiritual y lección de vida',
            'GAD': 'el verdadero yo, guía interior y el Potencial',
            'Chiron': 'sanación, sabiduría de las heridas y compasión',
            'Juno': 'estilo de apego, compromiso y necesidad de seguridad',
            'Ceres': 'nutrición, instinto protector y energía materna',
            'Pallas': 'mente estratégica, soluciones creativas y visión',
            'Vesta': 'foco interior, devoción sagrada y perseverancia',
            'Eros': 'pasión, intensidad del deseo y energía de acción',
            'Psyche': 'profundidad psíquica, vulnerabilidad y el inconsciente',
            'Sappho': 'sensibilidad, sentido estético y profundidad emocional',
            'Amor': 'amor incondicional, aceptación y vínculo del corazón',
        },
        'normal': {
            'Güneş': 'autoconciencia, identidad y fuerza vital',
            'Ay': 'el mundo emocional, el instinto y la nutrición',
            'Merkür': 'comunicación, intercambio mental y curiosidad',
            'Venüs': 'lenguaje del amor, estética y valores',
            'Mars': 'pasión, valor para actuar y atracción física',
            'Jüpiter': 'expansión, abundancia y crecimiento espiritual',
            'Satürn': 'estructura, responsabilidad y compromiso duradero',
            'Uranüs': 'libertad, novedad y cambios repentinos',
            'Neptün': 'espiritualidad, imaginación y amor incondicional',
            'Plüton': 'transformación, poder y renacimiento espiritual',
            'KAD': 'el nudo kármico, misión espiritual y vínculo kármico',
            'GAD': 'el verdadero yo, guía espiritual y la luz interior',
            'Chiron': 'sanación, vulnerabilidad y compasión',
            'Juno': 'lealtad matrimonial, asociación y compromiso',
            'Ceres': 'nutrición, protección y energía materna',
            'Pallas': 'mente estratégica, soluciones creativas y visión',
            'Vesta': 'adhara, foco sagrado y el fuego interior',
            'Eros': 'profundidad del deseo, atracción sexual y pasión',
            'Psyche': 'profundidad psíquica, vulnerabilidad y vínculo inconsciente',
            'Sappho': 'sensibilidad poética, pasión estética y profundidad emocional',
            'Amor': 'amor incondicional, destino romántico y vínculo del corazón',
        },
    },
    'dinamik': {
        'ebeveyn': {
            0: {
                'baslik': 'Estas dos energías se unen y crean un campo común de crecimiento',
                'aciklama': 'En esta conjunción, la energía de {anlam1} de {p1} y la de {anlam2} de {p2} se encuentran en el mismo punto. Esta unión tiene un efecto fuerte sobre {konu} dentro del vínculo padre-madre/hijo. Se completan mutuamente sus fortalezas y debilidades en esta área.',
                'konu_map': {
                    'Güneş': 'identidad y desarrollo de la personalidad',
                    'Ay': 'vínculo emocional y nutrición',
                    'Merkür': 'comunicación y aprendizaje',
                    'Venüs': 'valores y lenguaje del amor',
                    'Mars': 'independencia y acción',
                    'Jüpiter': 'expansión y sabiduría',
                    'Satürn': 'estructura y disciplina',
                    'Uranüs': 'libertad y novedad',
                    'Neptün': 'imaginación y espiritualidad',
                    'Plüton': 'transformación y poder',
                },
            },
            60: {
                'baslik': 'Entre estas dos energías hay un vínculo constructivo de oportunidad',
                'aciklama': 'En este sextil, hay un vínculo constructivo de oportunidad y apoyo entre la energía de {anlam1} de {p1} y la de {anlam2} de {p2}. Esta armonía abre nuevas puertas a {konu} dentro del vínculo padre-madre/hijo. Para aprovechar esta oportunidad basta con dar un paso juntos.',
                'konu_map': {
                    'Güneş': 'yo y expresión',
                    'Ay': 'apoyo emocional y nutrición',
                    'Merkür': 'comunicación y aprendizaje',
                    'Venüs': 'valores y belleza',
                    'Mars': 'independencia y valentía',
                    'Jüpiter': 'crecimiento y abundancia',
                    'Satürn': 'estructura y disciplina',
                    'Uranüs': 'novedad y libertad',
                    'Neptün': 'inspiración y espiritualidad',
                    'Plüton': 'transformación y fortalecimiento',
                },
            },
            90: {
                'baslik': 'Entre estas dos energías hay una lucha constructiva',
                'aciklama': 'En esta cuadratura, existe una tensión constante y una dinámica de atracción y rechazo entre la energía de {anlam1} de {p1} y la de {anlam2} de {p2}. Esta lucha genera una presión formativa sobre {konu} dentro del vínculo padre-madre/hijo. La forma más sana de canalizar esta energía es definir un objetivo común.',
                'konu_map': {
                    'Güneş': 'ego y yo',
                    'Ay': 'seguridad emocional',
                    'Merkür': 'comprensión y entendimiento',
                    'Venüs': 'valor y aceptación',
                    'Mars': 'independencia y acción',
                    'Jüpiter': 'fe y expansión',
                    'Satürn': 'responsabilidad y estructura',
                    'Uranüs': 'libertad y rutina',
                    'Neptün': 'realidad e imaginación',
                    'Plüton': 'poder y control',
                },
            },
            120: {
                'baslik': 'Entre estas dos energías fluye una armonía natural',
                'aciklama': 'En este trígono, existe una armonía y un flujo natural entre la energía de {anlam1} de {p1} y la de {anlam2} de {p2}. Este trío aporta suerte y facilidad en {konu} dentro del vínculo padre-madre/hijo. Se apoyan mutuamente sus puntos fuertes en esta área.',
                'konu_map': {
                    'Güneş': 'expresión del yo y fuerza',
                    'Ay': 'flujo emocional y nutrición',
                    'Merkür': 'comunicación y armonía mental',
                    'Venüs': 'valores y estética',
                    'Mars': 'independencia y acción afinada',
                    'Jüpiter': 'crecimiento y alegría',
                    'Satürn': 'estructura y apoyo',
                    'Uranüs': 'libertad y novedad',
                    'Neptün': 'espiritualidad e inspiración',
                    'Plüton': 'transformación y profundidad',
                },
            },
            180: {
                'baslik': 'Estas dos energías, en polos opuestos, se complementan',
                'aciklama': 'En esta oposición, la energía de {anlam1} de {p1} y la de {anlam2} de {p2} se sitúan en polos opuestos. Esta oposición genera de forma constante tensión y conciencia en {konu} dentro del vínculo padre-madre/hijo. Aceptar tus lados opuestos es la clave para convertir esta energía en algo constructivo.',
                'konu_map': {
                    'Güneş': 'identidad y yo',
                    'Ay': 'necesidades emocionales',
                    'Merkür': 'comunicación y estilo de pensamiento',
                    'Venüs': 'percepción de los valores',
                    'Mars': 'independencia y acción',
                    'Jüpiter': 'expansión y fe',
                    'Satürn': 'estructura y responsabilidad',
                    'Uranüs': 'libertad y cambio',
                    'Neptün': 'realidad e imaginación',
                    'Plüton': 'poder y control',
                },
            },
        },
        'normal': {
            0: {
                'baslik': 'Estas dos energías se unen y crean una fuerza común',
                'aciklama': 'En esta conjunción, la energía de {anlam1} de {p1} y la de {anlam2} de {p2} se encuentran en el mismo punto. Esta unión tiene un efecto fuerte sobre {konu} dentro de su relación. Se completan mutuamente sus fortalezas y debilidades en esta área.',
                'konu_map': {
                    'Güneş': 'autoconciencia y expresión',
                    'Ay': 'vínculo emocional y nutrición',
                    'Merkür': 'comunicación y comprensión',
                    'Venüs': 'amor y valores',
                    'Mars': 'pasión y acción',
                    'Jüpiter': 'crecimiento y abundancia',
                    'Satürn': 'estructura y compromiso',
                    'Uranüs': 'libertad y novedad',
                    'Neptün': 'espiritualidad y sueños',
                    'Plüton': 'transformación y poder',
                },
            },
            60: {
                'baslik': 'Entre estas dos energías hay un vínculo constructivo de oportunidad',
                'aciklama': 'En este sextil, hay un vínculo constructivo de oportunidad y apoyo entre la energía de {anlam1} de {p1} y la de {anlam2} de {p2}. Esta armonía abre nuevas puertas a {konu} dentro de su relación. Para aprovechar esta oportunidad basta con dar un paso juntos.',
                'konu_map': {
                    'Güneş': 'poder personal y expresión',
                    'Ay': 'apoyo emocional y nutrición',
                    'Merkür': 'comunicación y aprendizaje',
                    'Venüs': 'amor y belleza',
                    'Mars': 'pasión y valentía',
                    'Jüpiter': 'crecimiento y abundancia',
                    'Satürn': 'estructura y disciplina',
                    'Uranüs': 'novedad y libertad',
                    'Neptün': 'inspiración y espiritualidad',
                    'Plüton': 'transformación y fortalecimiento',
                },
            },
            90: {
                'baslik': 'Entre estas dos energías hay una lucha constructiva',
                'aciklama': 'En esta cuadratura, existe una tensión constante y una dinámica de atracción y rechazo entre la energía de {anlam1} de {p1} y la de {anlam2} de {p2}. Esta lucha genera una presión formativa sobre {konu} dentro de su relación. La forma más sana de canalizar esta energía es definir un objetivo común.',
                'konu_map': {
                    'Güneş': 'ego y yo',
                    'Ay': 'seguridad emocional',
                    'Merkür': 'comprensión y entendimiento',
                    'Venüs': 'valor y aceptación',
                    'Mars': 'acción y pasión',
                    'Jüpiter': 'fe y expansión',
                    'Satürn': 'responsabilidad y estructura',
                    'Uranüs': 'libertad y rutina',
                    'Neptün': 'realidad e imaginación',
                    'Plüton': 'poder y control',
                },
            },
            120: {
                'baslik': 'Entre estas dos energías fluye una armonía natural',
                'aciklama': 'En este trígono, existe una armonía y un flujo natural entre la energía de {anlam1} de {p1} y la de {anlam2} de {p2}. Este trío aporta suerte y facilidad en {konu} dentro de su relación. Se apoyan mutuamente sus puntos fuertes en esta área.',
                'konu_map': {
                    'Güneş': 'expresión del yo y fuerza',
                    'Ay': 'flujo emocional y nutrición',
                    'Merkür': 'comunicación y armonía mental',
                    'Venüs': 'valores y estética',
                    'Mars': 'pasión y acción afinada',
                    'Jüpiter': 'crecimiento y alegría',
                    'Satürn': 'estructura y apoyo',
                    'Uranüs': 'libertad y novedad',
                    'Neptün': 'espiritualidad e inspiración',
                    'Plüton': 'transformación y profundidad',
                },
            },
            180: {
                'baslik': 'Estas dos energías, en polos opuestos, se complementan',
                'aciklama': 'En esta oposición, la energía de {anlam1} de {p1} y la de {anlam2} de {p2} se sitúan en polos opuestos. Esta oposición genera de forma constante tensión y conciencia en {konu} dentro de su relación. Aceptar tus lados opuestos es la clave para convertir esta energía en algo constructivo.',
                'konu_map': {
                    'Güneş': 'yo y estilo de expresión',
                    'Ay': 'necesidades emocionales',
                    'Merkür': 'comunicación y estilo de pensamiento',
                    'Venüs': 'amor y percepción de los valores',
                    'Mars': 'acción y lenguaje de la pasión',
                    'Jüpiter': 'expansión y fe',
                    'Satürn': 'estructura y responsabilidad',
                    'Uranüs': 'libertad y cambio',
                    'Neptün': 'realidad e imaginación',
                    'Plüton': 'poder y control',
                },
            },
        },
    },
    'ders': 'Lección',
    'muhur': 'Sello',
    'temas': 'Tema de Contacto',
    'sifa': 'Remedio',
    'baslik_dersler': '💊 LECCIONES KÁRMICAS Y SUGERENCIAS DE SANACIÓN',
    'baslik_receteler': '💊 RECETAS DE SANACIÓN KÁRMICA',
    'baslik_planet_etkilesimleri': 'INTERACCIONES PLANETARIAS',
    'bos_mesaj': 'No se detectó ninguna interacción principal de sinastría.',
    'recete_yok': 'Sus contactos kármicos actuales no requieren un remedio urgente. Permanezca en su flujo natural.',
    'fallback_ebeveyn': 'las estructuras básicas del vínculo padre-madre/hijo',
    'fallback_normal': 'las estructuras básicas de su relación',
    'fallback_enerji': 'energía',
    'aktivite': 'Elijan una actividad compartida y canalicen esta energía tensa hacia un campo constructivo.',
    'hobi': 'Adopten un pasatiempo compartido y canalicen esta energía tensa hacia un campo constructivo.',
}


_DILLER = {"tr": TR, "en": EN, "es": ES}


def m(dil_adi=None):
    """Aktif dile gore metin sozlugunu dondurur (bulunamazsa TR)."""
    if dil_adi is None:
        try:
            import i18n
            dil_adi = i18n.get_lang()
        except Exception:
            dil_adi = "tr"
    return _DILLER.get(dil_adi, TR)
