# -*- coding: utf-8 -*-
"""
Her gezegenin her evdeki ILISKI-DILLI yorumu (BAGIL HARITA baglamma).
Format: {("Gezegen", "Ev No"): "Yorum metni"}

Bu yorumlar bagil harita analizinde kullanilir (fallback sozluk).
Her yorum kisiye ozel, somut, iliski odaklidir.
"Bu donemde" kalibi KULLANILMAZ (bagil harita olunecektir).
"""

FBST_YORUMLAR_EV = {
    # === GUNES — Kisinin iliskideki kimligi, nasil parladigi ===
    ("Güneş", "1"): "Siz bu iliskide kendinizi cesur ve acik bir sekilde ifade ediyorsunuz. Iliskinin yonunu siz belirliyor, kimliginizi iliskiye tam olarak yansitiyorsunuz. Partneriniz bu dogrudanlginizi ve ozguveninizi seviyor ama bazen cok on plana cikmaniz endise yaratiyor. Iliskide kendi benliginizi korumak cok onemli. Dengeli bir bicimde one ciktiginda bu iliskinin en parlak yildizi siz oluyorsunuz.",
    ("Güneş", "2"): "Siz bu iliskide degerlerinizi ve somut gucunuzu on plana cikiyorsunuz. Maddi guvenlik, kaliteli zaman ve somut sevgi dili iliskinizin temelini olusturuyor. Partneriniz guvenilirliginizi ve cimcirliginizi seviyor ama sahipci olmaniz zaman zaman sorun yaratiyor. Iliskide deger paylasimi cok onemli. Somut degerlerinizi paylastikca bu iliskinin en guvenceli temelini siz insa ediyorsunuz.",
    ("Güneş", "3"): "Siz bu iliskide iletisim ve zihinsel canlilik uzerine parliyorsunuz. Konusmak, ogrenmek, paylasmak iliskinizin yakıtı. Partneriniz zekanizi ve eglenceli iletisim tarzinizi seviyor ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Iliskide bilgi alisverisi cok onemli. Dengeli iletisim kurdugnuzda bu iliskinin en parlak iletisim kaynagi siz oluyorsunuz.",
    ("Güneş", "4"): "Siz bu iliskide ev, yuva ve kokenler uzerine parliyorsunuz. Sicak bir yuva kurmak, aile degerlerini yasatmak iliskinizin temelini olusturuyor. Partneriniz sicakliginizi ve koruyuculugunuzu seviyor ama asiri baglanmaniz zaman zaman bunaltabiliyor. Iliskide guvenli bir yuva olusturmak cok onemli. Duygusal baglari guclendirdiginizde bu iliskinin en sicak yuva kurucusu siz oluyorsunuz.",
    ("Güneş", "5"): "Siz bu iliskide yaraticilik, eglence ve tutku uzerine parliyorsunuz. Iliskiyi eglenceli, canli ve tutkulu kilmak icin elinizden geleni yapiyorsunuz. Partneriniz cimcirliginizi ve enerjinizi seviyor ama ego caprasmalariniz zaman zaman gerilim yaratiyor. Iliskide surprizler ve yenilikler cok onemli. Duygusal baglari da guclendirdiginizde bu iliskinin en buyuk eglence kaynagi siz oluyorsunuz.",
    ("Güneş", "6"): "Siz bu iliskide duzen, pratik cozumler ve hizmet uzerine parliyorsunuz. Iliskiyi gunluk adimlarla, kucuk dokunuslarla, yardimci olarak yurutuyorsunuz. Partneriniz caliskanliginizi ve sadakatinizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Iliskide pratik destek cok onemli. Ovgunuzu da ifade ettiginizde bu iliskinin en guvenilir destekcisi siz oluyorsunuz.",
    ("Güneş", "7"): "Siz bu iliskide iliskinin kendisi uzerine parliyorsunuz — ortaklik, denge ve karsiliklilik iliskinizin temelini olusturuyor. Partnerinizle esit bir sekilde yol almak cok onemli. Partneriniz uyum yeteneginizi ve zarafetinizi seviyor ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskide esitlik cok onemli. Net kararlar aldiginda bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Güneş", "8"): "Siz bu iliskide donusum, derinlik ve guc uzerine parliyorsunuz. Iliskiyi derinden donusturuyor, yuzeysel kalmamayi basariyorsunuz. Partneriniz derinliginizi ve tutkunuzu seviyor ama kontrolculugunuzden korkabiliyor. Iliskide guven ve sadakat cok onemli. Guvenmeyi ogrendiginizde bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Güneş", "9"): "Siz bu iliskide anlam, felsefe ve genis perspektif uzerine parliyorsunuz. Buyuk resmi goruyor, iliskiyi daha genis bir cercevede ele aliyorsunuz. Partneriniz iyimserliginizi ve vizyonunuza hayran ama somut adimlar atmamaniz zaman zaman sorun yaratiyor. Iliskide buyuk hayaller kurmak cok onemli. Topraklandiginizda bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Güneş", "10"): "Siz bu iliskide kariyer, statu ve uzun vadeli hedefler uzerine parliyorsunuz. Iliskiyi ciddiye aliyor, uzun vadeli planlar yapiyorsunuz. Partneriniz kararliliginizi ve guvenilirliginizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Iliskide uzun vadeli vizyon cok onemli. Duygusal paylasimlari da arttirdiginizda bu iliskinin en guvenilir destekcisi siz oluyorsunuz.",
    ("Güneş", "11"): "Siz bu iliskide ozgurluk, esitlik ve toplumsal vizyon uzerine parliyorsunuz. Iliskiyi arkadaslik temelinde kuruyor, esitlik ve ozgurluk on planda. Partneriniz vizyonunuza ve ozgunlugunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskide arkadaslik cok onemli. Sicaklastiginizda bu iliskinin en ozel arkadaslik bagini siz kuruyorsunuz.",
    ("Güneş", "12"): "Siz bu iliskide maneviyat, sezgi ve bilincdisi uzerine parliyorsunuz. Iliskiyi ruhsal bir boyutta yasiyor, derin sezgilerinizle hareket ediyorsunuz. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskide sinir koymak cok onemli. Sinir koydugunuzda bu iliskinin en guclu ruhsal bagini siz kuruyorsunuz.",

    # === AY — Duygusal ihtiyaclar, guvende hissettigi yer ===
    ("Ay", "1"): "Duygusal olarak iliskide kendinizi acik ve savunmasiz hissediyorsunuz. Duygulariniz disariya cok yansıyor, her hissinizi partnerinizle paylaşıyorsunuz. Partneriniz bu aciklginizi seviyor ama asiri duyarli olmaniz zaman zaman yorabiliyor. Iliskide duygusal aciklik cok onemli. Duygusal dengenizi korudugunuzda bu iliskinin en sicak kalbini siz olusturuyorsunuz.",
    ("Ay", "2"): "Duygusal olarak maddi guvenlik ve somut degerler uzerine kurulu bir guvene ihtiyaciniz var. Iliskide parasal konular, ev alisverisleri, yemek gibi somut seyler duygusal dengeniz icin cok onemli. Partneriniz guvenilirliginizi seviyor ama sahipci olmaniz zaman zaman sorun yaratiyor. Iliskide somut destek cok onemli. Duygusal baglari da guclendirdiginizde bu iliskinin en guvenli kaynagi siz oluyorsunuz.",
    ("Ay", "3"): "Duygusal olarak konusarak, paylasarak ve ogrenerek besleniyorsunuz. Iliskide iletisim cok onemli — duygularinizi kelimelerle ifade ediyorsunuz. Partneriniz zihinsel canliliginizi seviyor ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Iliskide bilgi alisverisi cok onemli. Duygusal derinligi de kattiginizda bu iliskinin en parlak iletisim koprusunu siz kuruyorsunuz.",
    ("Ay", "4"): "Duygusal olarak ev, yuva ve kokenler uzerine kurulu bir guvene ihtiyaciniz var. Iliskide sicak bir yuva, guvenli bir liman cok onemli. Partneriniz sicakliginizi ve koruyuculugunuzu seviyor ama asiri baglanmaniz zaman zaman bunaltabiliyor. Iliskide guvenli bir yuva olusturmak cok onemli. Duygusal baglari guclendirdiginizde bu iliskinin en sicak yuva kurucusu siz oluyorsunuz.",
    ("Ay", "5"): "Duygusal olarak yaraticilik, eglence ve tutku uzerine kurulu bir guvene ihtiyaciniz var. Iliskide surprizler, eglence ve tutku cok onemli. Partneriniz cimcirliginizi ve enerjinizi seviyor ama ego caprasmalariniz zaman zaman gerilim yaratiyor. Iliskide eglenceli zaman gecirmek cok onemli. Duygusal baglari da guclendirdiginizde bu iliskinin en buyuk eglence kaynagi siz oluyorsunuz.",
    ("Ay", "6"): "Duygusal olarak duzen, pratik cozumler ve hizmet uzerine kurulu bir guvene ihtiyaciniz var. Iliskide gunluk rutinler, pratik destek cok onemli. Partneriniz caliskanliginizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Iliskide pratik destek cok onemli. Ovgunuzu da ifade ettiginizde bu iliskinin en guvenilir destekcisi siz oluyorsunuz.",
    ("Ay", "7"): "Duygusal olarak iliskinin kendisi uzerine kurulu bir guvene ihtiyaciniz var. Partnerinizle olan bag cok onemli — denge, esitlik ve karsiliklilik cok degerli. Partneriniz uyum yeteneginizi seviyor ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskide esitlik cok onemli. Net kararlar aldiginda bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Ay", "8"): "Duygusal olarak donusum, derinlik ve guc uzerine kurulu bir guvene ihtiyaciniz var. Iliskide derin duygusal baglar cok onemli. Partneriniz derinliginizi seviyor ama kontrolculugunuzden korkabiliyor. Iliskide guven ve sadakat cok onemli. Guvenmeyi ogrendiginizde bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Ay", "9"): "Duygusal olarak anlam, felsefe ve genis perspektif uzerine kurulu bir guvene ihtiyaciniz var. Iliskide buyuk resmi gormek cok onemli. Partneriniz iyimserliginizi seviyor ama somut adimlar atmamaniz zaman zaman sorun yaratiyor. Iliskide buyuk hayaller kurmak cok onemli. Topraklandiginizda bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Ay", "10"): "Duygusal olarak kariyer, statu ve uzun vadeli hedefler uzerine kurulu bir guvene ihtiyaciniz var. Iliskide ciddiyet ve sorumluluk cok onemli. Partneriniz kararliliginizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Iliskide uzun vadeli vizyon cok onemli. Duygusal paylasimlari da arttirdiginizda bu iliskinin en guvenilir destekcisi siz oluyorsunuz.",
    ("Ay", "11"): "Duygusal olarak ozgurluk, esitlik ve toplumsal vizyon uzerine kurulu bir guvene ihtiyaciniz var. Iliskide arkadaslik temeli cok onemli. Partneriniz vizyonunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskide arkadaslik cok onemli. Sicaklastiginizda bu iliskinin en ozel arkadaslik bagini siz kuruyorsunuz.",
    ("Ay", "12"): "Duygusal olarak maneviyat, sezgi ve bilincdisi uzerine kurulu bir guvene ihtiyaciniz var. Iliskide derin ruhsal baglar cok onemli. Partneriniz merhametinizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskide sinir koymak cok onemli. Sinir koydugunuzda bu iliskinin en guclu ruhsal bagini siz kuruyorsunuz.",

    # === MERKUR — Iletisim dili, nasil anladigi/konusma bicimi ===
    ("Merkür", "1"): "Iletisimde kendinizi acik ve dogrudan ifade ediyorsunuz. Iliskide kelimelerinizi dogrudan kullaniyorsunuz — bu durustulugunuz partnerinizi bazen urkutebiliyor. Partneriniz zekanizi ve cabuklugunuzu seviyor ama sert cikislarinizdan sarsilabiliyor. Iliskide net iletisim cok onemli. Kelimelerinizi secmeyi ogrendiginizde bu iliskinin en guclu iletisim motoru siz oluyorsunuz.",
    ("Merkür", "2"): "Iletisimde somut, guvenilir ve pratik bir dille konusuyorsunuz. Her soylediginin arkasinda duran, bos konusmayan bir yapınız var. Partneriniz bu guvenilirliginize hayran ama konusma hizinizin yavasligi zaman zaman sabirsizlik yaratiyor. Iliskide somut konular, pratik cozumler onemli. Duygusal konulari da konusmayi ogrendiginizde bu iliskinin en saglam iletisim koprusunu siz kuruyorsunuz.",
    ("Merkür", "3"): "Iletisimde cok yonlu, espirili ve zihinsel olarak canli bir dille konusuyorsunuz. Iliskiyi konusarak, ogrenerek, paylasarak yurutuyorsunuz. Partneriniz zekaniza ve esprilerinize hayran ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Iliskide bilgi alisverisi cok yuki. Dinlemeyi de ogrendiginizde bu iliskinin en parlak iletisim koprusunu siz kuruyorsunuz.",
    ("Merkür", "4"): "Iletisimde duygusal, empatik ve hassas bir dille konusuyorsunuz. Karsinizdakinin hislerini hemen anlıyorsunuz ama kendi duygularinizi acmakta zorlanabiliyorsunuz. Partneriniz empati yeteneginizi seviyor ama bazen cok kapali kalmanizdan sikayet edebiliyor. Iliskide gecmis konulari tekrar etme egiliminiz var. Gecmisi birakip bugune odaklandiginizda bu iliskinin en derin anlayis koprusunu siz kuruyorsunuz.",
    ("Merkür", "5"): "Iletisimde gosterisli, etkileyici ve sahne aldiran bir dille konusuyorsunuz. Fikirlerinizi sunma biciminiz cok guclu — partnerinizi ikna etme kapasiteniz yuksek. Partneriniz hitabetinizi seviyor ama her konuda hakli olma ısrarınız zaman zaman gerilim yaratiyor. Iliskide dinlemek de cok onemli. Karsi tarafin da fikrini onemsediginizde bu iliskinin en buyuk sahne sanatcisi siz oluyorsunuz.",
    ("Merkür", "6"): "Iletisimde analitik, detayci ve elestirel bir dille konusuyorsunuz. Her seyi ince ince analiz ediyorsunuz — bu durum iliskide hem guclu hem de yorucu olabiliyor. Partneriniz zekanizin derinligini seviyor ama elestirilerinizin cogunlugundan yorulabiliyor. Iliskide kucuk detaylari buyutme egiliminiz var. Ovgunuzu da ifade ettiginizde bu iliskinin en ince gozlemcisi siz oluyorsunuz.",
    ("Merkür", "7"): "Iletisimde dengeli, zarif ve adil bir dille konusuyorsunuz. Her iki tarafin da gorusunu dinleyip dengelemeye calisiyorsunuz. Partneriniz adalet duygunuza ve zarafetinize hayran ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskide net kararlar almakta zorlanabiliyorsunuz. Netlastiginizde bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Merkür", "8"): "Iletisimde derin, arastirici ve stratejik bir dille konusuyorsunuz. Yuzeyde kalmak size yetmiyor — her konuyu en derinine inecek sekilde analiz ediyorsunuz. Partneriniz zekanizin derinligini seviyor ama sirlar saklamaniz ve stratejik durusunuz zaman zaman guvensizlik yaratiyor. Iliskide acik ve seffaf olmak cok onemli. Sirlarini paylastiginizda bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Merkür", "9"): "Iletisimde genis, felsefi ve iyimser bir dille konusuyorsunuz. Buyuk resmi goruyor, detaylarda kaybolmuyorsunuz. Partneriniz iyimserliginizi ve genis perspektifinizi seviyor ama bazen cok genel kalmaniz somut cozumleri geciktiriyor. Iliskide buyuk hayaller kurmak onemli ama ayaklar yere de basmali. Somut adimlar attiginizda bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Merkür", "10"): "Iletisimde ciddi, stratejik ve yapilandirici bir dille konusuyorsunuz. Plan yapmayi, programlamayi, somut adimlar belirlemeyi seviyorsunuz. Partneriniz bu ciddiyetinizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Iliskide duygulari da konusmak gerekiyor. Duygusal paylasimlari da arttirdiginizda bu iliskinin en guclu stratejisti siz oluyorsunuz.",
    ("Merkür", "11"): "Iletisimde ozgun, yenilikci ve siradisi bir dille konusuyorsunuz. Geleneksel dusunce kaliplarina uymuyorsunuz — fikirleriniz her zaman farkli ve ilginc. Partneriniz vizyonunuza ve ozgunlugunuza hayran ama mesafeli iletisim tarziniz sogukluk yaratabiliyor. Iliskide yakin iletisim de cok onemli. Sicaklastiginizda bu iliskinin en ozel ve farkli iletisim bagini siz kuruyorsunuz.",
    ("Merkür", "12"): "Iletisimde sezgisel, yaratici ve hayal gucu guclu bir dille konusuyorsunuz. Mantiksel analizden cok sezgisel kavrama gucunuz yuksek. Partneriniz hayal gucunuzu seviyor ama kelimelerinizi net secmekte zorlanmaniz anlasilmazlik yaratiyor. Iliskide net ve acik olmak cok onemli. Duygularinizi netlestirdiginizde bu iliskinin en derin ruhsal bagini siz kuruyorsunuz.",

    # === VENUS — Sevgi dili, nasil sevdigi ===
    ("Venüs", "1"): "Sevgiyi kendinizi acik ve ozguvenli bir sekilde ifade ederek gosteriyorsunuz. Iliskide cekiciligniz ve kisisel manyetizmaniz cok guclu. Partneriniz dogrudanlginizi ve ozguveninizi seviyor ama cok on plana cikmaniz zaman zaman sorun yaratiyor. Iliskide esitlik cok onemli. Diger tarafin da parlamaine izin verdiginizde bu iliskinin en buyuk sevgi sahnesini siz insa ediyorsunuz.",
    ("Venüs", "2"): "Sevgiyi somut eylemlerle, dokunarak, yemek yaparak, yaninda olarak gosteriyorsunuz. Iliskide maddi guvenlik ve fiziksel konfor cok onemli. Partneriniz guvenilirliginizi ve cimcirliginizi seviyor ama sahipci olmaniz zaman zaman sorun yaratiyor. Iliskide guzel seylerin tadini cikarmak cok onemli. Sevginizi paylastikca buyuyen bir iliski insa ediyorsunuz.",
    ("Venüs", "3"): "Sevgiyi sohbet, espri ve zihinsel uyumla gosteriyorsunuz. Entelektuel bag sizin icin fiziksel cekim kadar onemli. Partneriniz zekanizi ve eglenceli iletisim tarzinizi seviyor ama cok degisken olmaniz guvensizlik yaratiyor. Iliskide monotonluk size gore degil — surekli yenilik, ogrenme, paylasim olmali. Duygusal derinligi de kattiginizda bu iliskinin en eglenceli sevgilisi siz oluyorsunuz.",
    ("Venüs", "4"): "Sevgiyi koruyarak, besleyerek, kucaklayarak gosteriyorsunuz. Ev, sicaklik, yuva kavramlari cok onemli. Partneriniz sicakliginizi ve koruyuculugunuzu seviyor ama asiri baglanmaniz zaman zaman bunaltabiliyor. Iliskide guvenli bir liman olmak cok degerli. Sevginizi saglam bir temel uzerine kurduğunuzda bu iliskinin en guvenceli sevgilisi siz oluyorsunuz.",
    ("Venüs", "5"): "Sevgiyi buyuk, gosterisli ve cimcirik bicimde gosteriyorsunuz. Hediye almak, surpriz yapmak, goz onunde olmak size zevk veriyor. Partneriniz cimcirliginizi ve tutkunuzu seviyor ama ilgiye olan acginiz guvensizlik yaratiyor. Iliskide gozler uzerinizde olmali — ama partnerinizin de parlamasi cok onemli. Alan tanidiginizda bu iliskinin en buyuk sevgi sahnini siz insa ediyorsunuz.",
    ("Venüs", "6"): "Sevgiyi hizmet ederek, duzenleyerek, yasamini kolaylastirarak gosteriyorsunuz. Pratik sevgi dili cok guclu. Partneriniz sadakatinizi ve caliskanliginizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Iliskide kusursuzluk arayisi iliskiyi bogabiliyor. Sevginizi kabul ettiginizde, kusurlari guzel gordugunuzde bu iliskinin en ince sevgilisi siz oluyorsunuz.",
    ("Venüs", "7"): "Sevgiyi denge, zarafet ve guzellikle gosteriyorsunuz. Ilişkide esitlik, uyum, guzellik cok onemli. Partneriniz zarafetinizi ve adalet duygunuzu seviyor ama kararsizliginiz zaman zaman uzaklasma yaratiyor. Iliskide guzel seyler yasamak cok onemli — sanat, muzik, estetik. Sevginizi net bir sekilde ifade ettiginizde bu iliskinin en zarif sevgilisi siz oluyorsunuz.",
    ("Venüs", "8"): "Sevgiyi derin, yogun ve mutlak bir bicimde gosteriyorsunuz. Sevginiz yari yolda birakmak yok — ya tam ya hic. Partneriniz tutkunuzu ve derinliginizi seviyor ama kiskancliginiz ve kontrolculugunuz zaman zaman bunaltabiliyor. Iliskide guven ve sadakat cok onemli. Guvenmeyi ogrendiginizde bu iliskinin en derin sevgilisi siz oluyorsunuz.",
    ("Venüs", "9"): "Sevgiyi ozgurluk, neşe ve macera ile gosteriyorsunuz. Iliskiyi eglenceli, genis ve anlamlı yasamak istiyorsunuz. Partneriniz iyimserliginizi ve cimcirliginizi seviyor ama taahhut korkunuz endise yaratiyor. Iliskide buyuk hayaller kurmak cok guzel ama topraklanmak da gerekir. Topraklandiginizda bu iliskinin en buyuk sevgi rehberi siz oluyorsunuz.",
    ("Venüs", "10"): "Sevgiyi eylemlerle, sorumlulukla ve pratik destekle gosteriyorsunuz. Sevginizi soyle degil, yaparak gosteriyorsunuz. Partneriniz guvenilirliginizi ve ciddiyetinizi seviyor ama duygusal acikliginizin eksikligi sogukluk yaratiyor. Iliskide duygusal paylasim da cok onemli. Duygularinizi actiginizda bu iliskinin en guvenilir sevgilisi siz oluyorsunuz.",
    ("Venüs", "11"): "Sevgiyi arkadaslik, esitlik ve ozgurluk uzerine insa ediyorsunuz. Geleneksel iliski kaliplari size dar geliyor. Partneriniz ozgunlugunuzu ve vizyonunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskide yakinlik da cok onemli. Sicaklastiginizda bu iliskinin en ozel sevgilisi siz oluyorsunuz.",
    ("Venüs", "12"): "Sevgiyi kosulsuz, fedakar ve manevi bir bicimde gosteriyorsunuz. Sevginizi ruhsal bir boyutta yasiyorsunuz. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskide sinir koymak cok onemli. Sinir koyabildiginizde bu iliskinin en guclu sevgi kaynagi siz oluyorsunuz.",

    # === MARS — Tutku bicimi, sinirlarini nasil korudugu ===
    ("Mars", "1"): "Tutkunuzu cesurca, dogrudan ve eylemseel bicimde ifade ediyorsunuz. Iliskide oncu sizsiniz — ilk adimi atan, sinirlari cizen, harekete gecen hep sizsiniz. Partneriniz bu enerjinizi ve cesaretinizi seviyor ama ofkenizin siddetinden sarsilabiliyor. Iliskide rekabet ve macera cok onemli. Enerjinizi yonlendirmeyi ogrendiginizde bu iliskinin en guclu savascisi siz oluyorsunuz.",
    ("Mars", "2"): "Tutkunuzu sabirla, istikrarla ve somut eylemlerle ifade ediyorsunuz. Hizli degil, yavas ama emin adimlarla ilerliyorsunuz. Partneriniz guvenilirliginizi ve gucunuzu seviyor ama sahipci olmaniz zaman zaman sorun yaratiyor. Iliskide fiziksel dokunma cok onemli — sevginizi dokunarak, sarilarak, yaninda olarak ifade ediyorsunuz. Sabirli tutumunuz bu iliskinin en guclu temelini olusturuyor.",
    ("Mars", "3"): "Tutkunuzu kelimelerle, tartismalarla ve zihinsel uyumla ifade ediyorsunuz. Iliskide konusmak, tartismak, fikir alisverisi yapmak cok onemli. Partneriniz zekanizi ve esprili iletisim tarzinizi seviyor ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Tartismalarda kelimelerinizi secmek cok onemli. Dengeli iletisim kurdugnuzda bu iliskinin en parlak iletisim savascisi siz oluyorsunuz.",
    ("Mars", "4"): "Tutkunuzu koruyarak, sahiplenerek ve duygusal bicimde ifade ediyorsunuz. Iliskide koruma, savunma, sahiplenme cok onemli. Partneriniz sadakatinizi ve sicakliginizi seviyor ama ofkenizi iceye dondurme egiliminiz zaman zaman sorun yaratiyor. Duygusal patlamalar yerine sagirim onemli. Duygularinizi saglikli ifade ettiginizde bu iliskinin en guclu koruyucusu siz oluyorsunuz.",
    ("Mars", "5"): "Tutkunuzu gosterisli, tutkulu ve cesurca ifade ediyorsunuz. Iliskide goz onunde olmak, hayranlik uyandirmak cok onemli. Partneriniz cesaretinizi ve tutkunuzu seviyor ama ego caprasmalariniz zaman zaman gerilim yaratiyor. Iliskide partnerinizin de parlamasi cok onemli. Egonuzu yonlendirdiginizde bu iliskinin en buyuk tutku sahnesini siz insa ediyorsunuz.",
    ("Mars", "6"): "Tutkunuzu hizmet ederek, duzenleyerek ve pratik adimlarla ifade ediyorsunuz. Iliskide detaylara onem veriyorsunuz — her seyin yolunda olmasi cok onemli. Partneriniz caliskanliginizi ve sadakatinizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Ogrenme ve gelisme cok onemli. Kusurlari kabul ettiginizde bu iliskinin en ince gozlemcisi siz oluyorsunuz.",
    ("Mars", "7"): "Tutkunuzu denge, uyum ve karsiliklilik uzerine insa ediyorsunuz. Iliskide esitlik cok onemli — her iki tarafin da esit sekilde katilmasi gerekiyor. Partneriniz zarafetinizi ve uyum yeteneginizi seviyor ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Cesur adimlar atmak cok onemli. Netlastiginizde bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Mars", "8"): "Tutkunuzu derin, yogun ve mutlak bicimde ifade ediyorsunuz. Iliskide kontrol, guc ve derin bag cok onemli. Partneriniz tutkunuzu ve derinliginizi seviyor ama kontrolculugunuzden ve kiskancliginizdan yorulabiliyor. Guven ve sadakat cok onemli. Guvenmeyi ogrendiginizde bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Mars", "9"): "Tutkunuzu macera, ozgurluk ve anlami uzerine insa ediyorsunuz. Iliskide buyuk hayaller kurmak, yeni deneyimler yasamak cok onemli. Partneriniz iyimserliginizi ve cesaretinizi seviyor ama taahhut korkunuz endise yaratiyor. Topraklanmak da cok onemli. Somut adimlar attiginizda bu iliskinin en buyuk macera rehberi siz oluyorsunuz.",
    ("Mars", "10"): "Tutkunuzu sabirla, kararlilikla ve stratejik adimlarla ifade ediyorsunuz. Iliskide uzun vadeli hedefler cok onemli. Partneriniz kararliliginizi ve guvenilirliginizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Duygusal paylasim da cok onemli. Duygularinizi actiginizda bu iliskinin en guclu stratejisti siz oluyorsunuz.",
    ("Mars", "11"): "Tutkunuzu ozgurluk, yenilik ve toplumsal donusum uzerine insa ediyorsunuz. Geleneksel iliski kaliplari size dar geliyor. Partneriniz vizyonunuza ve ozgunlugunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Yakinlik da cok onemli. Sicaklastiginizda bu iliskinin en ozel bagini siz kuruyorsunuz.",
    ("Mars", "12"): "Tutkunuzu sezgisel, fedakar ve ruhsal bicimde ifade ediyorsunuz. Fiziksel mucadeleden cok manevi veya yaratici mucadele onemli. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Sinir koymak cok onemli. Sinir koydugunuzda bu iliskinin en guclu sevgi savascisi siz oluyorsunuz.",

    # === JUPITER — Iliskiye ne kattigi, genisleme alani ===
    ("Jüpiter", "1"): "Iliskiye cesaret, macera ve yenilik katmissiniz. Yeni baslangiclar, heyecan ve eylem enerjisi getiriyorsunuz. Partneriniz bu enerjinizi hayranlikla izliyor ama asiriya kacmaniz zaman zaman sorun yaratiyor. Iliskiyi genisleten, buyuten ve canli tutan sizsiniz. Bu genisleme enerjisini dengeli kullandiginizda bu iliskinin en buyuk sansi siz oluyorsunuz.",
    ("Jüpiter", "2"): "Iliskiye bolluk, bereket ve somut degerler katmissiniz. Finans, guvenlik ve fiziksel konfor konularinda buyuk firsatlar getiriyorsunuz. Partneriniz guvenilirliginizi ve cimcirliginizi seviyor ama sahipci olmaniz zaman zaman sorun yaratiyor. Iliskiyi somut degerlerle buyuten sizsiniz. Bu bolluk enerjisini paylastikca bu iliskinin en buyuk bereket kaynagi siz oluyorsunuz.",
    ("Jüpiter", "3"): "Iliskiye bilgi, iletisim ve zihinsel canlilik katmissiniz. Ogrenmek, ogretmek, paylasmak konularinda buyuk firsatlar getiriyorsunuz. Partneriniz zekanizi ve eglenceli iletisim tarzinizi seviyor ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Iliskiyi zihinsel olarak buyuten sizsiniz. Dengeli iletisim kurdugunuzda bu iliskinin en parlak iletisim kaynagi siz oluyorsunuz.",
    ("Jüpiter", "4"): "Iliskiye sicaklik, yuva ve aile degerleri katmissiniz. Evinizi buyutmek, aile kurmak, baglari guclendirmek konularinda buyuk firsatlar getiriyorsunuz. Partneriniz sicakliginizi ve koruyuculugunuzu seviyor ama asiri baglanmaniz zaman zaman bunaltabiliyor. Iliskiyi sicak bir yuvaya ceviren sizsiniz. Bu sicaklik enerjisini dengeli kullandiginizda bu iliskinin en buyuk guvenlik kaynagi siz oluyorsunuz.",
    ("Jüpiter", "5"): "Iliskiye tutku, eglence ve yaraticilik katmissiniz. Sanat, sahne ve eglence konularinda buyuk firsatlar getiriyorsunuz. Partneriniz cimcirliginizi ve enerjinizi seviyor ama ego caprasmalariniz zaman zaman gerilim yaratiyor. Iliskiyi eglenceli ve tutkulu kılan sizsiniz. Enerjinizi dengeli kullandiginizda bu iliskinin en buyuk eglence kaynagi siz oluyorsunuz.",
    ("Jüpiter", "6"): "Iliskiye hizmet, pratik cozumler ve iyilestirme katmissiniz. Gundeşik hayati duzenlemek, sorunlari cozumlemek konularinda buyuk firsatlar getiriyorsunuz. Partneriniz caliskanliginizi ve sadakatinizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Iliskiyi pratik olarak buyuten sizsiniz. Ovgunuzu da ifade ettiginizde bu iliskinin en buyuk hizmet kaynagi siz oluyorsunuz.",
    ("Jüpiter", "7"): "Iliskiye denge, uyum ve guzellik katmissiniz. Iliskiler, ortakliklar ve estetik konularinda buyuk firsatlar getiriyorsunuz. Partneriniz zarafetinizi ve adalet duygusu seviyor ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskiyi guzel ve dengeli kılan sizsiniz. Net kararlar aldiginda bu iliskinin en buyuk denge kaynagi siz oluyorsunuz.",
    ("Jüpiter", "8"): "Iliskiye donusum, derinlik ve buyuk kaynaklar katmissiniz. Cinsellik, ruhsal donusum ve ortak kaynaklar konularinda buyuk firsatlar getiriyorsunuz. Partneriniz derinliginizi ve tutkunuzu seviyor ama kontrolculugunuzden yorulabiliyor. Iliskiyi derinden donusturen sizsiniz. Guvenmeyi ogrendiginizde bu iliskinin en buyuk donusum kaynagi siz oluyorsunuz.",
    ("Jüpiter", "9"): "Iliskiye ozgurluk, anlam ve macera katmissiniz. Felsefe, seyahat ve yuksek ogrenim konularinda buyuk firsatlar getiriyorsunuz. Partneriniz iyimserliginizi ve genis perspektifinizi seviyor ama taahhut korkunuz endise yaratiyor. Iliskiyi buyuk resimde buyuten sizsiniz. Topraklandiginizda bu iliskinin en buyuk rehber kaynagi siz oluyorsunuz.",
    ("Jüpiter", "10"): "Iliskiye ciddiyet, sorumluluk ve uzun vadeli yapilandirma katmissiniz. Kariyer, statu ve uzun vadeli hedefler konularinda buyuk firsatlar getiriyorsunuz. Partneriniz kararliliginizi ve guvenilirliginizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Iliskiyi uzun vadede buyuten sizsiniz. Duygusal paylasimlari da arttirdiginizda bu iliskinin en buyuk guvence kaynagi siz oluyorsunuz.",
    ("Jüpiter", "11"): "Iliskiye ozgurluk, yenilik ve toplumsal vizyon katmissiniz. Arkadaslik, sosyal projeler ve teknoloji konularinda buyuk firsatlar getiriyorsunuz. Partneriniz vizyonunuza ve ozgunlugunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskiyi ozgurluk uzerine buyuten sizsiniz. Yakinlastiginizda bu iliskinin en ozel vizyon kaynagi siz oluyorsunuz.",
    ("Jüpiter", "12"): "Iliskiye maneviyat, sezgi ve kosulsuz sevgi katmissiniz. Sanat, muzik, meditasyon ve ruhsal pratikler konularinda buyuk firsatlar getiriyorsunuz. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskiyi ruhsal olarak buyuten sizsiniz. Sinir koydugunuzda bu iliskinin en buyuk manevi kaynagi siz oluyorsunuz.",

    # === SATURN — Iliskideki sinavi, nerede sinirlandigi ===
    ("Satürn", "1"): "Iliskide en buyuk sinaviniz sabirli olmak — hizli kararlar alma ve her seyi hemen isteme egiliminiz partnerinizi yoruyor. Cesaretiniz ve inisiyatif almaniz guclu ama sabirsizliginiz iliskiyi zedeleyebiliyor. Daha yavas, daha dusunceli adimlar attiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz sabretmeyi ogrenmek. Ogrendiginizde bu iliskinin en guclu motoru siz oluyorsunuz.",
    ("Satürn", "2"): "Iliskide en buyuk sinaviniz degisime acilmak — surekli ayni seyleri yapma ısrarınız iliskiyi bogabiliyor. Istikrariniz ve guvenilirliginiz guclu ama esnek olmamaniz zaman zaman gerilim yaratiyor. Kucuk degisikliklere acildiginizda iliski cok daha canli bir hale geliyor. Sinaviniz esnek ogrenmek. Ogrendiginizde bu iliskinin en saglam temelini siz insa ediyorsunuz.",
    ("Satürn", "3"): "Iliskide en buyuk sinaviniz derinlesmek — konularin ustunu kosarak gecme egiliminiz partnerinizi uzuyor. Zihinsel canliliginiz guclu ama yuzeyel kalmaniz zaman zaman uzaklik yaratiyor. Duygusal konularda da derinlestiginizde iliski cok daha guclu bir hale geliyor. Sinaviniz derinlesmeyi ogrenmek. Ogrendiginizde bu iliskinin en parlak iletisim koprusunu siz kuruyorsunuz.",
    ("Satürn", "4"): "Iliskide en buyuk sinaviniz ozgur birakmak — her seyi kontrol etme ihtiyaciniz partnerinizi bunaltiyor. Koruyuculugunuz ve sicakliginiz guclu ama asiri baglanmaniz zaman zaman sorun yaratiyor. Partnerinize alan tanidiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz guvenmeyi ogrenmek. Ogrendiginizde bu iliskinin en guvenli limanini siz insa ediyorsunuz.",
    ("Satürn", "5"): "Iliskide en buyuk sinaviniz ego yonetimi — iliskinin tek yildizi siz olma ısrarınız partnerinizi uzuyor. Parildayan ve dikkat ceken bir yapınız var ama karsi tarafin da parlamaine izin vermeniz cok onemli. Partnerinizin guclerini onemsediginizde iliski cok daha guclu bir hale geliyor. Sinaviniz alan tanimak. Ogrendiginizde bu iliskinin en buyuk gucu oluyorsunuz.",
    ("Satürn", "6"): "Iliskide en buyuk sinaviniz kendinizi de kabul etmek — kusursuzluk arayisiniz hem sizi hem partnerinizi yoruyor. Analiz yeteneginiz guclu ama her seyi elestirme egiliminiz zaman zaman uzaklik yaratiyor. Ovgunuzu da ifade ettiginizde iliski cok daha guclu bir hale geliyor. Sinaviniz kabullenmeyi ogrenmek. Ogrendiginizde bu iliskinin en ince guzelligini siz olusturuyorsunuz.",
    ("Satürn", "7"): "Iliskide en buyuk sinaviniz net kararlar almak — kararsizliginiz zaman zaman sinir bozucu olabiliyor. Denge ve uyum arayisiniz guclu ama her seyi erteleme egiliminiz iliskiyi yoruyor. Cesur adimlar attiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz netlesmeyi ogrenmek. Ogrendiginizde bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Satürn", "8"): "Iliskide en buyuk sinaviniz guvenmek — her seyi denetim altinda tutma ihtiyaciniz iliskiyi boguyor. Derinliginiz ve tutkunuz guclu ama kontrolculugunuz zaman zaman sogukluk yaratiyor. Guvenmeyi ogrendiginizde iliski cok daha guclu bir hale geliyor. Sinaviniz birakmayi ogrenmek. Ogrendiginizde bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Satürn", "9"): "Iliskide en buyuk sinaviniz topraklanmak — surekli baska ufuklara bakma egiliminiz partnerinizi guvensiz birakiyor. Buyuk hayaller kurmaniz guclu ama somut adimlar atmamaniz zaman zaman sorun yaratiyor. Somut adimlar attiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz ayaklarinizi yere basmayi ogrenmek. Ogrendiginizde bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Satürn", "10"): "Iliskide en buyuk sinaviniz acilmak — duvarlarinizin arkasina saklanmaniz partnerinizi uzuyor. Ciddiyetiniz ve kararliliginiz guclu ama duygularinizi gosterememeniz zaman zaman sogukluk yaratiyor. Duygularinizi actiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz acilmayi ogrenmek. Ogrendiginizde bu iliskinin en saglam temelini siz insa ediyorsunuz.",
    ("Satürn", "11"): "Iliskide en buyuk sinaviniz yakinlasmak — bagimsizlik ısrarınız partnerinizi uzaklastiriyor. Ozgurlugunuz ve vizyonunuz guclu ama mesafeli durusunuz zaman zaman sogukluk yaratiyor. Yakinlastiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz bag kurmayi ogrenmek. Ogrendiginizde bu iliskinin en ozel bagini siz kuruyorsunuz.",
    ("Satürn", "12"): "Iliskide en buyuk sinaviniz sinir koymak — kendinizi tamamen feda etme egiliminiz partnerinizi yoruyor. Merhametiniz ve derinliginiz guclu ama sinirlarinizin bulanik olmasi zaman zaman karisiklik yaratiyor. Sinir koydugunuzda iliski cok daha guclu bir hale geliyor. Sinaviniz sinirlari ogrenmek. Ogrendiginizde bu iliskinin en guclu sevgi kaynagi siz oluyorsunuz.",

    # === URANUS — OZGURLUK/SURPRIZ DINAMIGI ===
    ("Uranüs", "1"): "Iliskide ozgurluk ve bagimsizlik ısrarınız cok guclu. Ani degisikikler, beklenmedik kararlar ve yenilikci yaklasimlar iliskinizi surekli canli tutuyor. Partneriniz bu enerjinizi hayranlikla izliyor ama ongorelemezliginiz zaman zaman endise yaratiyor. Iliskide yenilik ve macera cok onemli. Dengeli bir ozgurluk anlayisi ile bu iliskinin en yenilikci ruhu siz oluyorsunuz.",
    ("Uranüs", "2"): "Iliskide deger ve guvenlik konularinda ani degisimler yasayabilirsiniz. Maddi konularda beklenmedik gelismeler, degerlerinizi yeniden tanimlama sureci iliskiyi etkiliyor. Partneriniz degisime acik olmanizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide yeni deger kaynaklari kefetmek cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci deger olusturucusu siz oluyorsunuz.",
    ("Uranüs", "3"): "Iliskide iletisim ve dusunce tarzinizda ani devrimler yasayabilirsiniz. Yeni fikirler, siradisi yaklasimlar ve hizli iletisim iliskiyi surekli canli tutuyor. Partneriniz zihinsel canliliginizi seviyor ama daginikliginiz zaman zaman kafa karisikligi yaratiyor. Iliskide yenilikci fikirler cok onemli. Odaginizi korudugunuzda bu iliskinin en yenilikci iletisim kaynagi siz oluyorsunuz.",
    ("Uranüs", "4"): "Iliskide ev ve aile konularinda ani degisiklikler yasayabilirsiniz. Tasinma, ev degisikligi veya aile yapisinda beklenmedik gelismeler iliskiyi etkiliyor. Partneriniz yenilikci yaklasiminizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide guvenli bir yuva olusturmak cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci yuva kurucusu siz oluyorsunuz.",
    ("Uranüs", "5"): "Iliskide yaraticilik ve eglence konularinda ani patlamalar yasayabilirsiniz. Sanat, eglence veya flortte ongorelemez gelismeler iliskiyi surekli canli tutuyor. Partneriniz yaraticiliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide surprizler ve yenilikler cok onemli. Duygusal baglari da guclendirdiginizde bu iliskinin en yenilikci ruhu siz oluyorsunuz.",
    ("Uranüs", "6"): "Iliskide gunluk hayati ve saglik konularinda ani degisiklikler yasayabilirsiniz. Calisma kosullarinda beklenmedik gelismeler, saglik konularinda ani farkindaliklar iliskiyi etkiliyor. Partneriniz yenilikci yaklasiminizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide pratik cozumler cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci cozum ureticisi siz oluyorsunuz.",
    ("Uranüs", "7"): "Iliskide ani ozgurluk ve denge arayislari yasayabilirsiniz. Evlilik veya ortaklikta beklenmedik gelismeler, ozgurluk ve denge arasindaki catisma iliskiyi etkiliyor. Partneriniz ozgurlugunuza saygi duymani seviyor ama belirsizlik zaman zaman endise yaratiyor. Iliskide esitlik cok onemli. Dengeli bir ozgurluk anlayisi ile bu iliskinin en yenilikci hakemi siz oluyorsunuz.",
    ("Uranüs", "8"): "Iliskide guc ve kontrol konularinda ani patlamalar yasayabilirsiniz. Gizli siralar aniden yuze cikabilir, kontrol kaybolabilir. Partneriniz derinliginizi seviyor ama ongorelemezliginiz zaman zaman korku yaratiyor. Iliskide derin donusum cok onemli. Kontrolu biraktiginizda bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Uranüs", "9"): "Iliskide inanç ve felsefe konularinda ani devrimler yasayabilirsiniz. Eski inanc sisteminiz sarsilabilir, yeni ve daha derin anlayislara acilabilirsiniz. Partneriniz vizyonunuza hayran ama belirsizlik zaman zaman endise yaratiyor. Iliskide buyuk resmi gormek cok onemli. Topraklandiginizda bu iliskinin en yenilikci rehberi siz oluyorsunuz.",
    ("Uranüs", "10"): "Iliskide kariyer ve statu konularinda ani degisiklikler yasayabilirsiniz. Is hayatinda beklenmedik gelismeler, kariyer yonunde degisiklikler iliskiyi etkiliyor. Partneriniz kararliliginizi seviyor ama ongorelemezliginiz zaman zaman tedirginlik yaratiyor. Iliskide uzun vadeli planlar cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci stratejisti siz oluyorsunuz.",
    ("Uranüs", "11"): "Iliskide ozgurluk ve yenilik konularinda ani patlamalar yasayabilirsiniz. Kisi donusumunuz cok hizli ve buyuk olabilir. Partneriniz ozgunlugunuzu seviyor ama mesafeli durusunuz zaman zaman sogukluk yaratabiliyor. Iliskide esitlik ve arkadaslik cok onemli. Yakinlastiginizda bu iliskinin en ozel ve farkli bagini siz kuruyorsunuz.",
    ("Uranüs", "12"): "Iliskide manevi dunyada ani donusumler yasayabilirsiniz. Sezgileriniz cok guclu ama belirsizlik de cok buyuk olabilir. Sanat veya muzikte ongorelemez ilham dalgalari gelebilir. Partneriniz derinliginizi seviyor ama ongorelemezliginiz zaman zaman kafa karisikligi yaratiyor. Iliskide sinirlar cok onemli. Sinirlarinizi netlestirdiginizde bu iliskinin en yenilikci ruhsal bagini siz kuruyorsunuz.",

    # === NEPTUN — IDEALIZMI, SEFFAFLIGI ===
    ("Neptün", "1"): "Iliskide kimlik ve hedefler konusunda bulaniklilar olabilir. Ne istediginiz konusunda belirsizlik yasayabilirsiniz ama sezgileriniz cok guclu. Partneriniz derinliginizi seviyor ama belirsizlik zaman zaman guvensizlik yaratiyor. Iliskide net olmak cok onemli. Netlestiginizde bu iliskinin en guclu sezgisel bagini siz kuruyorsunuz.",
    ("Neptün", "2"): "Iliskide deger ve guvenlik konusunda belirsizlikler olabilir. Para konularinda net olmayan durumlar, degerler uzerine kafa karisikliklari yasayabilirsiniz. Partneriniz guvenilirliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide somut degerler cok onemli. Somutlastirdiginizda bu iliskinin en guvenli kaynagi siz oluyorsunuz.",
    ("Neptün", "3"): "Iliskide iletisimde bulaniklilar olabilir. Soyledikleriniz ile kastettiginiz arasinda fark olabilir. Sezgisel iletisim cok guclu ama net olmamaniz zaman zaman anlasilmazlik yaratiyor. Iliskide acik ve net olmak cok onemli. Netlestiginizde bu iliskinin en derin anlayis koprusunu siz kuruyorsunuz.",
    ("Neptün", "4"): "Iliskide ev ve aile konularinda belirsizlikler olabilir. Aile yapisinda net olmayan dinamikler, gizli gercekler olabilir. Partneriniz sicakliginizi seviyor ama belirsizlik zaman zaman guvensizlik yaratiyor. Iliskide guvenli bir yuva cok onemli. Guvenli bir yuva olusturdugunuzda bu iliskinin en sicak limanini siz insa ediyorsunuz.",
    ("Neptün", "5"): "Iliskide yaraticilik ve eglence konusunda ilham dalgalari yasayabilirsiniz. Sanat veya eglencede cok guclu sezgisel akis var ama somutlastirmakta zorlanabilirsiniz. Partneriniz yaraticiliginizi seviyor ama belirsizlik zaman zaman hayal kirikligi yaratiyor. Iliskide tutkuyu somutlastirmak cok onemli. Somutlastirdiginizda bu iliskinin en buyuk eglence kaynagi siz oluyorsunuz.",
    ("Neptün", "6"): "Iliskide gunluk hayat ve saglik konusunda belirsizlikler olabilir. Calisma kosullarinda net olmayan durumlar, saglik konularinda kafa karisikliklari yasayabilirsiniz. Partneriniz caliskanliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide pratik cozumler cok onemli. Pratiklastirdiginizda bu iliskinin en guvenli kaynagi siz oluyorsunuz.",
    ("Neptün", "7"): "Iliskide idealizasyon ve hayal kirikligi riski cok yuksek. Partnerinizi oldugundan buyuk gorebilirsiniz ama kosulsuz sevgi potansiyeliniz de cok yuksek. Iliskide net gozlerle bakmak cok onemli. Net baktiginizda bu iliskinin en guclu sevgi bagini siz kuruyorsunuz.",
    ("Neptün", "8"): "Iliskide guc ve kontrol konusunda belirsizlikler olabilir. Gizli guc dinamikleri devrede, derin bir donusum sureci yasayabilirsiniz. Partneriniz derinliginizi seviyor ama belirsizlik zaman zaman korku yaratiyor. Iliskide derin guven cok onemli. Guvenebildiginizde bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Neptün", "9"): "Iliskide inanç ve felsefe konusunda belirsizlikler olabilir. Eski inanc sisteminiz sarsilabilir ama yeni ve daha derin anlayislara da acilabilirsiniz. Partneriniz vizyonunuza hayran ama belirsizlik zaman zaman endise yaratiyor. Iliskide buyuk resmi gormek cok onemli. Topraklandiginizda bu iliskinin en buyuk manevi rehberi siz oluyorsunuz.",
    ("Neptün", "10"): "Iliskide kariyer ve statu konusunda belirsizlikler olabilir. Hedefleriniz veya kariyer yonunuz konusunda kafa karisikligi yasayabilirsiniz. Partneriniz kararliliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide somut adimlar cok onemli. Somutlastirdiginizda bu iliskinin en guvenli stratejisti siz oluyorsunuz.",
    ("Neptün", "11"): "Iliskide arkadaslik ve toplumsal konularda belirsizlikler olabilir. Sosyal cevrenizde net olmayan dinamikler olabilir ama insani yardim icin cok guclu sezgisel baglar da kurabilirsiniz. Partneriniz vizyonunuza hayran ama belirsizlik zaman zaman endise yaratiyor. Iliskide netlik cok onemli. Netlestiginizde bu iliskinin en ozel vizyon bagini siz kuruyorsunuz.",
    ("Neptün", "12"): "Iliskide manevi dunyada belirsizlikler olabilir. Sezgileriniz cok guclu ama gerceklikle baginizi kaybetme riski de cok buyuk. Ruhunuz cok derin, sezgileriniz cok guclu. Iliskide sinirlar cok onemli. Sinirlarinizi netlestirdiginizde bu iliskinin en derin ruhsal bagini siz kuruyorsunuz.",

    # === PLUTON — GUC MUCADELESI, DONUSUM ===
    ("Plüton", "1"): "Iliskide guc ve kimlik donusumunun en yogun yasandigi yerdesiniz. Eski benliginizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz cesaretinizi ve donusum kapasitenizi seviyor ama kontrolculugunuzden korkabiliyor. Iliskide guc dengeleri surekli degisiyor. Kontrolu ogrendiginizde bu iliskinin en guclu donusum katalizoru siz oluyorsunuz.",
    ("Plüton", "2"): "Iliskide deger ve guvenlik uzerinde derin bir donusum yasiyorsunuz. Eski degerlerinizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz guvenilirliginizi seviyor ama sahipci olmanizdan korkabiliyor. Iliskide deger catismalari cok yogun. Degerlerinizi paylastiginizda bu iliskinin en guclu deger ortagi siz oluyorsunuz.",
    ("Plüton", "3"): "Iliskide iletisim ve dusunce tarzinizda derin bir donusum yasiyorsunuz. Eski iletisim kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz zekanizi seviyor ama manipulasyon riskine karsi dikkatli olmaniz gerekiyor. Iliskide acik ve seffaf iletisim cok onemli. Seffaf iletisim kurdugnuzda bu iliskinin en derin anlayis koprusunu siz kuruyorsunuz.",
    ("Plüton", "4"): "Iliskide ev, aile ve kokenler uzerinde derin bir donusum yasiyorsunuz. Eski aile kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz sicakliginizi seviyor ama asiri baglanmanizdan korkabiliyor. Iliskide guven ve baglanma cok yogun. Guvenli baglanti kurdugunuzda bu iliskinin en derin yuva kurucusu siz oluyorsunuz.",
    ("Plüton", "5"): "Iliskide yaraticilik, ego ve dikkat cekme uzerinde derin bir donusum yasiyorsunuz. Eski ego kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz cesaretinizi seviyor ama ego caprasmalarindan korkabiliyor. Iliskide guc dengeleri cok yogun. Egonuzu yonlendirdiginizde bu iliskinin en buyuk sahne sahibi siz oluyorsunuz.",
    ("Plüton", "6"): "Iliskide gunluk hayat, saglik ve hizmet uzerinde derin bir donusum yasiyorsunuz. Eski calisma kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz caliskanliginizi seviyor ama elestirel yaklasiminizdan korkabiliyor. Iliskide hizmet ve kusursuzluk cok yogun. Kusurlari kabul ettiginizde bu iliskinin en ince gozlemcisi siz oluyorsunuz.",
    ("Plüton", "7"): "Iliskide denge, uyum ve ortaklik uzerinde derin bir donusum yasiyorsunuz. Eski iliski kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz zarafetinizi seviyor ama guc mukavelesinden korkabiliyor. Iliskide denge ve esitlik cok yogun. Dengeyi buldugunuzda bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Plüton", "8"): "Iliskide guc, kontrol ve derin donusumun en yogun yasandigi yerdesiniz. Eski benliginizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz derinliginizi seviyor ama kontrolculugunuzden korkabiliyor. Iliskide guc mucadelesi cok yogun. Guvenmeyi ogrendiginizde bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Plüton", "9"): "Iliskide inanç, felsefe ve anlam uzerinde derin bir donusum yasiyorsunuz. Eski inanc sisteminizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz vizyonunuza hayran ama donusumun yogunlugundan korkabiliyor. Iliskide buyuk resim cok onemli. Somut adimlar attiginizda bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Plüton", "10"): "Iliskide kariyer, statu ve sorumluluklar uzerinde derin bir donusum yasiyorsunuz. Eski kariyer kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz kararliliginizi seviyor ama ciddiyetinizden korkabiliyor. Iliskide yapilandirma cok yogun. Duygusal acikligi da arttirdiginizda bu iliskinin en guvenilir destekcisi siz oluyorsunuz.",
    ("Plüton", "11"): "Iliskide ozgurluk, yenilik ve toplumsal donusum uzerinde derin bir donusum yasiyorsunuz. Eski toplumsal kaliplari birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz vizyonunuza hayran ama donusumun yogunlugundan korkabiliyor. Iliskide esitlik cok onemli. Yakinlastiginizda bu iliskinin en ozel vizyon bagini siz kuruyorsunuz.",
    ("Plüton", "12"): "Iliskide manevi dunya ve bilincdisi uzerinde derin bir donusum yasiyorsunuz. Eski ruhsal kaliplari birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz derinliginizi seviyor ama donusumun yogunlugundan korkabiliyor. Iliskide derin guven cok onemli. Guvenebildiginizde bu iliskinin en derin ruhsal bagini siz kuruyorsunuz.",

}
