# -*- coding: utf-8 -*-
# Traducciones al espanol de los textos del retorno lunar (lunar return).
# Cargadas por core/engine.py en modo ES.

lr_ebeveyn_vitrin_es = {
    'Koc': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Aries</b>. La necesidad de independencia de tu hijo y su energía exploradora son altas este mes. Un enfoque de crianza paciente y comprensivo nutre el coraje de tu hijo.',
    'Boga': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Tauro</b>. La seguridad, la estabilidad y el confort físico son el foco de este mes. Pasar tiempo tranquilo y sereno con tu hijo nutrirá tu alma.',
    'Ikizler': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Géminis</b>. Mucha comunicación, curiosidad y la necesidad de aprender pasan al frente este mes. Hablar, leer libros y descubrir cosas nuevas junto a tu hijo es la clave de este mes.',
    'Yengec': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Cáncer</b>. La familia, el hogar y el vínculo emocional están por encima de todo este mes. Pasar tiempo en casa con tu hijo y profundizar tu vínculo emocional te hará mucho bien.',
    'Aslan': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Leo</b>. El reconocimiento, la apreciación y la creatividad son la clave de este mes. Valorar los esfuerzos de tu hijo y animarlo será la inversión pedagógica más valiosa de este mes.',
    'Basak': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Virgo</b>. El orden, la salud y los asuntos prácticos están en primer plano. Crear hábitos regulares junto con tu hijo y centrarse en temas saludables será beneficioso.',
    'Terazi': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Libra</b>. La armonía, el equilibrio y la justicia son las prioridades de este mes. Mantener el equilibrio en la relación padre-hijo y fortalecer el respeto mutuo es fundamental.',
    'Akrep': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Escorpio</b>. Las emociones intensas y la profundización son la firma de este mes. Explorar el mundo interior de tu hijo y ser testigo de su profundización emocional es la experiencia importante de este mes.',
    'Yay': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Sagitario</b>. La necesidad de descubrimiento, expansión y aprendizaje es alta este mes. Compartir nuevas experiencias con tu hijo y ampliar vuestros horizontes nutrirá tu alma.',
    'Oglak': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Capricornio</b>. La estructura, la responsabilidad y la seriedad marcan el tono emocional de este mes. Ser claro y coherente con las reglas y los límites es la prueba importante de este mes.',
    'Kova': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Acuario</b>. El espacio personal y la libertad son fundamentales este mes. Respetar el espacio personal de tu hijo y apoyar su independencia es la lección importante de este mes.',
    'Balik': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Piscis</b>. La intuición, la compasión y la sensibilidad emocional son los temas centrales de este mes. Escuchar al corazón en lugar de la lógica, y construir un vínculo intuitivo con tu hijo, es la sanación de este mes.',
}

lr_bireysel_vitrin_es = {
    'Koc': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Aries</b>. Las decisiones repentinas, las discusiones acaloradas y las reconciliaciones rápidas marcan el ritmo emocional de este mes. Dirige tu energía no hacia las peleas, sino hacia empezar algo nuevo juntos.',
    'Boga': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Tauro</b>. El contacto físico, la buena comida y un hogar en paz nutrirán tu alma. Evita las decisiones apresuradas este mes; la calma y la estabilidad son tu prioridad.',
    'Ikizler': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Géminis</b>. Hablarás mucho, escribirás muchos mensajes y tus planes cambiarán a menudo. La armonía mental es la clave de este mes para la cercanía emocional.',
    'Yengec': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Cáncer</b>. El hogar, la familia y el sentido de pertenencia tienen prioridad este mes. Refugiarse el uno en el otro y cerrar las puertas al mundo exterior les hará bien.',
    'Aslan': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Leo</b>. Ser apreciado, ser generoso y celebrar su relación son las necesidades centrales de este mes. Elógiense el uno al otro abundantemente y hagan sorpresas románticas.',
    'Basak': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Virgo</b>. La ayuda práctica y el orden son tu lenguaje de amor este mes. Hacer la vida más fácil el uno al otro es tu mejor forma de crear un vínculo emocional.',
    'Terazi': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Libra</b>. La armonía, la justicia y la estética son las prioridades de este mes. Busca el consenso en lugar de discutir; crear juntos un entorno hermoso renovará tu alma.',
    'Akrep': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Escorpio</b>. Las emociones intensas, las conversaciones profundas y la fuerte atracción física son la seña de identidad de este mes. Compartir tus sentimientos ocultos profundizará tu relación.',
    'Yay': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Sagitario</b>. La libertad, la aventura y las nuevas experiencias alimentan tu alma este mes. Descubrir algo nuevo juntos o tener una conversación que amplíe horizontes satisfará tu hambre emocional.',
    'Oglak': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Capricornio</b>. La seriedad y la responsabilidad marcan el tono emocional de este mes. Muestra tus sentimientos no con palabras, sino con pasos concretos y un comportamiento confiable.',
    'Kova': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Acuario</b>. El espacio personal y la libertad son críticos este mes. Den espacio el uno al otro; respetar la independencia fortalecerá su relación este mes.',
    'Balik': 'Tus reflejos emocionales de este mes funcionarán bajo el tema de <b>Piscis</b>. La intuición, los sueños y la compasión incondicional son los temas centrales de este mes. Escucha a tu corazón en lugar de a la lógica; ser amable y comprensivo el uno con el otro lo resolverá todo.',
}

lr_ebeveyn_ayev_es = {
    1: 'Este mes la identidad individual de tu hijo y su necesidad de independencia pasan a primer plano. Apoyar su proceso de tomar sus propias decisiones es la oportunidad pedagógica más importante de este mes. Descubrir juntos un nuevo pasatiempo o actividad fortalecerá vuestro vínculo.',
    2: 'Este mes aumentan la autoconfianza de tu hijo y la conciencia de sus habilidades. Usa este mes abundante lenguaje de aprecio y gratitud. Trabajar en un proyecto concreto juntos o aprender una nueva habilidad será la experiencia valiosa de este mes.',
    3: 'Este mes la necesidad de comunicación y aprendizaje es muy alta. Conversar a menudo con tu hijo, responder con paciencia a sus preguntas y leer libros juntos es la actividad pedagógica más valiosa del mes. Una salida corta o un paseo por la naturaleza también nutrirá vuestra alma.',
    4: 'Este mes los asuntos del hogar y la familia pasan a primer plano. Crear juntos un ambiente seguro y tranquilo en casa profundizará vuestro vínculo emocional. Cocinar, ver una película o embellecer el hogar juntos son las actividades sanadoras de este mes.',
    5: 'Este mes la creatividad y la alegría están muy altas. Jugar, hacer actividades artísticas o simplemente divertirte con tu hijo es la necesidad más importante de este mes. Descubrir y compartir al niño que llevas dentro es el regalo de este mes.',
    6: 'Este mes el orden, la salud y los asuntos prácticos están en primer plano. Adoptar hábitos saludables y establecer una rutina regular junto a tu hijo es la ganancia concreta de este mes. Incluso limpiar juntos o pasar tiempo en la cocina puede ser una experiencia valiosa.',
    7: 'Este mes el equilibrio y la armonía entre padre e hijo son muy importantes. Comprender las necesidades de tu hijo e intentar ver desde su perspectiva es la lección más valiosa de este mes. Tomar decisiones conjuntas y llegar a acuerdos juntos es la enseñanza de este mes.',
    8: 'Este mes es un tiempo de profundización emocional y confrontación. Descubrir los sentimientos profundos en el mundo interior de tu hijo y comprender sus miedos y preocupaciones es una experiencia importante este mes. Ser paciente y comprensivo es la sanación de este mes.',
    9: 'Este mes la energía de ampliar horizontes y explorar es muy alta. Descubrir nuevos lugares, aprender cosas nuevas o mantener conversaciones filosóficas junto a tu hijo son las experiencias valiosas de este mes. Disfruta crecer y aprender juntos.',
    10: 'Este mes la estructura, la responsabilidad y la seriedad están en primer plano. Sentar bases duraderas, establecer reglas y límites para tu hijo es una tarea importante este mes. Ser firme y constante como padre es el mayor apoyo de este mes.',
    11: 'Este mes los círculos sociales y los planes de futuro pasan a primer plano. Apoyar las amistades y las necesidades sociales de tu hijo es una parte importante de este mes. Hablar sobre el futuro y fijar metas compartidas juntos es una experiencia valiosa.',
    12: 'Este mes es un tiempo de recogimiento y profundización espiritual. Construir un vínculo tranquilo y profundo con tu hijo y fortalecer la comunicación intuitiva es la experiencia más valiosa de este mes. Pasar tiempo en la naturaleza, meditar o simplemente estar juntos en silencio nutrirá vuestra alma.',
}

lr_bireysel_ayev_es = {
    1: "Este mes el sentido del 'yo' en tu relación está muy alto. La sensibilidad puede aumentar y ambos sentiréis la necesidad de proteger vuestros propios límites emocionales. No dudes en expresar tus necesidades personales; ir a la peluquería, comprar ropa nueva o renovar tu imagen aportará aire fresco a tu relación este mes.",
    2: "Este mes tu seguridad emocional depende por completo de los 'valores económicos y físicos'. Gastar dinero, intercambiar regalos o disfrutar de una cena de lujo hará bien a tu alma. Hacer un plan de presupuesto conjunto o pedir ese artículo especial que tanto tiempo llevabas queriendo comprar satisfará el hambre emocional de este mes.",
    3: 'Este mes solo quieres hablar, ser comprendido y escribirte mensajes. Un período en el que la armonía mental, las palabras y las pequeñas escapadas rápidas curarán. Conducir hasta un lago cercano o a una ciudad vecina el fin de semana y charlar largo y tendido por el camino es tu mayor sanación kármica este mes.',
    4: 'Este mes es tu mes de ver películas en el mismo sofá en lugar de salir, refugiarse el uno en el otro y pasar tiempo a solas en casa. La pertenencia está siendo puesta a prueba. Comprar una planta nueva, entrar juntos a la cocina para probar una nueva receta o cambiar la decoración del dormitorio os unirá espiritualmente.',
    5: 'Un mes en el que te sientes emocionalmente coqueto, juguetón y aniñado. La necesidad de romance y pasión alcanza su punto máximo. Este mes es un momento maravilloso para dejar de lado las responsabilidades de la relación e ir al cine, divertirse en un parque de atracciones o simplemente mimarse mutuamente con sorpresas apasionadas.',
    6: "Este mes se trata menos de romance y más de '¿Cuánto me ayudas?'. Hacer dieta, limpiar u organizar juntos os une el uno al otro. Limpiar la casa de arriba a abajo, hacerse un chequeo médico juntos o masajear el estrés de la oficina del otro son los actos tangibles de amor de este mes.",
    7: "Un período en el que te centras por completo en tu pareja y buscas la seguridad emocional de ser 'Nosotros'. Tu necesidad de aprobación es alta. Al tomar decisiones, deberías preguntar a menudo '¿Cómo crees que deberíamos hacerlo?' y reequilibrar tu armonía saliendo a cenar juntos, solo vosotros dos.",
    8: "El intenso mes de la alquimia de los celos, la pasión profunda y 'Ábreme tu alma'. Vuestro vínculo se fortalece resolviendo crisis o a través de los secretos del dormitorio. Más que temas superficiales, las conversaciones de medianoche en las que escucháis los miedos más ocultos del otro y una poderosa atracción sexual recrearán tu relación este mes.",
    9: 'Este mes te cansas de la rutina de la relación y quieres debatir nuevas filosofías, hacer planes en el extranjero o viajar muy lejos. Empezar una nueva serie documental, cenar en un restaurante de cultura extranjera o planificar la ruta de las vacaciones del año próximo dará a tu alma una sensación de expansión.',
    10: 'En lugar de mostrar abiertamente tus sentimientos, te centras en la seriedad de tu relación y en tu postura en público. Los mayores de la familia pueden estar en la agenda. Celebrar un éxito en la carrera de tu pareja, asistir a cenas familiares o tomar decisiones que formalicen el estatus de tu relación (compromiso, formalización) es el tema central de este mes.',
    11: "Este mes ser 'dos mejores amigos' en lugar de amantes románticos os hará bien. Socializar y pasar tiempo con amigos en común cura los sentimientos. Invitar a mucha gente a tu casa, organizar noches de juegos con vuestros amigos en común o apoyar juntos un proyecto de responsabilidad social refrescará tu relación.",
    12: 'Un mes delicado, místico e intuitivo en el que no quieres salir del capullo. Puedes liberar el cansancio emocional permaneciendo en silencio y tocando las almas del otro. Alejarse de las multitudes para dar un paseo tranquilo en la naturaleza, meditar juntos o interpretar los sueños del otro es la mayor medicina espiritual de este mes interior.',
}
