# -*- coding: utf-8 -*-
# Variante en español de ARAP_ILISKI_DICTS.py (modos pareja/couple e individual natal).
# Las claves se mantienen idénticas al archivo turco; solo los valores se traducen al español.
# Se carga a través de core/data.py (_load_all_ext_dicts); el idioma activo decide en el acceso.

ARAP_NOKTALARI_ILISKI = {
    "Şans Noktası":     {"nokta1": "Ay",     "nokta2": "Güneş",  "kisa": "SANS", "aciklama": "La puerta natural de oportunidades y abundancia que el destino te presenta"},
    "Ruh Noktası":      {"nokta1": "Güneş",  "nokta2": "Ay",     "kisa": "RUH",  "aciklama": "Tu propósito interior, tu viaje espiritual y la guía del alma"},
    "Evlilik Noktası":  {"nokta1": "Venüs",  "nokta2": "Satürn", "kisa": "EVLİ", "aciklama": "La energía del compromiso, el destino matrimonial y la alianza a largo plazo"},
    "Aşk Noktası":      {"nokta1": "Venüs",  "nokta2": "Mars",   "kisa": "AŞK",  "aciklama": "Tu lenguaje de amor, tu poder de atracción y la dirección de tu corazón"},
    "Tutku Noktası":    {"nokta1": "Mars",   "nokta2": "Venüs",  "kisa": "TUTK", "aciklama": "Tu intensidad de deseo, tu fuego interior y la fuerza que pone tu destino en movimiento"},
    "Para Noktası":     {"nokta1": "Merkür", "nokta2": "Güneş",  "kisa": "PARA", "aciklama": "El canal por el que la ganancia material, la abundancia y la prosperidad se abren hacia ti"},
}

ARAP_NOKTA_ADLARI_ES = {
    "Şans Noktası": "Parte de la Fortuna",
    "Ruh Noktası": "Punto del Alma",
    "Evlilik Noktası": "Punto del Matrimonio",
    "Aşk Noktası": "Punto del Amor",
    "Tutku Noktası": "Punto de la Pasión",
    "Para Noktası": "Punto del Dinero",
}

ARAP_NOKTA_BURC_YORUMLARI = {
    ("Şans Noktası", "Koç"): "Tu energía de fortuna es valiente y pionera; las puertas de la vida se abren en el momento en que tomas la iniciativa. El destino te llama a dar el primer paso.",
    ("Şans Noktası", "Boğa"): "Tu suerte reside en la paciencia y la constancia; las mayores oportunidades llegan con un esfuerzo concreto, paso a paso. El destino te ofrece valores duraderos.",
    ("Şans Noktası", "İkizler"): "Tu suerte brilla en la comunicación; las puertas se abren en el momento en que dices la palabra correcta. El conocimiento y las conexiones son las llaves que el destino te tiende.",
    ("Şans Noktası", "Yengeç"): "Tu suerte reside en la familia y la seguridad emocional; tus seres queridos y tu hogar te traen oportunidades inesperadas. El destino sonríe cuando sigues tu corazón.",
    ("Şans Noktası", "Aslan"): "Tu suerte reside en la creatividad y la autoexpresión; en el momento en que subes al escenario, el destino te recompensa. Tu valentía es la puerta de la abundancia.",
    ("Şans Noktası", "Başak"): "Tu suerte reside en los detalles y el servicio; tu meticulosidad te gana oportunidades invisibles. El destino recompensa a quienes aman el orden.",
    ("Şans Noktası", "Terazi"): "Tu suerte reside en la armonía y las relaciones; la vida te sonríe cuando encuentras el equilibrio. Las conexiones correctas son el regalo del destino.",
    ("Şans Noktası", "Akrep"): "Tu suerte está oculta en la transformación; cuando sales fortalecido de las crisis, el destino te abre nuevas puertas. La profundidad es la fuente de la abundancia.",
    ("Şans Noktası", "Yay"): "Tu suerte está en el horizonte y el descubrimiento; cuando te lanzas a la aventura, ganancias inesperadas te encuentran. El destino ama a quienes piensan en grande.",
    ("Şans Noktası", "Oğlak"): "Tu suerte reside en la disciplina y la planificación a largo plazo; cuando asciendes con paciencia, eres coronado en la cima. El destino es fiel a tu esfuerzo.",
    ("Şans Noktası", "Kova"): "Tu suerte reside en la originalidad; el universo te recompensa cuando piensas de forma distinta. Tus ideas poco convencionales son la clave de la abundancia.",
    ("Şans Noktası", "Balık"): "Tu suerte reside en la intuición y la espiritualidad; la magia ocurre cuando confías en tu voz interior. El destino está al lado de quienes creen.",

    ("Ruh Noktası", "Koç"): "La búsqueda de tu alma es la independencia; cuanto más trazas tu propio camino, más paz interior encuentras. Tu evolución espiritual se teje con coraje.",
    ("Ruh Noktası", "Boğa"): "Tu alma se nutre de la tierra y lo permanente; a medida que te valoras, te enriqueces espiritualmente. Tu evolución fluye con serenidad.",
    ("Ruh Noktası", "İkizler"): "Tu alma se nutre de conocimiento y comunicación; aprender y compartir son las piedras de tu viaje espiritual. Tu mente es el espejo de tu alma.",
    ("Ruh Noktası", "Yengeç"): "Tu alma se amasa con profundidad emocional y pertenencia; tus raíces y tu familia son tu alimento espiritual. Tu mundo interior es tu refugio sagrado.",
    ("Ruh Noktası", "Aslan"): "Tu alma se eleva con creatividad y brillo; a medida que ves tu propia luz, brillas espiritualmente. La generosidad de tu corazón es la firma de tu alma.",
    ("Ruh Noktası", "Başak"): "Tu alma se nutre de servicio y purificación; cuanto más útil eres a los demás, más serena está tu alma. Tu búsqueda de perfección es tu disciplina espiritual.",
    ("Ruh Noktası", "Terazi"): "Tu alma se nutre de equilibrio y armonía; a medida que encuentras paz interior, maduras espiritualmente. La belleza y la justicia son el lenguaje de tu alma.",
    ("Ruh Noktası", "Akrep"): "Tu alma se amasa con la transformación; cuanto más te enfrentas a tus sombras, más resucitas espiritualmente. La purificación profunda es el centro de tu evolución.",
    ("Ruh Noktası", "Yay"): "Tu alma se eleva con libertad y sabiduría; a medida que amplías tu horizonte, creces espiritualmente. La búsqueda de la verdad es la brújula de tu alma.",
    ("Ruh Noktası", "Oğlak"): "Tu alma madura con estructura y responsabilidad; a medida que aprendes las lecciones de la vida con paciencia, tu autoridad espiritual se fortalece. Tu evolución es un ascenso disciplinado.",
    ("Ruh Noktası", "Kova"): "Tu alma se eleva con libertad y amor por la humanidad; a medida que te abres a la conciencia universal, te iluminas espiritualmente. La diferencia es la riqueza de tu alma.",
    ("Ruh Noktası", "Balık"): "Tu alma se amasa con intuición y compasión; a medida que aprendes a ser uno con el universo, te profundizas espiritualmente. Tu flujo interior es tu guía divina.",

    ("Evlilik Noktası", "Koç"): "Tu destino de compromiso es valiente y claro; en tu matrimonio, la iniciativa viene de ti. Tendrás un camino fuerte con tu pareja destinada.",
    ("Evlilik Noktası", "Boğa"): "Tu destino de compromiso es sólido como la tierra; tu matrimonio se construye sobre la confianza y la estabilidad. Tu vínculo destinado se fortalece con el tiempo.",
    ("Evlilik Noktası", "İkizler"): "Tu destino de compromiso se teje con comunicación y sintonía mental; tu matrimonio crece hablando y compartiendo. Tu pareja destinada es como tu alma gemela.",
    ("Evlilik Noktası", "Yengeç"): "Tu destino de compromiso se asienta en el alimento emocional; tu matrimonio se profundiza con el hogar y los valores familiares. Tu vínculo destinado es el refugio de tu corazón.",
    ("Evlilik Noktası", "Aslan"): "Tu destino de compromiso se teje con honor y generosidad; tu matrimonio se asienta en brillar juntos. Con tu pareja destinada compartís las luces del escenario.",
    ("Evlilik Noktası", "Başak"): "Tu destino de compromiso funciona con servicio y meticulosidad; tu matrimonio madura con el cuidado mutuo. Tu vínculo destinado se esconde en el amor por los detalles.",
    ("Evlilik Noktası", "Terazi"): "Tu destino de compromiso se construye con equilibrio y justicia; tu matrimonio se eleva sobre la igualdad. Tu pareja destinada es la mitad complementaria de tu vida.",
    ("Evlilik Noktası", "Akrep"): "Tu destino de compromiso es profundo y transformador; tu matrimonio es como un contrato espiritual. Tu vínculo destinado no se destruye con ninguna tormenta.",
    ("Evlilik Noktası", "Yay"): "Tu destino de compromiso se nutre de libertad y aventura; tu matrimonio se asienta en descubrir juntos. Con tu pareja destinada navegáis hacia horizontes.",
    ("Evlilik Noktası", "Oğlak"): "Tu destino de compromiso se construye sobre la responsabilidad y la estructura; tu matrimonio es a largo plazo y sólido. Tu vínculo destinado es un contrato de por vida.",
    ("Evlilik Noktası", "Kova"): "Tu destino de compromiso es original y poco convencional; tu matrimonio se construye rompiendo moldes. Tu pareja destinada es tu mejor amigo.",
    ("Evlilik Noktası", "Balık"): "Tu destino de compromiso se teje con amor incondicional; tu matrimonio es una unión espiritual. Tu vínculo destinado es la sagrada fusión de las almas.",

    ("Aşk Noktası", "Koç"): "Tu lenguaje de amor es valiente y directo; tu corazón no conoce obstáculos. Tu destino amoroso comienza con pasión y se corona con victoria.",
    ("Aşk Noktası", "Boğa"): "Tu lenguaje de amor es sensorial y leal; expresas tu amor con el tacto y la confianza. Tu destino amoroso es duradero y nutritivo.",
    ("Aşk Noktası", "İkizler"): "Tu lenguaje de amor son las palabras y el juego mental; tu corazón late con curiosidad. Tu destino amoroso brota con la charla y crece con el conocimiento.",
    ("Aşk Noktası", "Yengeç"): "Tu lenguaje de amor es el cariño y la seguridad emocional; tu corazón ama abrir los brazos. Tu destino amoroso es profundo y protector.",
    ("Aşk Noktası", "Aslan"): "Tu lenguaje de amor es la generosidad y la atención apasionada; tu corazón arde con las luces del escenario. Tu destino amoroso es magnífico y honorable.",
    ("Aşk Noktası", "Başak"): "Tu lenguaje de amor es el servicio y la delicadeza; muestras tu amor con cariño práctico. Tu destino amoroso es meticuloso y leal.",
    ("Aşk Noktası", "Terazi"): "Tu lenguaje de amor es la elegancia y la armonía; tu corazón se alimenta de estética. Tu destino amoroso es equilibrado y justo.",
    ("Aşk Noktası", "Akrep"): "Tu lenguaje de amor es intenso y transformador; tu corazón late en las profundidades del alma. Tu destino amoroso es un vínculo mortal.",
    ("Aşk Noktası", "Yay"): "Tu lenguaje de amor es la aventura y el entusiasmo; tu corazón alza el vuelo hacia los horizontes. Tu destino amoroso es alegre y expansivo.",
    ("Aşk Noktası", "Oğlak"): "Tu lenguaje de amor es serio y responsable; tu corazón se fortalece con el esfuerzo. Tu destino amoroso se construye sobre la lealtad.",
    ("Aşk Noktası", "Kova"): "Tu lenguaje de amor es original y amistoso; tu corazón se nutre de libertad. Tu destino amoroso es poco convencional y libre.",
    ("Aşk Noktası", "Balık"): "Tu lenguaje de amor es romántico e incondicional; tu corazón se llena de sueños y compasión. Tu destino amoroso es espiritual y de cuento.",

    ("Tutku Noktası", "Koç"): "Tu fuego interior arde repentino y fuerte; tus deseos se convierten directamente en acción. Tu pasión escribe tu destino con valentía.",
    ("Tutku Noktası", "Boğa"): "Tu fuego interior arde profundo y constante; tus deseos son sensoriales y duraderos. Tu pasión construye tu destino con determinación.",
    ("Tutku Noktası", "İkizler"): "Tu fuego interior arde mental y ágil; tus deseos se nutren de curiosidad. Tu pasión teje tu destino con descubrimiento.",
    ("Tutku Noktası", "Yengeç"): "Tu fuego interior arde emocional y protector; tus deseos están ligados a la familia y la seguridad. Tu pasión dirige tu destino con cariño.",
    ("Tutku Noktası", "Aslan"): "Tu fuego interior arde magnífico y creativo; tus deseos se fortalecen con el aprecio y el brillo. Tu pasión corona tu destino con esplendor.",
    ("Tutku Noktası", "Başak"): "Tu fuego interior arde meticuloso y ordenado; tus deseos se amasan con servicio y perfección. Tu pasión talla tu destino con delicadeza.",
    ("Tutku Noktası", "Terazi"): "Tu fuego interior arde elegante y armonioso; tus deseos se nutren de belleza y equilibrio. Tu pasión dirige tu destino con estética.",
    ("Tutku Noktası", "Akrep"): "Tu fuego interior arde intenso e inextinguible; tus deseos se fortalecen con profundidad y control. Tu pasión escribe tu destino transformándolo.",
    ("Tutku Noktası", "Yay"): "Tu fuego interior arde expansivo y entusiasta; tus deseos se nutren de libertad e ideales. Tu pasión lleva tu destino hacia el horizonte.",
    ("Tutku Noktası", "Oğlak"): "Tu fuego interior arde disciplinado y decidido; tus deseos se nutren de éxito y estatus. Tu pasión lleva tu destino a la cima.",
    ("Tutku Noktası", "Kova"): "Tu fuego interior arde original y revolucionario; tus deseos se nutren de libertad e ideales. Tu pasión pone tu destino en un camino poco convencional.",
    ("Tutku Noktası", "Balık"): "Tu fuego interior arde intuitivo y fluido; tus deseos se nutren de sueños y espiritualidad. Tu pasión dirige tu destino con inspiración.",

    ("Para Noktası", "Koç"): "Tu destino de dinero se abre con el espíritu emprendedor; cuando das el primer paso con valentía, la abundancia te encuentra. Las oportunidades materiales llegan cuando eres pionero.",
    ("Para Noktası", "Boğa"): "Tu destino de dinero se teje con tierra y constancia; tus ahorros regulares traen abundancia. La prosperidad material es el fruto de tu esfuerzo paciente.",
    ("Para Noktası", "İkizler"): "Tu destino de dinero se abre con la comunicación y el comercio; tu conocimiento y tus conexiones generan ganancias. Las oportunidades materiales crecen al compartir.",
    ("Para Noktası", "Yengeç"): "Tu destino de dinero está ligado a la seguridad y el hogar; los trabajos que añaden valor a tu familia traen abundancia. La prosperidad se nutre de la seguridad emocional.",
    ("Para Noktası", "Aslan"): "Tu destino de dinero se abre con la creatividad y el escaparate; a medida que exhibes tus talentos, las ganancias aumentan. La abundancia llega alimentando tu generosidad.",
    ("Para Noktası", "Başak"): "Tu destino de dinero se teje con servicio y análisis; los recursos gestionados con meticulosidad se multiplican. La abundancia llega con los sistemas ordenados.",
    ("Para Noktası", "Terazi"): "Tu destino de dinero se abre con la alianza y la armonía; las colaboraciones y tu gusto estético generan ganancias. La abundancia aumenta con el reparto equilibrado.",
    ("Para Noktası", "Akrep"): "Tu destino de dinero se teje con transformación y profundidad; tu poder de gestión de recursos es alto. La abundancia llega con la reestructuración.",
    ("Para Noktası", "Yay"): "Tu destino de dinero se abre con la expansión y las oportunidades; las conexiones y los descubrimientos en el extranjero generan ganancias. La abundancia llega con una visión amplia.",
    ("Para Noktası", "Oğlak"): "Tu destino de dinero se teje con disciplina y estrategia; los objetivos a largo plazo engrandecen tu ganancia. La abundancia es el resultado del ascenso paciente.",
    ("Para Noktası", "Kova"): "Tu destino de dinero se abre con la innovación y la tecnología; tus ideas poco convencionales generan ganancias. La abundancia llega con los emprendimientos originales.",
    ("Para Noktası", "Balık"): "Tu destino de dinero se teje con intuición e inspiración; los ámbitos artísticos y espirituales te ofrecen oportunidades. La abundancia llega cuando confías en el flujo.",
}

ARAP_NOKTA_EV_YORUMLARI = {
    ("Şans Noktası", 1): "Tu energía de fortuna se corona en tu identidad; las oportunidades te encuentran en tu primer paso.",
    ("Şans Noktası", 2): "Tu energía de fortuna se alimenta de valores materiales; las oportunidades se multiplican con tu autoestima.",
    ("Şans Noktası", 3): "Tu energía de fortuna brilla en la comunicación; las oportunidades llegan con tu entorno y tu conocimiento.",
    ("Şans Noktası", 4): "Tu energía de fortuna está oculta en tus raíces; la familia y el hogar te abren la puerta de las oportunidades.",
    ("Şans Noktası", 5): "Tu energía de fortuna brilla en la creatividad; las oportunidades llegan a través del juego y el arte.",
    ("Şans Noktası", 6): "Tu energía de fortuna funciona en el orden diario; las oportunidades llegan con el servicio y la meticulosidad.",
    ("Şans Noktası", 7): "Tu energía de fortuna se eleva en las alianzas; las oportunidades llegan con tus relaciones.",
    ("Şans Noktası", 8): "Tu energía de fortuna se fortalece en la transformación; las oportunidades llegan con la herencia y los vínculos profundos.",
    ("Şans Noktası", 9): "Tu energía de fortuna brilla en el horizonte; las oportunidades llegan con el viaje y la sabiduría.",
    ("Şans Noktası", 10): "Tu energía de fortuna se corona en la carrera; las oportunidades llegan con tus objetivos.",
    ("Şans Noktası", 11): "Tu energía de fortuna se eleva en las amistades; las oportunidades llegan con tus comunidades.",
    ("Şans Noktası", 12): "Tu energía de fortuna se profundiza en la espiritualidad; las oportunidades llegan con tu intuición.",

    ("Ruh Noktası", 1): "Tu propósito espiritual está entrelazado con tu identidad; vives tu alma siendo tú mismo.",
    ("Ruh Noktası", 2): "Tu propósito espiritual se nutre de tus valores; tu autoestima es el espejo de tu alma.",
    ("Ruh Noktası", 3): "Tu propósito espiritual está en aprender y compartir; las palabras son el puente de tu alma.",
    ("Ruh Noktası", 4): "Tu propósito espiritual está oculto en tus raíces; tus lazos familiares nutren tu alma.",
    ("Ruh Noktası", 5): "Tu propósito espiritual brilla en la creatividad; tu expresión es la alegría de tu alma.",
    ("Ruh Noktası", 6): "Tu propósito espiritual funciona en el servicio; ser útil purifica tu alma.",
    ("Ruh Noktası", 7): "Tu propósito espiritual se refleja en las relaciones; tus vínculos maduran tu alma.",
    ("Ruh Noktası", 8): "Tu propósito espiritual se profundiza en la transformación; la purificación es la sanación de tu alma.",
    ("Ruh Noktası", 9): "Tu propósito espiritual se eleva en la verdad; tu fe es la luz de tu alma.",
    ("Ruh Noktası", 10): "Tu propósito espiritual se corona en la responsabilidad; tu misión es el camino de tu alma.",
    ("Ruh Noktası", 11): "Tu propósito espiritual brilla en el amor por la humanidad; tu comunidad nutre tu alma.",
    ("Ruh Noktası", 12): "Tu propósito espiritual se profundiza en la espiritualidad; tu flujo interior es tu guía divina.",

    ("Evlilik Noktası", 1): "Tu destino de matrimonio está ligado a tu identidad; el compromiso es la base de tu ser.",
    ("Evlilik Noktası", 2): "Tu destino de matrimonio se nutre de confianza y valores; tu alianza se asienta en la base material.",
    ("Evlilik Noktası", 3): "Tu destino de matrimonio se fortalece con la comunicación; tu unión crece con la charla.",
    ("Evlilik Noktası", 4): "Tu destino de matrimonio se corona en la vida del hogar; formar una familia es el centro de tu destino.",
    ("Evlilik Noktası", 5): "Tu destino de matrimonio se nutre de alegría y creatividad; tu unión está llena de entusiasmo.",
    ("Evlilik Noktası", 6): "Tu destino de matrimonio funciona con el servicio diario; tu alianza se fortalece con el cuidado.",
    ("Evlilik Noktası", 7): "Tu destino de matrimonio es el ámbito de la casa número uno; tu pareja es el espejo de tu vida.",
    ("Evlilik Noktası", 8): "Tu destino de matrimonio se teje con vínculos profundos; tu unión es un contrato espiritual.",
    ("Evlilik Noktası", 9): "Tu destino de matrimonio se eleva con los ideales comunes; crecéis juntos.",
    ("Evlilik Noktası", 10): "Tu destino de matrimonio se corona en el rol social; camináis hacia los objetivos junto a tu pareja.",
    ("Evlilik Noktası", 11): "Tu destino de matrimonio se nutre de la amistad; tu pareja es tu amigo más cercano.",
    ("Evlilik Noktası", 12): "Tu destino de matrimonio se profundiza en la espiritualidad; tu unión es una fusión espiritual.",

    ("Aşk Noktası", 1): "Tu destino de amor brilla con tu identidad; tu amor es la luz de tu ser.",
    ("Aşk Noktası", 2): "Tu destino de amor se nutre del valor propio; cuanto más te amas, más amor atraes.",
    ("Aşk Noktası", 3): "Tu destino de amor brota en la comunicación; tu corazón habla con palabras.",
    ("Aşk Noktası", 4): "Tu destino de amor florece en la seguridad emocional; tu corazón busca un hogar.",
    ("Aşk Noktası", 5): "Tu destino de amor brilla con el romanticismo; tu corazón arde con juegos y alegría.",
    ("Aşk Noktası", 6): "Tu destino de amor se nutre de servicio y cuidado; tu amor crece con el cariño práctico.",
    ("Aşk Noktası", 7): "Tu destino de amor se refleja en las relaciones; el amor es la base principal de tu vida.",
    ("Aşk Noktası", 8): "Tu destino de amor se amasa en la profundidad; tu corazón late con vínculos espirituales.",
    ("Aşk Noktası", 9): "Tu destino de amor brilla con la aventura; tu corazón viaja hacia tierras lejanas.",
    ("Aşk Noktası", 10): "Tu destino de amor se fortalece con el rol social; tu amor se nutre de respeto.",
    ("Aşk Noktası", 11): "Tu destino de amor florece en la amistad; tu corazón late dentro de una comunidad.",
    ("Aşk Noktası", 12): "Tu destino de amor se profundiza en la espiritualidad; tu corazón arde con amor divino.",

    ("Tutku Noktası", 1): "Tu pasión brota de tu identidad; tu fuego pone tu ser en movimiento.",
    ("Tutku Noktası", 2): "Tu pasión se nutre de tus valores; tus deseos se convierten en ganancia.",
    ("Tutku Noktası", 3): "Tu pasión brilla en tu mente; tus deseos se fortalecen con las ideas.",
    ("Tutku Noktası", 4): "Tu pasión arde en tus raíces; tu familia alimenta tu fuego.",
    ("Tutku Noktası", 5): "Tu pasión se enciende en la creatividad; tus deseos brillan en el arte.",
    ("Tutku Noktası", 6): "Tu pasión funciona en el servicio; tus deseos encuentran fuerza en las tareas diarias.",
    ("Tutku Noktası", 7): "Tu pasión arde en las relaciones; tus deseos se fortalecen con los vínculos.",
    ("Tutku Noktası", 8): "Tu pasión se enciende en la profundidad; tus deseos se nutren de transformación.",
    ("Tutku Noktası", 9): "Tu pasión brilla en el horizonte; tus deseos crecen con el descubrimiento.",
    ("Tutku Noktası", 10): "Tu pasión se corona en la carrera; tus deseos se elevan con los objetivos.",
    ("Tutku Noktası", 11): "Tu pasión arde en la amistad; tus deseos se fortalecen con los ideales.",
    ("Tutku Noktası", 12): "Tu pasión se profundiza en la espiritualidad; tus deseos se nutren de inspiración.",

    ("Para Noktası", 1): "Tu destino de dinero está ligado a tu identidad; tu ganancia crece con tu iniciativa.",
    ("Para Noktası", 2): "Tu destino de dinero es tu ámbito natural; la abundancia desborda desde aquí.",
    ("Para Noktası", 3): "Tu destino de dinero funciona con el comercio y la comunicación; tu conocimiento se convierte en ganancia.",
    ("Para Noktası", 4): "Tu destino de dinero está en la familia y los bienes raíces; tus raíces te traen ganancia.",
    ("Para Noktası", 5): "Tu destino de dinero brilla con la creatividad; tus talentos se convierten en ganancia.",
    ("Para Noktası", 6): "Tu destino de dinero funciona con el servicio; tu esfuerzo meticuloso trae abundancia.",
    ("Para Noktası", 7): "Tu destino de dinero se eleva en las alianzas; las colaboraciones traen ganancia.",
    ("Para Noktası", 8): "Tu destino de dinero está en los recursos profundos; la inversión y la herencia te ofrecen oportunidades.",
    ("Para Noktası", 9): "Tu destino de dinero brilla en la expansión; los vínculos extranjeros aumentan tu ganancia.",
    ("Para Noktası", 10): "Tu destino de dinero se corona en la carrera; tu profesión trae abundancia.",
    ("Para Noktası", 11): "Tu destino de dinero se nutre de redes; tu comunidad aumenta tu ganancia.",
    ("Para Noktası", 12): "Tu destino de dinero funciona en la espiritualidad; tu intuición percibe las oportunidades.",
}

ARAP_EV_KISAYORUMLARI = {
    1: "Crea un efecto destinado en el ámbito de la identidad y el ser.",
    2: "Crea un efecto destinado en el ámbito de los valores y los recursos materiales.",
    3: "Crea un efecto destinado en el ámbito de la comunicación y el entorno cercano.",
    4: "Crea un efecto destinado en el ámbito de las raíces familiares y el hogar.",
    5: "Crea un efecto destinado en el ámbito de la creatividad y la vida amorosa.",
    6: "Crea un efecto destinado en el ámbito del orden diario y la salud.",
    7: "Crea un efecto destinado en el ámbito de las alianzas y las relaciones.",
    8: "Crea un efecto destinado en el ámbito de la transformación y los vínculos profundos.",
    9: "Crea un efecto destinado en el ámbito de la fe y la expansión.",
    10: "Crea un efecto destinado en el ámbito de la carrera y el rol social.",
    11: "Crea un efecto destinado en el ámbito de las amistades y las comunidades.",
    12: "Crea un efecto destinado en el ámbito del subconsciente y la espiritualidad.",
}

ARAP_NOKTA_SINASTRI_YORUMLARI = {
    ("Şans Noktası", "Şans Noktası"): "Vuestros puntos de fortuna vibran en la misma sintonía del destino; os espera un viaje afortunado juntos.",
    ("Şans Noktası", "Ruh Noktası"): "La fortuna de uno ilumina el camino espiritual del otro; vuestros destinos se alimentan mutuamente.",
    ("Şans Noktası", "Evlilik Noktası"): "Tu fortuna fortalece vuestro compromiso; las oportunidades se abren cuando estáis juntos.",
    ("Şans Noktası", "Aşk Noktası"): "Tu energía de fortuna y amor se entrelazan; vuestra unión se alimenta de la gracia del destino.",
    ("Şans Noktası", "Tutku Noktası"): "Tu fortuna pone vuestra pasión en movimiento; dais pasos valientes cuando estáis juntos.",
    ("Şans Noktası", "Para Noktası"): "Tu energía de fortuna y abundancia se unen; las oportunidades materiales se abren cuando estáis juntos.",
    ("Ruh Noktası", "Ruh Noktası"): "Vuestros puntos del alma están en la misma frecuencia; existe un acuerdo espiritual entre vosotros.",
    ("Ruh Noktası", "Evlilik Noktası"): "Tu camino espiritual se cruza con vuestro destino de compromiso; vuestra unión lleva un propósito espiritual.",
    ("Ruh Noktası", "Aşk Noktası"): "Tu alma y tu corazón laten juntos; tu amor lleva una profundidad espiritual.",
    ("Ruh Noktası", "Tutku Noktası"): "Tu propósito espiritual y tu pasión se unen; vuestro fuego interior se fortalece cuando estáis juntos.",
    ("Ruh Noktası", "Para Noktası"): "Tu camino espiritual se apoya en recursos materiales; juntos encontráis el equilibrio.",
    ("Evlilik Noktası", "Evlilik Noktası"): "Vuestros puntos de matrimonio vibran en la misma sintonía; entre vosotros hay un contrato de compromiso destinado.",
    ("Evlilik Noktası", "Aşk Noktası"): "Vuestro destino de amor y compromiso se une; vuestra unión es duradera y apasionada.",
    ("Evlilik Noktası", "Tutku Noktası"): "Vuestra energía de compromiso y pasión se entrelaza; vuestra unión es ardiente pero sólida.",
    ("Evlilik Noktası", "Para Noktası"): "Vuestra energía de compromiso y abundancia se une; construís juntos un futuro sólido.",
    ("Aşk Noktası", "Aşk Noktası"): "Vuestros puntos de amor están en la misma frecuencia; vuestros corazones laten al mismo ritmo.",
    ("Aşk Noktası", "Tutku Noktası"): "Vuestra energía de amor y pasión está en perfecta armonía; vuestra unión es romántica y ardiente.",
    ("Aşk Noktası", "Para Noktası"): "Vuestra energía de amor y abundancia se une; cuando estáis juntos fluyen el amor y la prosperidad.",
    ("Tutku Noktası", "Tutku Noktası"): "Vuestros puntos de pasión vibran en la misma sintonía; vuestra energía se multiplica cuando estáis juntos.",
    ("Tutku Noktası", "Para Noktası"): "Vuestra energía de pasión y abundancia se une; vuestro coraje crea oportunidades materiales.",
    ("Para Noktası", "Para Noktası"): "Vuestros puntos de dinero están en la misma frecuencia; vuestra energía de abundancia se fortalece cuando estáis juntos.",
}

ARAP_NOKTA_GEZEGEN_SINASTRI = {
    ("Şans Noktası", "Güneş"): "Tu punto de fortuna se une al Sol del otro; tu presencia trae oportunidades a su vida.",
    ("Şans Noktası", "Ay"): "Tu punto de fortuna se une a la Luna del otro; sus emociones encuentran suerte a tu lado.",
    ("Şans Noktası", "Venüs"): "Tu punto de fortuna se une a la Venus del otro; la belleza y las oportunidades van juntas cuando estáis juntos.",
    ("Şans Noktası", "Mars"): "Tu punto de fortuna se une al Marte del otro; los pasos valientes traen abundancia cuando estáis juntos.",
    ("Şans Noktası", "Jüpiter"): "Tu punto de fortuna se une al Júpiter del otro; la expansión y la abundancia fluyen juntas.",
    ("Şans Noktası", "Satürn"): "Tu punto de fortuna se une al Saturno del otro; las oportunidades llegan con la responsabilidad.",
    ("Ruh Noktası", "Güneş"): "Tu punto del alma se une al Sol del otro; su presencia ilumina tu camino espiritual.",
    ("Ruh Noktası", "Ay"): "Tu punto del alma se une a la Luna del otro; vuestras almas se encuentran en una profundidad emocional.",
    ("Ruh Noktası", "Venüs"): "Tu punto del alma se une a la Venus del otro; vuestro vínculo espiritual se teje con amor.",
    ("Ruh Noktası", "Mars"): "Tu punto del alma se une al Marte del otro; vuestro camino espiritual avanza con valentía.",
    ("Ruh Noktası", "Jüpiter"): "Tu punto del alma se une al Júpiter del otro; juntos os expandís espiritualmente.",
    ("Ruh Noktası", "Satürn"): "Tu punto del alma se une al Saturno del otro; vuestro vínculo espiritual es obra del destino.",
    ("Evlilik Noktası", "Güneş"): "Tu punto de matrimonio se une al Sol del otro; su identidad completa tu destino de compromiso.",
    ("Evlilik Noktası", "Ay"): "Tu punto de matrimonio se une a la Luna del otro; vuestro vínculo emocional se nutre del compromiso.",
    ("Evlilik Noktası", "Venüs"): "Tu punto de matrimonio se une a la Venus del otro; vuestro destino de amor y compromiso se une.",
    ("Evlilik Noktası", "Mars"): "Tu punto de matrimonio se une al Marte del otro; vuestra unión es ardiente y fiel.",
    ("Evlilik Noktası", "Jüpiter"): "Tu punto de matrimonio se une al Júpiter del otro; vuestro compromiso se nutre de abundancia.",
    ("Evlilik Noktası", "Satürn"): "Tu punto de matrimonio se une al Saturno del otro; vuestro vínculo es la firma más sólida del destino.",
    ("Aşk Noktası", "Güneş"): "Tu punto de amor se une al Sol del otro; su presencia calienta tu corazón.",
    ("Aşk Noktası", "Ay"): "Tu punto de amor se une a la Luna del otro; tu corazón late con sus emociones.",
    ("Aşk Noktası", "Venüs"): "Tu punto de amor se une a la Venus del otro; vuestra energía de amor está en perfecta armonía.",
    ("Aşk Noktası", "Mars"): "Tu punto de amor se une al Marte del otro; vuestra atracción es fuerte y apasionada.",
    ("Aşk Noktası", "Jüpiter"): "Tu punto de amor se une al Júpiter del otro; vuestro amor crece juntos.",
    ("Aşk Noktası", "Satürn"): "Tu punto de amor se une al Saturno del otro; vuestro amor desafía al tiempo.",
    ("Tutku Noktası", "Güneş"): "Tu punto de pasión se une al Sol del otro; su presencia aviva tu fuego interior.",
    ("Tutku Noktası", "Ay"): "Tu punto de pasión se une a la Luna del otro; vuestras emociones se encienden juntas.",
    ("Tutku Noktası", "Venüs"): "Tu punto de pasión se une a la Venus del otro; el deseo y el amor se entrelazan.",
    ("Tutku Noktası", "Mars"): "Tu punto de pasión se une al Marte del otro; vuestra energía se duplica juntos.",
    ("Tutku Noktası", "Jüpiter"): "Tu punto de pasión se une al Júpiter del otro; vuestro entusiasmo crece cuando estáis juntos.",
    ("Tutku Noktası", "Satürn"): "Tu punto de pasión se une al Saturno del otro; tu deseo se fortalece con la disciplina.",
    ("Para Noktası", "Güneş"): "Tu punto de dinero se une al Sol del otro; su presencia aumenta tu ganancia.",
    ("Para Noktası", "Ay"): "Tu punto de dinero se une a la Luna del otro; la seguridad material aumenta cuando estáis juntos.",
    ("Para Noktası", "Venüs"): "Tu punto de dinero se une a la Venus del otro; la abundancia y la belleza fluyen juntas.",
    ("Para Noktası", "Mars"): "Tu punto de dinero se une al Marte del otro; trabajáis con valentía por la ganancia cuando estáis juntos.",
    ("Para Noktası", "Jüpiter"): "Tu punto de dinero se une al Júpiter del otro; la abundancia se multiplica cuando estáis juntos.",
    ("Para Noktası", "Satürn"): "Tu punto de dinero se une al Saturno del otro; construís juntos una fortuna sólida.",
}

ASTEROID_ISIMLERI = {
    "Juno": {"etki": "Energía del matrimonio, la lealtad, el compromiso y la alianza"},
    "Ceres": {"etki": "Instinto de nutrición, compasión, maternidad y protección"},
    "Pallas": {"etki": "Inteligencia estratégica, solución creativa y sabiduría"},
    "Vesta": {"etki": "Enfoque sagrado, dedicación y fuego interior"},
    "Eros": {"etki": "Pasión, intensidad del deseo y atracción sexual"},
    "Psyche": {"etki": "Profundidad espiritual, vulnerabilidad y vínculo inconsciente"},
    "Sappho": {"etki": "Romanticismo, pasión estética y profundidad emocional"},
    "Amor": {"etki": "Amor incondicional, aceptación y vínculo del corazón"},
}

ASTEROID_SINASTRI_YORUMLARI = {
    ("Juno", "Güneş"): "Tu Juno se une a su Sol; tu compromiso se integra con su identidad y la lealtad se instala en el centro de vuestro destino.",
    ("Juno", "Ay"): "Tu Juno se une a su Luna; la seguridad emocional y la lealtad van juntas, vuestro vínculo se nutre de compasión.",
    ("Juno", "Venüs"): "Tu Juno se une a su Venus; la energía del matrimonio y el amor se unen, vuestra unión queda sellada con amor.",
    ("Juno", "Mars"): "Tu Juno se une a su Marte; tu compromiso se enciende con pasión, la atracción entre vosotros es fuerte.",
    ("Juno", "Jüpiter"): "Tu Juno se une a su Júpiter; vuestra unión se nutre de abundancia y expansión.",
    ("Juno", "Satürn"): "Tu Juno se une a su Saturno; vuestro compromiso es destinado y duradero, el contrato de matrimonio es fuerte.",
    ("Ceres", "Ay"): "Tu Ceres se une a su Luna; la nutrición mutua y la compasión se convierten en la base de vuestro vínculo.",
    ("Ceres", "Venüs"): "Tu Ceres se une a su Venus; tu amor es nutritivo y compasivo, vuestra unión está llena de paz.",
    ("Ceres", "Güneş"): "Tu Ceres se une a su Sol; su presencia te nutre, entre vosotros fluye una energía maternal.",
    ("Ceres", "Mars"): "Tu Ceres se une a su Marte; tu instinto de protección es fuerte, superáis juntos las dificultades.",
    ("Ceres", "Jüpiter"): "Tu Ceres se une a su Júpiter; la compasión y la abundancia fluyen juntas cuando estáis juntos.",
    ("Ceres", "Satürn"): "Tu Ceres se une a su Saturno; construís un vínculo de cuidado y confianza responsable.",
    ("Pallas", "Merkür"): "Tu Pallas se une a su Mercurio; vuestra sintonía mental es alta, encontráis soluciones inteligentes juntos.",
    ("Pallas", "Güneş"): "Tu Pallas se une a su Sol; tu sabiduría estratégica fortalece su identidad.",
    ("Pallas", "Ay"): "Tu Pallas se une a su Luna; vuestra inteligencia emocional es alta, os conectáis con soluciones intuitivas.",
    ("Pallas", "Venüs"): "Tu Pallas se une a su Venus; la elegancia y la estrategia se unen, vuestra unión es refinada.",
    ("Pallas", "Mars"): "Tu Pallas se une a su Marte; os convertís en un equipo que lucha con inteligencia.",
    ("Vesta", "Güneş"): "Tu Vesta se une a su Sol; vuestro enfoque aumenta cuando estáis juntos, os dedicáis a vuestros objetivos comunes.",
    ("Vesta", "Ay"): "Tu Vesta se une a su Luna; vuestra dedicación emocional es fuerte, tu vínculo se nutre de fuego interior.",
    ("Vesta", "Mars"): "Tu Vesta se une a su Marte; vuestra energía común es disciplinada y orientada a objetivos.",
    ("Vesta", "Satürn"): "Tu Vesta se une a su Saturno; vuestra unión es como una misión sagrada, vuestra dedicación es sólida.",
    ("Eros", "Venüs"): "Tu Eros se une a su Venus; la pasión y el amor se entrelazan, vuestra atracción es irresistible.",
    ("Eros", "Mars"): "Tu Eros se une a su Marte; la atracción entre vosotros es intensa y ardiente, el deseo dirige vuestro destino.",
    ("Eros", "Ay"): "Tu Eros se une a su Luna; vuestro vínculo emocional se amasa con pasión.",
    ("Eros", "Güneş"): "Tu Eros se une a su Sol; su presencia enciende tus deseos.",
    ("Psyche", "Ay"): "Tu Psyche se une a su Luna; vuestras almas se encuentran en la profundidad emocional, creáis un vínculo telepático.",
    ("Psyche", "Venüs"): "Tu Psyche se une a su Venus; el amor espiritual y romántico se unen, vuestro vínculo es de cuento.",
    ("Psyche", "Güneş"): "Tu Psyche se une a su Sol; tu alma se vincula profundamente con su identidad.",
    ("Psyche", "Neptün"): "Tu Psyche se une a su Neptuno; vuestro vínculo espiritual alcanza dimensiones divinas.",
    ("Sappho", "Venüs"): "Tu Sappho se une a su Venus; vuestro romanticismo está en la cima, vuestro amor es estético y profundo.",
    ("Sappho", "Ay"): "Tu Sappho se une a su Luna; vuestro vínculo emocional es poético y sensible.",
    ("Sappho", "Mars"): "Tu Sappho se une a su Marte; un romanticismo apasionado fluye entre vosotros.",
    ("Sappho", "Güneş"): "Tu Sappho se une a su Sol; su presencia hace brillar tus sentimientos románticos.",
    ("Amor", "Venüs"): "Tu Amor se une a su Venus; el amor incondicional y el amor se unen, vuestro vínculo es sagrado.",
    ("Amor", "Ay"): "Tu Amor se une a su Luna; tu amor es incondicional y compasivo, vuestro vínculo emocional es profundo.",
    ("Amor", "Güneş"): "Tu Amor se une a su Sol; tu amor completa su presencia.",
    ("Amor", "Mars"): "Tu Amor se une a su Marte; tu amor incondicional se fortalece con la pasión.",
}

ARAP_NOKTA_ADLARI_ES = {
    "Şans Noktası": "Parte de la Fortuna",
    "Ruh Noktası": "Punto del Espíritu",
    "Evlilik Noktası": "Punto del Matrimonio",
    "Aşk Noktası": "Punto del Amor",
    "Tutku Noktası": "Punto de la Pasión",
    "Para Noktası": "Punto del Dinero",
}