ARAP_NOKTALARI_EBEVEYN = {
    "Baba Noktası":     {"nokta1": "10HC", "nokta2": "Güneş", "kisa": "BABA", "aciklama": "Baba figürü, otorite ve disiplin enerjisi"},
    "Anne Noktası":     {"nokta1": "4HC",  "nokta2": "Ay",     "kisa": "ANNE", "aciklama": "Anne figürü, besleme ve duygusal koruma"},
    "Çocuk Ruhu":       {"nokta1": "5HC",  "nokta2": "Jüpiter","kisa": "ÇRUH", "aciklama": "Çocuğun ruhsal amacı ve yaratıcı potansiyeli"},
    "Koruma Noktası":   {"nokta1": "2HC",  "nokta2": "Mars",   "kisa": "KORU", "aciklama": "Fiziksel ve maddi koruma enerjisi"},
    "Eğitim Noktası":   {"nokta1": "9HC",  "nokta2": "Merkür", "kisa": "EĞİT", "aciklama": "Öğretme-öğrenme ve felsefi aktarım"},
    "Sınır Noktası":    {"nokta1": "6HC",  "nokta2": "Satürn", "kisa": "SINR", "aciklama": "Disiplin, sınır koyma ve günlük düzen"},
    "Bağlanma Noktası": {"nokta1": "4HC",  "nokta2": "Venüs",  "kisa": "BAGL", "aciklama": "Duygusal bağlanma biçimi ve şefkat dili"},
    "Sorumluluk":       {"nokta1": "10HC", "nokta2": "Satürn", "kisa": "SORU", "aciklama": "Ebeveynlik sorumluluğu ve toplumsal rol"},
}

ARAP_NOKTA_BURC_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", "Koç"): "Baba enerjisi kaderselliğiniz cesur, öncü ve bağımsız bir ruhla harmanlanmış. Çocuğunuz için dünyanın karşısında dimdik duran, inisiyatif alan bir baba/anne figürü sergilersiniz.",
    ("Baba Noktası", "Boğa"): "Baba enerjisi kaderselliğiniz toprak, güvenirlik ve kalıcılık üzerine kuruludur. Çocuğunuza maddi ve manevi güvenlik sağlayan, sarsılmaz bir koruyucu olursunuz.",
    ("Baba Noktası", "İkizler"): "Baba enerjisi kaderselliğiniz iletişim, zihinsel uyum ve çok yönlülük üzerine inşa edilmiş. Çocuğunuzla konuşarak, öğrenerek ve paylaşarak büyüyen bir baba/anne olursunuz.",
    ("Baba Noktası", "Yengeç"): "Baba enerjisi kaderselliğiniz derin duygusal beslenme ve koruma içgüdüsüyle yoğrulmuş. Çocuğunuz için sarsılmaz bir duygusal sığınak inşa edersiniz.",
    ("Baba Noktası", "Aslan"): "Baba enerjisi kaderselliğiniz görkem, yaratıcılık ve cömertlik üzerine kuruludur. Çocuğunuzun yeteneklerini parlatan, onunla gurur duyan bir rehber olursunuz.",
    ("Baba Noktası", "Başak"): "Baba enerjisi kaderselliğiniz hizmet, mükemmellik arayışı ve pratik düzen üzerine inşa edilmiş. Çocuğunuzun her ihtiyacını titizlikle karşılayan bir sistem kurarsınız.",
    ("Baba Noktası", "Terazi"): "Baba enerjisi kaderselliğiniz uyum, estetik ve denge üzerine kuruludur. Çocuğunuzla adaletli ve dengeli bir ilişki kuran, zarif bir rehber olursunuz.",
    ("Baba Noktası", "Akrep"): "Baba enerjisi kaderselliğiniz derin dönüşüm, yoğunluk ve gizem üzerine yoğrulmuş. Çocuğunuz için her türlü tehlikeye karşı tetikte olan, okült bir baba/anne enerjisi sergilersiniz.",
    ("Baba Noktası", "Yay"): "Baba enerjisi kaderselliğiniz özgürlük, genişleme ve felsefi derinlik üzerine kuruludur. Çocuğunuza geniş bir vizyon aşılayan, hayatı birlikte keşfeden bir rehber olursunuz.",
    ("Baba Noktası", "Oğlak"): "Baba enerjisi kaderselliğiniz yapı, sorumluluk ve uzun vadeli planlar üzerine inşa edilmiş. Çocuğunuza disiplin ve yapı veren, hayata hazırlayan bir baba/anne olursunuz.",
    ("Baba Noktası", "Kova"): "Baba enerjisi kaderselliğiniz sıra dışı,özgür ve devrimci bir ruhla harmanlanmış. Çocuğunuzu kalıplara sokmayan, bireyselliğine saygı duyan bir rehber olursunuz.",
    ("Baba Noktası", "Balık"): "Baba enerjisi kaderselliğiniz maneviyat, fedakarlık ve sezgisel derinlik üzerine kuruludur. Çocuğunuzla ruhsal bir bağ kuran, onun manevi gelişimine odaklanan bir baba/anne olursunuz.",

    ("Anne Noktası", "Koç"): "Anne enerjisi kaderselliğiniz cesur, inisiyatif alan ve koruyucu bir ruhla yoğrulmuş. Çocuğunuz için dünyaya meydan okuyan, onu korumak adına her şeyi yapan bir anne/anne figürü sergilersiniz.",
    ("Anne Noktası", "Boğa"): "Anne enerjisi kaderselliğiniz toprak, besleyicilik ve kalıcılık üzerine kuruludur. Çocuğunuzu fiziksel ve duygusal olarak besleyen, güvenli bir yuva inşa eden bir rehber olursunuz.",
    ("Anne Noktası", "İkizler"): "Anne enerjisi kaderselliğiniz iletişim, neşe ve merak üzerine inşa edilmiş. Çocuğunuzla bilgi paylaşan, her şeyi birlikte keşfeden eğlenceli bir anne/anne olursunuz.",
    ("Anne Noktası", "Yengeç"): "Anne enerjisi kaderselliğiniz derin duygusal beslenme ve koruma içgüdüsüyle yoğrulmuş. Çocuğunuz için sarsılmaz bir duygusal liman, sıcak bir kucaksınız.",
    ("Anne Noktası", "Aslan"): "Anne enerjisi kaderselliğiniz görkem, cömertlik ve sevgi dolu bir kalple kuruludur. Çocuğunuzun parlakığını sahneye koyan, onunla gurur duyan bir anne/anne olursunuz.",
    ("Anne Noktası", "Başak"): "Anne enerjisi kaderselliğiniz titizlik, hizmet ve pratik mükemmellik üzerine inşa edilmiş. Çocuğunuzun sağlık, beslenme ve bakım ihtiyaçlarını kusursuz karşılayan bir düzen kurarsınız.",
    ("Anne Noktası", "Terazi"): "Anne enerjisi kaderselliğiniz zarafet, uyum ve denge üzerine kuruludur. Çocuğunuzla adil ve dengeli bir ilişki kuran, estetik duyarlılık taşıyan bir rehber olursunuz.",
    ("Anne Noktası", "Akrep"): "Anne enerjisi kaderselliğiniz derin yoğunluk, dönüşüm ve koruyuculuk üzerine yoğrulmuş. Çocuğunuz için her türlü tehlikeye karşı tetikte olan, derin bir sezgiye sahip bir anne/anne olursunuz.",
    ("Anne Noktası", "Yay"): "Anne enerjisi kaderselliğiniz özgürlük, iyimserlik ve macera arzusuyla beslenir. Çocuğunuza geniş bir ufuk açan, hayatı birlikte öğrenen bir rehber olursunuz.",
    ("Anne Noktası", "Oğlak"): "Anne enerjisi kaderselliğiniz yapı, sorumluluk ve sabır üzerine inşa edilmiş. Çocuğunuza sınır koyan, disiplin veren ama sevgisini asla eksik etmeyen bir anne/anne olursunuz.",
    ("Anne Noktası", "Kova"): "Anne enerjisi kaderselliğiniz sıra dışı,özgür ve insancıl bir ruhla harmanlanmış. Çocuğunuzun bireyselliğine saygı duyan, onu kalıplara sokmayan bir rehber olursunuz.",
    ("Anne Noktası", "Balık"): "Anne enerjisi kaderselliğiniz sezgisel derinlik, şefkat ve koşulsuz sevgi üzerine kuruludur. Çocuğunuzla telepatik düzeyde bağ kuran, onun manevi światını besleyen bir anne/anne olursunuz.",

    ("Çocuk Ruhu", "Koç"): "Çocuğunuzun ruhsal amacı cesur, bağımsız ve öncü bir enerji taşır. Hayatta kendi yolunu açan, inisiyatif alan ve liderlik nitelikleri taşıyan bir ruhla dünyaya gelmiştir.",
    ("Çocuk Ruhu", "Boğa"): "Çocuğunuzun ruhsal amacı toprak, güzellik ve kalıcılık üzerine kuruludur. Sanatsal duyarlılık, duyusal zevkler ve somut değerler yaratma potansiyeli taşır.",
    ("Çocuk Ruhu", "İkizler"): "Çocuğunuzun ruhsal amacı iletişim, merak ve çok yönlülük üzerine inşa edilmiş. Bilgiyi işleyen, paylaşan ve xãi toplumla bağlantı kuran bir zihin taşır.",
    ("Çocuk Ruhu", "Yengeç"): "Çocuğunuzun ruhsal amacı duygusal derinlik, koruyuculuk ve aidiyet hissiyle yoğrulmuş. Ailesine ve sevdiklerine derin bir bağla bağlı, şefkat dolu bir ruh taşır.",
    ("Çocuk Ruhu", "Aslan"): "Çocuğunuzun ruhsal amacı yaratıcılık, cömertlik ve parlak bir öz-neşe üzerine kuruludur. Sanatsal yetenekleri, sahne enerjisi ve cömert kalbiyle parlayan bir ruhtur.",
    ("Çocuk Ruhu", "Başak"): "Çocuğunuzun ruhsal amacı titizlik, hizmet ve pratik mükemmellik üzerine inşa edilmiş. Detaycı zihni, yardımseverlik duygusu ve düzen kurma becerisiyle öne çıkan bir ruhtur.",
    ("Çocuk Ruhu", "Terazi"): "Çocuğunuzun ruhsal amacı denge, estetik ve uyum üzerine kuruludur. Adalet duygusu, sanatsal hassasiyet ve ilişkilerde denge kurma potansiyeli taşıyan bir ruhtur.",
    ("Çocuk Ruhu", "Akrep"): "Çocuğunuzun ruhsal amacı derin dönüşüm, yoğunluk ve gizem üzerine yoğrulmuş. İç dünyası derin, sezgileri güçlü ve hayatı her yönüyle deneyimleyen bir ruhtur.",
    ("Çocuk Ruhu", "Yay"): "Çocuğunuzun ruhsal amacı özgürlük, keşif ve felsefi genişleme üzerine kuruludur. Farklı kültürler, bilgelik arayışı ve macera tutkusu taşıyan geniş bir ruhtur.",
    ("Çocuk Ruhu", "Oğlak"): "Çocuğunuzun ruhsal amacı yapı, sorumluluk ve uzun vadeli hedefler üzerine inşa edilmiş. Erken olgunluk, disiplin ve hedeflerine ulaşmak için sabırla çalışan bir ruhtur.",
    ("Çocuk Ruhu", "Kova"): "Çocuğunuzun ruhsal amacı özgünlük, insancıllık ve vizyoner bakış üzerine kuruludur. Sıra dışı düşünen, topluma katkıda bulunan ve geleceği tasarlayan bir ruhtur.",
    ("Çocuk Ruhu", "Balık"): "Çocuğunuzun ruhsal amacı maneviyat, şefkat ve sezgisel derinlik üzerine yoğrulmuş. Sanatsal yetenekleri, merhamet duygusu ve ruhsal algılarıyla öne çıkan bir ruhtur.",

    ("Koruma Noktası", "Koç"): "Koruma enerjiniz cesur, doğrudan ve eyleme dönük bir şekilde yoğrulmuş. Çocuğunuzu korumak için gerektiğinde dünyanın karşısına dikilen, cesur bir kalkan olursunuz.",
    ("Koruma Noktası", "Boğa"): "Koruma enerjiniz toprak, somut ve kalıcı bir şekilde kuruludur. Çocuğunuzun maddi ve fiziksel güvenliğini sağlayan, sarsılmaz bir güvence kaynağı olursunuz.",
    ("Koruma Noktası", "İkizler"): "Koruma enerjiniz iletişim, bilgi ve zihinsel çeviklik üzerine inşa edilmiş. Çocuğunuzu zihinsel olarak besleyen, ona bilgiyi araç olarak aktaran bir koruyucu olursunuz.",
    ("Koruma Noktası", "Yengeç"): "Koruma enerjiniz derin duygusal bağ ve anne içgüdüsüyle yoğrulmuş. Çocuğunuz için sarsılmaz bir duygusal kalkan, sıcak bir sığınak olursunuz.",
    ("Koruma Noktası", "Aslan"): "Koruma enerjiniz görkemli, cömert ve onurlu bir şekilde kuruludur. Çocuğunuzun parlakığını koruyan, onun için gururla savaşan bir aslan/anne olursunuz.",
    ("Koruma Noktası", "Başak"): "Koruma enerjiniz titiz, pratik ve detaycı bir şekilde işler. Çocuğunuzun sağlık, beslenme ve günlük ihtiyaçlarını kusursuz karşılayan bir koruma sistemi kurarsınız.",
    ("Koruma Noktası", "Terazi"): "Koruma enerjiniz dengeli, zarif ve adaletli bir şekilde kuruludur. Çocuğunuz için adil bir koruma alanı yaratan, dengeli bir rehber olursunuz.",
    ("Koruma Noktası", "Akrep"): "Koruma enerjiniz derin, yoğun ve okült bir şekilde işler. Çocuğunuz için her türlü tehlikeye karşı sezgisel olarak tetikte olan, güçlü bir kalkan olursunuz.",
    ("Koruma Noktası", "Yay"): "Koruma enerjiniz genişleyici, iyimser ve felsefi bir şekilde kuruludur. Çocuğunuzu geniş bir perspektiften koruyan, ona yaşam görüşü aşılayan bir rehber olursunuz.",
    ("Koruma Noktası", "Oğlak"): "Koruma enerjiniz yapısal, disiplinli ve sorumluluk bilinciyle yoğrulmuş. Çocuğunuza yapı ve sınır koyarak koruyan, uzun vadeli bir güvenlik sistemi kuran bir rehber olursunuz.",
    ("Koruma Noktası", "Kova"): "Koruma enerjiniz sıra dışı,özgür ve toplumsal bir şekilde kuruludur. Çocuğunuzu kalıpların dışında koruyan, toplumsal bilinçle besleyen bir rehber olursunuz.",
    ("Koruma Noktası", "Balık"): "Koruma enerjiniz sezgisel, manevi ve koşulsuz bir şekilde işler. Çocuğunuzu sezgisel olarak hisseden, ruhsal düzeyde koruyan bir rehber olursunuz.",

    ("Eğitim Noktası", "Koç"): "Eğitim enerjiniz cesur, öncü ve eyleme dönük bir şekilde kuruludur. Çocuğunuza inisiyatif almayı, cesaret ve liderlik becerilerini öğretirken heyecanla beslenirsiniz.",
    ("Eğitim Noktası", "Boğa"): "Eğitim enerjiniz somut, pratik ve duyusal bir şekilde işler. Çocuğunuza sanat, doğa ve somut deneyimler aracılığıyla öğretmenin yollarını keşfedersiniz.",
    ("Eğitim Noktası", "İkizler"): "Eğitim enerjiniz iletişim, merak ve çok yönlülük üzerine inşa edilmiş. Çocuğunuzla bilgiyi paylaşmanın, her konuyu eğlenceli hale getirmenin yollarını bulursunuz.",
    ("Eğitim Noktası", "Yengeç"): "Eğitim enerjiniz duygusal beslenme ve koruma içgüdüsüyle yoğrulmuş. Çocuğunuza duygusal zekayı, empatiyi ve aile değerlerini aktarırken beslenirsiniz.",
    ("Eğitim Noktası", "Aslan"): "Eğitim enerjiniz yaratıcı, cömert ve sahne odaklı bir şekilde kuruludur. Çocuğunuzun sanatsal yeteneklerini geliştirmesine, kendini ifade etmesine alan açarsınız.",
    ("Eğitim Noktası", "Başak"): "Eğitim enerjiniz titiz, sistematik ve mükemmellik odaklı bir şekilde işler. Çocuğunuza düzen, detaycılık ve pratik becerileri öğretirken kusursuz bir sistem kurarsınız.",
    ("Eğitim Noktası", "Terazi"): "Eğitim enerjiniz dengeli, estetik ve uyumlu bir şekilde kuruludur. Çocuğunuza adalet, sanat ve ilişkilerde dengeyi öğretirken zarif bir yol çizersiniz.",
    ("Eğitim Noktası", "Akrep"): "Eğitim enerjiniz derin, yoğun ve dönüştürücü bir şekilde işler. Çocuğunuza iç dünyanın derinliklerini keşfetmeyi, dönüşümü ve gücü doğru kullanmayı öğretirsiniz.",
    ("Eğitim Noktası", "Yay"): "Eğitim enerjiniz genişleyici, felsefi ve macera dolu bir şekilde kuruludur. Çocuğunuza farklı kültürleri, felsefeyi ve geniş bir yaşam perspektifini aşılar",
    ("Eğitim Noktası", "Oğlak"): "Eğitim enerjiniz yapısal, sorumluluk odaklı ve sabırlı bir şekilde işler. Çocuğunuza hedef koymayı, sabrı ve uzun vadeli planlama becerilerini aktarırken beslenirsiniz.",
    ("Eğitim Noktası", "Kova"): "Eğitim enerjiniz sıra dışı, yenilikçi ve toplumsal bir şekilde kuruludur. Çocuğunuza geleceğin becerilerini, teknolojiyi ve toplumsal duyarlılığı aktarırsınız.",
    ("Eğitim Noktası", "Balık"): "Eğitim enerjiniz sezgisel, sanatsal ve manevi bir şekilde işler. Çocuğunuza hayal gücünü, sanatsal duyarlılığı ve ruhsal bilgelik aktarırken beslenirsiniz.",

    ("Sınır Noktası", "Koç"): "Sınır koyma enerjiniz cesur, net ve doğrudan bir şekilde kuruludur. Çocuğunuza açık ve keskin sınırlar çizen, gerektiğinde kararlı duran bir rehber olursunuz.",
    ("Sınır Noktası", "Boğa"): "Sınır koyma enerjiniz toprak, sabırlı ve kalıcı bir şekilde işler. Çocuğunuza sabırla sınır koyan, istikrarlı ve güvenilir bir yapı sunan bir rehber olursunuz.",
    ("Sınır Noktası", "İkizler"): "Sınır koyma enerjiniz iletişim, esneklik ve zihinsel çeviklik üzerine inşa edilmiş. Çocuğunuzla konuşarak sınır koyan, açıklamalı ve bilgilendirici bir rehber olursunuz.",
    ("Sınır Noktası", "Yengeç"): "Sınır koyma enerjiniz duygusal derinlik ve koruma içgüdüsüyle yoğrulmuş. Çocuğunuzu korumak adına koyduğunuz sınırlar, sevgi ve şefkatle beslenir.",
    ("Sınır Noktası", "Aslan"): "Sınır koyma enerjiniz görkemli, onurlu ve otoriter bir şekilde kuruludur. Çocuğunuza net ve saygın sınırlar çizen, otoritesini sevgiyle harmanlayan bir rehber olursunuz.",
    ("Sınır Noktası", "Başak"): "Sınır koyma enerjiniz titiz, sistematik ve düzenli bir şekilde işler. Çocuğunuza kurallar, rutinler ve detaylı bir yaşam yapısı sunan bir rehber olursunuz.",
    ("Sınır Noktası", "Terazi"): "Sınır koyma enerjiniz dengeli, adil ve zarif bir şekilde kuruludur. Çocuğunuzla adil sınırlar koyan, müzakereye açık bir rehber olursunuz.",
    ("Sınır Noktası", "Akrep"): "Sınır koyma enerjiniz derin, keskin ve dönüştürücü bir şekilde işler. Çocuğunuza keskin sınırlar çizen, ama bu sınırların arkasındaki derin sevgiyi de aktaran bir rehber olursunuz.",
    ("Sınır Noktası", "Yay"): "Sınır koyma enerjiniz genişleyici, esnek ve felsefi bir şekilde kuruludur. Çocuğunuza esnek sınırlar çizen, özgürlük ile sorumluluk dengesini öğreten bir rehber olursunuz.",
    ("Sınır Noktası", "Oğlak"): "Sınır koyma enerjiniz yapısal, disiplinli ve katı bir şekilde işler. Çocuğunuza katı ama adil sınırlar çizen, yapı ve düzen veren bir rehber olursunuz.",
    ("Sınır Noktası", "Kova"): "Sınır koyma enerjiniz sıra dışı, esnek ve toplumsal bir şekilde kuruludur. Çocuğunuza geleneksel olmayan, ama işlevsel sınırlar çizen bir rehber olursunuz.",
    ("Sınır Noktası", "Balık"): "Sınır koyma enerjiniz sezgisel, esnek ve duygusal bir şekilde işler. Çocuğunuza duygusal sınırları öğretirken, sezgisel bir rehberlik sunarsınız.",

    ("Bağlanma Noktası", "Koç"): "Bağlanma biçiminiz cesur, bağımsız ve eyleme dönük bir şekilde kuruludur. Çocuğunuzla kavgacı ama sevgi dolu bir bağ kurar, onu cesaretle beslersiniz.",
    ("Bağlanma Noktası", "Boğa"): "Bağlanma biçiminiz toprak, duyusal ve kalıcı bir şekilde işler. Çocuğunuzla fiziksel temas, dokunma ve somut sevgi dilleriyle derin bir bağ kurarsınız.",
    ("Bağlanma Noktası", "İkizler"): "Bağlanma biçiminiz iletişim, neşe ve zihinsel uyum üzerine inşa edilmiş. Çocuğunuzla konuşarak, oynayarak ve bilgi paylaşarak keyifli bir bağ kurarsınız.",
    ("Bağlanma Noktası", "Yengeç"): "Bağlanma biçiminiz derin duygusal beslenme ve koruma içgüdüsüyle yoğrulmuş. Çocuğunuzla anne kucağı kadar sıcak, sarsılmaz bir duygusal bağ kurarsınız.",
    ("Bağlanma Noktası", "Aslan"): "Bağlanma biçiminiz görkemli, cömert ve sevgi dolu bir şekilde kuruludur. Çocuğunuzu sahneye koyan, onunla gurur duyan ve sevgisini cömertçe gösteren bir bağ kurarsınız.",
    ("Bağlanma Noktası", "Başak"): "Bağlanma biçiminiz pratik, hizmet odaklı ve düzenli bir şekilde işler. Çocuğunuzun ihtiyaçlarını kusursuz karşılayarak, hizmet yoluyla derin bir bağ kurarsınız.",
    ("Bağlanma Noktası", "Terazi"): "Bağlanma biçiminiz dengeli, zarif ve uyumlu bir şekilde kuruludur. Çocuğunuzla denge, adalet ve estetik duyarlılık üzerinden derin bir bağ kurarsınız.",
    ("Bağlanma Noktası", "Akrep"): "Bağlanma biçiminiz derin, yoğun ve dönüştürücü bir şekilde işler. Çocuğunuzla çok derin, neredeyse ruhsal bir bağ kurarsınız. Yoğunluk bu bağın temelidir.",
    ("Bağlanma Noktası", "Yay"): "Bağlanma biçiminiz genişleyici, neşeli ve macera dolu bir şekilde kuruludur. Çocuğunuzla birlikte hayatı keşfederken, özgürlük ve neşeyle bağ kurarsınız.",
    ("Bağlanma Noktası", "Oğlak"): "Bağlanma biçiminiz yapısal, sorumluluk bilinciyle ve sabırla işler. Çocuğunuza yapı, düzen ve güven vererek, uzun vadeli bir bağ inşa edersiniz.",
    ("Bağlanma Noktası", "Kova"): "Bağlanma biçiminiz sıra dışı,özgür ve dostane bir şekilde kuruludur. Çocuğunuzla arkadaşça, eşitlikçi ve yenilikçi bir bağ kurarsınız.",
    ("Bağlanma Noktası", "Balık"): "Bağlanma biçiminiz sezgisel, koşulsuz ve manevi bir şekilde işler. Çocuğunuzla telepatik düzeyde, koşulsuz sevgiyle beslenen derin bir bağ kurarsınız.",

    ("Sorumluluk", "Koç"): "Ebeveynlik sorumluluğunuz cesur, inisiyatif alan ve eyleme dönük bir şekilde kuruludur. Çocuğunuz için dünyaya meydan okuyan, sorumluluğu cesaretle taşıyan bir rehber olursunuz.",
    ("Sorumluluk", "Boğa"): "Ebeveynlik sorumluluğunuz toprak, güvenilir ve kalıcı bir şekilde işler. Çocuğunuza maddi ve manevi güvence sağlayan, uzun vadeli bir sorumluluk bilinciyle hareket edersiniz.",
    ("Sorumluluk", "İkizler"): "Ebeveynlik sorumluluğunuz iletişim, esneklik ve zihinsel çeviklik üzerine inşa edilmiş. Çocuğunuzla iletişim kurarak, bilgiyi paylaşarak sorumluluğunuzu yerine getirirsiniz.",
    ("Sorumluluk", "Yengeç"): "Ebeveynlik sorumluluğunuz derin duygusal beslenme ve koruma içgüdüsüyle yoğrulmuş. Çocuğunuz için her şeyini feda eden, sorumluluğu sevgiyle taşıyan bir rehber olursunuz.",
    ("Sorumluluk", "Aslan"): "Ebeveynlik sorumluluğunuz görkemli, cömert ve onurlu bir şekilde kuruludur. Çocuğunuzun yeteneklerini geliştirmesine olanak sağlayan, sorumluluğu gururla taşıyan bir rehber olursunuz.",
    ("Sorumluluk", "Başak"): "Ebeveynlik sorumluluğunuz titiz, pratik ve mükemmellik odaklı bir şekilde işler. Çocuğunuzun her ihtiyacını detaylıca karşılayan, sorumluluğu kusursuz yerine getiren bir rehber olursunuz.",
    ("Sorumluluk", "Terazi"): "Ebeveynlik sorumluluğunuz dengeli, adil ve zarif bir şekilde kuruludur. Çocuğunuzla adil bir ilişki kuran, sorumluluğu dengeli bir şekilde paylaşan bir rehber olursunuz.",
    ("Sorumluluk", "Akrep"): "Ebeveynlik sorumluluğunuz derin, yoğun ve dönüştürücü bir şekilde işler. Çocuğunuz için her türlü fedakarlığı yapan, sorumluluğu derin bir kararlılıkla taşıyan bir rehber olursunuz.",
    ("Sorumluluk", "Yay"): "Ebeveynlik sorumluluğunuz genişleyici, felsefi ve macera dolu bir şekilde kuruludur. Çocuğunuza geniş bir yaşam perspektifi aşılayan, sorumluluğu neşeyle taşıyan bir rehber olursunuz.",
    ("Sorumluluk", "Oğlak"): "Ebeveynlik sorumluluğunuz yapısal, disiplinli ve katı bir şekilde işler. Çocuğunuza yapı, düzen ve ciddiyetle yaklaşan, sorumluluğu titizlikle taşıyan bir rehber olursunuz.",
    ("Sorumluluk", "Kova"): "Ebeveynlik sorumluluğunuz sıra dışı, yenilikçi ve toplumsal bir şekilde kuruludur. Çocuğunuza toplumsal bilinç aşılayan, sorumluluğu geleceğe yönelik taşıyan bir rehber olursunuz.",
    ("Sorumluluk", "Balık"): "Ebeveynlik sorumluluğunuz sezgisel, manevi ve koşulsuz bir şekilde işler. Çocuğunuzun ruhsal gelişimine odaklanan, sorumluluğu sevgiyle ve sezgiyle taşıyan bir rehber olursunuz.",
}

ARAP_NOKTA_EV_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", 1): "Baba enerjisi kimliğinizle doğrudan bağlantılı. Ebeveynlik rolünüz hayatınızın merkezinde.",
    ("Baba Noktası", 2): "Baba enerjisi maddi güvence ve değerlerle beslenir. Çocuğunuza somut bir temel inşa edersiniz.",
    ("Baba Noktası", 3): "Baba enerjisi iletişim ve çevreyle bağlantılı. Çocuğunuzla bilgi ve deneyim paylaşımı ön plandadır.",
    ("Baba Noktası", 4): "Baba enerjisi aile kökleri ve ev hayatıyla derin bir bağa sahip. Yuva inşası bu enerjinin temelidir.",
    ("Baba Noktası", 5): "Baba enerjisi yaratıcılık ve çocuk dünyasıyla yoğrulmuş. Oyun ve neşe bu enerjinin besin kaynağıdır.",
    ("Baba Noktası", 6): "Baba enerjisi günlük bakım ve sağlıkla bağlantılı. Pratik destek ve düzen bu enerjinin temelidir.",
    ("Baba Noktası", 7): "Baba enerjisi denge ve aynalanma alanında güçlüdür. Ebeveynlik rollerinizde denge arayışı ön plandadır.",
    ("Baba Noktası", 8): "Baba enerjisi dönüşüm ve krizlerle derinleşir. Zor zamanlarda güçlü bir koruyucu olursunuz.",
    ("Baba Noktası", 9): "Baba enerjisi felsefe ve eğitimle beslenir. Çocuğunuza değerler ve bilgelik aktarırsınız.",
    ("Baba Noktası", 10): "Baba enerjisi kariyer ve toplumsal rolde taçlanır. Toplum nezdinde güçlü bir baba/anne figürü olursunuz.",
    ("Baba Noktası", 11): "Baba enerjisi arkadaşlık ve gruplarla bağlantılı. Çocuğunuzun sosyal dünyasında aktif rol alırsınız.",
    ("Baba Noktası", 12): "Baba enerjisi bilinçaltı ve maneviyatla derinleşir. sezgisel bir baba/anne bilgeliği taşırsınız.",

    ("Anne Noktası", 1): "Anne enerjisi kimliğinizle doğrudan bağlantılı. Ebeveynlik rolünüz kişiliğinizin temelini oluşturur.",
    ("Anne Noktası", 2): "Anne enerjisi maddi güvence ve beslenmeyle beslenir. Çocuğunuza fiziksel ve duygusal şifa sunarsınız.",
    ("Anne Noktası", 3): "Anne enerjisi iletişim ve çevreyle bağlantılı. Çocuğunuzla sürekli iletişim halinde olan bir rehber olursunuz.",
    ("Anne Noktası", 4): "Anne enerjisi aile kökleri ve yuva hayatıyla derin bir bağa sahip. Yuva inşası bu enerjinin kalbidir.",
    ("Anne Noktası", 5): "Anne enerjisi yaratıcılık ve oyun zamanlarıyla yoğrulmuş. Çocuğunuzla birlikte yaratıcı anlar paylaşırsınız.",
    ("Anne Noktası", 6): "Anne enerjisi günlük bakım ve sağlıkla bağlantılı. Çocuğunuzun rutin ihtiyaçlarını kusursuz karşılarsınız.",
    ("Anne Noktası", 7): "Anne enerjisi denge ve karşılıklılıkta güçlüdür. Çocuğunuzla dengeli bir ilişki kurarsınız.",
    ("Anne Noktası", 8): "Anne enerjisi dönüşüm ve derinleşmeyle yoğrulmuş. Kriz anlarında güçlü bir şifacı olursunuz.",
    ("Anne Noktası", 9): "Anne enerjisi felsefe ve eğitimle beslenir. Çocuğunuza geniş bir yaşam perspektifi aşılar",
    ("Anne Noktası", 10): "Anne enerjisi toplumsal rolde taçlanır. Toplum nezdinde saygın bir anne/anne figürü olursunuz.",
    ("Anne Noktası", 11): "Anne enerjisi umutlar ve gruplarla bağlantılı. Çocuğunuzun hayallerini destekleyen bir rehber olursunuz.",
    ("Anne Noktası", 12): "Anne enerjisi sezgisel derinlik ve maneviyatla beslenir. Telepatik düzeyde bir anne/anne bağı kurarsınız.",

    ("Çocuk Ruhu", 1): "Çocuğunuzun ruhsal amacı kimliğiyle doğrudan bağlantılı. Kendi benliğini keşfetme yolculuğu ön plandadır.",
    ("Çocuk Ruhu", 2): "Çocuğunuzun ruhsal amacı maddi değerler ve somut deneyimlerle beslenir. Sanatsal ve duyusal potansiyeli yüksektir.",
    ("Çocuk Ruhu", 3): "Çocuğunuzun ruhsal amacı iletişim ve çevreyle bağlantılı. Bilgiyi paylaşma ve çevreyle bağlantı kurma yeteneği öne çıkar.",
    ("Çocuk Ruhu", 4): "Çocuğunuzun ruhsal amacı aile kökleri ve yuva hayatıyla derin bir bağa sahip. Aile bağları onun için kutsaldır.",
    ("Çocuk Ruhu", 5): "Çocuğunuzun ruhsal amacı yaratıcılık ve kendini ifade etmeyle yoğrulmuş. Sanatsal yetenekleri ve oyun enerjisi yüksektir.",
    ("Çocuk Ruhu", 6): "Çocuğunuzun ruhsal amacı günlük düzen ve hizmetle bağlantılı. Pratik becerileri ve yardımseverlik duygusu öne çıkar.",
    ("Çocuk Ruhu", 7): "Çocuğunuzun ruhsal amacı ilişkiler ve dengeyle derinleşir. İlişkilerde denge kurma ve uyum sağlama potansiyeli yüksektir.",
    ("Çocuk Ruhu", 8): "Çocuğunuzun ruhsal amacı dönüşüm ve derinleşmeyle yoğrulmuş. İç dünyada güçlü bir dönüşüm potansiyeli taşır.",
    ("Çocuk Ruhu", 9): "Çocuğunuzun ruhsal amacı felsefe ve genişlemeyle beslenir. Farklı kültürler ve bilgelik arayışı onu besler.",
    ("Çocuk Ruhu", 10): "Çocuğunuzun ruhsal amacı kariyer ve toplumsal rolde taçlanır. Hedeflerine ulaşmak için disiplinli çalışır.",
    ("Çocuk Ruhu", 11): "Çocuğunuzun ruhsal amacı arkadaşlık ve topluluklarla bağlantılı. Sosyal çevresi geniş ve destekleyicidir.",
    ("Çocuk Ruhu", 12): "Çocuğunuzun ruhsal amacı sezgisel derinlik ve maneviyatla beslenir. Yüksek sezgi güçleri ve hayal gücü taşır.",

    ("Koruma Noktası", 1): "Koruma enerjiniz kimliğinizle doğrudan bağlantılı. Kendinizi ve çocuğunuzu koruma içgüdünüz çok güçlüdür.",
    ("Koruma Noktası", 2): "Koruma enerjiniz maddi güvence ve değerlerle beslenir. Çocuğunuzun maddi ihtiyaçlarını karşılama konusunda kararlısınız.",
    ("Koruma Noktası", 3): "Koruma enerjiniz iletişim ve çevreyle bağlantılı. Çocuğunuzu çevredekilere karşı bilgilendirici bir şekilde korursunuz.",
    ("Koruma Noktası", 4): "Koruma enerjiniz aile kökleri ve yuva hayatıyla derin bir bağa sahip. Yuva, sizin için korumanın merkezidir.",
    ("Koruma Noktası", 5): "Koruma enerjiniz yaratıcılık ve oyun zamanlarıyla yoğrulmuş. Çocuğunuzun yaratıcı güvenliğini sağlarsınız.",
    ("Koruma Noktası", 6): "Koruma enerjiniz günlük bakım ve sağlıkla bağlantılı. Çocuğunuzun fiziksel sağlığını koruma konusunda titizsiniz.",
    ("Koruma Noktası", 7): "Koruma enerjiniz denge ve ilişkilerde güçlüdür. Çocuğunuzu dengeli ve adil bir şekilde korursunuz.",
    ("Koruma Noktası", 8): "Koruma enerjiniz dönüşüm ve krizlerle derinleşir. Zor zamanlarda güçlü bir koruyucu kalkan olursunuz.",
    ("Koruma Noktası", 9): "Koruma enerjiniz felsefe ve değerlerle beslenir. Çocuğunuzu değerleriniz ve inançlarınızla korursunuz.",
    ("Koruma Noktası", 10): "Koruma enerjiniz kariyer ve toplumsal rollerde taçlanır. Toplumsal statünüzü koruma enerjisi olarak kullanırsınız.",
    ("Koruma Noktası", 11): "Koruma enerjiniz arkadaşlık ve gruplarla bağlantılı. Çocuğunuzun sosyal çevresini koruma altına alırsınız.",
    ("Koruma Noktası", 12): "Koruma enerjiniz sezgisel derinlik ve maneviyatla beslenir. Çocuğunuzu sezgisel olarak tehlikelere karşı korursunuz.",

    ("Eğitim Noktası", 1): "Eğitim enerjiniz kimliğinizle doğrudan bağlantılı. Öğretme rolünüz kişiliğinizin temelini oluşturur.",
    ("Eğitim Noktası", 2): "Eğitim enerjiniz maddi kaynaklar ve somut deneyimlerle beslenir. Pratik becerileri öğretme konusunda uzmansınız.",
    ("Eğitim Noktası", 3): "Eğitim enerjiniz iletişim ve çevreyle bağlantılı. Çocuğunuzla sürekli bilgi paylaşımı yaparsınız.",
    ("Eğitim Noktası", 4): "Eğitim enerjiniz aile kökleri ve ev hayatıyla derin bir bağa sahip. Aile içi eğitim bu enerjinin temelidir.",
    ("Eğitim Noktası", 5): "Eğitim enerjiniz yaratıcılık ve oyun zamanlarıyla yoğrulmuş. Oyun yoluyla öğretme beceriniz çok güçlüdür.",
    ("Eğitim Noktası", 6): "Eğitim enerjiniz günlük rutin ve pratik düzen ile bağlantılı. Günlük hayatta sürekli öğretme fırsatları yaratırsınız.",
    ("Eğitim Noktası", 7): "Eğitim enerjiniz denge ve karşılıklılıkta güçlüdür. Karşılıklı öğrenme ve öğretme dengeyi bulur.",
    ("Eğitim Noktası", 8): "Eğitim enerjiniz dönüşüm ve derinleşmeyle yoğrulmuş. Zor deneyimlerden öğrenmeyi öğretirsiniz.",
    ("Eğitim Noktası", 9): "Eğitim enerjiniz felsefe ve genişlemeyle beslenir. Farklı kültürler ve felsefi perspektifler aktarırsınız.",
    ("Eğitim Noktası", 10): "Eğitim enerjiniz kariyer ve toplumsal rollerde taçlanır. Eğitimsel hedefler ve uzun vadeli planlar ön plandadır.",
    ("Eğitim Noktası", 11): "Eğitim enerjiniz arkadaşlık ve topluluklarla bağlantılı. Sosyal çevrede öğretme ve öğrenme paylaşımı yaparsınız.",
    ("Eğitim Noktası", 12): "Eğitim enerjiniz sezgisel derinlik ve maneviyatla beslenir. Manevi ve sezgisel bilgileri aktarırsınız.",

    ("Sınır Noktası", 1): "Sınır koyma enerjiniz kimliğinizle doğrudan bağlantılı. Sınırlar, kişiliğinizin temel bir parçasıdır.",
    ("Sınır Noktası", 2): "Sınır koyma enerjiniz maddi değerler ve kaynaklarla beslenir. Maddi konularda net sınırlar koyarsınız.",
    ("Sınır Noktası", 3): "Sınır koyma enerjiniz iletişim ve çevreyle bağlantılı. İletişim sınırlarını belirleme beceriniz güçlüdür.",
    ("Sınır Noktası", 4): "Sınır koyma enerjiniz aile kökleri ve yuva hayatıyla derin bir bağa sahip. Ev içi sınırlar bu enerjinin temelidir.",
    ("Sınır Noktası", 5): "Sınır koyma enerjiniz yaratıcılık ve oyun zamanlarıyla yoğrulmuş. Oyun sınırlarını belirleme beceriniz güçlüdür.",
    ("Sınır Noktası", 6): "Sınır koyma enerjiniz günlük rutin ve sağlıkla bağlantılı. Günlük düzen ve sınır koyma konusunda uzmansınız.",
    ("Sınır Noktası", 7): "Sınır koyma enerjiniz denge ve ilişkilerde güçlüdür. İlişkilerde adil sınırlar koyma beceriniz güçlüdür.",
    ("Sınır Noktası", 8): "Sınır koyma enerjiniz dönüşüm ve krizlerle derinleşir. Kriz anlarında güçlü sınırlar koyarsınız.",
    ("Sınır Noktası", 9): "Sınır koyma enerjiniz felsefe ve değerlerle beslenir. Değerler temelinde sınırlar koyarsınız.",
    ("Sınır Noktası", 10): "Sınır koyma enerjiniz kariyer ve toplumsal rollerde taçlanır. Toplumsal sınırları belirleme beceriniz güçlüdür.",
    ("Sınır Noktası", 11): "Sınır koyma enerjiniz arkadaşlık ve gruplarla bağlantılı. Sosyal çevre sınırlarını belirleme beceriniz güçlüdür.",
    ("Sınır Noktası", 12): "Sınır koyma enerjiniz sezgisel derinlik ve maneviyatla beslenir. Sezgisel sınırları belirleme beceriniz güçlüdür.",

    ("Bağlanma Noktası", 1): "Bağlanma biçiminiz kimliğinizle doğrudan bağlantılı. Bağlanma stiliniz kişiliğinizin temel bir parçasıdır.",
    ("Bağlanma Noktası", 2): "Bağlanma biçiminiz maddi değerler ve duyusal deneyimlerle beslenir. Fiziksel temas ve somut sevgi dili ön plandadır.",
    ("Bağlanma Noktası", 3): "Bağlanma biçiminiz iletişim ve çevreyle bağlantılı. Konuşarak ve bilgi paylaşarak bağ kurarsınız.",
    ("Bağlanma Noktası", 4): "Bağlanma biçiminiz aile kökleri ve yuva hayatıyla derin bir bağa sahip. Yuva, bağlanmanızın merkezidir.",
    ("Bağlanma Noktası", 5): "Bağlanma biçiminiz yaratıcılık ve oyun zamanlarıyla yoğrulmuş. Oyun ve neşe yoluyla bağ kurarsınız.",
    ("Bağlanma Noktası", 6): "Bağlanma biçiminiz günlük rutin ve hizmetle bağlantılı. Hizmet ve bakım yoluyla bağ kurarsınız.",
    ("Bağlanma Noktası", 7): "Bağlanma biçiminiz denge ve karşılıklılıkta güçlüdür. Karşılıklı bağlanma ve denge ön plandadır.",
    ("Bağlanma Noktası", 8): "Bağlanma biçiminiz dönüşüm ve derinleşmeyle yoğrulmuş. Derin ve yoğun bağlanma stiliniz vardır.",
    ("Bağlanma Noktası", 9): "Bağlanma biçiminiz felsefe ve genişlemeyle beslenir. Felsefi değerler ve ortak inançlar yoluyla bağ kurarsınız.",
    ("Bağlanma Noktası", 10): "Bağlanma biçiminiz kariyer ve toplumsal rollerde taçlanır. Toplumsal sorumluluklar yoluyla bağ kurarsınız.",
    ("Bağlanma Noktası", 11): "Bağlanma biçiminiz arkadaşlık ve topluluklarla bağlantılı. Arkadaşlık ve gruplar yoluyla bağ kurarsınız.",
    ("Bağlanma Noktası", 12): "Bağlanma biçiminiz sezgisel derinlik ve maneviyatla beslenir. Sezgisel ve ruhsal bağlar kurarsınız.",

    ("Sorumluluk", 1): "Ebeveynlik sorumluluğunuz kimliğinizle doğrudan bağlantılı. Ebeveynlik, benliğinizin temel bir parçasıdır.",
    ("Sorumluluk", 2): "Ebeveynlik sorumluluğunuz maddi kaynaklar ve değerlerle beslenir. Maddi sorumluluk bilinciniz güçlüdür.",
    ("Sorumluluk", 3): "Ebeveynlik sorumluluğunuz iletişim ve çevreyle bağlantılı. Çocuğunuzla iletişim kurarak sorumluluğunuzu yerine getirirsiniz.",
    ("Sorumluluk", 4): "Ebeveynlik sorumluluğunuz aile kökleri ve yuva hayatıyla derin bir bağa sahip. Yuva sorumluluğunuz en temel değerinizdir.",
    ("Sorumluluk", 5): "Ebeveynlik sorumluluğunuz yaratıcılık ve oyun zamanlarıyla yoğrulmuş. Sorumluluğu neşe ve yaratıcılıkla harmanlarsınız.",
    ("Sorumluluk", 6): "Ebeveynlik sorumluluğunuz günlük rutin ve sağlıkla bağlantılı. Günlük bakım ve düzen sorumluluğunuz güçlüdür.",
    ("Sorumluluk", 7): "Ebeveynlik sorumluluğunuz denge ve ilişkilerde güçlüdür. İlişkilerde denge ve karşılıklılık ön plandadır.",
    ("Sorumluluk", 8): "Ebeveynlik sorumluluğunuz dönüşüm ve krizlerle derinleşir. Kriz anlarında güçlü bir sorumluluk bilinci sergilersiniz.",
    ("Sorumluluk", 9): "Ebeveynlik sorumluluğunuz felsefe ve değerlerle beslenir. Değerler temelinde sorumluluk bilinci taşırsınız.",
    ("Sorumluluk", 10): "Ebeveynlik sorumluluğunuz kariyer ve toplumsal rollerde taçlanır. Toplumsal sorumluluk bilinciniz çok güçlüdür.",
    ("Sorumluluk", 11): "Ebeveynlik sorumluluğunuz arkadaşlık ve topluluklarla bağlantılı. Sosyal sorumluluk bilinci taşrsınız.",
    ("Sorumluluk", 12): "Ebeveynlik sorumluluğunuz sezgisel derinlik ve maneviyatla beslenir. Manevi sorumluluk bilinci taşırsınız.",
}

ARAP_NOKTA_SINASTRI_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", "Baba Noktası"): "Her iki ebeveyn de güçlü baba/otorite enerjisi taşıyor. Çocuğunuz için iki güçlü rehber aynı frekansında titreşiyor.",
    ("Baba Noktası", "Anne Noktası"): "Baba ve anne noktalarının dengeli buluşması! Otorite ve şefkat, çocuğunuz için mükemmel bir denge yaratıyor.",
    ("Baba Noktası", "Çocuk Ruhu"): "Baba enerjisi çocuğunuzun ruhsalpurpose'ıyla derin bir uyum içinde. Ebeveynlik vizyonunuz onun ruhsal gelişimini besliyor.",
    ("Baba Noktası", "Koruma Noktası"): "Baba ve koruma noktalarının güçlü ittifakı! Çocuğunuz için güçlü bir koruma kalkanı oluşuyor.",
    ("Baba Noktası", "Eğitim Noktası"): "Baba ve eğitim noktalarının bilgelik ittifakı! Çocuğunuza yapı ve bilgiyi birlikte aktarıyorsunuz.",
    ("Baba Noktası", "Sınır Noktası"): "Baba ve sınır noktalarının disiplin birleşmesi! Çocuğunuza net ve adil sınırlar çizen güçlü bir ekip oluyorsunuz.",
    ("Baba Noktası", "Bağlanma Noktası"): "Baba ve bağlanma noktalarının şefkat dansı! Otorite ve sevgi, çocuğunuz için güvenli bir alan yaratıyor.",
    ("Baba Noktası", "Sorumluluk"): "Baba ve sorumluluk noktalarının güçlü kavuşumu! Ebeveynlik sorumluluğunuz zirve noktasında.",

    ("Anne Noktası", "Anne Noktası"): "Her iki ebeveyn de güçlü anne/besleme enerjisi taşıyor. Çocuğunuz için iki şefkatli liman aynı frekansında titreşiyor.",
    ("Anne Noktası", "Çocuk Ruhu"): "Anne enerjisi çocuğunuzun ruhsalpurpose'ıyla derin bir uyum içinde. Duygusal beslenmeniz onun ruhsal gelişimini destekliyor.",
    ("Anne Noktası", "Koruma Noktası"): "Anne ve koruma noktalarının şefkatli kalkanı! Çocuğunuz için hem duygusal hem fiziksel koruma sağlanıyor.",
    ("Anne Noktası", "Eğitim Noktası"): "Anne ve eğitim noktalarının bilgelik birleşmesi! Duygusal beslenme ve eğitim, çocuğunuz için mükemmel bir uyum yaratıyor.",
    ("Anne Noktası", "Sınır Noktası"): "Anne ve sınır noktalarının dengeli buluşması! Şefkat ve disiplin, çocuğunuz için dengeli bir yapı oluşturuyor.",
    ("Anne Noktası", "Bağlanma Noktası"): "Anne ve bağlanma noktalarının güçlü kavuşumu! Duygusal bağlanma ve beslenme, çocuğunuz için derin bir sığınak yaratıyor.",
    ("Anne Noktası", "Sorumluluk"): "Anne ve sorumluluk noktalarının kutsal birleşmesi! Besleme ve sorumluluk, ebeveynlik yolculuğunuzun temelini oluşturuyor.",

    ("Çocuk Ruhu", "Çocuk Ruhu"): "Her iki ebeveyn de çocuğunuzun ruhsalpurpose'ını güçlü bir şekilde taşıyor. Çocuğunuz için iki ruhsal rehber aynı frekansında titreşiyor.",
    ("Çocuk Ruhu", "Koruma Noktası"): "Çocuk ruhu ve koruma noktalarının güçlü birleşmesi! Çocuğunuzun ruhsal gelişimi güçlü bir koruma altında.",
    ("Çocuk Ruhu", "Eğitim Noktası"): "Çocuk ruhu ve eğitim noktalarının bilgelik ittifakı! Çocuğunuzun ruhsal amacı eğitim yoluyla besleniyor.",
    ("Çocuk Ruhu", "Sınır Noktası"): "Çocuk ruhu ve sınır noktalarının dengeli buluşması! Çocuğunuzun ruhsal gelişimi yapı ve sınır içinde besleniyor.",
    ("Çocuk Ruhu", "Bağlanma Noktası"): "Çocuk ruhu ve bağlanma noktalarının derin bağı! Çocuğunuzun ruhsal amacı sevgi ve bağlanma yoluyla besleniyor.",
    ("Çocuk Ruhu", "Sorumluluk"): "Çocuk ruhu ve sorumluluk noktalarının güçlü kavuşumu! Çocuğunuzun ruhsal amacı sorumluluk bilinciyle besleniyor.",

    ("Koruma Noktası", "Koruma Noktası"): "Her iki ebeveyn de güçlü koruma enerjisi taşıyor. Çocuğunuz için çift koruma kalkanı aktif.",
    ("Koruma Noktası", "Eğitim Noktası"): "Koruma ve eğitim noktalarının dengeli ittifakı! Çocuğunuzun güvenliği ve eğitimi mükemmel uyum içinde.",
    ("Koruma Noktası", "Sınır Noktası"): "Koruma ve sınır noktalarının güçlü birleşmesi! Çocuğunuz için güçlü ve net bir koruma yapısı oluşuyor.",
    ("Koruma Noktası", "Bağlanma Noktası"): "Koruma ve bağlanma noktalarının şefkatli kalkanı! Çocuğunuz için güvenli ve sevgi dolu bir alan yaratılıyor.",
    ("Koruma Noktası", "Sorumluluk"): "Koruma ve sorumluluk noktalarının güçlü kavuşumu! Koruma içgüdüsü ve sorumluluk bilinci zirve noktasında.",

    ("Eğitim Noktası", "Eğitim Noktası"): "Her iki ebeveyn de güçlü eğitim enerjisi taşıyor. Çocuğunuz için iki bilgelik kaynağı aynı frekansında titreşiyor.",
    ("Eğitim Noktası", "Sınır Noktası"): "Eğitim ve sınır noktalarının dengeli buluşması! Öğrenme ve disiplin, çocuğunuz için mükemmel bir uyum yaratıyor.",
    ("Eğitim Noktası", "Bağlanma Noktası"): "Eğitim ve bağlanma noktalarının şefkatli birleşmesi! Bilgi aktarımı sevgiyle besleniyor.",
    ("Eğitim Noktası", "Sorumluluk"): "Eğitim ve sorumluluk noktalarının güçlü kavuşumu! Öğretme ve sorumluluk, ebeveynlik vizyonunuzun temeli.",

    ("Sınır Noktası", "Sınır Noktası"): "Her iki ebeveyn de güçlü sınır koyma enerjisi taşıyor. Çocuğunuz için net ve tutarlı sınırlar oluşturuluyor.",
    ("Sınır Noktası", "Bağlanma Noktası"): "Sınır ve bağlanma noktalarının dengeli dansı! Sınırlar sevgiyle, bağlanma yapıyla besleniyor.",
    ("Sınır Noktası", "Sorumluluk"): "Sınır ve sorumluluk noktalarının güçlü kavuşumu! Disiplin ve sorumluluk, çocuğunuz için sağlam bir temel oluşturuyor.",

    ("Bağlanma Noktası", "Bağlanma Noktası"): "Her iki ebeveyn de güçlü bağlanma enerjisi taşıyor. Çocuğunuz için iki şefkatli kalp aynı frekansında titreşiyor.",
    ("Bağlanma Noktası", "Sorumluluk"): "Bağlanma ve sorumluluk noktalarının kutsal birleşmesi! Sevgi ve sorumluluk, ebeveynlik yolculuğunuzun temeli.",

    ("Sorumluluk", "Sorumluluk"): "Her iki ebeveyn de güçlü sorumluluk enerjisi taşıyor. Çocuğunuz için iki sorumluluk bilinci sahibi rehber aynı frekansında titreşiyor.",
}

ARAP_NOKTA_GEZEGEN_SINASTRI_EBEVEYN = {
    ("Baba Noktası", "Güneş"): "Baba enerjisi çocuğunuzun öz-bilinciyle derin bir uyum içinde. Ebeveynlik rolünüz onun parlakığını besleyen bir ışık olacak.",
    ("Baba Noktası", "Ay"): "Baba enerjisi çocuğunuzun duygusal dünyasıyla derin bir uyum içinde. Otorite ve şefkat, onun için güvenli bir alan yaratıyor.",
    ("Baba Noktası", "Merkür"): "Baba enerjisi çocuğunuzun iletişim dünyasıyla uyum içinde. Bilgi aktarımı ve zihinsel beslenme bu bağın temeli.",
    ("Baba Noktası", "Venüs"): "Baba enerjisi çocuğunuzun sevgi diliyle uyum içinde. Estetik duyarlılık ve şefkat, bu ebeveynlik bağını besliyor.",
    ("Baba Noktası", "Mars"): "Baba enerjisi çocuğunuzun eylem enerjisiyle derin bir uyum içinde. Koruma ve cesaret bu bağın güçlü temeli.",
    ("Baba Noktası", "Jüpiter"): "Baba enerjisi çocuğunuzun genişleme enerjisiyle besleniyor. Bilgelik ve rehberlik, bu ebeveynlik yolculuğunu zenginleştiriyor.",
    ("Baba Noktası", "Satürn"): "Baba enerjisi çocuğunuzun yapı enerjisiyle derin bir uyum içinde. Sorumluluk ve disiplin, bu bağın iskeletini oluşturuyor.",

    ("Anne Noktası", "Güneş"): "Anne enerjisi çocuğunuzun öz-bilinciyle derin bir uyum içinde. Besleme ve koruma, onun parlakığını besleyen bir güneş olacak.",
    ("Anne Noktası", "Ay"): "Anne enerjisi çocuğunuzun duygusal dünyasıyla mükemmel bir dans yapıyor. Duygusal beslenme ve koruma bu bağın ruhudur.",
    ("Anne Noktası", "Merkür"): "Anne enerjisi çocuğunuzun iletişim dünyasıyla uyum içinde. Anlatım ve anlama, bu anne-çocuk bağını güçlendiriyor.",
    ("Anne Noktası", "Venüs"): "Anne enerjisi çocuğunuzun sevgi dilinde derin bir uyum yaratır. Şefkat, güzellik ve estetik bu anne bağını besliyor.",
    ("Anne Noktası", "Mars"): "Anne enerjisi çocuğunuzun eylem enerjisiyle derin bir uyum içinde. Koruma içgüdüsü ve cesaret bu anne bağını besler.",
    ("Anne Noktası", "Jüpiter"): "Anne enerjisi çocuğunuzun genişleme enerjisiyle besleniyor. Bilgelik ve şefkat, bu anne-çocuk yolculuğunu zenginleştiriyor.",
    ("Anne Noktası", "Satürn"): "Anne enerjisi çocuğunuzun yapı enerjisiyle derin bir uyum içinde. Sorumluluk ve yapı, bu anne bağının temelini oluşturuyor.",

    ("Çocuk Ruhu", "Güneş"): "Çocuğunuzun ruhsalpurpose'ı onun öz-bilinciyle derin bir uyum içinde. Hayat yolculuğu parlak ve anlamlı.",
    ("Çocuk Ruhu", "Ay"): "Çocuğunuzun ruhsalpurpose'ı duygusal dünyasıyla derin bir uyum içinde. Duygusal zekası ve sezgileri çok güçlü.",
    ("Çocuk Ruhu", "Merkür"): "Çocuğunuzun ruhsalpurpose'ı iletişim dünyasıyla uyum içinde. Zihinsel yetenekleri ve öğrenme kapasitesi çok yüksek.",
    ("Çocuk Ruhu", "Venüs"): "Çocuğunuzun ruhsalpurpose'ı sevgi dilinde derin bir uyum yaratır. Sanatsal yetenekleri ve estetik duyarlılığı çok güçlü.",
    ("Çocuk Ruhu", "Mars"): "Çocuğunuzun ruhsalpurpose'ı eylem enerjisiyle derin bir uyum içinde. Cesaret ve eylem yeteneği çok güçlü.",
    ("Çocuk Ruhu", "Jüpiter"): "Çocuğunuzun ruhsalpurpose'ı genişleme enerjisiyle mükemmel bir uyum içinde. Bilgelik ve bolluk onun yolunu aydınlatıyor.",
    ("Çocuk Ruhu", "Satürn"): "Çocuğunuzun ruhsalpurpose'ı yapı enerjisiyle derin bir uyum içinde. Disiplin ve sorumluluk bilinci çok güçlü.",

    ("Koruma Noktası", "Güneş"): "Koruma enerjiniz çocuğunuzun öz-bilinciyle derin bir uyum içinde. Onun parlakığını koruyan güçlü bir kalkan oluyorsunuz.",
    ("Koruma Noktası", "Ay"): "Koruma enerjiniz çocuğunuzun duygusal dünyasıyla derin bir uyum içinde. Duygusal koruma ve beslenme bu bağın temeli.",
    ("Koruma Noktası", "Merkür"): "Koruma enerjiniz çocuğunuzun iletişim dünyasıyla uyum içinde. Bilgi ve iletişim yoluyla koruma sağlıyorsunuz.",
    ("Koruma Noktası", "Venüs"): "Koruma enerjiniz çocuğunuzun sevgi dilinde derin bir uyum yaratır. Sevgi ve koruma, bu ebeveynlik bağını besliyor.",
    ("Koruma Noktası", "Mars"): "Koruma enerjiniz çocuğunuzun eylem enerjisiyle mükemmel bir uyum içinde. Cesaret ve koruma içgüdüsü zirve noktasında.",
    ("Koruma Noktası", "Jüpiter"): "Koruma enerjiniz çocuğunuzun genişleme enerjisiyle besleniyor. Koruma ve bilgelik birlikte çalışıyor.",
    ("Koruma Noktası", "Satürn"): "Koruma enerjiniz çocuğunuzun yapı enerjisiyle derin bir uyum içinde. Yapı ve koruma, çocuğunuz için güvenli bir temel oluşturuyor.",

    ("Eğitim Noktası", "Güneş"): "Eğitim enerjiniz çocuğunuzun öz-bilinciyle derin bir uyum içinde. Onun parlakığını besleyen bir öğretmen oluyorsunuz.",
    ("Eğitim Noktası", "Ay"): "Eğitim enerjiniz çocuğunuzun duygusal dünyasıyla derin bir uyum içinde. Duygusal zeka ve empati eğitimi bu bağın temeli.",
    ("Eğitim Noktası", "Merkür"): "Eğitim enerjiniz çocuğunuzun iletişim dünyasıyla mükemmel bir uyum içinde. Zihinsel beslenme ve bilgi aktarımı zirve noktasında.",
    ("Eğitim Noktası", "Venüs"): "Eğitim enerjiniz çocuğunuzun sevgi dilinde derin bir uyum yaratır. Sevgiyle öğrenme ve estetik eğitim bu bağın ruhudur.",
    ("Eğitim Noktası", "Mars"): "Eğitim enerjiniz çocuğunuzun eylem enerjisiyle derin bir uyum içinde. Eylem yoluyla öğrenme ve cesaret eğitimi ön planda.",
    ("Eğitim Noktası", "Jüpiter"): "Eğitim enerjiniz çocuğunuzun genişleme enerjisiyle mükemmel bir uyum içinde. Bilgelik ve eğitim, bu ebeveynlik yolculuğunu zenginleştiriyor.",
    ("Eğitim Noktası", "Satürn"): "Eğitim enerjiniz çocuğunuzun yapı enerjisiyle derin bir uyum içinde. Yapı ve disiplinli eğitim, bu bağın temelini oluşturuyor.",

    ("Sınır Noktası", "Güneş"): "Sınır koyma enerjiniz çocuğunuzun öz-bilinciyle derin bir uyum içinde. Onun benliğine saygı duyan sınırlar çiziyorsunuz.",
    ("Sınır Noktası", "Ay"): "Sınır koyma enerjiniz çocuğunuzun duygusal dünyasıyla derin bir uyum içinde. Duygusal sınırlar ve güvenlik bu bağın temeli.",
    ("Sınır Noktası", "Merkür"): "Sınır koyma enerjiniz çocuğunuzun iletişim dünyasıyla uyum içinde. İletişim sınırlarını net bir şekilde çiziyorsunuz.",
    ("Sınır Noktası", "Venüs"): "Sınır koyma enerjiniz çocuğunuzun sevgi dilinde derin bir uyum yaratır. Sevgiyle sınırlama, bu ebeveynlik bağını besliyor.",
    ("Sınır Noktası", "Mars"): "Sınır koyma enerjiniz çocuğunuzun eylem enerjisiyle derin bir uyum içinde. Kararlı ve net sınırlar çiziyorsunuz.",
    ("Sınır Noktası", "Jüpiter"): "Sınır koyma enerjiniz çocuğunuzun genişleme enerjisiyle besleniyor. Geniş perspektifli sınırlar çiziyorsunuz.",
    ("Sınır Noktası", "Satürn"): "Sınır koyma enerjiniz çocuğunuzun yapı enerjisiyle mükemmel bir uyum içinde. Yapı ve disiplin, sınırlarınızın temelini oluşturuyor.",

    ("Bağlanma Noktası", "Güneş"): "Bağlanma enerjiniz çocuğunuzun öz-bilinciyle derin bir uyum içinde. Onun benliğiyle derin bir bağ kuruyorsunuz.",
    ("Bağlanma Noktası", "Ay"): "Bağlanma enerjiniz çocuğunuzun duygusal dünyasıyla mükemmel bir dans yapıyor. Duygusal bağlanma ve beslenme bu bağın ruhudur.",
    ("Bağlanma Noktası", "Merkür"): "Bağlanma enerjiniz çocuğunuzun iletişim dünyasıyla uyum içinde. İletişim ve bilgi paylaşımı yoluyla derin bağ kuruyorsunuz.",
    ("Bağlanma Noktası", "Venüs"): "Bağlanma enerjiniz çocuğunuzun sevgi dilinde derin bir uyum yaratır. Sevgi, şefkat ve estetik bu bağlanma bağını besliyor.",
    ("Bağlanma Noktası", "Mars"): "Bağlanma enerjiniz çocuğunuzun eylem enerjisiyle derin bir uyum içinde. Eylem ve cesaret yoluyla bağ kuruyorsunuz.",
    ("Bağlanma Noktası", "Jüpiter"): "Bağlanma enerjiniz çocuğunuzun genişleme enerjisiyle besleniyor. Bilgelik ve geniş perspektif, bu bağı zenginleştiriyor.",
    ("Bağlanma Noktası", "Satürn"): "Bağlanma enerjiniz çocuğunuzun yapı enerjisiyle derin bir uyum içinde. Yapı ve sorumluluk, bu bağın temelini oluşturuyor.",

    ("Sorumluluk", "Güneş"): "Sorumluluk enerjiniz çocuğunuzun öz-bilinciyle derin bir uyum içinde. Onun benliğine saygı duyan sorumluluklar taşıyorsunuz.",
    ("Sorumluluk", "Ay"): "Sorumluluk enerjiniz çocuğunuzun duygusal dünyasıyla derin bir uyum içinde. Duygusal sorumluluk ve beslenme bu bağın temeli.",
    ("Sorumluluk", "Merkür"): "Sorumluluk enerjiniz çocuğunuzun iletişim dünyasıyla uyum içinde. İletişim ve bilgi paylaşımı yoluyla sorumluluk taşıyorsunuz.",
    ("Sorumluluk", "Venüs"): "Sorumluluk enerjiniz çocuğunuzun sevgi dilinde derin bir uyum yaratır. Sevgi ve sorumluluk, bu ebeveynlik bağını besliyor.",
    ("Sorumluluk", "Mars"): "Sorumluluk enerjiniz çocuğunuzun eylem enerjisiyle derin bir uyum içinde. Cesaret ve sorumluluk, bu bağın güçlü temeli.",
    ("Sorumluluk", "Jüpiter"): "Sorumluluk enerjiniz çocuğunuzun genişleme enerjisiyle besleniyor. Bilgelik ve sorumluluk, bu ebeveynlik yolculuğunu zenginleştiriyor.",
    ("Sorumluluk", "Satürn"): "Sorumluluk enerjiniz çocuğunuzun yapı enerjisiyle mükemmel bir uyum içinde. Yapı ve sorumluluk, bu bağın temelini oluşturuyor.",
}
