# -*- coding: utf-8 -*-
# Variante en español de ARAP_EBEVEYN_DICTS.py. Las claves se mantienen idénticas; solo los valores se traducen al español.

ARAP_NOKTALARI_EBEVEYN = {
    "Baba Noktası":     {"nokta1": "10HC", "nokta2": "Güneş", "kisa": "BABA", "aciklama": "Figura paterna, energía de autoridad y disciplina"},
    "Anne Noktası":     {"nokta1": "4HC",  "nokta2": "Ay",     "kisa": "ANNE", "aciklama": "Figura materna, nutrición y protección emocional"},
    "Çocuk Ruhu":       {"nokta1": "5HC",  "nokta2": "Jüpiter","kisa": "ÇRUH", "aciklama": "El propósito espiritual y el potencial creativo del niño"},
    "Koruma Noktası":   {"nokta1": "2HC",  "nokta2": "Mars",   "kisa": "KORU", "aciklama": "Energía de protección física y material"},
    "Eğitim Noktası":   {"nokta1": "9HC",  "nokta2": "Merkür", "kisa": "EĞİT", "aciklama": "Enseñanza-aprendizaje y transmisión filosófica"},
    "Sınır Noktası":    {"nokta1": "6HC",  "nokta2": "Satürn", "kisa": "SINR", "aciklama": "Disciplina, establecimiento de límites y rutina diaria"},
    "Bağlanma Noktası": {"nokta1": "4HC",  "nokta2": "Venüs",  "kisa": "BAGL", "aciklama": "Forma de vinculación emocional y lenguaje de la ternura"},
    "Sorumluluk":       {"nokta1": "10HC", "nokta2": "Satürn", "kisa": "SORU", "aciklama": "Responsabilidad parental y papel social"},
}

ARAP_NOKTA_BURC_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", "Koç"): "Tu energía paterna se entrelaza con un espíritu valiente, pionero e independiente. Para tu hijo te conviertes en una figura de padre/madre que se mantiene firme ante el mundo y toma la iniciativa.",
    ("Baba Noktası", "Boğa"): "Tu energía paterna se asienta en la tierra, la fiabilidad y la permanencia. Te conviertes en un protector inquebrantable que brinda a tu hijo seguridad material y espiritual.",
    ("Baba Noktası", "İkizler"): "Tu energía paterna está construida sobre la comunicación, la sintonía mental y la versatilidad. Eres un padre/madre que crece con tu hijo conversando, aprendiendo y compartiendo.",
    ("Baba Noktası", "Yengeç"): "Tu energía paterna se amasa con una profunda nutrición emocional y el instinto de protección. Construyes para tu hijo un refugio emocional inquebrantable.",
    ("Baba Noktası", "Aslan"): "Tu energía paterna se asienta en la grandeza, la creatividad y la generosidad. Eres un guía que hace brillar los talentos de tu hijo y se enorgullece de él.",
    ("Baba Noktası", "Başak"): "Tu energía paterna está construida sobre el servicio, la búsqueda de la perfección y el orden práctico. Creas un sistema que atiende con meticulosidad cada necesidad de tu hijo.",
    ("Baba Noktası", "Terazi"): "Tu energía paterna se asienta en la armonía, la estética y el equilibrio. Eres un guía elegante que construye una relación justa y equilibrada con tu hijo.",
    ("Baba Noktası", "Akrep"): "Tu energía paterna se amasa con transformación profunda, intensidad y misterio. Despliegas una energía paterna oculta, siempre alerta ante cualquier peligro por tu hijo.",
    ("Baba Noktası", "Yay"): "Tu energía paterna se asienta en la libertad, la expansión y la profundidad filosófica. Eres un guía que inspira en tu hijo una amplia visión y descubre la vida junto a él.",
    ("Baba Noktası", "Oğlak"): "Tu energía paterna está construida sobre la estructura, la responsabilidad y los planes a largo plazo. Eres un padre/madre que da disciplina y estructura a tu hijo y lo prepara para la vida.",
    ("Baba Noktası", "Kova"): "Tu energía paterna se entrelaza con un espíritu extraordinario, libre y revolucionario. Eres un guía que no encasilla a tu hijo y respeta su individualidad.",
    ("Baba Noktası", "Balık"): "Tu energía paterna se asienta en la espiritualidad, el sacrificio y la profundidad intuitiva. Eres un padre/madre que establece un vínculo espiritual con tu hijo y se centra en su desarrollo espiritual.",

    ("Anne Noktası", "Koç"): "Tu energía materna se amasa con un espíritu valiente, que toma la iniciativa y protege. Por tu hijo te conviertes en una figura materna que desafía al mundo y hace cualquier cosa por protegerlo.",
    ("Anne Noktası", "Boğa"): "Tu energía materna se asienta en la tierra, la nutrición y la permanencia. Eres un guía que nutre a tu hijo física y emocionalmente y construye un hogar seguro.",
    ("Anne Noktası", "İkizler"): "Tu energía materna está construida sobre la comunicación, la alegría y la curiosidad. Eres una madre divertida que comparte conocimiento con tu hijo y descubre todo a su lado.",
    ("Anne Noktası", "Yengeç"): "Tu energía materna se amasa con una profunda nutrición emocional y el instinto de protección. Eres para tu hijo un puerto emocional inquebrantable, un cálido abrazo.",
    ("Anne Noktası", "Aslan"): "Tu energía materna se asienta con grandeza, generosidad y un corazón lleno de amor. Eres una madre que pone el brillo de tu hijo en el escenario y se enorgullece de él.",
    ("Anne Noktası", "Başak"): "Tu energía materna está construida sobre la meticulosidad, el servicio y la perfección práctica. Creas un orden que atiende con perfección las necesidades de salud, alimentación y cuidado de tu hijo.",
    ("Anne Noktası", "Terazi"): "Tu energía materna se asienta en la elegancia, la armonía y el equilibrio. Eres un guía que construye una relación justa y equilibrada con tu hijo y posee sensibilidad estética.",
    ("Anne Noktası", "Akrep"): "Tu energía materna se amasa con intensidad profunda, transformación y protección. Eres una madre siempre alerta ante cualquier peligro y dotada de una profunda intuición por tu hijo.",
    ("Anne Noktası", "Yay"): "Tu energía materna se nutre de libertad, optimismo y el deseo de aventura. Eres un guía que abre a tu hijo un amplio horizonte y aprende la vida a su lado.",
    ("Anne Noktası", "Oğlak"): "Tu energía materna está construida sobre la estructura, la responsabilidad y la paciencia. Eres una madre que pone límites a tu hijo, le da disciplina pero nunca le escatima su amor.",
    ("Anne Noktası", "Kova"): "Tu energía materna se entrelaza con un espíritu extraordinario, libre y humanitario. Eres un guía que respeta la individualidad de tu hijo y no lo encasilla.",
    ("Anne Noktası", "Balık"): "Tu energía materna se asienta en la profundidad intuitiva, la compasión y el amor incondicional. Eres una madre que se conecta con tu hijo a nivel telepático y nutre su mundo espiritual.",

    ("Çocuk Ruhu", "Koç"): "El propósito espiritual de tu hijo lleva una energía valiente, independiente y pionera. Ha llegado al mundo con un espíritu que se abre su propio camino, toma la iniciativa y posee cualidades de liderazgo.",
    ("Çocuk Ruhu", "Boğa"): "El propósito espiritual de tu hijo se asienta en la tierra, la belleza y la permanencia. Lleva un potencial de sensibilidad artística, placeres sensoriales y creación de valores concretos.",
    ("Çocuk Ruhu", "İkizler"): "El propósito espiritual de tu hijo está construido sobre la comunicación, la curiosidad y la versatilidad. Posee una mente que procesa el conocimiento, lo comparte y conecta con la sociedad.",
    ("Çocuk Ruhu", "Yengeç"): "El propósito espiritual de tu hijo se amasa con profundidad emocional, protección y un sentimiento de pertenencia. Lleva un espíritu compasivo, profundamente ligado a su familia y a sus seres queridos.",
    ("Çocuk Ruhu", "Aslan"): "El propósito espiritual de tu hijo se asienta en la creatividad, la generosidad y un brillante gozo interior. Es un espíritu que destaca por sus talentos artísticos, su energía escénica y su generoso corazón.",
    ("Çocuk Ruhu", "Başak"): "El propósito espiritual de tu hijo está construido sobre la meticulosidad, el servicio y la perfección práctica. Es un espíritu que sobresale por su mente detallista, su sentido de la ayuda y su habilidad para crear orden.",
    ("Çocuk Ruhu", "Terazi"): "El propósito espiritual de tu hijo se asienta en el equilibrio, la estética y la armonía. Es un espíritu con sentido de la justicia, sensibilidad artística y potencial para crear equilibrio en las relaciones.",
    ("Çocuk Ruhu", "Akrep"): "El propósito espiritual de tu hijo se amasa con transformación profunda, intensidad y misterio. Es un espíritu de profundo mundo interior, intuiciones poderosas y que experimenta la vida en todas sus dimensiones.",
    ("Çocuk Ruhu", "Yay"): "El propósito espiritual de tu hijo se asienta en la libertad, el descubrimiento y la expansión filosófica. Es un espíritu amplio que lleva distintas culturas, la búsqueda de la sabiduría y la pasión por la aventura.",
    ("Çocuk Ruhu", "Oğlak"): "El propósito espiritual de tu hijo está construido sobre la estructura, la responsabilidad y las metas a largo plazo. Es un espíritu que trabaja con madurez temprana, disciplina y paciencia para alcanzar sus objetivos.",
    ("Çocuk Ruhu", "Kova"): "El propósito espiritual de tu hijo se asienta en la originalidad, el humanitarismo y la visión de futuro. Es un espíritu que piensa de forma extraordinaria, contribuye a la sociedad y diseña el futuro.",
    ("Çocuk Ruhu", "Balık"): "El propósito espiritual de tu hijo se amasa con espiritualidad, compasión y profundidad intuitiva. Es un espíritu que sobresale por sus talentos artísticos, su sentido de la misericordia y sus percepciones espirituales.",

    ("Koruma Noktası", "Koç"): "Tu energía de protección se amasa de forma valiente, directa y orientada a la acción. Eres un escudo valiente que, cuando es necesario, se planta ante el mundo para proteger a tu hijo.",
    ("Koruma Noktası", "Boğa"): "Tu energía de protección está construida de forma terrenal, concreta y permanente. Eres una fuente de seguridad inquebrantable que garantiza la seguridad material y física de tu hijo.",
    ("Koruma Noktası", "İkizler"): "Tu energía de protección está construida sobre la comunicación, el conocimiento y la agilidad mental. Eres un protector que nutre mentalmente a tu hijo y le transmite el conocimiento como herramienta.",
    ("Koruma Noktası", "Yengeç"): "Tu energía de protección se amasa con un profundo vínculo emocional y el instinto materno. Eres para tu hijo un escudo emocional inquebrantable y un cálido refugio.",
    ("Koruma Noktası", "Aslan"): "Tu energía de protección está construida de forma magnífica, generosa y honorable. Eres un león protector que preserva el brillo de tu hijo y lucha con orgullo por él.",
    ("Koruma Noktası", "Başak"): "Tu energía de protección funciona de forma meticulosa, práctica y detallista. Creas un sistema de protección que atiende con perfección la salud, la alimentación y las necesidades diarias de tu hijo.",
    ("Koruma Noktası", "Terazi"): "Tu energía de protección está construida de forma equilibrada, elegante y justa. Eres un guía equilibrado que crea para tu hijo un espacio de protección justo.",
    ("Koruma Noktası", "Akrep"): "Tu energía de protección funciona de forma profunda, intensa y oculta. Eres un poderoso escudo que se mantiene intuitivamente alerta ante cualquier peligro por tu hijo.",
    ("Koruma Noktası", "Yay"): "Tu energía de protección está construida de forma expansiva, optimista y filosófica. Eres un guía que protege a tu hijo desde una amplia perspectiva y le infunde una visión de la vida.",
    ("Koruma Noktası", "Oğlak"): "Tu energía de protección se amasa con estructura, disciplina y sentido de la responsabilidad. Eres un guía que protege a tu hijo estableciendo estructura y límites, creando un sistema de seguridad a largo plazo.",
    ("Koruma Noktası", "Kova"): "Tu energía de protección está construida de forma extraordinaria, libre y social. Eres un guía que protege a tu hijo fuera de los moldes y lo nutre con conciencia social.",
    ("Koruma Noktası", "Balık"): "Tu energía de protección funciona de forma intuitiva, espiritual e incondicional. Eres un guía que siente a tu hijo intuitivamente y lo protege a nivel espiritual.",

    ("Eğitim Noktası", "Koç"): "Tu energía educativa está construida de forma valiente, pionera y orientada a la acción. Te nutres con emoción mientras enseñas a tu hijo a tomar la iniciativa, el coraje y las habilidades de liderazgo.",
    ("Eğitim Noktası", "Boğa"): "Tu energía educativa funciona de forma concreta, práctica y sensorial. Descubres formas de enseñar a tu hijo a través del arte, la naturaleza y las experiencias concretas.",
    ("Eğitim Noktası", "İkizler"): "Tu energía educativa está construida sobre la comunicación, la curiosidad y la versatilidad. Encuentras formas de compartir conocimiento con tu hijo y de hacer cada tema divertido.",
    ("Eğitim Noktası", "Yengeç"): "Tu energía educativa se amasa con nutrición emocional y el instinto de protección. Te nutres mientras transmites a tu hijo la inteligencia emocional, la empatía y los valores familiares.",
    ("Eğitim Noktası", "Aslan"): "Tu energía educativa está construida de forma creativa, generosa y orientada al escenario. Abres espacio para que tu hijo desarrolle sus talentos artísticos y se exprese a sí mismo.",
    ("Eğitim Noktası", "Başak"): "Tu energía educativa funciona de forma meticulosa, sistemática y centrada en la perfección. Construyes un sistema perfecto mientras enseñas a tu hijo el orden, la atención al detalle y las habilidades prácticas.",
    ("Eğitim Noktası", "Terazi"): "Tu energía educativa está construida de forma equilibrada, estética y armoniosa. Trazas un camino elegante mientras enseñas a tu hijo la justicia, el arte y el equilibrio en las relaciones.",
    ("Eğitim Noktası", "Akrep"): "Tu energía educativa funciona de forma profunda, intensa y transformadora. Enseñas a tu hijo a explorar las profundidades del mundo interior, la transformación y el uso correcto del poder.",
    ("Eğitim Noktası", "Yay"): "Tu energía educativa está construida de forma expansiva, filosófica y llena de aventura. Transmites a tu hijo distintas culturas, la filosofía y una amplia perspectiva de la vida.",
    ("Eğitim Noktası", "Oğlak"): "Tu energía educativa funciona de forma estructural, orientada a la responsabilidad y paciente. Te nutres mientras transmites a tu hijo el establecimiento de metas, la paciencia y las habilidades de planificación a largo plazo.",
    ("Eğitim Noktası", "Kova"): "Tu energía educativa está construida de forma extraordinaria, innovadora y social. Transmites a tu hijo las habilidades del futuro, la tecnología y la sensibilidad social.",
    ("Eğitim Noktası", "Balık"): "Tu energía educativa funciona de forma intuitiva, artística y espiritual. Te nutres mientras transmites a tu hijo la imaginación, la sensibilidad artística y la sabiduría espiritual.",

    ("Sınır Noktası", "Koç"): "Tu energía para poner límites está construida de forma valiente, clara y directa. Eres un guía que traza límites nítidos y claros a tu hijo y se mantiene firme cuando es necesario.",
    ("Sınır Noktası", "Boğa"): "Tu energía para poner límites funciona de forma terrenal, paciente y permanente. Eres un guía que pone límites a tu hijo con paciencia, ofreciendo una estructura estable y fiable.",
    ("Sınır Noktası", "İkizler"): "Tu energía para poner límites está construida sobre la comunicación, la flexibilidad y la agilidad mental. Eres un guía que pone límites conversando con tu hijo, de forma explicativa e informativa.",
    ("Sınır Noktası", "Yengeç"): "Tu energía para poner límites se amasa con profundidad emocional y el instinto de protección. Los límites que pones para proteger a tu hijo se nutren de amor y ternura.",
    ("Sınır Noktası", "Aslan"): "Tu energía para poner límites está construida de forma magnífica, honorable y autoritaria. Eres un guía que traza límites claros y respetables, combinando su autoridad con el amor.",
    ("Sınır Noktası", "Başak"): "Tu energía para poner límites funciona de forma meticulosa, sistemática y ordenada. Eres un guía que ofrece a tu hijo reglas, rutinas y una estructura de vida detallada.",
    ("Sınır Noktası", "Terazi"): "Tu energía para poner límites está construida de forma equilibrada, justa y elegante. Eres un guía que pone límites justos a tu hijo y está abierto a la negociación.",
    ("Sınır Noktası", "Akrep"): "Tu energía para poner límites funciona de forma profunda, incisiva y transformadora. Eres un guía que traza límites definidos a tu hijo, pero también transmite el profundo amor que hay tras ellos.",
    ("Sınır Noktası", "Yay"): "Tu energía para poner límites está construida de forma expansiva, flexible y filosófica. Eres un guía que traza límites flexibles y enseña a tu hijo el equilibrio entre libertad y responsabilidad.",
    ("Sınır Noktası", "Oğlak"): "Tu energía para poner límites funciona de forma estructural, disciplinada y firme. Eres un guía que traza límites estrictos pero justos, otorgando estructura y orden.",
    ("Sınır Noktası", "Kova"): "Tu energía para poner límites está construida de forma extraordinaria, flexible y social. Eres un guía que traza límites no tradicionales pero funcionales para tu hijo.",
    ("Sınır Noktası", "Balık"): "Tu energía para poner límites funciona de forma intuitiva, flexible y emocional. Ofreces una guía intuitiva mientras enseñas a tu hijo los límites emocionales.",

    ("Bağlanma Noktası", "Koç"): "Tu forma de vincular está construida de forma valiente, independiente y orientada a la acción. Estableces con tu hijo un vínculo combativo pero lleno de amor, y lo nutres con coraje.",
    ("Bağlanma Noktası", "Boğa"): "Tu forma de vincular funciona de forma terrenal, sensorial y permanente. Creas un vínculo profundo con tu hijo a través del contacto físico, el tacto y los lenguajes de amor concretos.",
    ("Bağlanma Noktası", "İkizler"): "Tu forma de vincular está construida sobre la comunicación, la alegría y la sintonía mental. Estableces un vínculo agradable con tu hijo conversando, jugando y compartiendo conocimiento.",
    ("Bağlanma Noktası", "Yengeç"): "Tu forma de vincular se amasa con profunda nutrición emocional y el instinto de protección. Estableces con tu hijo un vínculo emocional tan cálido e inquebrantable como el regazo materno.",
    ("Bağlanma Noktası", "Aslan"): "Tu forma de vincular está construida de forma magnífica, generosa y llena de amor. Creas un vínculo que pone a tu hijo en el escenario, se enorgullece de él y muestra el amor con generosidad.",
    ("Bağlanma Noktası", "Başak"): "Tu forma de vincular funciona de forma práctica, orientada al servicio y ordenada. Atiendes con perfección las necesidades de tu hijo y creas un vínculo profundo a través del servicio.",
    ("Bağlanma Noktası", "Terazi"): "Tu forma de vincular está construida de forma equilibrada, elegante y armoniosa. Estableces un vínculo profundo con tu hijo a través del equilibrio, la justicia y la sensibilidad estética.",
    ("Bağlanma Noktası", "Akrep"): "Tu forma de vincular funciona de forma profunda, intensa y transformadora. Estableces con tu hijo un vínculo muy profundo, casi espiritual. La intensidad es la base de este vínculo.",
    ("Bağlanma Noktası", "Yay"): "Tu forma de vincular está construida de forma expansiva, alegre y llena de aventura. Te vinculas con libertad y alegría mientras descubres la vida junto a tu hijo.",
    ("Bağlanma Noktası", "Oğlak"): "Tu forma de vincular funciona con estructura, sentido de la responsabilidad y paciencia. Construyes un vínculo a largo plazo dando a tu hijo estructura, orden y confianza.",
    ("Bağlanma Noktası", "Kova"): "Tu forma de vincular está construida de forma extraordinaria, libre y amistosa. Estableces con tu hijo un vínculo amistoso, igualitario e innovador.",
    ("Bağlanma Noktası", "Balık"): "Tu forma de vincular funciona de forma intuitiva, incondicional y espiritual. Estableces con tu hijo un vínculo profundo a nivel telepático, alimentado por el amor incondicional.",

    ("Sorumluluk", "Koç"): "Tu responsabilidad parental está construida de forma valiente, con iniciativa y orientada a la acción. Eres un guía que desafía al mundo por tu hijo y lleva la responsabilidad con coraje.",
    ("Sorumluluk", "Boğa"): "Tu responsabilidad parental funciona de forma terrenal, fiable y permanente. Actúas con un sentido de la responsabilidad a largo plazo que proporciona a tu hijo garantía material y espiritual.",
    ("Sorumluluk", "İkizler"): "Tu responsabilidad parental está construida sobre la comunicación, la flexibilidad y la agilidad mental. Cumples con tu responsabilidad comunicándote con tu hijo y compartiendo conocimiento.",
    ("Sorumluluk", "Yengeç"): "Tu responsabilidad parental se amasa con profunda nutrición emocional y el instinto de protección. Eres un guía que lo sacrifica todo por tu hijo y lleva la responsabilidad con amor.",
    ("Sorumluluk", "Aslan"): "Tu responsabilidad parental está construida de forma magnífica, generosa y honorable. Eres un guía que permite a tu hijo desarrollar sus talentos y lleva la responsabilidad con orgullo.",
    ("Sorumluluk", "Başak"): "Tu responsabilidad parental funciona de forma meticulosa, práctica y centrada en la perfección. Eres un guía que atiende cada necesidad de tu hijo en detalle y cumple su responsabilidad a la perfección.",
    ("Sorumluluk", "Terazi"): "Tu responsabilidad parental está construida de forma equilibrada, justa y elegante. Eres un guía que establece una relación justa con tu hijo y comparte la responsabilidad de forma equilibrada.",
    ("Sorumluluk", "Akrep"): "Tu responsabilidad parental funciona de forma profunda, intensa y transformadora. Eres un guía que hace cualquier sacrificio por tu hijo y lleva la responsabilidad con profunda determinación.",
    ("Sorumluluk", "Yay"): "Tu responsabilidad parental está construida de forma expansiva, filosófica y llena de aventura. Eres un guía que infunde a tu hijo una amplia perspectiva de la vida y lleva la responsabilidad con alegría.",
    ("Sorumluluk", "Oğlak"): "Tu responsabilidad parental funciona de forma estructural, disciplinada y firme. Eres un guía que se acerca a tu hijo con estructura, orden y seriedad, y lleva la responsabilidad con meticulosidad.",
    ("Sorumluluk", "Kova"): "Tu responsabilidad parental está construida de forma extraordinaria, innovadora y social. Eres un guía que infunde conciencia social a tu hijo y orienta la responsabilidad hacia el futuro.",
    ("Sorumluluk", "Balık"): "Tu responsabilidad parental funciona de forma intuitiva, espiritual e incondicional. Eres un guía que se centra en el desarrollo espiritual de tu hijo y lleva la responsabilidad con amor e intuición.",
}

ARAP_NOKTA_EV_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", 1): "La energía paterna está directamente conectada con tu identidad. Tu rol parental está en el centro de tu vida.",
    ("Baba Noktası", 2): "La energía paterna se nutre de la seguridad material y los valores. Construyes para tu hijo una base concreta.",
    ("Baba Noktası", 3): "La energía paterna está conectada con la comunicación y el entorno. El intercambio de conocimiento y experiencias con tu hijo está en primer plano.",
    ("Baba Noktası", 4): "La energía paterna tiene un vínculo profundo con las raíces familiares y la vida del hogar. La construcción del hogar es la base de esta energía.",
    ("Baba Noktası", 5): "La energía paterna se amasa con la creatividad y el mundo infantil. El juego y la alegría son la fuente de alimento de esta energía.",
    ("Baba Noktası", 6): "La energía paterna está conectada con el cuidado diario y la salud. El apoyo práctico y el orden son la base de esta energía.",
    ("Baba Noktası", 7): "La energía paterna es fuerte en el ámbito del equilibrio y el espejo. La búsqueda del equilibrio en tus roles parentales está en primer plano.",
    ("Baba Noktası", 8): "La energía paterna se profundiza con la transformación y las crisis. Eres un protector poderoso en los tiempos difíciles.",
    ("Baba Noktası", 9): "La energía paterna se nutre de la filosofía y la educación. Transmites a tu hijo valores y sabiduría.",
    ("Baba Noktası", 10): "La energía paterna se corona en la carrera y el rol social. Eres una figura paterna fuerte a los ojos de la sociedad.",
    ("Baba Noktası", 11): "La energía paterna está conectada con la amistad y los grupos. Participas activamente en el mundo social de tu hijo.",
    ("Baba Noktası", 12): "La energía paterna se profundiza con el subconsciente y la espiritualidad. Posees una sabiduría paterna intuitiva.",

    ("Anne Noktası", 1): "La energía materna está directamente conectada con tu identidad. Tu rol parental constituye la base de tu personalidad.",
    ("Anne Noktası", 2): "La energía materna se nutre de la seguridad material y la nutrición. Ofreces a tu hijo sanación física y emocional.",
    ("Anne Noktası", 3): "La energía materna está conectada con la comunicación y el entorno. Eres un guía que mantiene comunicación constante con tu hijo.",
    ("Anne Noktası", 4): "La energía materna tiene un vínculo profundo con las raíces familiares y la vida del hogar. La construcción del hogar es el corazón de esta energía.",
    ("Anne Noktası", 5): "La energía materna se amasa con la creatividad y los momentos de juego. Compartes momentos creativos con tu hijo.",
    ("Anne Noktası", 6): "La energía materna está conectada con el cuidado diario y la salud. Atiendes con perfección las necesidades rutinarias de tu hijo.",
    ("Anne Noktası", 7): "La energía materna es fuerte en el equilibrio y la reciprocidad. Estableces una relación equilibrada con tu hijo.",
    ("Anne Noktası", 8): "La energía materna se amasa con la transformación y la profundización. Eres una sanadora poderosa en los momentos de crisis.",
    ("Anne Noktası", 9): "La energía materna se nutre de la filosofía y la educación. Transmites a tu hijo una amplia perspectiva de la vida.",
    ("Anne Noktası", 10): "La energía materna se corona en el rol social. Eres una figura materna respetable a los ojos de la sociedad.",
    ("Anne Noktası", 11): "La energía materna está conectada con las esperanzas y los grupos. Eres un guía que apoya los sueños de tu hijo.",
    ("Anne Noktası", 12): "La energía materna se nutre de profundidad intuitiva y espiritualidad. Estableces un vínculo materno a nivel telepático.",

    ("Çocuk Ruhu", 1): "El propósito espiritual de tu hijo está directamente conectado con su identidad. El viaje de descubrir su propio ser está en primer plano.",
    ("Çocuk Ruhu", 2): "El propósito espiritual de tu hijo se nutre de los valores materiales y las experiencias concretas. Su potencial artístico y sensorial es alto.",
    ("Çocuk Ruhu", 3): "El propósito espiritual de tu hijo está conectado con la comunicación y el entorno. Destaca su capacidad de compartir el conocimiento y conectarse con el entorno.",
    ("Çocuk Ruhu", 4): "El propósito espiritual de tu hijo tiene un vínculo profundo con las raíces familiares y la vida del hogar. Los lazos familiares son sagrados para él.",
    ("Çocuk Ruhu", 5): "El propósito espiritual de tu hijo se amasa con la creatividad y la autoexpresión. Sus talentos artísticos y su energía lúdica son elevados.",
    ("Çocuk Ruhu", 6): "El propósito espiritual de tu hijo está conectado con el orden diario y el servicio. Destacan sus habilidades prácticas y su sentido de la ayuda.",
    ("Çocuk Ruhu", 7): "El propósito espiritual de tu hijo se profundiza con las relaciones y el equilibrio. Es alto su potencial para crear equilibrio y armonía en las relaciones.",
    ("Çocuk Ruhu", 8): "El propósito espiritual de tu hijo se amasa con la transformación y la profundización. Lleva un fuerte potencial de transformación en su mundo interior.",
    ("Çocuk Ruhu", 9): "El propósito espiritual de tu hijo se nutre de la filosofía y la expansión. Lo nutren las distintas culturas y la búsqueda de la sabiduría.",
    ("Çocuk Ruhu", 10): "El propósito espiritual de tu hijo se corona en la carrera y el rol social. Trabaja con disciplina para alcanzar sus metas.",
    ("Çocuk Ruhu", 11): "El propósito espiritual de tu hijo está conectado con la amistad y las comunidades. Su entorno social es amplio y de apoyo.",
    ("Çocuk Ruhu", 12): "El propósito espiritual de tu hijo se nutre de profundidad intuitiva y espiritualidad. Posee poderosas facultades intuitivas e imaginación.",

    ("Koruma Noktası", 1): "Tu energía de protección está directamente conectada con tu identidad. Tu instinto de protegerte a ti mismo y a tu hijo es muy poderoso.",
    ("Koruma Noktası", 2): "Tu energía de protección se nutre de la seguridad material y los valores. Estás decidido a cubrir las necesidades materiales de tu hijo.",
    ("Koruma Noktası", 3): "Tu energía de protección está conectada con la comunicación y el entorno. Proteges a tu hijo frente a los demás de forma informativa.",
    ("Koruma Noktası", 4): "Tu energía de protección tiene un vínculo profundo con las raíces familiares y la vida del hogar. El hogar es el centro de la protección para ti.",
    ("Koruma Noktası", 5): "Tu energía de protección se amasa con la creatividad y los momentos de juego. Garantizas la seguridad creativa de tu hijo.",
    ("Koruma Noktası", 6): "Tu energía de protección está conectada con el cuidado diario y la salud. Eres meticuloso en la protección de la salud física de tu hijo.",
    ("Koruma Noktası", 7): "Tu energía de protección es fuerte en el equilibrio y las relaciones. Proteges a tu hijo de forma equilibrada y justa.",
    ("Koruma Noktası", 8): "Tu energía de protección se profundiza con la transformación y las crisis. Eres un escudo protector poderoso en los tiempos difíciles.",
    ("Koruma Noktası", 9): "Tu energía de protección se nutre de la filosofía y los valores. Proteges a tu hijo con tus valores y creencias.",
    ("Koruma Noktası", 10): "Tu energía de protección se corona en la carrera y los roles sociales. Usas tu estatus social como energía de protección.",
    ("Koruma Noktası", 11): "Tu energía de protección está conectada con la amistad y los grupos. Pones bajo protección el entorno social de tu hijo.",
    ("Koruma Noktası", 12): "Tu energía de protección se nutre de profundidad intuitiva y espiritualidad. Proteges intuitivamente a tu hijo contra los peligros.",

    ("Eğitim Noktası", 1): "Tu energía educativa está directamente conectada con tu identidad. Tu rol de maestro constituye la base de tu personalidad.",
    ("Eğitim Noktası", 2): "Tu energía educativa se nutre de los recursos materiales y las experiencias concretas. Eres experto en enseñar habilidades prácticas.",
    ("Eğitim Noktası", 3): "Tu energía educativa está conectada con la comunicación y el entorno. Compartes conocimiento constantemente con tu hijo.",
    ("Eğitim Noktası", 4): "Tu energía educativa tiene un vínculo profundo con las raíces familiares y la vida del hogar. La educación en la familia es la base de esta energía.",
    ("Eğitim Noktası", 5): "Tu energía educativa se amasa con la creatividad y los momentos de juego. Tu habilidad para enseñar a través del juego es muy poderosa.",
    ("Eğitim Noktası", 6): "Tu energía educativa está conectada con la rutina diaria y el orden práctico. Creas oportunidades constantes de enseñanza en la vida diaria.",
    ("Eğitim Noktası", 7): "Tu energía educativa es fuerte en el equilibrio y la reciprocidad. El aprendizaje y la enseñanza mutuos encuentran el equilibrio.",
    ("Eğitim Noktası", 8): "Tu energía educativa se amasa con la transformación y la profundización. Enseñas a aprender de las experiencias difíciles.",
    ("Eğitim Noktası", 9): "Tu energía educativa se nutre de la filosofía y la expansión. Transmites distintas culturas y perspectivas filosóficas.",
    ("Eğitim Noktası", 10): "Tu energía educativa se corona en la carrera y los roles sociales. Las metas educativas y los planes a largo plazo están en primer plano.",
    ("Eğitim Noktası", 11): "Tu energía educativa está conectada con la amistad y las comunidades. Compartes la enseñanza y el aprendizaje en el entorno social.",
    ("Eğitim Noktası", 12): "Tu energía educativa se nutre de profundidad intuitiva y espiritualidad. Transmites conocimientos espirituales e intuitivos.",

    ("Sınır Noktası", 1): "Tu energía para poner límites está directamente conectada con tu identidad. Los límites son una parte fundamental de tu personalidad.",
    ("Sınır Noktası", 2): "Tu energía para poner límites se nutre de los valores materiales y los recursos. Pones límites claros en los asuntos materiales.",
    ("Sınır Noktası", 3): "Tu energía para poner límites está conectada con la comunicación y el entorno. Tu habilidad para definir límites en la comunicación es fuerte.",
    ("Sınır Noktası", 4): "Tu energía para poner límites tiene un vínculo profundo con las raíces familiares y la vida del hogar. Los límites en el hogar son la base de esta energía.",
    ("Sınır Noktası", 5): "Tu energía para poner límites se amasa con la creatividad y los momentos de juego. Tu habilidad para definir los límites del juego es fuerte.",
    ("Sınır Noktası", 6): "Tu energía para poner límites está conectada con la rutina diaria y la salud. Eres experto en el orden diario y el establecimiento de límites.",
    ("Sınır Noktası", 7): "Tu energía para poner límites es fuerte en el equilibrio y las relaciones. Tu habilidad para poner límites justos en las relaciones es fuerte.",
    ("Sınır Noktası", 8): "Tu energía para poner límites se profundiza con la transformación y las crisis. Pones límites firmes en los momentos de crisis.",
    ("Sınır Noktası", 9): "Tu energía para poner límites se nutre de la filosofía y los valores. Pones límites sobre la base de los valores.",
    ("Sınır Noktası", 10): "Tu energía para poner límites se corona en la carrera y los roles sociales. Tu habilidad para definir los límites sociales es fuerte.",
    ("Sınır Noktası", 11): "Tu energía para poner límites está conectada con la amistad y los grupos. Tu habilidad para definir los límites del entorno social es fuerte.",
    ("Sınır Noktası", 12): "Tu energía para poner límites se nutre de profundidad intuitiva y espiritualidad. Tu habilidad para definir límites intuitivos es fuerte.",

    ("Bağlanma Noktası", 1): "Tu forma de vincular está directamente conectada con tu identidad. Tu estilo de apego es una parte fundamental de tu personalidad.",
    ("Bağlanma Noktası", 2): "Tu forma de vincular se nutre de los valores materiales y las experiencias sensoriales. El contacto físico y el lenguaje de amor concreto están en primer plano.",
    ("Bağlanma Noktası", 3): "Tu forma de vincular está conectada con la comunicación y el entorno. Te vinculas conversando y compartiendo conocimiento.",
    ("Bağlanma Noktası", 4): "Tu forma de vincular tiene un vínculo profundo con las raíces familiares y la vida del hogar. El hogar es el centro de tu vinculación.",
    ("Bağlanma Noktası", 5): "Tu forma de vincular se amasa con la creatividad y los momentos de juego. Te vinculas a través del juego y la alegría.",
    ("Bağlanma Noktası", 6): "Tu forma de vincular está conectada con la rutina diaria y el servicio. Te vinculas a través del servicio y el cuidado.",
    ("Bağlanma Noktası", 7): "Tu forma de vincular es fuerte en el equilibrio y la reciprocidad. El vínculo mutuo y el equilibrio están en primer plano.",
    ("Bağlanma Noktası", 8): "Tu forma de vincular se amasa con la transformación y la profundización. Tienes un estilo de apego profundo e intenso.",
    ("Bağlanma Noktası", 9): "Tu forma de vincular se nutre de la filosofía y la expansión. Te vinculas a través de los valores filosóficos y las creencias compartidas.",
    ("Bağlanma Noktası", 10): "Tu forma de vincular se corona en la carrera y los roles sociales. Te vinculas a través de las responsabilidades sociales.",
    ("Bağlanma Noktası", 11): "Tu forma de vincular está conectada con la amistad y las comunidades. Te vinculas a través de la amistad y los grupos.",
    ("Bağlanma Noktası", 12): "Tu forma de vincular se nutre de profundidad intuitiva y espiritualidad. Estableces vínculos intuitivos y espirituales.",

    ("Sorumluluk", 1): "Tu responsabilidad parental está directamente conectada con tu identidad. La paternidad/maternidad es una parte fundamental de tu ser.",
    ("Sorumluluk", 2): "Tu responsabilidad parental se nutre de los recursos materiales y los valores. Tu sentido de la responsabilidad material es fuerte.",
    ("Sorumluluk", 3): "Tu responsabilidad parental está conectada con la comunicación y el entorno. Cumples tu responsabilidad comunicándote con tu hijo.",
    ("Sorumluluk", 4): "Tu responsabilidad parental tiene un vínculo profundo con las raíces familiares y la vida del hogar. Tu responsabilidad por el hogar es tu valor más fundamental.",
    ("Sorumluluk", 5): "Tu responsabilidad parental se amasa con la creatividad y los momentos de juego. Combinas la responsabilidad con la alegría y la creatividad.",
    ("Sorumluluk", 6): "Tu responsabilidad parental está conectada con la rutina diaria y la salud. Tu responsabilidad por el cuidado y el orden diario es fuerte.",
    ("Sorumluluk", 7): "Tu responsabilidad parental es fuerte en el equilibrio y las relaciones. El equilibrio y la reciprocidad en las relaciones están en primer plano.",
    ("Sorumluluk", 8): "Tu responsabilidad parental se profundiza con la transformación y las crisis. Despliegas un fuerte sentido de la responsabilidad en los momentos de crisis.",
    ("Sorumluluk", 9): "Tu responsabilidad parental se nutre de la filosofía y los valores. Llevas un sentido de la responsabilidad sobre la base de los valores.",
    ("Sorumluluk", 10): "Tu responsabilidad parental se corona en la carrera y los roles sociales. Tu sentido de la responsabilidad social es muy fuerte.",
    ("Sorumluluk", 11): "Tu responsabilidad parental está conectada con la amistad y las comunidades. Llevas un sentido de la responsabilidad social.",
    ("Sorumluluk", 12): "Tu responsabilidad parental se nutre de profundidad intuitiva y espiritualidad. Llevas un sentido de la responsabilidad espiritual.",
}

ARAP_NOKTA_SINASTRI_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", "Baba Noktası"): "Ambos padres llevan una fuerte energía paterna/de autoridad. Dos guías poderosos vibran en la misma frecuencia para tu hijo.",
    ("Baba Noktası", "Anne Noktası"): "¡El encuentro equilibrado de los puntos del padre y de la madre! La autoridad y la ternura crean un equilibrio perfecto para tu hijo.",
    ("Baba Noktası", "Çocuk Ruhu"): "La energía paterna está en profunda armonía con el propósito espiritual de tu hijo. Tu visión parental nutre su desarrollo espiritual.",
    ("Baba Noktası", "Koruma Noktası"): "¡La poderosa alianza de los puntos del padre y de la protección! Se forma un fuerte escudo de protección para tu hijo.",
    ("Baba Noktası", "Eğitim Noktası"): "¡La alianza de sabiduría de los puntos del padre y de la educación! Transmites a tu hijo estructura y conocimiento a la vez.",
    ("Baba Noktası", "Sınır Noktası"): "¡La unión disciplinaria de los puntos del padre y de los límites! Formáis un equipo poderoso que traza límites claros y justos a tu hijo.",
    ("Baba Noktası", "Bağlanma Noktası"): "¡La danza de ternura de los puntos del padre y del vínculo! La autoridad y el amor crean un espacio seguro para tu hijo.",
    ("Baba Noktası", "Sorumluluk"): "¡La poderosa conjunción de los puntos del padre y de la responsabilidad! Tu responsabilidad parental está en su punto culminante.",

    ("Anne Noktası", "Anne Noktası"): "Ambos padres llevan una fuerte energía materna/nutricia. Dos puertos de ternura vibran en la misma frecuencia para tu hijo.",
    ("Anne Noktası", "Çocuk Ruhu"): "La energía materna está en profunda armonía con el propósito espiritual de tu hijo. Tu nutrición emocional apoya su desarrollo espiritual.",
    ("Anne Noktası", "Koruma Noktası"): "¡El escudo tierno de los puntos de la madre y de la protección! Se proporciona a tu hijo tanto protección emocional como física.",
    ("Anne Noktası", "Eğitim Noktası"): "¡La unión de sabiduría de los puntos de la madre y de la educación! La nutrición emocional y la educación crean una armonía perfecta para tu hijo.",
    ("Anne Noktası", "Sınır Noktası"): "¡El encuentro equilibrado de los puntos de la madre y de los límites! La ternura y la disciplina forman una estructura equilibrada para tu hijo.",
    ("Anne Noktası", "Bağlanma Noktası"): "¡La poderosa conjunción de los puntos de la madre y del vínculo! El apego emocional y la nutrición crean un refugio profundo para tu hijo.",
    ("Anne Noktası", "Sorumluluk"): "¡La sagrada unión de los puntos de la madre y de la responsabilidad! La nutrición y la responsabilidad constituyen la base de tu viaje parental.",

    ("Çocuk Ruhu", "Çocuk Ruhu"): "Ambos padres llevan de forma poderosa el propósito espiritual de tu hijo. Dos guías espirituales vibran en la misma frecuencia para tu hijo.",
    ("Çocuk Ruhu", "Koruma Noktası"): "¡La poderosa unión del espíritu del niño y del punto de la protección! El desarrollo espiritual de tu hijo está bajo una fuerte protección.",
    ("Çocuk Ruhu", "Eğitim Noktası"): "¡La alianza de sabiduría del espíritu del niño y del punto de la educación! El propósito espiritual de tu hijo se nutre a través de la educación.",
    ("Çocuk Ruhu", "Sınır Noktası"): "¡El encuentro equilibrado del espíritu del niño y del punto de los límites! El desarrollo espiritual de tu hijo se nutre dentro de la estructura y los límites.",
    ("Çocuk Ruhu", "Bağlanma Noktası"): "¡El profundo vínculo del espíritu del niño y del punto del vínculo! El propósito espiritual de tu hijo se nutre a través del amor y el apego.",
    ("Çocuk Ruhu", "Sorumluluk"): "¡La poderosa conjunción del espíritu del niño y del punto de la responsabilidad! El propósito espiritual de tu hijo se nutre con el sentido de la responsabilidad.",

    ("Koruma Noktası", "Koruma Noktası"): "Ambos padres llevan una fuerte energía de protección. El doble escudo de protección está activo para tu hijo.",
    ("Koruma Noktası", "Eğitim Noktası"): "¡La alianza equilibrada de los puntos de la protección y de la educación! La seguridad y la educación de tu hijo están en perfecta armonía.",
    ("Koruma Noktası", "Sınır Noktası"): "¡La poderosa unión de los puntos de la protección y de los límites! Se forma una estructura de protección fuerte y clara para tu hijo.",
    ("Koruma Noktası", "Bağlanma Noktası"): "¡El escudo tierno de los puntos de la protección y del vínculo! Se crea para tu hijo un espacio seguro y lleno de amor.",
    ("Koruma Noktası", "Sorumluluk"): "¡La poderosa conjunción de los puntos de la protección y de la responsabilidad! El instinto de protección y el sentido de la responsabilidad están en su punto culminante.",

    ("Eğitim Noktası", "Eğitim Noktası"): "Ambos padres llevan una fuerte energía educativa. Dos fuentes de sabiduría vibran en la misma frecuencia para tu hijo.",
    ("Eğitim Noktası", "Sınır Noktası"): "¡El encuentro equilibrado de los puntos de la educación y de los límites! El aprendizaje y la disciplina crean una armonía perfecta para tu hijo.",
    ("Eğitim Noktası", "Bağlanma Noktası"): "¡La tierna unión de los puntos de la educación y del vínculo! La transmisión del conocimiento se nutre con amor.",
    ("Eğitim Noktası", "Sorumluluk"): "¡La poderosa conjunción de los puntos de la educación y de la responsabilidad! La enseñanza y la responsabilidad son la base de tu visión parental.",

    ("Sınır Noktası", "Sınır Noktası"): "Ambos padres llevan una fuerte energía para poner límites. Se establecen límites claros y consistentes para tu hijo.",
    ("Sınır Noktası", "Bağlanma Noktası"): "¡La danza equilibrada de los puntos de los límites y del vínculo! Los límites se nutren con amor y el vínculo con estructura.",
    ("Sınır Noktası", "Sorumluluk"): "¡La poderosa conjunción de los puntos de los límites y de la responsabilidad! La disciplina y la responsabilidad forman una base sólida para tu hijo.",

    ("Bağlanma Noktası", "Bağlanma Noktası"): "Ambos padres llevan una fuerte energía de vinculación. Dos corazones tiernos vibran en la misma frecuencia para tu hijo.",
    ("Bağlanma Noktası", "Sorumluluk"): "¡La sagrada unión de los puntos del vínculo y de la responsabilidad! El amor y la responsabilidad son la base de tu viaje parental.",

    ("Sorumluluk", "Sorumluluk"): "Ambos padres llevan una fuerte energía de responsabilidad. Dos guías con sentido de la responsabilidad vibran en la misma frecuencia para tu hijo.",
}

ARAP_NOKTA_GEZEGEN_SINASTRI_EBEVEYN = {
    ("Baba Noktası", "Güneş"): "La energía paterna está en profunda armonía con la autoconciencia de tu hijo. Tu rol parental será una luz que nutre su brillo.",
    ("Baba Noktası", "Ay"): "La energía paterna está en profunda armonía con el mundo emocional de tu hijo. La autoridad y la ternura crean para él un espacio seguro.",
    ("Baba Noktası", "Merkür"): "La energía paterna está en armonía con el mundo comunicativo de tu hijo. La transmisión del conocimiento y la nutrición mental son la base de este vínculo.",
    ("Baba Noktası", "Venüs"): "La energía paterna está en armonía con el lenguaje de amor de tu hijo. La sensibilidad estética y la ternura nutren este vínculo parental.",
    ("Baba Noktası", "Mars"): "La energía paterna está en profunda armonía con la energía de acción de tu hijo. La protección y el coraje son la sólida base de este vínculo.",
    ("Baba Noktası", "Jüpiter"): "La energía paterna se nutre con la energía de expansión de tu hijo. La sabiduría y la guía enriquecen este viaje parental.",
    ("Baba Noktası", "Satürn"): "La energía paterna está en profunda armonía con la energía estructural de tu hijo. La responsabilidad y la disciplina forman el esqueleto de este vínculo.",

    ("Anne Noktası", "Güneş"): "La energía materna está en profunda armonía con la autoconciencia de tu hijo. La nutrición y la protección serán un sol que alimenta su brillo.",
    ("Anne Noktası", "Ay"): "La energía materna danza a la perfección con el mundo emocional de tu hijo. La nutrición emocional y la protección son el alma de este vínculo.",
    ("Anne Noktası", "Merkür"): "La energía materna está en armonía con el mundo comunicativo de tu hijo. La expresión y la comprensión fortalecen este vínculo materno-infantil.",
    ("Anne Noktası", "Venüs"): "La energía materna crea una profunda armonía en el lenguaje de amor de tu hijo. La ternura, la belleza y la estética nutren este vínculo materno.",
    ("Anne Noktası", "Mars"): "La energía materna está en profunda armonía con la energía de acción de tu hijo. El instinto de protección y el coraje nutren este vínculo materno.",
    ("Anne Noktası", "Jüpiter"): "La energía materna se nutre con la energía de expansión de tu hijo. La sabiduría y la ternura enriquecen este viaje materno-infantil.",
    ("Anne Noktası", "Satürn"): "La energía materna está en profunda armonía con la energía estructural de tu hijo. La responsabilidad y la estructura forman la base de este vínculo materno.",

    ("Çocuk Ruhu", "Güneş"): "El propósito espiritual de tu hijo está en profunda armonía con su autoconciencia. Su viaje vital es brillante y significativo.",
    ("Çocuk Ruhu", "Ay"): "El propósito espiritual de tu hijo está en profunda armonía con su mundo emocional. Su inteligencia emocional y sus intuiciones son muy poderosas.",
    ("Çocuk Ruhu", "Merkür"): "El propósito espiritual de tu hijo está en armonía con su mundo comunicativo. Sus capacidades mentales y su capacidad de aprendizaje son muy elevadas.",
    ("Çocuk Ruhu", "Venüs"): "El propósito espiritual de tu hijo crea una profunda armonía en su lenguaje de amor. Sus talentos artísticos y su sensibilidad estética son muy fuertes.",
    ("Çocuk Ruhu", "Mars"): "El propósito espiritual de tu hijo está en profunda armonía con su energía de acción. Su coraje y su capacidad de acción son muy poderosos.",
    ("Çocuk Ruhu", "Jüpiter"): "El propósito espiritual de tu hijo está en perfecta armonía con su energía de expansión. La sabiduría y la abundancia iluminan su camino.",
    ("Çocuk Ruhu", "Satürn"): "El propósito espiritual de tu hijo está en profunda armonía con su energía estructural. Su disciplina y su sentido de la responsabilidad son muy fuertes.",

    ("Koruma Noktası", "Güneş"): "Tu energía de protección está en profunda armonía con la autoconciencia de tu hijo. Te conviertes en un poderoso escudo que protege su brillo.",
    ("Koruma Noktası", "Ay"): "Tu energía de protección está en profunda armonía con el mundo emocional de tu hijo. La protección y la nutrición emocional son la base de este vínculo.",
    ("Koruma Noktası", "Merkür"): "Tu energía de protección está en armonía con el mundo comunicativo de tu hijo. Proporcionas protección a través del conocimiento y la comunicación.",
    ("Koruma Noktası", "Venüs"): "Tu energía de protección crea una profunda armonía en el lenguaje de amor de tu hijo. El amor y la protección nutren este vínculo parental.",
    ("Koruma Noktası", "Mars"): "Tu energía de protección está en perfecta armonía con la energía de acción de tu hijo. El coraje y el instinto de protección están en su punto culminante.",
    ("Koruma Noktası", "Jüpiter"): "Tu energía de protección se nutre con la energía de expansión de tu hijo. La protección y la sabiduría trabajan juntas.",
    ("Koruma Noktası", "Satürn"): "Tu energía de protección está en profunda armonía con la energía estructural de tu hijo. La estructura y la protección forman una base segura para tu hijo.",

    ("Eğitim Noktası", "Güneş"): "Tu energía educativa está en profunda armonía con la autoconciencia de tu hijo. Te conviertes en un maestro que nutre su brillo.",
    ("Eğitim Noktası", "Ay"): "Tu energía educativa está en profunda armonía con el mundo emocional de tu hijo. La educación de la inteligencia emocional y la empatía es la base de este vínculo.",
    ("Eğitim Noktası", "Merkür"): "Tu energía educativa está en perfecta armonía con el mundo comunicativo de tu hijo. La nutrición mental y la transmisión del conocimiento están en su punto culminante.",
    ("Eğitim Noktası", "Venüs"): "Tu energía educativa crea una profunda armonía en el lenguaje de amor de tu hijo. El aprendizaje con amor y la educación estética son el alma de este vínculo.",
    ("Eğitim Noktası", "Mars"): "Tu energía educativa está en profunda armonía con la energía de acción de tu hijo. El aprendizaje a través de la acción y la educación del coraje están en primer plano.",
    ("Eğitim Noktası", "Jüpiter"): "Tu energía educativa está en perfecta armonía con la energía de expansión de tu hijo. La sabiduría y la educación enriquecen este viaje parental.",
    ("Eğitim Noktası", "Satürn"): "Tu energía educativa está en profunda armonía con la energía estructural de tu hijo. La estructura y la educación disciplinada forman la base de este vínculo.",

    ("Sınır Noktası", "Güneş"): "Tu energía para poner límites está en profunda armonía con la autoconciencia de tu hijo. Trazas límites que respetan su individualidad.",
    ("Sınır Noktası", "Ay"): "Tu energía para poner límites está en profunda armonía con el mundo emocional de tu hijo. Los límites emocionales y la seguridad son la base de este vínculo.",
    ("Sınır Noktası", "Merkür"): "Tu energía para poner límites está en armonía con el mundo comunicativo de tu hijo. Trazas límites comunicativos de forma clara.",
    ("Sınır Noktası", "Venüs"): "Tu energía para poner límites crea una profunda armonía en el lenguaje de amor de tu hijo. Poner límites con amor nutre este vínculo parental.",
    ("Sınır Noktası", "Mars"): "Tu energía para poner límites está en profunda armonía con la energía de acción de tu hijo. Trazas límites decididos y claros.",
    ("Sınır Noktası", "Jüpiter"): "Tu energía para poner límites se nutre con la energía de expansión de tu hijo. Trazas límites con una amplia perspectiva.",
    ("Sınır Noktası", "Satürn"): "Tu energía para poner límites está en perfecta armonía con la energía estructural de tu hijo. La estructura y la disciplina forman la base de tus límites.",

    ("Bağlanma Noktası", "Güneş"): "Tu energía de vinculación está en profunda armonía con la autoconciencia de tu hijo. Estableces un vínculo profundo con su ser.",
    ("Bağlanma Noktası", "Ay"): "Tu energía de vinculación danza a la perfección con el mundo emocional de tu hijo. El apego emocional y la nutrición son el alma de este vínculo.",
    ("Bağlanma Noktası", "Merkür"): "Tu energía de vinculación está en armonía con el mundo comunicativo de tu hijo. Estableces un vínculo profundo a través de la comunicación y el intercambio de conocimiento.",
    ("Bağlanma Noktası", "Venüs"): "Tu energía de vinculación crea una profunda armonía en el lenguaje de amor de tu hijo. El amor, la ternura y la estética nutren este vínculo.",
    ("Bağlanma Noktası", "Mars"): "Tu energía de vinculación está en profunda armonía con la energía de acción de tu hijo. Te vinculas a través de la acción y el coraje.",
    ("Bağlanma Noktası", "Jüpiter"): "Tu energía de vinculación se nutre con la energía de expansión de tu hijo. La sabiduría y la amplia perspectiva enriquecen este vínculo.",
    ("Bağlanma Noktası", "Satürn"): "Tu energía de vinculación está en profunda armonía con la energía estructural de tu hijo. La estructura y la responsabilidad forman la base de este vínculo.",

    ("Sorumluluk", "Güneş"): "Tu energía de responsabilidad está en profunda armonía con la autoconciencia de tu hijo. Llevas responsabilidades que respetan su individualidad.",
    ("Sorumluluk", "Ay"): "Tu energía de responsabilidad está en profunda armonía con el mundo emocional de tu hijo. La responsabilidad emocional y la nutrición son la base de este vínculo.",
    ("Sorumluluk", "Merkür"): "Tu energía de responsabilidad está en armonía con el mundo comunicativo de tu hijo. Llevas la responsabilidad a través de la comunicación y el intercambio de conocimiento.",
    ("Sorumluluk", "Venüs"): "Tu energía de responsabilidad crea una profunda armonía en el lenguaje de amor de tu hijo. El amor y la responsabilidad nutren este vínculo parental.",
    ("Sorumluluk", "Mars"): "Tu energía de responsabilidad está en profunda armonía con la energía de acción de tu hijo. El coraje y la responsabilidad son la sólida base de este vínculo.",
    ("Sorumluluk", "Jüpiter"): "Tu energía de responsabilidad se nutre con la energía de expansión de tu hijo. La sabiduría y la responsabilidad enriquecen este viaje parental.",
    ("Sorumluluk", "Satürn"): "Tu energía de responsabilidad está en perfecta armonía con la energía estructural de tu hijo. La estructura y la responsabilidad forman la base de este vínculo.",
}

ARAP_EBEVEYN_NOKTA_ADLARI_ES = {
    "Baba Noktası": "Punto del Padre",
    "Anne Noktası": "Punto de la Madre",
    "Çocuk Ruhu": "Alma del Niño",
    "Koruma Noktası": "Punto de Protección",
    "Eğitim Noktası": "Punto de Educación",
    "Sınır Noktası": "Punto del Límite",
    "Bağlanma Noktası": "Punto de Vínculo",
    "Sorumluluk": "Responsabilidad",
}
