# -*- coding: utf-8 -*-
# English variant of ARAP_EBEVEYN_DICTS.py (parent-child mode).
# Keys are kept identical to the Turkish file; only values are translated to English.

ARAP_NOKTALARI_EBEVEYN = {
    "Baba Noktası":     {"nokta1": "10HC", "nokta2": "Güneş", "kisa": "BABA", "aciklama": "Father figure, authority and discipline energy"},
    "Anne Noktası":     {"nokta1": "4HC",  "nokta2": "Ay",     "kisa": "ANNE", "aciklama": "Mother figure, nurturing and emotional protection"},
    "Çocuk Ruhu":       {"nokta1": "5HC",  "nokta2": "Jüpiter","kisa": "ÇRUH", "aciklama": "The child's spiritual purpose and creative potential"},
    "Koruma Noktası":   {"nokta1": "2HC",  "nokta2": "Mars",   "kisa": "KORU", "aciklama": "Physical and material protection energy"},
    "Eğitim Noktası":   {"nokta1": "9HC",  "nokta2": "Merkür", "kisa": "EĞİT", "aciklama": "Teaching-learning and philosophical transmission"},
    "Sınır Noktası":    {"nokta1": "6HC",  "nokta2": "Satürn", "kisa": "SINR", "aciklama": "Discipline, boundary setting and daily routine"},
    "Bağlanma Noktası": {"nokta1": "4HC",  "nokta2": "Venüs",  "kisa": "BAGL", "aciklama": "Emotional attachment style and the language of affection"},
    "Sorumluluk":       {"nokta1": "10HC", "nokta2": "Satürn", "kisa": "SORU", "aciklama": "Parenting responsibility and social role"},
}

ARAP_EBEVEYN_NOKTA_ADLARI_EN = {
    "Baba Noktası": "Father Point",
    "Anne Noktası": "Mother Point",
    "Çocuk Ruhu": "Child Soul",
    "Koruma Noktası": "Protection Point",
    "Eğitim Noktası": "Education Point",
    "Sınır Noktası": "Boundary Point",
    "Bağlanma Noktası": "Attachment Point",
    "Sorumluluk": "Responsibility",
}

ARAP_NOKTA_BURC_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", "Koç"): "Your father-energy karma is blended with a bold, pioneering and independent spirit. For your child you embody a father/mother figure who stands firm against the world and takes initiative.",
    ("Baba Noktası", "Boğa"): "Your father-energy karma is built on earth, reliability and permanence. You become an unshakable protector who provides your child material and spiritual security.",
    ("Baba Noktası", "İkizler"): "Your father-energy karma is built on communication, mental harmony and versatility. You become a parent who grows by talking, learning and sharing with your child.",
    ("Baba Noktası", "Yengeç"): "Your father-energy karma is kneaded with deep emotional nurturing and the protective instinct. You build an unshakable emotional refuge for your child.",
    ("Baba Noktası", "Aslan"): "Your father-energy karma is built on grandeur, creativity and generosity. You become a guide who makes your child's talents shine and takes pride in them.",
    ("Baba Noktası", "Başak"): "Your father-energy karma is built on service, the pursuit of excellence and practical order. You build a system that carefully meets every need of your child.",
    ("Baba Noktası", "Terazi"): "Your father-energy karma is built on harmony, aesthetics and balance. You become an elegant guide who builds a fair and balanced relationship with your child.",
    ("Baba Noktası", "Akrep"): "Your father-energy karma is kneaded with deep transformation, intensity and mystery. You project a father/mother energy that stays vigilant against every danger for your child.",
    ("Baba Noktası", "Yay"): "Your father-energy karma is built on freedom, expansion and philosophical depth. You become a guide who instills a broad vision in your child and explores life together.",
    ("Baba Noktası", "Oğlak"): "Your father-energy karma is built on structure, responsibility and long-term plans. You become a parent who gives your child discipline and structure and prepares them for life.",
    ("Baba Noktası", "Kova"): "Your father-energy karma is blended with an unconventional, free and revolutionary spirit. You become a guide who does not put your child in a mold and respects their individuality.",
    ("Baba Noktası", "Balık"): "Your father-energy karma is built on spirituality, sacrifice and intuitive depth. You become a parent who connects spiritually with your child and focuses on their spiritual growth.",

    ("Anne Noktası", "Koç"): "Your mother-energy karma is kneaded with a bold, initiative-taking and protective spirit. You project a mother figure who defies the world and does everything to protect your child.",
    ("Anne Noktası", "Boğa"): "Your mother-energy karma is built on earth, nurturing and permanence. You become a guide who nourishes your child physically and emotionally and builds a safe home.",
    ("Anne Noktası", "İkizler"): "Your mother-energy karma is built on communication, joy and curiosity. You become a playful parent who shares knowledge and explores everything with your child.",
    ("Anne Noktası", "Yengeç"): "Your mother-energy karma is kneaded with deep emotional nurturing and the protective instinct. For your child you are an unshakable emotional harbor and a warm embrace.",
    ("Anne Noktası", "Aslan"): "Your mother-energy karma is built with grandeur, generosity and a loving heart. You become a mother figure who puts your child's radiance on stage and takes pride in them.",
    ("Anne Noktası", "Başak"): "Your mother-energy karma is built on meticulousness, service and practical excellence. You build an order that flawlessly meets your child's health, nutrition and care needs.",
    ("Anne Noktası", "Terazi"): "Your mother-energy karma is built on grace, harmony and balance. You become a guide who builds a fair and balanced relationship with your child, carrying aesthetic sensitivity.",
    ("Anne Noktası", "Akrep"): "Your mother-energy karma is kneaded with deep intensity, transformation and protectiveness. You become a mother figure with deep intuition, alert against every danger for your child.",
    ("Anne Noktası", "Yay"): "Your mother-energy karma is fed by freedom, optimism and the desire for adventure. You become a guide who opens a wide horizon for your child and learns life together.",
    ("Anne Noktası", "Oğlak"): "Your mother-energy karma is built on structure, responsibility and patience. You become a mother figure who sets boundaries and gives discipline for your child, yet never spares your love.",
    ("Anne Noktası", "Kova"): "Your mother-energy karma is blended with an unconventional, free and humane spirit. You become a guide who respects your child's individuality and does not put them in a mold.",
    ("Anne Noktası", "Balık"): "Your mother-energy karma is built on intuitive depth, compassion and unconditional love. You become a parent who bonds with your child at a telepathic level and nourishes their spiritual world",

    ("Çocuk Ruhu", "Koç"): "Your child's spiritual purpose carries a bold, independent and pioneering energy. They came into the world with a soul that opens its own path, takes initiative and carries leadership qualities.",
    ("Çocuk Ruhu", "Boğa"): "Your child's spiritual purpose is built on earth, beauty and permanence. They carry a potential for artistic sensitivity, sensory pleasure and creating tangible values.",
    ("Çocuk Ruhu", "İkizler"): "Your child's spiritual purpose is built on communication, curiosity and versatility. They carry a mind that processes, shares and connects knowledge with the world.",
    ("Çocuk Ruhu", "Yengeç"): "Your child's spiritual purpose is kneaded with emotional depth, protectiveness and a sense of belonging. They carry a compassionate soul deeply bound to family and loved ones.",
    ("Çocuk Ruhu", "Aslan"): "Your child's spiritual purpose is built on creativity, generosity and radiant self-joy. They are a soul that shines with artistic talent, stage energy and a generous heart.",
    ("Çocuk Ruhu", "Başak"): "Your child's spiritual purpose is built on meticulousness, service and practical excellence. They stand out with a detail-oriented mind, a sense of helpfulness and a skill for creating order.",
    ("Çocuk Ruhu", "Terazi"): "Your child's spiritual purpose is built on balance, aesthetics and harmony. They are a soul carrying a sense of justice, artistic sensitivity and potential for balance in relationships.",
    ("Çocuk Ruhu", "Akrep"): "Your child's spiritual purpose is kneaded with deep transformation, intensity and mystery. They are a soul with a deep inner world, strong intuition, who experiences life in all its aspects.",
    ("Çocuk Ruhu", "Yay"): "Your child's spiritual purpose is built on freedom, discovery and philosophical expansion. They are a broad soul carrying different cultures, the search for wisdom and a passion for adventure.",
    ("Çocuk Ruhu", "Oğlak"): "Your child's spiritual purpose is built on structure, responsibility and long-term goals. They are a soul with early maturity, discipline and patience to reach their goals.",
    ("Çocuk Ruhu", "Kova"): "Your child's spiritual purpose is built on originality, humanitarianism and a visionary perspective. They are a soul that thinks beyond the ordinary, contributes to society and designs the future.",
    ("Çocuk Ruhu", "Balık"): "Your child's spiritual purpose is kneaded with spirituality, compassion and intuitive depth. They stand out with artistic talents, a sense of mercy and spiritual perceptions.",

("Koruma Noktası", "Koç"): "Your protection energy is kneaded in a bold, direct and action-oriented way. You become a brave shield that stands against the world when needed to protect your child.",
    ("Koruma Noktası", "Boğa"): "Your protection energy is built in an earthy, tangible and lasting way. You become an unshakable source of assurance that provides your child material and physical security.",
    ("Koruma Noktası", "İkizler"): "Your protection energy is built on communication, knowledge and mental agility. You become a protector who nourishes your child mentally and passes knowledge on as a tool.",
    ("Koruma Noktası", "Yengeç"): "Your protection energy is kneaded with deep emotional bonding and maternal instinct. You become an unshakable emotional shield and a warm refuge for your child.",
    ("Koruma Noktası", "Aslan"): "Your protection energy is built in a grand, generous and honorable way. You become a parent who protects your child's radiance and fights with pride for them.",
    ("Koruma Noktası", "Başak"): "Your protection energy works in a meticulous, practical and detail-oriented way. You build a protection system that flawlessly meets your child's health, nutrition and daily needs.",
    ("Koruma Noktası", "Terazi"): "Your protection energy is built in a balanced, graceful and fair way. You become a balanced guide who creates a fair protective field for your child.",
    ("Koruma Noktası", "Akrep"): "Your protection energy works in a deep, intense and occult way. You become a powerful shield that stays intuitively alert against every danger for your child.",
    ("Koruma Noktası", "Yay"): "Your protection energy is built in an expansive, optimistic and philosophical way. You become a guide who protects your child from a broad perspective and instills a worldview.",
    ("Koruma Noktası", "Oğlak"): "Your protection energy is kneaded with structure, discipline and a sense of responsibility. You become a guide who protects your child by setting structure and boundaries, building a long-term security system.",
    ("Koruma Noktası", "Kova"): "Your protection energy is built in an unconventional, free and social way. You become a guide who protects your child outside of the mold and nourishes them with social consciousness.",
    ("Koruma Noktası", "Balık"): "Your protection energy works in an intuitive, spiritual and unconditional way. You become a guide who senses your child intuitively and protects them on a spiritual level.",

    ("Eğitim Noktası", "Koç"): "Your education energy is built in a bold, pioneering and action-oriented way. You thrive with excitement while teaching your child initiative, courage and leadership skills.",
    ("Eğitim Noktası", "Boğa"): "Your education energy works in a concrete, practical and sensory way. You discover ways to teach your child through art, nature and tangible experiences.",
    ("Eğitim Noktası", "İkizler"): "Your education energy is built on communication, curiosity and versatility. You find ways to share knowledge with your child and make every subject fun.",
    ("Eğitim Noktası", "Yengeç"): "Your education energy is kneaded with emotional nurturing and the protective instinct. You are nourished while passing emotional intelligence, empathy and family values to your child.",
    ("Eğitim Noktası", "Aslan"): "Your education energy is built in a creative, generous and stage-focused way. You open space for your child to develop their artistic talents and express themselves.",
    ("Eğitim Noktası", "Başak"): "Your education energy works in a meticulous, systematic and excellence-oriented way. You build a flawless system while teaching your child order, attention to detail and practical skills.",
    ("Eğitim Noktası", "Terazi"): "Your education energy is built in a balanced, aesthetic and harmonious way. You draw an elegant path while teaching your child justice, art and balance in relationships.",
    ("Eğitim Noktası", "Akrep"): "Your education energy works in a deep, intense and transformative way. You teach your child to explore the depths of the inner world, transformation and the rightful use of power.",
    ("Eğitim Noktası", "Yay"): "Your education energy is built in an expansive, philosophical and adventurous way. You instill different cultures, philosophy and a broad life perspective in your child.",
    ("Eğitim Noktası", "Oğlak"): "Your education energy works in a structural, responsibility-oriented and patient way. You are nourished while passing goal-setting, patience and long-term planning skills to your child.",
    ("Eğitim Noktası", "Kova"): "Your education energy is built in an unconventional, innovative and social way. You pass the skills of the future, technology and social sensitivity to your child.",
    ("Eğitim Noktası", "Balık"): "Your education energy works in an intuitive, artistic and spiritual way. You are nourished while passing imagination, artistic sensitivity and spiritual wisdom to your child.",

    ("Sınır Noktası", "Koç"): "Your boundary-setting energy is built in a bold, clear and direct way. You become a guide who draws clear and sharp boundaries for your child and stands firm when needed.",
    ("Sınır Noktası", "Boğa"): "Your boundary-setting energy works in an earthy, patient and lasting way. You become a guide who sets boundaries patiently and offers a steady, reliable structure.",
    ("Sınır Noktası", "İkizler"): "Your boundary-setting energy is built on communication, flexibility and mental agility. You become an explanatory, informative guide who sets boundaries by talking with your child.",
    ("Sınır Noktası", "Yengeç"): "Your boundary-setting energy is kneaded with emotional depth and the protective instinct. The boundaries you set to protect your child are nourished by love and compassion.",
    ("Sınır Noktası", "Aslan"): "Your boundary-setting energy is built in a grand, honorable and authoritative way. You become a guide who draws clear, respected boundaries and blends authority with love.",
    ("Sınır Noktası", "Başak"): "Your boundary-setting energy works in a meticulous, systematic and orderly way. You become a guide offering your child rules, routines and a detailed life structure.",
    ("Sınır Noktası", "Terazi"): "Your boundary-setting energy is built in a balanced, fair and graceful way. You become a guide who sets fair boundaries with your child and is open to negotiation.",
    ("Sınır Noktası", "Akrep"): "Your boundary-setting energy works in a deep, sharp and transformative way. You become a guide who draws sharp boundaries but also conveys the deep love behind them.",
    ("Sınır Noktası", "Yay"): "Your boundary-setting energy is built in an expansive, flexible and philosophical way. You become a guide who draws flexible boundaries and teaches the balance of freedom and responsibility.",
    ("Sınır Noktası", "Oğlak"): "Your boundary-setting energy works in a structural, disciplined and firm way. You become a guide who draws firm but fair boundaries and gives structure and order.",
    ("Sınır Noktası", "Kova"): "Your boundary-setting energy is built in an unconventional, flexible and social way. You become a guide who draws non-traditional yet functional boundaries.",
    ("Sınır Noktası", "Balık"): "Your boundary-setting energy works in an intuitive, flexible and emotional way. You offer intuitive guidance while teaching emotional boundaries to your child.",

    ("Bağlanma Noktası", "Koç"): "Your attachment style is built in a bold, independent and action-oriented way. You build a spirited yet loving bond with your child and nourish them with courage.",
    ("Bağlanma Noktası", "Boğa"): "Your attachment style works in an earthy, sensory and lasting way. You build a deep bond with your child through physical contact, touch and concrete love languages.",
    ("Bağlanma Noktası", "İkizler"): "Your attachment style is built on communication, joy and mental harmony. You build a delightful bond by talking, playing and sharing knowledge with your child.",
    ("Bağlanma Noktası", "Yengeç"): "Your attachment style is kneaded with deep emotional nurturing and the protective instinct. You build a bond as warm as a mother's lap, an unshakable emotional tie with your child.",
    ("Bağlanma Noktası", "Aslan"): "Your attachment style is built in a grand, generous and loving way. You build a bond that puts your child on stage, takes pride in them and shows your love generously.",
    ("Bağlanma Noktası", "Başak"): "Your attachment style works in a practical, service-oriented and orderly way. You build a deep bond through service, flawlessly meeting your child's every need.",
    ("Bağlanma Noktası", "Terazi"): "Your attachment style is built in a balanced, graceful and harmonious way. You build a deep bond with your child through balance, justice and aesthetic sensitivity.",
    ("Bağlanma Noktası", "Akrep"): "Your attachment style works in a deep, intense and transformative way. You build a very deep, nearly spiritual bond with your child. Intensity is the foundation of this bond.",
    ("Bağlanma Noktası", "Yay"): "Your attachment style is built in an expansive, cheerful and adventurous way. You bond with freedom and joy while discovering life together with your child.",
    ("Bağlanma Noktası", "Oğlak"): "Your attachment style works with structure, a sense of responsibility and patience. You build a long-term bond by giving your child structure, order and trust.",
    ("Bağlanma Noktası", "Kova"): "Your attachment style is built in an unconventional, free and friendly way. You build a friendly, egalitarian and innovative bond with your child.",
    ("Bağlanma Noktası", "Balık"): "Your attachment style works in an intuitive, unconditional and spiritual way. You build a deep bond with your child at a telepathic level, nourished by unconditional love.",

    ("Sorumluluk", "Koç"): "Your parenting responsibility is built in a bold, initiative-taking and action-oriented way. You become a guide who defies the world for your child and carries responsibility with courage.",
    ("Sorumluluk", "Boğa"): "Your parenting responsibility works in an earthy, reliable and lasting way. You act with long-term responsibility, providing your child material and spiritual assurance.",
    ("Sorumluluk", "İkizler"): "Your parenting responsibility is built on communication, flexibility and mental agility. You fulfill your responsibility by communicating and sharing knowledge with your child.",
    ("Sorumluluk", "Yengeç"): "Your parenting responsibility is kneaded with deep emotional nurturing and the protective instinct. You become a guide who sacrifices everything for your child and carries responsibility with love.",
    ("Sorumluluk", "Aslan"): "Your parenting responsibility is built in a grand, generous and honorable way. You become a guide who lets your child's talents flourish and carries responsibility with pride.",
    ("Sorumluluk", "Başak"): "Your parenting responsibility works in a meticulous, practical and excellence-oriented way. You become a guide who meets every need of your child in detail and fulfills responsibility flawlessly.",
    ("Sorumluluk", "Terazi"): "Your parenting responsibility is built in a balanced, fair and graceful way. You become a guide who builds a fair relationship and shares responsibility in a balanced way.",
    ("Sorumluluk", "Akrep"): "Your parenting responsibility works in a deep, intense and transformative way. You become a guide who makes every sacrifice for your child and carries responsibility with deep determination.",
    ("Sorumluluk", "Yay"): "Your parenting responsibility is built in an expansive, philosophical and adventurous way. You become a guide who instills a broad life perspective and carries responsibility with joy.",
    ("Sorumluluk", "Oğlak"): "Your parenting responsibility works in a structural, disciplined and firm way. You become a guide who approaches your child with structure, order and seriousness and carries responsibility meticulously.",
    ("Sorumluluk", "Kova"): "Your parenting responsibility is built in an unconventional, innovative and social way. You become a guide who instills social consciousness and carries responsibility toward the future.",
    ("Sorumluluk", "Balık"): "Your parenting responsibility works in an intuitive, spiritual and unconditional way. You become a guide focused on your child's spiritual growth, carrying responsibility with love and intuition.",
}

ARAP_NOKTA_EV_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", 1): "Your father energy is directly connected to your identity. Your parenting role is at the center of your life.",
    ("Baba Noktası", 2): "Your father energy is nourished by material security and values. You build a concrete foundation for your child.",
    ("Baba Noktası", 3): "Your father energy is connected to communication and your surroundings. Sharing knowledge and experience with your child takes the foreground.",
    ("Baba Noktası", 4): "Your father energy has a deep bond with family roots and home life. Building a home is the foundation of this energy.",
    ("Baba Noktası", 5): "Your father energy is kneaded with creativity and the world of children. Play and joy are the nourishment of this energy.",
    ("Baba Noktası", 6): "Your father energy is connected to daily care and health. Practical support and order are the foundation of this energy.",
    ("Baba Noktası", 7): "Your father energy is strong in the field of balance and reflection. The search for balance in your parenting roles takes the foreground.",
    ("Baba Noktası", 8): "Your father energy deepens with transformation and crises. You become a strong protector in hard times.",
    ("Baba Noktası", 9): "Your father energy is nourished by philosophy and education. You pass values and wisdom to your child.",
    ("Baba Noktası", 10): "Your father energy is crowned in career and social role. You become a strong father/mother figure in the eyes of society.",
    ("Baba Noktası", 11): "Your father energy is connected to friendship and groups. You take an active role in your child's social world.",
    ("Baba Noktası", 12): "Your father energy deepens with the subconscious and spirituality. You carry an intuitive father/mother wisdom.",

    ("Anne Noktası", 1): "Your mother energy is directly connected to your identity. Your parenting role forms the foundation of your personality.",
    ("Anne Noktası", 2): "Your mother energy is nourished by material security and nurturing. You offer your child physical and emotional healing.",
    ("Anne Noktası", 3): "Your mother energy is connected to communication and your surroundings. You become a guide who is in constant communication with your child.",
    ("Anne Noktası", 4): "Your mother energy has a deep bond with family roots and home life. Building a home is the heart of this energy.",
    ("Anne Noktası", 5): "Your mother energy is kneaded with creativity and playtime. You share creative moments with your child.",
    ("Anne Noktası", 6): "Your mother energy is connected to daily care and health. You meet your child's routine needs flawlessly.",
    ("Anne Noktası", 7): "Your mother energy is strong in balance and reciprocity. You build a balanced relationship with your child.",
    ("Anne Noktası", 8): "Your mother energy is kneaded with transformation and deepening. You become a strong healer at times of crisis.",
    ("Anne Noktası", 9): "Your mother energy is nourished by philosophy and education. You instill a broad life perspective in your child.",
    ("Anne Noktası", 10): "Your mother energy is crowned in the social role. You become a respected mother figure in the eyes of society.",
    ("Anne Noktası", 11): "Your mother energy is connected to hopes and groups. You become a guide who supports your child's dreams.",
    ("Anne Noktası", 12): "Your mother energy is nourished by intuitive depth and spirituality. You build a mother bond at a telepathic level.",

    ("Çocuk Ruhu", 1): "Your child's spiritual purpose is directly connected to their identity. The journey of self-discovery takes the foreground.",
    ("Çocuk Ruhu", 2): "Your child's spiritual purpose is nourished by material values and concrete experiences. Their artistic and sensory potential is high.",
    ("Çocuk Ruhu", 3): "Your child's spiritual purpose is connected to communication and their surroundings. Their ability to share knowledge and connect with the world stands out.",
    ("Çocuk Ruhu", 4): "Your child's spiritual purpose has a deep bond with family roots and home life. Family ties are sacred to them.",
    ("Çocuk Ruhu", 5): "Your child's spiritual purpose is kneaded with creativity and self-expression. Their artistic talents and play energy are high.",
    ("Çocuk Ruhu", 6): "Your child's spiritual purpose is connected to daily order and service. Their practical skills and sense of helpfulness stand out.",
    ("Çocuk Ruhu", 7): "Your child's spiritual purpose deepens with relationships and balance. Their potential to create balance and harmony in relationships is high.",
    ("Çocuk Ruhu", 8): "Your child's spiritual purpose is kneaded with transformation and deepening. They carry strong transformative potential in their inner world.",
    ("Çocuk Ruhu", 9): "Your child's spiritual purpose is nourished by philosophy and expansion. Different cultures and the search for wisdom nourish them.",
    ("Çocuk Ruhu", 10): "Your child's spiritual purpose is crowned in career and social role. They work with discipline to reach their goals.",
    ("Çocuk Ruhu", 11): "Your child's spiritual purpose is connected to friendship and communities. Their social circle is wide and supportive.",
    ("Çocuk Ruhu", 12): "Your child's spiritual purpose is nourished by intuitive depth and spirituality. They carry high intuitive powers and imagination.",

    ("Koruma Noktası", 1): "Your protection energy is directly connected to your identity. Your instinct to protect yourself and your child is very strong.",
    ("Koruma Noktası", 2): "Your protection energy is nourished by material security and values. You are determined to meet your child's material needs.",
    ("Koruma Noktası", 3): "Your protection energy is connected to communication and your surroundings. You protect your child from those around them in an informative way.",
    ("Koruma Noktası", 4): "Your protection energy has a deep bond with family roots and home life. For you, home is the center of protection.",
    ("Koruma Noktası", 5): "Your protection energy is kneaded with creativity and playtime. You ensure your child's creative safety.",
    ("Koruma Noktası", 6): "Your protection energy is connected to daily care and health. You are meticulous in protecting your child's physical health.",
    ("Koruma Noktası", 7): "Your protection energy is strong in balance and relationships. You protect your child in a balanced and fair way.",
    ("Koruma Noktası", 8): "Your protection energy deepens with transformation and crises. You become a strong protective shield in hard times.",
    ("Koruma Noktası", 9): "Your protection energy is nourished by philosophy and values. You protect your child with your values and beliefs.",
    ("Koruma Noktası", 10): "Your protection energy is crowned in career and social roles. You use your social status as your protection energy.",
    ("Koruma Noktası", 11): "Your protection energy is connected to friendship and groups. You place your child's social circle under protection.",
    ("Koruma Noktası", 12): "Your protection energy is nourished by intuitive depth and spirituality. You intuitively protect your child against dangers.",

    ("Eğitim Noktası", 1): "Your education energy is directly connected to your identity. Your teaching role forms the foundation of your personality.",
    ("Eğitim Noktası", 2): "Your education energy is nourished by material resources and concrete experiences. You are an expert at teaching practical skills.",
    ("Eğitim Noktası", 3): "Your education energy is connected to communication and your surroundings. You constantly share knowledge with your child.",
    ("Eğitim Noktası", 4): "Your education energy has a deep bond with family roots and home life. Education within the family is the foundation of this energy.",
    ("Eğitim Noktası", 5): "Your education energy is kneaded with creativity and playtime. Your ability to teach through play is very strong.",
    ("Eğitim Noktası", 6): "Your education energy is connected to daily routine and practical order. You create constant teaching opportunities in daily life.",
    ("Eğitim Noktası", 7): "Your education energy is strong in balance and reciprocity. Mutual learning and teaching find their balance.",
    ("Eğitim Noktası", 8): "Your education energy is kneaded with transformation and deepening. You teach learning through difficult experiences.",
    ("Eğitim Noktası", 9): "Your education energy is nourished by philosophy and expansion. You pass on different cultures and philosophical perspectives.",
    ("Eğitim Noktası", 10): "Your education energy is crowned in career and social roles. Educational goals and long-term plans take the foreground.",
    ("Eğitim Noktası", 11): "Your education energy is connected to friendship and communities. You share teaching and learning within your social circle.",
    ("Eğitim Noktası", 12): "Your education energy is nourished by intuitive depth and spirituality. You pass on spiritual and intuitive knowledge.",

    ("Sınır Noktası", 1): "Your boundary-setting energy is directly connected to your identity. Boundaries are a fundamental part of your personality.",
    ("Sınır Noktası", 2): "Your boundary-setting energy is nourished by material values and resources. You set clear boundaries in material matters.",
    ("Sınır Noktası", 3): "Your boundary-setting energy is connected to communication and your surroundings. Your ability to define communication boundaries is strong.",
    ("Sınır Noktası", 4): "Your boundary-setting energy has a deep bond with family roots and home life. Boundaries within the home are the foundation of this energy.",
    ("Sınır Noktası", 5): "Your boundary-setting energy is kneaded with creativity and playtime. Your ability to set play boundaries is strong.",
    ("Sınır Noktası", 6): "Your boundary-setting energy is connected to daily routine and health. You are an expert at daily order and setting boundaries.",
    ("Sınır Noktası", 7): "Your boundary-setting energy is strong in balance and relationships. Your ability to set fair boundaries in relationships is strong.",
    ("Sınır Noktası", 8): "Your boundary-setting energy deepens with transformation and crises. You set strong boundaries at times of crisis.",
    ("Sınır Noktası", 9): "Your boundary-setting energy is nourished by philosophy and values. You set boundaries based on values.",
    ("Sınır Noktası", 10): "Your boundary-setting energy is crowned in career and social roles. Your ability to define social boundaries is strong.",
    ("Sınır Noktası", 11): "Your boundary-setting energy is connected to friendship and groups. Your ability to define social-circle boundaries is strong.",
    ("Sınır Noktası", 12): "Your boundary-setting energy is nourished by intuitive depth and spirituality. Your ability to define intuitive boundaries is strong.",

    ("Bağlanma Noktası", 1): "Your attachment style is directly connected to your identity. Your attachment style is a fundamental part of your personality.",
    ("Bağlanma Noktası", 2): "Your attachment style is nourished by material values and sensory experiences. Physical contact and concrete love language take the foreground.",
    ("Bağlanma Noktası", 3): "Your attachment style is connected to communication and your surroundings. You build bonds by talking and sharing knowledge.",
    ("Bağlanma Noktası", 4): "Your attachment style has a deep bond with family roots and home life. Home is the center of your attachment.",
    ("Bağlanma Noktası", 5): "Your attachment style is kneaded with creativity and playtime. You build bonds through play and joy.",
    ("Bağlanma Noktası", 6): "Your attachment style is connected to daily routine and service. You build bonds through service and care.",
    ("Bağlanma Noktası", 7): "Your attachment style is strong in balance and reciprocity. Mutual attachment and balance take the foreground.",
    ("Bağlanma Noktası", 8): "Your attachment style is kneaded with transformation and deepening. You have a deep and intense attachment style.",
    ("Bağlanma Noktası", 9): "Your attachment style is nourished by philosophy and expansion. You build bonds through philosophical values and shared beliefs.",
    ("Bağlanma Noktası", 10): "Your attachment style is crowned in career and social roles. You build bonds through social responsibilities.",
    ("Bağlanma Noktası", 11): "Your attachment style is connected to friendship and communities. You build bonds through friendship and groups.",
    ("Bağlanma Noktası", 12): "Your attachment style is nourished by intuitive depth and spirituality. You build intuitive and spiritual bonds.",

    ("Sorumluluk", 1): "Your parenting responsibility is directly connected to your identity. Parenting is a fundamental part of your self.",
    ("Sorumluluk", 2): "Your parenting responsibility is nourished by material resources and values. Your sense of material responsibility is strong.",
    ("Sorumluluk", 3): "Your parenting responsibility is connected to communication and your surroundings. You fulfill your responsibility by communicating with your child.",
    ("Sorumluluk", 4): "Your parenting responsibility has a deep bond with family roots and home life. Your responsibility for the home is your most fundamental value.",
    ("Sorumluluk", 5): "Your parenting responsibility is kneaded with creativity and playtime. You blend responsibility with joy and creativity.",
    ("Sorumluluk", 6): "Your parenting responsibility is connected to daily routine and health. Your responsibility for daily care and order is strong.",
    ("Sorumluluk", 7): "Your parenting responsibility is strong in balance and relationships. Balance and reciprocity in relationships take the foreground.",
    ("Sorumluluk", 8): "Your parenting responsibility deepens with transformation and crises. You display a strong sense of responsibility at times of crisis.",
    ("Sorumluluk", 9): "Your parenting responsibility is nourished by philosophy and values. You carry a sense of responsibility based on values.",
    ("Sorumluluk", 10): "Your parenting responsibility is crowned in career and social roles. Your sense of social responsibility is very strong.",
    ("Sorumluluk", 11): "Your parenting responsibility is connected to friendship and communities. You carry a sense of social responsibility.",
    ("Sorumluluk", 12): "Your parenting responsibility is nourished by intuitive depth and spirituality. You carry a sense of spiritual responsibility.",
}

ARAP_NOKTA_SINASTRI_YORUMLARI_EBEVEYN = {
    ("Baba Noktası", "Baba Noktası"): "Both parents carry strong father/authority energy. Two strong guides vibrate on the same frequency for your child.",
    ("Baba Noktası", "Anne Noktası"): "The balanced meeting of the father and mother points! Authority and compassion create a perfect balance for your child.",
    ("Baba Noktası", "Çocuk Ruhu"): "Your father energy is deeply in harmony with your child's spiritual purpose. Your parenting vision nourishes their spiritual growth.",
    ("Baba Noktası", "Koruma Noktası"): "The strong alliance of the father and protection points! A powerful protective shield forms for your child.",
    ("Baba Noktası", "Eğitim Noktası"): "The wisdom alliance of the father and education points! You pass structure and knowledge to your child together.",
    ("Baba Noktası", "Sınır Noktası"): "The discipline union of the father and boundary points! You become a strong team drawing clear and fair boundaries for your child.",
    ("Baba Noktası", "Bağlanma Noktası"): "The dance of compassion between the father and attachment points! Authority and love create a safe space for your child.",
    ("Baba Noktası", "Sorumluluk"): "The powerful conjunction of the father and responsibility points! Your parenting responsibility is at its peak.",

    ("Anne Noktası", "Anne Noktası"): "Both parents carry strong mother/nurturing energy. Two compassionate harbors vibrate on the same frequency for your child.",
    ("Anne Noktası", "Çocuk Ruhu"): "Your mother energy is deeply in harmony with your child's spiritual purpose. Your emotional nurturing supports their spiritual growth.",
    ("Anne Noktası", "Koruma Noktası"): "The compassionate shield of the mother and protection points! Both emotional and physical protection is provided for your child.",
    ("Anne Noktası", "Eğitim Noktası"): "The wisdom union of the mother and education points! Emotional nurturing and education create a perfect harmony for your child.",
    ("Anne Noktası", "Sınır Noktası"): "The balanced meeting of the mother and boundary points! Compassion and discipline create a balanced structure for your child.",
    ("Anne Noktası", "Bağlanma Noktası"): "The powerful conjunction of the mother and attachment points! Emotional attachment and nurturing create a deep refuge for your child.",
    ("Anne Noktası", "Sorumluluk"): "The sacred union of the mother and responsibility points! Nurturing and responsibility form the foundation of your parenting journey.",

    ("Çocuk Ruhu", "Çocuk Ruhu"): "Both parents strongly carry your child's spiritual purpose. Two spiritual guides vibrate on the same frequency for your child.",
    ("Çocuk Ruhu", "Koruma Noktası"): "The powerful union of the child's soul and protection points! Your child's spiritual growth is under strong protection.",
    ("Çocuk Ruhu", "Eğitim Noktası"): "The wisdom alliance of the child's soul and education points! Your child's spiritual purpose is nourished through education.",
    ("Çocuk Ruhu", "Sınır Noktası"): "The balanced meeting of the child's soul and boundary points! Your child's spiritual growth is nourished within structure and boundaries.",
    ("Çocuk Ruhu", "Bağlanma Noktası"): "The deep bond of the child's soul and attachment points! Your child's spiritual purpose is nourished through love and attachment.",
    ("Çocuk Ruhu", "Sorumluluk"): "The powerful conjunction of the child's soul and responsibility points! Your child's spiritual purpose is nourished with a sense of responsibility.",

    ("Koruma Noktası", "Koruma Noktası"): "Both parents carry strong protection energy. A double protective shield is active for your child.",
    ("Koruma Noktası", "Eğitim Noktası"): "The balanced alliance of the protection and education points! Your child's safety and education are in perfect harmony.",
    ("Koruma Noktası", "Sınır Noktası"): "The powerful union of the protection and boundary points! A strong and clear protection structure forms for your child.",
    ("Koruma Noktası", "Bağlanma Noktası"): "The compassionate shield of the protection and attachment points! A safe and loving space is created for your child.",
    ("Koruma Noktası", "Sorumluluk"): "The powerful conjunction of the protection and responsibility points! The protective instinct and sense of responsibility are at their peak.",

    ("Eğitim Noktası", "Eğitim Noktası"): "Both parents carry strong education energy. Two sources of wisdom vibrate on the same frequency for your child.",
    ("Eğitim Noktası", "Sınır Noktası"): "The balanced meeting of the education and boundary points! Learning and discipline create a perfect harmony for your child.",
    ("Eğitim Noktası", "Bağlanma Noktası"): "The compassionate union of the education and attachment points! The transfer of knowledge is nourished with love.",
    ("Eğitim Noktası", "Sorumluluk"): "The powerful conjunction of the education and responsibility points! Teaching and responsibility are the foundation of your parenting vision.",

    ("Sınır Noktası", "Sınır Noktası"): "Both parents carry strong boundary-setting energy. Clear and consistent boundaries are formed for your child.",
    ("Sınır Noktası", "Bağlanma Noktası"): "The balanced dance of the boundary and attachment points! Boundaries are nourished with love, attachment with structure.",
    ("Sınır Noktası", "Sorumluluk"): "The powerful conjunction of the boundary and responsibility points! Discipline and responsibility form a solid foundation for your child.",

    ("Bağlanma Noktası", "Bağlanma Noktası"): "Both parents carry strong attachment energy. Two compassionate hearts vibrate on the same frequency for your child.",
    ("Bağlanma Noktası", "Sorumluluk"): "The sacred union of the attachment and responsibility points! Love and responsibility are the foundation of your parenting journey.",

    ("Sorumluluk", "Sorumluluk"): "Both parents carry strong responsibility energy. Two responsibility-conscious guides vibrate on the same frequency for your child.",
}

ARAP_NOKTA_GEZEGEN_SINASTRI_EBEVEYN = {
    ("Baba Noktası", "Güneş"): "Your father energy is deeply in harmony with your child's self-consciousness. Your parenting role will be a light nourishing their radiance.",
    ("Baba Noktası", "Ay"): "Your father energy is deeply in harmony with your child's emotional world. Authority and compassion create a safe space for them.",
    ("Baba Noktası", "Merkür"): "Your father energy is in harmony with your child's world of communication. The transfer of knowledge and mental nourishment are the foundation of this bond.",
    ("Baba Noktası", "Venüs"): "Your father energy is in harmony with your child's love language. Aesthetic sensitivity and compassion nourish this parenting bond.",
    ("Baba Noktası", "Mars"): "Your father energy is deeply in harmony with your child's action energy. Protection and courage are the strong foundation of this bond.",
    ("Baba Noktası", "Jüpiter"): "Your father energy is nourished by your child's expansion energy. Wisdom and guidance enrich this parenting journey.",
    ("Baba Noktası", "Satürn"): "Your father energy is deeply in harmony with your child's structure energy. Responsibility and discipline form the skeleton of this bond.",

    ("Anne Noktası", "Güneş"): "Your mother energy is deeply in harmony with your child's self-consciousness. Nurturing and protection will be a sun nourishing their radiance.",
    ("Anne Noktası", "Ay"): "Your mother energy dances perfectly with your child's emotional world. Emotional nurturing and protection are the soul of this bond.",
    ("Anne Noktası", "Merkür"): "Your mother energy is in harmony with your child's world of communication. Expression and understanding strengthen this mother-child bond.",
    ("Anne Noktası", "Venüs"): "Your mother energy creates deep harmony in your child's love language. Compassion, beauty and aesthetics nourish this mother bond.",
    ("Anne Noktası", "Mars"): "Your mother energy is deeply in harmony with your child's action energy. The protective instinct and courage nourish this mother bond.",
    ("Anne Noktası", "Jüpiter"): "Your mother energy is nourished by your child's expansion energy. Wisdom and compassion enrich this mother-child journey.",
    ("Anne Noktası", "Satürn"): "Your mother energy is deeply in harmony with your child's structure energy. Responsibility and structure form the foundation of this mother bond.",

    ("Çocuk Ruhu", "Güneş"): "Your child's spiritual purpose is deeply in harmony with their self-consciousness. Their life journey is radiant and meaningful.",
    ("Çocuk Ruhu", "Ay"): "Your child's spiritual purpose is deeply in harmony with their emotional world. Their emotional intelligence and intuition are very strong.",
    ("Çocuk Ruhu", "Merkür"): "Your child's spiritual purpose is in harmony with their world of communication. Their mental abilities and learning capacity are very high.",
    ("Çocuk Ruhu", "Venüs"): "Your child's spiritual purpose creates deep harmony in their love language. Their artistic talents and aesthetic sensitivity are very strong.",
    ("Çocuk Ruhu", "Mars"): "Your child's spiritual purpose is deeply in harmony with their action energy. Their courage and capacity for action are very strong.",
    ("Çocuk Ruhu", "Jüpiter"): "Your child's spiritual purpose is in perfect harmony with their expansion energy. Wisdom and abundance illuminate their path.",
    ("Çocuk Ruhu", "Satürn"): "Your child's spiritual purpose is deeply in harmony with their structure energy. Their sense of discipline and responsibility is very strong.",

    ("Koruma Noktası", "Güneş"): "Your protection energy is deeply in harmony with your child's self-consciousness. You become a strong shield protecting their radiance.",
    ("Koruma Noktası", "Ay"): "Your protection energy is deeply in harmony with your child's emotional world. Emotional protection and nurturing are the foundation of this bond.",
    ("Koruma Noktası", "Merkür"): "Your protection energy is in harmony with your child's world of communication. You provide protection through knowledge and communication.",
    ("Koruma Noktası", "Venüs"): "Your protection energy creates deep harmony in your child's love language. Love and protection nourish this parenting bond.",
    ("Koruma Noktası", "Mars"): "Your protection energy is in perfect harmony with your child's action energy. Courage and the protective instinct are at their peak.",
    ("Koruma Noktası", "Jüpiter"): "Your protection energy is nourished by your child's expansion energy. Protection and wisdom work together.",
    ("Koruma Noktası", "Satürn"): "Your protection energy is deeply in harmony with your child's structure energy. Structure and protection create a safe foundation for your child.",

    ("Eğitim Noktası", "Güneş"): "Your education energy is deeply in harmony with your child's self-consciousness. You become a teacher nourishing their radiance.",
    ("Eğitim Noktası", "Ay"): "Your education energy is deeply in harmony with your child's emotional world. Emotional intelligence and empathy education are the foundation of this bond.",
    ("Eğitim Noktası", "Merkür"): "Your education energy is in perfect harmony with your child's world of communication. Mental nourishment and the transfer of knowledge are at their peak.",
    ("Eğitim Noktası", "Venüs"): "Your education energy creates deep harmony in your child's love language. Learning with love and aesthetic education are the soul of this bond.",
    ("Eğitim Noktası", "Mars"): "Your education energy is deeply in harmony with your child's action energy. Learning through action and courage-based education take the foreground.",
    ("Eğitim Noktası", "Jüpiter"): "Your education energy is in perfect harmony with your child's expansion energy. Wisdom and education enrich this parenting journey.",
    ("Eğitim Noktası", "Satürn"): "Your education energy is deeply in harmony with your child's structure energy. Structured, disciplined education forms the foundation of this bond.",

    ("Sınır Noktası", "Güneş"): "Your boundary-setting energy is deeply in harmony with your child's self-consciousness. You draw boundaries that respect their selfhood.",
    ("Sınır Noktası", "Ay"): "Your boundary-setting energy is deeply in harmony with your child's emotional world. Emotional boundaries and security are the foundation of this bond.",
    ("Sınır Noktası", "Merkür"): "Your boundary-setting energy is in harmony with your child's world of communication. You draw communication boundaries clearly.",
    ("Sınır Noktası", "Venüs"): "Your boundary-setting energy creates deep harmony in your child's love language. Boundaries set with love nourish this parenting bond.",
    ("Sınır Noktası", "Mars"): "Your boundary-setting energy is deeply in harmony with your child's action energy. You draw firm and clear boundaries.",
    ("Sınır Noktası", "Jüpiter"): "Your boundary-setting energy is nourished by your child's expansion energy. You draw boundaries with a broad perspective.",
    ("Sınır Noktası", "Satürn"): "Your boundary-setting energy is in perfect harmony with your child's structure energy. Structure and discipline form the foundation of your boundaries.",

    ("Bağlanma Noktası", "Güneş"): "Your attachment energy is deeply in harmony with your child's self-consciousness. You build a deep bond with their selfhood.",
    ("Bağlanma Noktası", "Ay"): "Your attachment energy dances perfectly with your child's emotional world. Emotional attachment and nurturing are the soul of this bond.",
    ("Bağlanma Noktası", "Merkür"): "Your attachment energy is in harmony with your child's world of communication. You build a deep bond through communication and sharing knowledge.",
    ("Bağlanma Noktası", "Venüs"): "Your attachment energy creates deep harmony in your child's love language. Love, compassion and aesthetics nourish this attachment bond.",
    ("Bağlanma Noktası", "Mars"): "Your attachment energy is deeply in harmony with your child's action energy. You build bonds through action and courage.",
    ("Bağlanma Noktası", "Jüpiter"): "Your attachment energy is nourished by your child's expansion energy. Wisdom and a broad perspective enrich this bond.",
    ("Bağlanma Noktası", "Satürn"): "Your attachment energy is deeply in harmony with your child's structure energy. Structure and responsibility form the foundation of this bond.",

    ("Sorumluluk", "Güneş"): "Your responsibility energy is deeply in harmony with your child's self-consciousness. You carry responsibilities that respect their selfhood.",
    ("Sorumluluk", "Ay"): "Your responsibility energy is deeply in harmony with your child's emotional world. Emotional responsibility and nurturing are the foundation of this bond.",
    ("Sorumluluk", "Merkür"): "Your responsibility energy is in harmony with your child's world of communication. You carry responsibility through communication and sharing knowledge.",
    ("Sorumluluk", "Venüs"): "Your responsibility energy creates deep harmony in your child's love language. Love and responsibility nourish this parenting bond.",
    ("Sorumluluk", "Mars"): "Your responsibility energy is deeply in harmony with your child's action energy. Courage and responsibility are the strong foundation of this bond.",
    ("Sorumluluk", "Jüpiter"): "Your responsibility energy is nourished by your child's expansion energy. Wisdom and responsibility enrich this parenting journey.",
    ("Sorumluluk", "Satürn"): "Your responsibility energy is in perfect harmony with your child's structure energy. Structure and responsibility form the foundation of this bond.",
}

