# -*- coding: utf-8 -*-
# English variant of ARAP_ILISKI_DICTS.py (relationship / couple & individual natal modes).
# Keys are kept identical to the Turkish file; only values are translated to English.

ARAP_NOKTALARI_ILISKI = {
    "Şans Noktası":     {"nokta1": "Ay",     "nokta2": "Güneş",  "kisa": "SANS", "aciklama": "The natural door of opportunity and abundance destiny presents to you"},
    "Ruh Noktası":      {"nokta1": "Güneş",  "nokta2": "Ay",     "kisa": "RUH",  "aciklama": "Your inner purpose, spiritual journey and soul guidance"},
    "Evlilik Noktası":  {"nokta1": "Venüs",  "nokta2": "Satürn", "kisa": "EVLİ", "aciklama": "The energy of commitment, marriage destiny and long-term partnership"},
    "Aşk Noktası":      {"nokta1": "Venüs",  "nokta2": "Mars",   "kisa": "AŞK",  "aciklama": "Your love language, attraction power and the direction of your heart"},
    "Tutku Noktası":    {"nokta1": "Mars",   "nokta2": "Venüs",  "kisa": "TUTK", "aciklama": "Your intensity of desire, inner fire and the force that sets your destiny in motion"},
    "Para Noktası":     {"nokta1": "Merkür", "nokta2": "Güneş",  "kisa": "PARA", "aciklama": "The channel through which material gain, abundance and prosperity open to you"},
}

ARAP_NOKTA_ADLARI_EN = {
    "Şans Noktası": "Part of Fortune",
    "Ruh Noktası": "Spirit Point",
    "Evlilik Noktası": "Marriage Point",
    "Aşk Noktası": "Love Point",
    "Tutku Noktası": "Passion Point",
    "Para Noktası": "Money Point",
}

ARAP_NOKTA_BURC_YORUMLARI = {
    ("Şans Noktası", "Koç"): "Your fortune energy is bold and pioneering; the doors of life open the moment you take initiative. Destiny calls you to take the first step.",
    ("Şans Noktası", "Boğa"): "Your luck lies in patience and steadiness; the greatest opportunities arrive through concrete, step-by-step effort. Destiny offers you lasting values.",
    ("Şans Noktası", "İkizler"): "Your luck shines in communication; doors open the moment you say the right word. Knowledge and connections are the keys destiny hands you.",
    ("Şans Noktası", "Yengeç"): "Your luck lies in family and emotional security; your loved ones and home bring you unexpected opportunities. Destiny smiles when you follow your heart.",
    ("Şans Noktası", "Aslan"): "Your luck lies in creativity and self-expression; the moment you step on stage, destiny rewards you. Your courage is the gate of abundance.",
    ("Şans Noktası", "Başak"): "Your luck lies in details and service; your meticulousness wins you invisible opportunities. Destiny rewards those who love order.",
    ("Şans Noktası", "Terazi"): "Your luck lies in harmony and relationships; life smiles when you strike balance. The right connections are destiny's gift to you.",
    ("Şans Noktası", "Akrep"): "Your luck is hidden in transformation; when you emerge stronger from crises, destiny opens new doors for you. Depth is the source of abundance.",
    ("Şans Noktası", "Yay"): "Your luck lies on the horizon and in discovery; when you leap into adventure, unexpected gains find you. Destiny loves those who think big.",
    ("Şans Noktası", "Oğlak"): "Your luck lies in discipline and long-term planning; when you rise patiently, you are crowned at the summit. Destiny is faithful to your effort.",
    ("Şans Noktası", "Kova"): "Your luck lies in originality; the universe rewards you when you think differently. Your unconventional ideas are the key to abundance.",
    ("Şans Noktası", "Balık"): "Your luck lies in intuition and spirituality; magic happens when you trust your inner voice. Destiny stands beside the believers.",

    ("Ruh Noktası", "Koç"): "Your soul's quest is for independence; the more you chart your own path, the more inner peace you find. Your spiritual evolution is woven with courage.",
    ("Ruh Noktası", "Boğa"): "Your soul is nourished by earth and permanence; as you value yourself you grow spiritually rich. Your evolution flows with serenity.",
    ("Ruh Noktası", "İkizler"): "Your soul is nourished by knowledge and communication; learning and sharing are the stones of your spiritual journey. Your mind is the mirror of your soul.",
    ("Ruh Noktası", "Yengeç"): "Your soul is kneaded with emotional depth and belonging; your roots and family are your spiritual nourishment. Your inner world is your sacred refuge.",
    ("Ruh Noktası", "Aslan"): "Your soul rises with creativity and radiance; as you see your own light, you shine spiritually. The generosity of your heart is your soul's signature.",
    ("Ruh Noktası", "Başak"): "Your soul is nourished by service and purification; the more useful you are to others, the calmer your soul grows. Your pursuit of excellence is your spiritual discipline.",
    ("Ruh Noktası", "Terazi"): "Your soul is nourished by balance and harmony; as you find inner peace you mature spiritually. Beauty and justice are the language of your soul.",
    ("Ruh Noktası", "Akrep"): "Your soul is kneaded with transformation; the more you confront your shadows, the more spiritually alive you become. Deep purification is the center of your evolution.",
    ("Ruh Noktası", "Yay"): "Your soul rises with freedom and wisdom; as you broaden your horizons you grow spiritually. The search for truth is your soul's compass.",
    ("Ruh Noktası", "Oğlak"): "Your soul matures with structure and responsibility; as you patiently learn life's lessons, your spiritual authority strengthens. Your evolution is a disciplined ascent.",
    ("Ruh Noktası", "Kova"): "Your soul rises with freedom and love of humanity; as you open to universal consciousness you become spiritually enlightened. Difference is your soul's richness.",
    ("Ruh Noktası", "Balık"): "Your soul is kneaded with intuition and compassion; as you learn to become one with the universe you deepen spiritually. Your inner flow is your divine guidance.",

    ("Evlilik Noktası", "Koç"): "Your commitment destiny is bold and clear; in your marriage, initiative comes from you. You will have a powerful journey with your fated partner.",
    ("Evlilik Noktası", "Boğa"): "Your commitment destiny is as solid as earth; your marriage is built on trust and stability. Your fated bond grows even stronger over time.",
    ("Evlilik Noktası", "İkizler"): "Your commitment destiny is woven with communication and mental harmony; your marriage grows by talking and sharing. Your fated partner is like your soul twin.",
    ("Evlilik Noktası", "Yengeç"): "Your commitment destiny is built on emotional nurturing; your marriage deepens with home and family values. Your fated bond is your heart's refuge.",
    ("Evlilik Noktası", "Aslan"): "Your commitment destiny is woven with honor and generosity; your marriage is built on shining together. You share the stage lights with your fated partner.",
    ("Evlilik Noktası", "Başak"): "Your commitment destiny works through service and care; your marriage matures with mutual attentiveness. Your fated bond is hidden in the love of details.",
    ("Evlilik Noktası", "Terazi"): "Your commitment destiny is built on balance and justice; your marriage rises on equality. Your fated partner is the complementary half of your life.",
    ("Evlilik Noktası", "Akrep"): "Your commitment destiny is deep and transformative; your marriage is like a spiritual contract. Your fated bond cannot be toppled by any storm.",
    ("Evlilik Noktası", "Yay"): "Your commitment destiny is fed by freedom and adventure; your marriage is built on exploring together. You journey to the horizons with your fated partner.",
    ("Evlilik Noktası", "Oğlak"): "Your commitment destiny is built on responsibility and structure; your marriage is long-term and solid. Your fated bond is a contract that lasts a lifetime.",
    ("Evlilik Noktası", "Kova"): "Your commitment destiny is original and unconventional; your marriage is built by breaking the mold. Your fated partner is your best friend.",
    ("Evlilik Noktası", "Balık"): "Your commitment destiny is woven with unconditional love; your marriage is a spiritual union. Your fated bond is the sacred merging of souls.",

    ("Aşk Noktası", "Koç"): "Your love language is bold and direct; your heart recognizes no obstacle. Your love destiny begins with passion and is crowned with victory.",
    ("Aşk Noktası", "Boğa"): "Your love language is sensual and loyal; you express love through touch and trust. Your love destiny is lasting and nurturing.",
    ("Aşk Noktası", "İkizler"): "Your love language is words and mental play; your heart beats with curiosity. Your love destiny sprouts from conversation and grows with knowledge.",
    ("Aşk Noktası", "Yengeç"): "Your love language is compassion and emotional security; your heart loves to open its arms. Your love destiny is deep and protective.",
    ("Aşk Noktası", "Aslan"): "Your love language is generosity and passionate attention; your heart burns with stage lights. Your love destiny is grand and honoring.",
    ("Aşk Noktası", "Başak"): "Your love language is service and refinement; you show love through practical care. Your love destiny is meticulous and faithful.",
    ("Aşk Noktası", "Terazi"): "Your love language is elegance and harmony; your heart feeds on aesthetics. Your love destiny is balanced and just.",
    ("Aşk Noktası", "Akrep"): "Your love language is intense and transformative; your heart beats in the depths of the soul. Your love destiny is a binding devotion.",
    ("Aşk Noktası", "Yay"): "Your love language is adventure and enthusiasm; your heart wings toward the horizons. Your love destiny is joyful and expanding.",
    ("Aşk Noktası", "Oğlak"): "Your love language is serious and responsible; your heart strengthens with effort. Your love destiny is built on loyalty.",
    ("Aşk Noktası", "Kova"): "Your love language is original and friendly; your heart feeds on freedom. Your love destiny is unconventional and free.",
    ("Aşk Noktası", "Balık"): "Your love language is romantic and unconditional; your heart fills with dream and compassion. Your love destiny is spiritual and fairytale-like.",

    ("Tutku Noktası", "Koç"): "Your inner fire is sudden and strong; your desires turn directly into action. Your passion writes your destiny boldly.",
    ("Tutku Noktası", "Boğa"): "Your inner fire burns deep and steady; your desires are sensual and lasting. Your passion builds your destiny with determination.",
    ("Tutku Noktası", "İkizler"): "Your inner fire burns mentally and nimbly; your desires are fed by curiosity. Your passion weaves your destiny with discovery.",
    ("Tutku Noktası", "Yengeç"): "Your inner fire burns emotionally and protectively; your desires are tied to family and security. Your passion guides your destiny with compassion.",
    ("Tutku Noktası", "Aslan"): "Your inner fire burns grandly and creatively; your desires strengthen with appreciation and radiance. Your passion crowns your destiny with brilliance.",
    ("Tutku Noktası", "Başak"): "Your inner fire burns meticulously and orderly; your desires are kneaded with service and perfection. Your passion works your destiny with refinement.",
    ("Tutku Noktası", "Terazi"): "Your inner fire burns gracefully and harmoniously; your desires are fed by beauty and balance. Your passion guides your destiny with aesthetics.",
    ("Tutku Noktası", "Akrep"): "Your inner fire burns intensely and unquenchably; your desires strengthen with depth and control. Your passion writes your destiny through transformation.",
    ("Tutku Noktası", "Yay"): "Your inner fire burns expansively and enthusiastically; your desires are fed by freedom and ideals. Your passion carries your destiny toward the horizon.",
    ("Tutku Noktası", "Oğlak"): "Your inner fire burns disciplined and determined; your desires are fed by success and status. Your passion carries your destiny to the summit.",
    ("Tutku Noktası", "Kova"): "Your inner fire burns originally and revolutionary; your desires are fed by freedom and ideals. Your passion sets your destiny on an unconventional path.",
    ("Tutku Noktası", "Balık"): "Your inner fire burns intuitively and fluidly; your desires are fed by dream and spirituality. Your passion guides your destiny with inspiration.",

    ("Para Noktası", "Koç"): "Your money destiny opens with entrepreneurship; abundance finds you when you take the first step courageously. Material opportunities come when you lead.",
    ("Para Noktası", "Boğa"): "Your money destiny is woven with earth and stability; your regular savings bring abundance. Material wealth is the reward of your patient effort.",
    ("Para Noktası", "İkizler"): "Your money destiny opens with communication and commerce; your knowledge and connections bring gain. Material opportunities grow the more you share.",
    ("Para Noktası", "Yengeç"): "Your money destiny is linked to security and home; work that adds value to your family brings abundance. Material wealth is fed by emotional security.",
    ("Para Noktası", "Aslan"): "Your money destiny opens with creativity and display; the more you showcase your talents, the more your gain grows. Material wealth arrives by feeding your generosity.",
    ("Para Noktası", "Başak"): "Your money destiny is woven with service and analysis; carefully managed resources multiply. Material abundance comes through orderly systems.",
    ("Para Noktası", "Terazi"): "Your money destiny opens with partnership and harmony; collaborations and your aesthetic taste bring gain. Material wealth grows with balanced sharing.",
    ("Para Noktası", "Akrep"): "Your money destiny is woven with transformation and depth; your resource-management power is high. Material abundance comes through restructuring.",
    ("Para Noktası", "Yay"): "Your money destiny opens with expansion and opportunities; foreign connections and discoveries bring gain. Material wealth comes with broad vision.",
    ("Para Noktası", "Oğlak"): "Your money destiny is woven with discipline and strategy; long-term goals enlarge your gain. Material abundance is the result of patient ascent.",
    ("Para Noktası", "Kova"): "Your money destiny opens with innovation and technology; your unconventional ideas bring gain. Material wealth comes through original ventures.",
    ("Para Noktası", "Balık"): "Your money destiny is woven with intuition and inspiration; artistic and spiritual fields offer you opportunity. Material abundance comes when you trust the flow.",
}

ARAP_NOKTA_EV_YORUMLARI = {
    ("Şans Noktası", 1): "Your fortune energy is crowned in your identity; opportunities find you at your first step.",
    ("Şans Noktası", 2): "Your fortune energy is fed by material values; opportunities multiply with your self-confidence.",
    ("Şans Noktası", 3): "Your fortune energy shines in communication; opportunities come through your circle and knowledge.",
    ("Şans Noktası", 4): "Your fortune energy is hidden in your roots; family and home open the door of opportunity to you.",
    ("Şans Noktası", 5): "Your fortune energy shines in creativity; opportunities come through play and art.",
    ("Şans Noktası", 6): "Your fortune energy works in daily order; opportunities come through service and care.",
    ("Şans Noktası", 7): "Your fortune energy rises in partnerships; opportunities come through your relationships.",
    ("Şans Noktası", 8): "Your fortune energy strengthens in transformation; opportunities come through inheritance and deep bonds.",
    ("Şans Noktası", 9): "Your fortune energy shines on the horizon; opportunities come through travel and wisdom.",
    ("Şans Noktası", 10): "Your fortune energy is crowned in career; opportunities come through your goals.",
    ("Şans Noktası", 11): "Your fortune energy rises in friendships; opportunities come through your communities.",
    ("Şans Noktası", 12): "Your fortune energy deepens in spirituality; opportunities come through your intuition.",

    ("Ruh Noktası", 1): "Your spiritual purpose is intertwined with your identity; you live your soul by being yourself.",
    ("Ruh Noktası", 2): "Your spiritual purpose is fed by your values; your self-confidence is the mirror of your soul.",
    ("Ruh Noktası", 3): "Your spiritual purpose lies in learning and sharing; words are the bridge of your soul.",
    ("Ruh Noktası", 4): "Your spiritual purpose is hidden in your roots; family bonds nourish your soul.",
    ("Ruh Noktası", 5): "Your spiritual purpose shines in creativity; your expression is the joy of your soul.",
    ("Ruh Noktası", 6): "Your spiritual purpose works through service; being useful purifies your soul.",
    ("Ruh Noktası", 7): "Your spiritual purpose is mirrored in relationships; your bonds mature your soul.",
    ("Ruh Noktası", 8): "Your spiritual purpose deepens in transformation; purification is the healing of your soul.",
    ("Ruh Noktası", 9): "Your spiritual purpose rises in truth; your faith is the light of your soul.",
    ("Ruh Noktası", 10): "Your spiritual purpose is crowned in responsibility; your mission is the path of your soul.",
    ("Ruh Noktası", 11): "Your spiritual purpose shines in love of humanity; your community nourishes your soul.",
    ("Ruh Noktası", 12): "Your spiritual purpose deepens in spirituality; your inner flow is your divine guide.",

    ("Evlilik Noktası", 1): "Your marriage destiny is tied to your identity; commitment is the foundation of your selfhood.",
    ("Evlilik Noktası", 2): "Your marriage destiny is fed by trust and values; your partnership rests on a material foundation.",
    ("Evlilik Noktası", 3): "Your marriage destiny strengthens with communication; your union grows through conversation.",
    ("Evlilik Noktası", 4): "Your marriage destiny is crowned in home life; starting a family is the center of your destiny.",
    ("Evlilik Noktası", 5): "Your marriage destiny is fed by joy and creativity; your union is full of enthusiasm.",
    ("Evlilik Noktası", 6): "Your marriage destiny works through daily service; your partnership strengthens with care.",
    ("Evlilik Noktası", 7): "Your marriage destiny is the number one house area; your partner is the mirror of your life.",
    ("Evlilik Noktası", 8): "Your marriage destiny is woven with deep bonds; your union is a spiritual contract.",
    ("Evlilik Noktası", 9): "Your marriage destiny rises with shared ideals; you expand together.",
    ("Evlilik Noktası", 10): "Your marriage destiny is crowned in a social role; you walk toward goals with your partner.",
    ("Evlilik Noktası", 11): "Your marriage destiny is fed by friendship; your partner is your closest friend.",
    ("Evlilik Noktası", 12): "Your marriage destiny deepens in spirituality; your union is a spiritual merging.",

    ("Aşk Noktası", 1): "Your love destiny shines with your identity; your love is the light of your selfhood.",
    ("Aşk Noktası", 2): "Your love destiny is fed by self-worth; the more you love yourself, the more love you attract.",
    ("Aşk Noktası", 3): "Your love destiny sprouts in communication; your heart speaks with words.",
    ("Aşk Noktası", 4): "Your love destiny blooms in emotional security; your heart seeks a home.",
    ("Aşk Noktası", 5): "Your love destiny shines with romance; your heart burns with play and joy.",
    ("Aşk Noktası", 6): "Your love destiny is fed by service and care; your love grows with practical compassion.",
    ("Aşk Noktası", 7): "Your love destiny is mirrored in relationships; love is the main foundation of your life.",
    ("Aşk Noktası", 8): "Your love destiny is kneaded in depth; your heart beats with spiritual bonds.",
    ("Aşk Noktası", 9): "Your love destiny shines with adventure; your heart journeys to far lands.",
    ("Aşk Noktası", 10): "Your love destiny strengthens with a social role; your love is fed by respect.",
    ("Aşk Noktası", 11): "Your love destiny blooms in friendship; your heart beats within the community.",
    ("Aşk Noktası", 12): "Your love destiny deepens in spirituality; your heart burns with divine love.",

    ("Tutku Noktası", 1): "Your passion gushes from your identity; your fire sets your selfhood in motion.",
    ("Tutku Noktası", 2): "Your passion is fed by your values; your desires turn into gain.",
    ("Tutku Noktası", 3): "Your passion shines in your mind; your desires strengthen with ideas.",
    ("Tutku Noktası", 4): "Your passion burns in your roots; your family feeds your fire.",
    ("Tutku Noktası", 5): "Your passion ignites in creativity; your desires shine in art.",
    ("Tutku Noktası", 6): "Your passion works in service; your desires find power in daily tasks.",
    ("Tutku Noktası", 7): "Your passion burns in relationships; your desires strengthen with bonds.",
    ("Tutku Noktası", 8): "Your passion ignites in depth; your desires are fed by transformation.",
    ("Tutku Noktası", 9): "Your passion shines on the horizon; your desires grow with discovery.",
    ("Tutku Noktası", 10): "Your passion is crowned in career; your desires rise with goals.",
    ("Tutku Noktası", 11): "Your passion burns in friendship; your desires strengthen with ideals.",
    ("Tutku Noktası", 12): "Your passion deepens in spirituality; your desires are fed by inspiration.",

    ("Para Noktası", 1): "Your money destiny is tied to your identity; your gain grows with your initiative.",
    ("Para Noktası", 2): "Your money destiny is its natural house area; abundance overflows from here.",
    ("Para Noktası", 3): "Your money destiny works through trade and communication; your knowledge turns into gain.",
    ("Para Noktası", 4): "Your money destiny lies in family and real estate; your roots bring you gain.",
    ("Para Noktası", 5): "Your money destiny shines with creativity; your talents turn into gain.",
    ("Para Noktası", 6): "Your money destiny works through service; your meticulous effort brings abundance.",
    ("Para Noktası", 7): "Your money destiny rises in partnerships; collaborations bring gain.",
    ("Para Noktası", 8): "Your money destiny lies in deep resources; investment and inheritance offer you opportunity.",
    ("Para Noktası", 9): "Your money destiny shines in expansion; foreign ties increase your gain.",
    ("Para Noktası", 10): "Your money destiny is crowned in career; your profession brings abundance.",
    ("Para Noktası", 11): "Your money destiny is fed by networks; your community enlarges your gain.",
    ("Para Noktası", 12): "Your money destiny works in spirituality; your intuition senses opportunities.",
}

ARAP_EV_KISAYORUMLARI = {
    1: "Creates a karmic influence in the area of identity and selfhood.",
    2: "Creates a karmic influence in the area of values and material resources.",
    3: "Creates a karmic influence in the area of communication and the immediate environment.",
    4: "Creates a karmic influence in the area of family roots and home.",
    5: "Creates a karmic influence in the area of creativity and love life.",
    6: "Creates a karmic influence in the area of daily order and health.",
    7: "Creates a karmic influence in the area of partnerships and relationships.",
    8: "Creates a karmic influence in the area of transformation and deep bonds.",
    9: "Creates a karmic influence in the area of faith and expansion.",
    10: "Creates a karmic influence in the area of career and social role.",
    11: "Creates a karmic influence in the area of friendships and communities.",
    12: "Creates a karmic influence in the area of the subconscious and spirituality.",
}

ARAP_NOKTA_SINASTRI_YORUMLARI = {
    ("Şans Noktası", "Şans Noktası"): "Your Part of Fortune points vibrate on the same frequency of destiny; a fortunate journey awaits you together.",
    ("Şans Noktası", "Ruh Noktası"): "One person's fortune illuminates the other's spiritual path; your destiny nourishes each other.",
    ("Şans Noktası", "Evlilik Noktası"): "Your fortune strengthens your commitment; opportunities open while you are together.",
    ("Şans Noktası", "Aşk Noktası"): "Your fortune and love energy are intertwined; your union is fed by destiny's grace.",
    ("Şans Noktası", "Tutku Noktası"): "Your fortune sets your passion in motion; you take bold steps while together.",
    ("Şans Noktası", "Para Noktası"): "Your fortune and abundance energy unite; material opportunities open while you are together.",
    ("Ruh Noktası", "Ruh Noktası"): "Your Spirit Points are on the same frequency; there is a spiritual agreement between you.",
    ("Ruh Noktası", "Evlilik Noktası"): "Your spiritual path crosses your commitment destiny; your union carries a spiritual purpose.",
    ("Ruh Noktası", "Aşk Noktası"): "Your soul and heart beat together; your love carries a spiritual depth.",
    ("Ruh Noktası", "Tutku Noktası"): "Your spiritual purpose and passion unite; your inner fire strengthens while together.",
    ("Ruh Noktası", "Para Noktası"): "Your spiritual path is supported by material means; you find balance together.",
    ("Evlilik Noktası", "Evlilik Noktası"): "Your Marriage Points are on the same vibration; a karmic commitment contract lies between you.",
    ("Evlilik Noktası", "Aşk Noktası"): "Your love and commitment destinies unite; your union is lasting and passionate.",
    ("Evlilik Noktası", "Tutku Noktası"): "Your commitment and passion energy are intertwined; your union is fiery yet solid.",
    ("Evlilik Noktası", "Para Noktası"): "Your commitment and abundance energy unite; you build a solid future together.",
    ("Aşk Noktası", "Aşk Noktası"): "Your Love Points are on the same frequency; your hearts beat in the same rhythm.",
    ("Aşk Noktası", "Tutku Noktası"): "Your love and passion energy are in perfect harmony; your union is romantic and fiery.",
    ("Aşk Noktası", "Para Noktası"): "Your love and abundance energy unite; both love and prosperity flow while you are together.",
    ("Tutku Noktası", "Tutku Noktası"): "Your Passion Points vibrate in unison; your energy multiplies while together.",
    ("Tutku Noktası", "Para Noktası"): "Your passion and abundance energy unite; your courage creates material opportunities.",
    ("Para Noktası", "Para Noktası"): "Your Money Points are on the same frequency; your abundance energy strengthens while together.",
}

ARAP_NOKTA_GEZEGEN_SINASTRI = {
    ("Şans Noktası", "Güneş"): "Your Part of Fortune conjuncts the other's Sun; your presence brings opportunity into their life.",
    ("Şans Noktası", "Ay"): "Your Part of Fortune conjuncts the other's Moon; their emotions find fortune with you.",
    ("Şans Noktası", "Venüs"): "Your Part of Fortune conjuncts the other's Venus; beauty and opportunity intertwine while together.",
    ("Şans Noktası", "Mars"): "Your Part of Fortune conjuncts the other's Mars; bold steps bring abundance while together.",
    ("Şans Noktası", "Jüpiter"): "Your Part of Fortune conjuncts the other's Jupiter; expansion and abundance flow together.",
    ("Şans Noktası", "Satürn"): "Your Part of Fortune conjuncts the other's Saturn; opportunities come with responsibility while together.",
    ("Ruh Noktası", "Güneş"): "Your Spirit Point conjuncts the other's Sun; their presence illuminates your spiritual path.",
    ("Ruh Noktası", "Ay"): "Your Spirit Point conjuncts the other's Moon; your souls meet in emotional depth.",
    ("Ruh Noktası", "Venüs"): "Your Spirit Point conjuncts the other's Venus; your spiritual bond is woven with love.",
    ("Ruh Noktası", "Mars"): "Your Spirit Point conjuncts the other's Mars; your spiritual path advances boldly together.",
    ("Ruh Noktası", "Jüpiter"): "Your Spirit Point conjuncts the other's Jupiter; you expand spiritually together.",
    ("Ruh Noktası", "Satürn"): "Your Spirit Point conjuncts the other's Saturn; your spiritual bond is the work of destiny.",
    ("Evlilik Noktası", "Güneş"): "Your Marriage Point conjuncts the other's Sun; their identity completes your commitment destiny.",
    ("Evlilik Noktası", "Ay"): "Your Marriage Point conjuncts the other's Moon; your emotional bond is fed by commitment.",
    ("Evlilik Noktası", "Venüs"): "Your Marriage Point conjuncts the other's Venus; your love and commitment destinies unite.",
    ("Evlilik Noktası", "Mars"): "Your Marriage Point conjuncts the other's Mars; your union is fiery and devoted.",
    ("Evlilik Noktası", "Jüpiter"): "Your Marriage Point conjuncts the other's Jupiter; your commitment is fed by abundance.",
    ("Evlilik Noktası", "Satürn"): "Your Marriage Point conjuncts the other's Saturn; your bond is destiny's most solid signature.",
    ("Aşk Noktası", "Güneş"): "Your Love Point conjuncts the other's Sun; their presence warms your heart.",
    ("Aşk Noktası", "Ay"): "Your Love Point conjuncts the other's Moon; your heart beats with their emotions.",
    ("Aşk Noktası", "Venüs"): "Your Love Point conjuncts the other's Venus; your love energy is in perfect harmony.",
    ("Aşk Noktası", "Mars"): "Your Love Point conjuncts the other's Mars; your attraction is strong and passionate.",
    ("Aşk Noktası", "Jüpiter"): "Your Love Point conjuncts the other's Jupiter; your love grows together.",
    ("Aşk Noktası", "Satürn"): "Your Love Point conjuncts the other's Saturn; your love defies time.",
    ("Tutku Noktası", "Güneş"): "Your Passion Point conjuncts the other's Sun; their presence fans your inner fire.",
    ("Tutku Noktası", "Ay"): "Your Passion Point conjuncts the other's Moon; your emotions ignite together.",
    ("Tutku Noktası", "Venüs"): "Your Passion Point conjuncts the other's Venus; desire and love intertwine.",
    ("Tutku Noktası", "Mars"): "Your Passion Point conjuncts the other's Mars; your energy doubles together.",
    ("Tutku Noktası", "Jüpiter"): "Your Passion Point conjuncts the other's Jupiter; your enthusiasm grows while together.",
    ("Tutku Noktası", "Satürn"): "Your Passion Point conjuncts the other's Saturn; your desire strengthens with discipline.",
    ("Para Noktası", "Güneş"): "Your Money Point conjuncts the other's Sun; their presence increases your gain.",
    ("Para Noktası", "Ay"): "Your Money Point conjuncts the other's Moon; material security increases while together.",
    ("Para Noktası", "Venüs"): "Your Money Point conjuncts the other's Venus; abundance and beauty flow together.",
    ("Para Noktası", "Mars"): "Your Money Point conjuncts the other's Mars; you work boldly for gain while together.",
    ("Para Noktası", "Jüpiter"): "Your Money Point conjuncts the other's Jupiter; abundance multiplies while together.",
    ("Para Noktası", "Satürn"): "Your Money Point conjuncts the other's Saturn; you build a solid fortune together.",
}

ASTEROID_ISIMLERI = {
    "Juno": {"etki": "The energy of marriage, loyalty, commitment and partnership"},
    "Ceres": {"etki": "The instinct of nourishment, compassion, motherhood and protection"},
    "Pallas": {"etki": "Strategic intelligence, creative solutions and wisdom"},
    "Vesta": {"etki": "Sacred focus, devotion and inner fire"},
    "Eros": {"etki": "Passion, intensity of desire and sexual attraction"},
    "Psyche": {"etki": "Spiritual depth, vulnerability and the subconscious bond"},
    "Sappho": {"etki": "Romance, aesthetic passion and emotional depth"},
    "Amor": {"etki": "Unconditional love, acceptance and the bonding of hearts"},
}

ASTEROID_SINASTRI_YORUMLARI = {
    ("Juno", "Güneş"): "Your Juno conjuncts their Sun; your commitment integrates with their identity and loyalty takes the center of your destiny.",
    ("Juno", "Ay"): "Your Juno conjuncts their Moon; emotional security and loyalty intertwine, your bond is fed by compassion.",
    ("Juno", "Venüs"): "Your Juno conjuncts their Venus; marriage and love energy unite, your union is sealed with love.",
    ("Juno", "Mars"): "Your Juno conjuncts their Mars; your commitment is fired with passion and the attraction between you is strong.",
    ("Juno", "Jüpiter"): "Your Juno conjuncts their Jupiter; your union is fed by abundance and expansion.",
    ("Juno", "Satürn"): "Your Juno conjuncts their Saturn; your commitment is karmic and lasting, the marriage contract is strong.",
    ("Ceres", "Ay"): "Your Ceres conjuncts their Moon; mutual nurturing and compassion become the foundation of your bond.",
    ("Ceres", "Venüs"): "Your Ceres conjuncts their Venus; your love is nurturing and compassionate, your union is peaceful.",
    ("Ceres", "Güneş"): "Your Ceres conjuncts their Sun; their presence nourishes you, maternal energy flows between you.",
    ("Ceres", "Mars"): "Your Ceres conjuncts their Mars; your protective instinct is strong and you overcome difficulties together.",
    ("Ceres", "Jüpiter"): "Your Ceres conjuncts their Jupiter; compassion and abundance flow together while you are together.",
    ("Ceres", "Satürn"): "Your Ceres conjuncts their Saturn; you build a bond of responsible care and trust.",
    ("Pallas", "Merkür"): "Your Pallas conjuncts their Mercury; your mental harmony is high and you find wise solutions together.",
    ("Pallas", "Güneş"): "Your Pallas conjuncts their Sun; your strategic wisdom strengthens their identity.",
    ("Pallas", "Ay"): "Your Pallas conjuncts their Moon; your emotional intelligence is high and you bond through intuitive solutions.",
    ("Pallas", "Venüs"): "Your Pallas conjuncts their Venus; elegance and strategy unite, your union is refined.",
    ("Pallas", "Mars"): "Your Pallas conjuncts their Mars; you become a team that fights wisely.",
    ("Vesta", "Güneş"): "Your Vesta conjuncts their Sun; your focus increases while together and you devote yourself to shared goals.",
    ("Vesta", "Ay"): "Your Vesta conjuncts their Moon; your emotional devotion is strong and your bond is fed by inner fire.",
    ("Vesta", "Mars"): "Your Vesta conjuncts their Mars; your shared energy is disciplined and goal-oriented.",
    ("Vesta", "Satürn"): "Your Vesta conjuncts their Saturn; your union is like a sacred duty and your devotion is solid.",
    ("Eros", "Venüs"): "Your Eros conjuncts their Venus; passion and love intertwine, your attraction is irresistible.",
    ("Eros", "Mars"): "Your Eros conjuncts their Mars; the attraction between you is intense and fiery, desire guides your destiny.",
    ("Eros", "Ay"): "Your Eros conjuncts their Moon; your emotional bond is kneaded with passion.",
    ("Eros", "Güneş"): "Your Eros conjuncts their Sun; their presence ignites your desires.",
    ("Psyche", "Ay"): "Your Psyche conjuncts their Moon; your souls meet in emotional depth and you form a telepathic bond.",
    ("Psyche", "Venüs"): "Your Psyche conjuncts their Venus; spiritual and romantic love unite, your bond is fairytale-like.",
    ("Psyche", "Güneş"): "Your Psyche conjuncts their Sun; your soul bonds deeply with their identity.",
    ("Psyche", "Neptün"): "Your Psyche conjuncts their Neptune; your spiritual bond reaches divine dimensions.",
    ("Sappho", "Venüs"): "Your Sappho conjuncts their Venus; your romance peaks, your love is aesthetic and deep.",
    ("Sappho", "Ay"): "Your Sappho conjuncts their Moon; your emotional bond is poetic and sensitive.",
    ("Sappho", "Mars"): "Your Sappho conjuncts their Mars; passionate romance flows between you.",
    ("Sappho", "Güneş"): "Your Sappho conjuncts their Sun; their presence makes your romantic feelings shine.",
    ("Amor", "Venüs"): "Your Amor conjuncts their Venus; unconditional love and romance unite, your bond is sacred.",
    ("Amor", "Ay"): "Your Amor conjuncts their Moon; your love is unconditional and compassionate, your emotional bond is deep.",
    ("Amor", "Güneş"): "Your Amor conjuncts their Sun; your love completes their presence.",
    ("Amor", "Mars"): "Your Amor conjuncts their Mars; your unconditional love strengthens with passion.",
}
