fbst_sabian_ebeveyn = {
    "Koc": {
        1: ("A woman just emerging from the sea, embracing a seal", "The eager, raw emotion of taking your first step into parenthood, and your child's unconditional devotion, transforming you into a completely new role."),
        2: ("A comedian displaying his talents in a hidden valley", "The opportunity to discover and nurture your child's inner talents and joy, independent of the outer world's expectations."),
        3: ("A man making a map of his country", "The responsibility of charting your child's developmental path, mapping their strengths and weaknesses so you can offer the most fitting guidance."),
        4: ("Two lovers walking along a remote, deserted lane", "That one-of-a-kind, deep bond between parent and child, far from the world's interference; the quiet and sacred journey of growing together."),
        5: ("A winged triangle", "The unity of mind, feeling and spirit between parent and child; the power that elevates your child's potential and carries them into life."),
        6: ("A square with one side brilliantly illuminated", "Illuminating guidance falling upon the solid foundations of your child's life; the points on which to focus in order to clarify their karmic direction."),
        7: ("A man able to express himself in two different worlds at once", "The ability to speak the languages of both childhood and adulthood simultaneously, connecting with your child on the level of both play and depth."),
        8: ("A large woman's hat trimmed with ribbons, waving in the east wind", "The art of weaving an intuitive shield of protection against your child's emotional storms, supporting them by harmonizing rather than unsettling."),
        9: ("A medium focusing on a crystal ball", "The gift of intuitively reading your child's inner needs that have not yet been spoken, their silent call and their emotional wounds."),
        10: ("A teacher giving new forms to traditional images", "The opportunity to break free of old parenting patterns and toxic family imprints, creating a wholly new and healthy language of connection with your child."),
        11: ("The ruler of a country", "The time to fully embrace your role as a parent, establishing the family's order and your child's realm of safety with true responsibility."),
        12: ("A flock of wild geese flying in a triangle formation", "The power to move toward common goals as parent and child, in perfect harmony and with instinctive cooperation."),
        13: ("An unexploded bomb; a failed social insurrection", "The gift of resolving your child's pent-up anger or challenging behaviors with patience and understanding so that, instead of exploding destructively, they become opportunities for growth."),
        14: ("A serpent coiling near a man and a woman", "The karmic bond between parent and child; the wisdom passed between generations and the transformative potential awakening in your child's depths."),
        15: ("An Indian weaving a ceremonial blanket", "The labor of patiently and devotedly weaving each of your child's moments of growth into a safe and sacred home, an armor for their spirit."),
        16: ("Nature spirits at work at sunset", "Beyond your parental efforts, invisible universal forces and natural protective energies are supporting your child's development."),
        17: ("Two spinsters sitting in silence with dignity", "The recognition that the silent moments shared with your child carry a deep love and serenity too; the sacredness of simply existing together without words."),
        18: ("An empty hammock stretched between two trees", "That sacred pause within constant striving, when both your child and yourself are allowed to rest and flow naturally."),
        19: ("A magic carpet", "The potential to transcend the limits of imagination with your child, enriching their world in a way that is wondrous and inspiring."),
        20: ("A young girl feeding birds in winter", "Even in the hardest, most trying seasons, the miracle of nourishing your child's spirit with compassion, patience and unconditional love."),
        21: ("A boxer entering the ring", "Taking up arms with courage and determination as a parent, to fight against external obstacles for the values and future your child deserves."),
        22: ("A gate opening into the garden of all fulfilled desires", "The profound joy of seeing your child reach their potential; the opportunity to fully support their essence, gifts and karmic path."),
        23: ("A pregnant woman in a light summer dress", "A new vision, a wellspring of creativity, or a spiritual fruit growing within your child, being prepared for its birth."),
        24: ("Curtains blown through an open window taking the shape of a cornucopia", "When you surrender completely to the universal flow, cosmic fortune and spiritual abundance pour into your family in unexpected ways."),
        25: ("The possibility for a man to gain experience on two different planes of being", "The grace of living parenthood masterfully on both levels at once, in the deepest physical devotion and in the highest divine dimension."),
        26: ("A man possessing more talents than he can carry", "The overflowing of your child's potential; the trial of focusing this intense karmic energy and directing it rightly rather than letting it scatter."),
        27: ("A lost opportunity regained through imagination", "The rewriting of the karmic course, as past mistakes and missed chances are repaired through the power of steadfast love and faith."),
        28: ("A performer faced with a large, disappointed audience", "The collision of excessive expectations with reality in your relationship with your child; the trial of letting the masks fall and embracing the bare truth with love, as it is."),
        29: ("The music of the celestial spheres", "That divine, cosmic point of synchronization where your souls resonate fully with the universal frequency and no words are needed."),
        30: ("A duck pond and its brood", "Coming to serenity in this phase of the karmic journey; the completion of belonging, of building a peaceful home, and of an absolute space of protection.")
    },
    "Boga": {
        1: ("Gold dust carried by a clear mountain stream", "The time to perceive the immense material and spiritual wealth hidden within your family's natural flow, and to receive this abundance with love."),
        2: ("An electrical storm; nature's magnificent power in a dark sky", "The crises and sudden eruptions within the family are, in truth, showing you the opportunity to purify these energies with patience and understanding."),
        3: ("Natural steps ascending a grassy meadow blossoming with clover", "Your child growing step by step, organically, without haste, on the road to peace, abundance and a sense of rootedness."),
        4: ("A pot of gold at the end of the rainbow", "The great karmic reward that follows the stormy processes and trials; the spiritual and material fulfillment reached together."),
        5: ("A widow keeping vigil before an open grave", "The trial of bidding farewell to the sorrows of the past and finished karmic bonds, making complete room, through spiritual purification, for this new family relationship."),
        6: ("A suspension bridge built over a deep chasm", "The power to cross the differences between parent and child that seemed utterly insurmountable, by means of a solid and reliable bridge of communication."),
        7: ("The Samaritan woman at the well", "The virtue of dissolving old prejudices and worldly taboos, quenching the deepest thirst in your child's soul with unconditional love."),
        8: ("A sled standing on snowless ground", "Understanding the importance of timing in plans made for the future; the will to wait patiently until the right conditions arise."),
        9: ("A fully decorated Christmas tree", "Keeping hope alive in the family's darkest or coldest days, and the celebration of the inner values you offer one another."),
        10: ("A Red Cross nurse", "Unconditional compassion, devotion and the covenant of being your child's greatest spiritual healer in their most vulnerable, wounded moments."),
        11: ("A woman watering the flowers of her garden", "The wisdom that love, only when nourished by daily, steady and practical care, becomes a home that is unbreakable and enduring."),
        12: ("A young couple looking into shop windows", "The phase of dreaming together, building the future side by side, and defining the family's worldly and material goals with joy."),
        13: ("A porter carrying heavy burdens", "Courageously shouldering the family's material or karmic loads; fidelity and responsibility turning into a heavy test of endurance."),
        14: ("Children playing on the seashore with seashells at the water's edge", "Living joy safely within natural boundaries; surrendering within a peaceful home to childlike, protected and pure feelings."),
        15: ("A man with his head wrapped in a thick scarf", "The need to protect the family's privacy against the noise and toxic interference of the outer world, listening only to one another's inner voice."),
        16: ("An old teacher unable to engage his students", "The time to let go of old, unworkable patterns in the family relationship; the necessity of finding a new and inspiring shared language instead of stubborn rules."),
        17: ("A symbolic battle between swords and torches", "The trial of choosing between mental illumination and destructive criticism in communication; choosing healing over being right."),
        18: ("A woman airing an old bag through an open window", "The purification of releasing the old poisons, doubts and burdens gathered in the subconscious, cleansed by love's fresh and healing wind."),
        19: ("A new continent rising from the depths of the ocean", "The miracle of the family creating a brand-new, unshakeable and concrete foundation after great crises and emotional upheavals."),
        20: ("Wing-like clouds drifting through the sky", "Spiritual inspiration, universal protection and lightness entering the family; stripping away excessive materialism and trusting the divine flow."),
        21: ("A finger pointing to a line in an open book", "The moment of noticing a very clear sign, message or synchronicity that your karmic contract offers, and aligning yourself with it."),
        22: ("A white dove flying over stormy waters", "Even amid the greatest crises, quarrels and fears, a universal peace, trust and divine protection hovering over the family."),
        23: ("A jewelry shop filled with precious gems", "The summit of perceiving the family's high intrinsic worth, its rare talents and its radiant shared wealth."),
        24: ("An Indian warrior galloping with enemy scalps at his waist", "The risk of a protective instinct or sense of ownership turning into destructive jealousy or control; the trial of taming the primitive ego."),
        25: ("A vast and magnificent public park", "Transcending the boundaries of personal love, the family becoming a collective realm of peace, abundance and tolerance that inspires the outer world."),
        26: ("A Spanish lover serenading his beloved", "Boldly and aesthetically expressing the language of love, reigniting the magnetic power of the family."),
        27: ("An old woman selling the crafts of her tribe", "Adapting traditions, roots and the ancient wisdom of the past in ways that serve the family's present-day material and spiritual construction."),
        28: ("A mature woman awakened anew to love", "Despite every disappointment of the past, courageously reopening the heart; perceiving that love is timeless and that the family can bloom anew at any moment."),
        29: ("Two cobblers working at a table", "Working shoulder to shoulder for a common purpose, with zero ego; the seal of a practical, balanced and flawless collaboration that turns visions into reality."),
        30: ("A peacock parading on the terrace of an old castle", "The rightful pride in achievements that have passed the tests of time, in nobility and in eternal confidence; the family crowned in splendor upon a storied empire.")
    },
    "Ikizler": {
        1: ("People observing the ocean floor from a glass-bottomed boat", "Going beyond the superficial, the desire to explore your child's deepest spiritual waters with mental curiosity."),
        2: ("Santa Claus secretly filling stockings", "Karmic gifts arriving at unexpected moments, and the pure, childlike innocence within the family being rewarded by an invisible hand."),
        3: ("The Tuileries Gardens in Paris", "The construction of communication with elegance, mental order and intellectual harmony, built as a flawless architecture of shared language."),
        4: ("Holly and mistletoe", "Nostalgia, old memories and rooted traditions keeping the family's mental bond vibrantly alive."),
        5: ("A radical magazine calling to action", "Intellectual rebellion! The need to break the family's ordinariness and routine, generating fresh and revolutionary ideas that set your child's mind ablaze."),
        6: ("Workers drilling for oil", "Going far beyond daily chatter and superficial conversation, the endeavor to reach the rich and hidden source of power in the family's deepest core."),
        7: ("An old-fashioned well", "Drawing from one another's minds as from an inexhaustible well of ancient wisdom and inspiration; quenching spiritual thirst with words."),
        8: ("Angry strikers gathered around a factory", "Difference of opinion turning into crisis; a tremulous confrontation demanding intellectual justice and an equal voice within the family."),
        9: ("A quiver full of arrows", "Mental sharpness! Words locked onto their target; the trial of using words not to wound one another but to strike the obstacles you face together."),
        10: ("An airplane making a nose dive", "Dangerous maneuvers in communication; taking great intellectual risks and courageously bringing about the much-feared confrontation within the family."),
        11: ("Virgin fields of experience offered on newly opened lands", "Expanding the limits of the mind; the family setting sail toward brand-new horizons, shared learning, or subjects never before spoken of."),
        12: ("A Black slave girl demanding her rights from her mistress", "The eruption of hidden imbalances in communication; one side rising up against the other's intellectual domination, demanding freedom and respect."),
        13: ("A famous musician giving a piano concert", "The flawless display of intellectual talents; the state of inspiring and enchanting one another with your ideas, vision and communication."),
        14: ("The telepathic communication of two people living far apart", "Despite physical distance or silence, minds connecting on a quantum level, exchanging their thoughts in a tremendous telepathic transmission."),
        15: ("Two Dutch children talking among themselves", "Setting complex philosophies aside, the miracle of establishing that purest, most joyful, simple shared language that only the family understands."),
        16: ("A woman activist making an emotional speech", "Passionate advocacy for beliefs and shared goals; the family's mental energy turning into a shield against the outer world."),
        17: ("A strapping youth's head turning into the head of a mature thinker", "The family's intellectual ascent; childlike curiosity and impulsiveness, seasoned by experience, evolving into deep karmic wisdom."),
        18: ("Two Chinese speaking their native tongue amid an American crowd", "Within the outer world's crowd and noise, communicating on that hidden mental frequency and with the private codes that only you can decipher."),
        19: ("A great archaic volume revealing traditional wisdom", "The moment of nourishing the family with its roots, with a great lesson drawn from the past or from ancient teachings, and with philosophical enlightenment."),
        20: ("A cafeteria offering numerous choices", "The trial of mental scatter and indecision; the power to select the family's karmic course with a common mind among many ideas and options."),
        21: ("A noisy labor demonstration", "The harsh clash of logic and emotion, right and wrong; the bottleneck through which the family's accumulated mental pressures must be released."),
        22: ("Couples dancing at a harvest festival", "Gathering the fruits of mental harmony, productive ideas and successful communication; the family becoming a joyful and spirited celebration."),
        23: ("Three fledgling birds in a nest at the top of a tree", "The growth of mental seeds; shared ideas, plans or projects still in their incubation stage, needing to be tenderly protected."),
        24: ("Children ice skating on a frozen village pond", "The ability to overcome cold, crisis-ridden or distant periods through quick wit, joy and flexibility in communication."),
        25: ("A gardener pruning great palm trees", "Pruning the family's mental branches; trimming away needless details, toxic thoughts and past fixations to focus on the main goal, the trunk."),
        26: ("Trees covered in frost against the winter sky", "Even in periods of emotional distance or silence, the crystallized, unique and noble beauty of that solid mental bond between you."),
        27: ("A gypsy emerging from the forest where his tribe has camped", "The quest for intellectual freedom; the courage to step out of habitual thought patterns and the family's comfort zone to try a new philosophy."),
        28: ("Society granting a fresh start through bankruptcy", "The complete collapse of old ways of communicating or of mental structures; after this ruin, the chance to rebuild the mind from scratch, far more honest and strong."),
        29: ("The first nightingale of spring", "Rebirth, joyful tidings and fresh ideas; the family's communication emerging from its shell and coming to life with spring's exuberance and a sweet melody."),
        30: ("A pageant of beauties entering the sea", "Boldly displaying mental and aesthetic harmony to the world; the energy of shining with confidence in the family's social showcase.")
    },
    "Yengec": {
        1: ("Aboard a ship, sailors lower an old flag and raise a new one (Lowering the old flag on the sailboat and raising a new one)", "The courage to let the old allegiances, familial ties and past come to an end, being born into a brand-new shared identity of home through this family relationship."),
        2: ("A man viewing a vast territory from a magic carpet", "The ability of the family to rise above everyday worldly cares and regard one another's soul from a higher perspective, with objective compassion."),
        3: ("A man wrapped in furs, guiding a hairy deer", "The instinct to be an unshakeable shield of protection for your child's tender soul, even in the coldest, hardest and most turbulent times."),
        4: ("A cat arguing with a mouse", "Minor power struggles within the shared living space of the home; the test of whether emotional boundaries are probed with love or with manipulation."),
        5: ("An automobile smashed by a train on the railway", "The destructiveness of stubbornly pitting the personal ego against destiny's unstoppable flow; the necessity of absolute surrender to the system and the divine plan."),
        6: ("Play-birds feathering their nests", "The time to invest emotionally and materially in marriage, shared living and the home; the virtue of building the safest, warmest corner in one another's hearts."),
        7: ("Two nature spirits dancing in the moonlight", "The fairytale-like, childlike and magical emotional harmony that begins where logic ends; the relationship stepping out of the rational world and healing in the realm of dreams."),
        8: ("A parade of rabbits dressed in human clothes", "The danger of donning the artificial forms that the outer world, other families or society impose upon the relationship; a warning to flee pretense and return to essence."),
        9: ("A small, naked girl trying to catch fish in a pond", "Returning to the family's purest, most innocent and most vulnerable moments, capturing and protecting that first-day excitement guilelessly."),
        10: ("A great, rough diamond in its first stage of cutting", "The process by which raw, primal love is refined through time, crises and patience, to become a priceless, eternal diamond of fidelity."),
        11: ("A clown imitating celebrities", "The talent for softening egos, tensions and conflicts within the family with magnificent humor and a compassionate jest, adding joy to the home."),
        12: ("A woman nursing a baby whose aura reveals an incarnated sage", "The great and sacred awareness that, while tending one another's naive, childlike wounds, you are in fact nourishing a very ancient and karmic soul."),
        13: ("A hand with a prominent thumb extended for examination", "Openly and honestly placing willpower, character and concrete actions on the table, and facing them without masks."),
        14: ("A very old man gazing into the dark, bottomless void toward the northeast", "An unshakeable spiritual wisdom cultivated together against the unknown, the future and old age; the courage to walk hand in hand into eternity."),
        15: ("Guests resting in a luxurious dining hall after a great feast", "The moment of great spiritual harvest, when the family, having weathered hard days, attains the peak of material and spiritual satisfaction, fullness and domestic peace."),
        16: ("A man studying a mandala before him with the aid of an ancient book", "The desire to decipher this deep and intricate karmic structure between you not with a superficial mind, but with universal laws and spiritual wisdom."),
        17: ("A seed turning into knowledge and life", "The divine glad tidings that a tiny seed of love and compassion, once rooted, becomes a magnificent garden of life, a whole family."),
        18: ("A hen scratching the earth to feed her chicks", "That unending, devoted and sacred maternal labor poured into protecting the family, the children and the family's shared future."),
        19: ("A priest officiating at a marriage ceremony", "The family being sealed by a karmic covenant; fidelity crowned not merely by a worldly signature but by a divine approval and a universal contract."),
        20: ("Venetian gondoliers serenading", "The power to celebrate love with magnificent grace above emotional fluctuations, crises and waters."),
        21: ("A renowned singer displaying her skill at the opera", "Living the pinnacle of the deep love, devotion and belonging you hold for one another, and presenting it to the world with a dignified presence."),
        22: ("A young woman awaiting the sailboat", "Waiting with unshakeable faith, fidelity and patience for the karmic partner, the awaited spiritual savior, or the family's peaceful days to come."),
        23: ("A meeting of a literary club", "Not only shared emotions but shared intellectual values, cultural roots and common ideals strengthening the family's foundation and roof."),
        24: ("A woman and two men marooned on a small island in the southern seas", "A karmic isolation within the family, tests of jealousy, or the boundaries of belonging and fidelity being put to trial at the extremes, amid crises."),
        25: ("The shadow of a superior power descending upon a man of will", "Personal egos and stubbornness being crushed before the family's divine destiny; being compelled toward total surrender to the universe and this love."),
        26: ("Guests reading in the library of a luxurious home", "Finding magnificent peace in a home rich in spirit and mind; arguments replaced by shared wisdom and quiet harmony."),
        27: ("A violent storm in a canyon of luxurious homes", "A karmic crisis striking comfort and the home! The family's unshakeable roots being put through a test of material and spiritual resilience."),
        28: ("An Indian girl introducing her white lover to her tribe", "Uniting two different roots, families, traditions or pasts over a single bridge of love; the great test of harmony that rootedness brings."),
        29: ("A Greek muse weighing newborn twins on golden scales", "That golden seal in which inner duality, logic and emotion, you and I, is placed within the family upon a flawless, divine and tireless balance."),
        30: ("A daughter of the American Revolution", "The deep honor felt for roots, for the past and for one another; the family drawing its worldly power and revolutionary force from this unshakeable belonging.")
    },
    "Aslan": {
        1: ("Blood spurts onto a man's head as his vital energy is stirred by ambition", "Ego and passion suddenly flaring within the family; the awakening of locking onto a shared goal and moving into action with unstoppable force."),
        2: ("A mumps epidemic", "The danger of a crisis or an infectious pessimism spreading swiftly within the family; the test of isolating toxic energies before they infect others."),
        3: ("A middle-aged woman in youthful clothes with her hair falling over her shoulders", "The family defying time and age; casting off the warmth of routine and wearing anew that first, fresh, rebellious and free-spirited soul."),
        4: ("An old man in official attire standing beside the spoils of a hunt", "The test of ego and pride! Taking pride in past achievements or the family's social standing; the warning to see your child as an individual, not a trophy."),
        5: ("Majestic rock formations rising over a deep canyon", "The seal of unshakeability! The family, despite the abrasions of time and the deep crises around it, standing tall, noble and immovable like a tower."),
        6: ("An old-fashioned, conservative woman confronted by a modern girl of today", "The collision of the past's deeply rooted values with the future's longing for liberation; finding a shared, modern language within the family by loving beyond old taboos."),
        7: ("Constellations blazing brilliantly in the night sky", "The realization that in even your darkest hours your souls are guarded by universal guidance, and that your family serves a divine plan."),
        8: ("An activist spreading revolutionary ideals", "The passion to transform and rebuild something at its very root within the family; yet the necessity that this rebellion liberate the bond, not destroy the child."),
        9: ("Glass blowers shaping glass aglow with their breath", "Karmic alchemy! Touching one another's soul and transforming this bond, raw at first, into a magnificent aesthetic and an enduring work of art."),
        10: ("Morning dew drops glistening as sunlight floods the field", "A fresh spiritual awakening after a dark period; the family being washed anew each morning, with hope and a divine optimism."),
        11: ("Children swinging on a swing hanging from the branches of a giant oak", "The grace of fearlessly living the family's most innocent, playful and childlike side, in the shadow of a deeply rooted, sheltered and unshakeable trust."),
        12: ("An evening party of adults on a lawn lit by ornate lanterns", "The time for the family to shine in the social showcase; taking the stage with pride, aesthetics, and a harmony the outer world approves of and admires."),
        13: ("An old sea captain rocking on the porch of his cabin", "That peaceful moment of settling, when a family that has weathered great storms, crises and trials of endurance now smiles upon the past with experience and wisdom."),
        14: ("A human soul seeking opportunities for self-expression", "Love kept hidden only in hearts now bursting with the need to become, in the concrete world, a work, a family life, or an enduring co-creation."),
        15: ("A splendid parade advancing down a street filled with cheering crowds", "The family proclaiming its own kingdom; a noble karmic zenith, showy, bold and won with the highest approval of those around it."),
        16: ("Nature's joy in brilliant sunlight after the storm has passed", "The immense relief following a very heavy crisis or power struggle; tears giving way to a love washed clean and pristine."),
        17: ("A volunteer church choir singing hymns", "Different voices, the egos, harmonizing for a single higher purpose; the family stepping out of the earthly dimension and uniting in spiritual devotion."),
        18: ("A chemist conducting experiments for his students", "The time to decode the family's mathematics and chemistry! Mastering how formulas, elements and emotions react, through experience."),
        19: ("A boat party, a floating home", "Perceiving commitment not as a shackle but as a joyful and free voyage shared together; stretching the family's boundaries and focusing on delight."),
        20: ("Zuni Indians performing a sun ritual", "Feeling deep gratitude for the source of your existence and of this magnificent family; zeroing the ego and connecting reverently to the divine power."),
        21: ("Drunk chickens, dizzy and flapping their wings as they try to fly", "A warning against the family being swept into capacities beyond its reach, unrealistic expectations or inflated egos; the risk of falling into comical or crisis-ridden situations while trying to fly."),
        22: ("A carrier pigeon fulfilling its mission", "The seal of fidelity! The virtue of honoring the karmic vow you made to one another, even under the hardest conditions, and of delivering love's sacred message to its destination."),
        23: ("A rider on a riderless horse in a circus enchanting the excited crowd", "The family's dangerous, risky yet equally hypnotic power; achieving boldly while disregarding obstacles and rules."),
        24: ("A man utterly indifferent to his physical appearance, focused on spiritual enlightenment", "The outer world's show, ego and aesthetics losing all meaning; the family focusing entirely on the subconscious, the mystical and the subterranean alchemy."),
        25: ("A great camel crossing a vast and merciless desert", "A test of immense power and endurance! In the family's arid and crisis-ridden passages, walking patiently and stubbornly toward the goal, drawing upon your inner reserves of water, of love."),
        26: ("A rainbow appearing after a heavy storm", "A karmic promise! After the pains endured and the tears shed, the divine bridge of hope, repair and healing that the universe offers your family."),
        27: ("The glow of dawn in the eastern sky", "A dark era closing forever; with this family, the soul opening its eyes to a new consciousness, to hope, and to the sun, the awakening."),
        28: ("Many little birds chirping on the branch of a great tree", "The shared circle, friendships and small joys nourishing the family; moving away from heavy drama toward a simple, playful and lively communication."),
        29: ("A mermaid rising from the ocean waves to be reborn in human form", "Great alchemical evolution! Unconscious emotions and jealousies left behind, the family transforming into a fully conscious, mature and concrete structure."),
        30: ("An unsealed letter", "Absolute transparency! A free phase in which secrets, masks and hidden agendas vanish entirely, and hearts open to one another to be read honestly and without censorship.")
    },
    "Basak": {
        1: ("An animal's hide on a man's head", "The ability to tame your own primitive, animal-like drives or raw energy with discipline, work and practical intelligence, and to wield them in a higher form."),
        2: ("A white cross in a wide plain", "Realizing that sacrifice and service within the family are not a burden, but the fundamental pillar that upholds the family's lasting peace, its sacred dimension."),
        3: ("Two angels, ready to help", "At the very moments you are most stuck, most striving to perfect, the universe opening the door with a practical solution and an intuitive aid."),
        4: ("A young man's imagination turning into reality", "The family's dreams and ideas becoming a concrete work, a home, a success, through labor, attention to detail and practical steps."),
        5: ("A man holding a book of fairy tales full of dreams", "The art of living within the practicality of daily life without forgetting that fairytale and divine root of love."),
        6: ("A ballroom filled with ornaments", "Aesthetics in detail; the achievement of managing the family's daily order with such care and perfection that it resembles a work of art or a dance."),
        7: ("A table set with two glasses of wine", "Within the practical rush of daily life, the karmic value of those small yet quality moments of sharing you set aside for one another."),
        8: ("A girl feeding her pet birds", "The tender, regular nourishment and protection of the family's small, vulnerable parts in need of attention, the childlike side, the fragile aspects."),
        9: ("A painter painting himself", "Observing the family and yourself from an outside eye, with the meticulousness of an artist; revising errors on the spot in the pursuit of perfection."),
        10: ("A two-headed man contemplating life", "Using logic and intuition at once; the faculty of focusing simultaneously on practical affairs and on the family's future spiritual needs."),
        11: ("An untouched valley gleaming with the dawning of a new day", "Old crises and errors dissolving through Virgo's analytical purity; the cleanliness of making an utterly fresh start each morning."),
        12: ("A man seeking his treasure", "Within the family's daily tasks, home, work and routine, realizing that the great karmic treasure you seek, spiritual maturity, lies hidden."),
        13: ("A statesman speaking before the public", "Representing the family's order, rules and vision before the outer world; a disciplined and respected family life, like an institution."),
        14: ("A family album being photographed", "Standing against the flow of time; recording each phase, memory and lesson of the family with discipline, and carrying it to the future as a legacy of lived experience."),
        15: ("A little girl playing with dolls", "Resolving the family's responsibilities, roles and crises with a playful seriousness, without judgment or blame, experiencing them as though in a simulation."),
        16: ("Fertile soil formed after a volcanic eruption", "The greatest crises, the eruptions, when processed with Virgo's analytical power, become the most fertile soil, the very experience that will nourish your family in the future."),
        17: ("A clergyman praying for his people", "Daily service within the family turning into an act of worship; the awareness that filling one another's gaps or establishing order is, in truth, blessing one another's souls."),
        18: ("A researcher working in a great library", "The desire to decode the family's karmic codes; investigating one another's past, psychology and the very reason this family exists, with scientific and analytical rigor."),
        19: ("A blossoming pomegranate tree", "Beneath a practical and plain appearance, a multitude of fertile seeds and vital energy lie hidden; the overflowing of the family's potential."),
        20: ("A peasant harvesting his field", "The day every kind of karmic labor worked, planned and woven stitch by stitch is repaid in full, on time and in abundance."),
        21: ("A girls' basketball team", "Working in coordinated fashion toward a shared goal; a team where everyone performs their role flawlessly, with no ego conflict, running like clockwork."),
        22: ("A royal guard bearing the royal coat of arms", "Unshakeable fidelity and devotion to the system; safeguarding the family's values, order and private world against external dangers with steely discipline."),
        23: ("A man cleaning a cage in a zoo", "The wild, uncontrolled or animal-like instincts within the family being domesticated through meticulous cleanliness and discipline, so as not to harm the system."),
        24: ("A sentry keeping watch at the gate of a great palace", "Controlling entry into and exit from the family's sacred home; firm and secure boundaries over who, or which energies, may enter this realm."),
        25: ("A man weeding his garden", "Purifying the family's spiritual soil of weeds, toxic thoughts and anxieties; nourishing the bond only with what is pure and functional."),
        26: ("Unripe fruits hanging on a tree", "The family's plans or dreams not yet having reached their time; the discipline of waiting patiently, without haste, for them to ripen regularly, for their harvest."),
        27: ("A teapot gleaming in the sunlight", "Sanctifying the family's daily ritual; the mastery of turning even an ordinary cup of tea into a moment of magnificent peace and healing."),
        28: ("A monk with his bald head bowed", "The complete retreat of the ego within the family; intellectual pride giving way to silent service and profound humility."),
        29: ("A man emerging through a hidden door", "Surmounting the family's problems, crises and blockages by way of a practical, ingenious and hidden path, a method that no one else has noticed."),
        30: ("A star broom sweeping the sky", "The family's karmic purification! Virgo's meticulous discipline has cleansed even the karmic dust and accumulated residue of the heavens, rendering the bond as crystal-clear as glass.")
    },
    "Terazi": {
        1: ("An arrow sign with an arrow on a butterfly's wing", "Determining the family's emotional or mental orientation, the arrow; perceiving toward which karmic goal the exchange between you is ultimately directed."),
        2: ("A man holding six shimmering orbs of light", "The faculty of holding the fundamental forces of life, the spheres of light, in balance, and of governing them with a shared aesthetic."),
        3: ("A new day being born in a forest at dawn", "A fresh beginning that wipes away all the weights of the past; the discipline of the family beginning each new day with a clean page and with hope."),
        4: ("A man departing from a group to go his own way", "The art within the family of preserving individual freedom and an original character while becoming we; to be devoted, not dependent."),
        5: ("A brilliant ring containing a goblet of wine", "That sacred inner wholeness brought by togetherness; embracing one another like a completed ring and savoring the taste of this bond."),
        6: ("A small statue containing the figure of a man", "Leaving a lasting, noble and aesthetic mark on one another's lives; the family being remembered in the world like a concrete work of art."),
        7: ("A sky standing utterly still before a storm", "That critical, silent and serene moment of observation before the crises; sensing the approaching karmic change intuitively, without argument, and taking precautions."),
        8: ("A group warming themselves by a fireplace", "Even in the coldest crises, the ability to keep the family's inner warmth, its trust and its quality of being a home alive through one another's presence."),
        9: ("Three master artists working in their own studios", "For the family's shared vision, each side producing its own talents, intelligence and labor independently yet in harmony."),
        10: ("A group building a canoe", "In the family's flow, everyone paddling to the same rhythm; calming the conflicts and moving in synchronization toward a single karmic direction, a single goal."),
        11: ("A man with a light in his eyes", "Inner illumination! Seeing the family's problems, the other's intentions and the universal message with a vision far deeper than what is visible."),
        12: ("A diamond freshly mined", "The family's raw and unprocessed potential being polished through challenges into a true, priceless and enduring value."),
        13: ("A man standing in the sun with his hat removed", "Egos stepping completely aside; that deep, maskless and humble surrender to one another and to the karmic course."),
        14: ("Two angels speeding toward one another in the sky", "Those moments when the family is supported by a divine hand; crises finding resolution through miraculous, seemingly coincidental help."),
        15: ("Baby birds gathered in a nest", "That phase when the family is most vulnerable, most childlike and most in need of protection; sheltering the child within one another and raising it with trust."),
        16: ("A man holding a compass", "The skill of charting the family's karmic course without deviation, in accordance with the universal compass of conscience and truth."),
        17: ("A man lost in a dense forest", "A period of confusion and uncertainty within the family! The risk of being swayed by the outer world, by others' opinions, and drifting from your own karmic center."),
        18: ("An empty suit of armor hanging on the walls of an old castle", "The past's defense mechanisms becoming unnecessary; the courage to stand before one another defenseless, without masks."),
        19: ("A group of people examining a work of art", "Awareness of how the family appears to the outside; objectively evaluating the family's value, aesthetics and success."),
        20: ("A season in which all flowers bloom", "The peak of creativity, love and sharing within the family; the point where everything runs smoothly and beauty and abundance overflow."),
        21: ("A pine tree standing erect amid a storm", "Even under the most jarring external influences, the bond between you bending yet never breaking; the unshakeable power of your roots."),
        22: ("A sacred fire burning on a hilltop", "The family's karmic purpose being so clear and so high that all can see it; the power to warm the world with a shared faith."),
        23: ("A cat observing itself in a mirror", "The distinction between me and you becoming clear within the family; the awareness of seeing both your own flaws and your own beauties in your child's eyes."),
        24: ("An old key held in a man's hand", "Accessing that very special, ancient wisdom or method which will open all the family's locked karmic doors."),
        25: ("An eagle soaring in the sky", "The family rising far above worldly cares; seeing perspective, foresight and the karmic wholeness from above, with a godlike gaze."),
        26: ("A serpent in the talons of an eagle", "Crisis, manipulation or fear, the serpent, being neutralized and turned into healing by the family's highest vision, the eagle."),
        27: ("The laughter of children playing in a garden", "Amid seriousness and responsibilities, the imperative to preserve the family's purest, most joyful, childlike delight; happiness is a choice."),
        28: ("A man arranging the shelves of a library with great care", "Setting the family's past, its memories and its learned lessons into mental order; keeping recollections as accumulated wisdom."),
        29: ("A horizon line burning at sunset", "The closing of an era! That enchanting transitional interval before one phase of the family ends and a new, entirely different level begins."),
        30: ("An actor playing his role on the world stage", "The family's karmic duty in the universal theater; just as everyone has a role, so too the divine message your family represents in the world, played honestly.")
    },
    "Akrep": {
        1: ("A watching eye gleaming in the midnight sky", "Every moment of the family being under universal observation; that vigilant stance in which fidelity and intention are tested in the deepest layers."),
        2: ("The scent of essence seeping from a broken bottle", "An old pain or a suppressed feeling being released, utterly changing the family's atmosphere; the beginning of the healing process."),
        3: ("A wild house cat being tamed", "The test of bringing the family's rebellious, uncontrollable and free-spirited aspects into the home and the system, with compassion and patience."),
        4: ("A young man reading papers by candlelight", "The ability to read the family's karmic contracts, hidden intentions and one another's spiritual maps clearly, even in that darkness."),
        5: ("A jellyfish on a self-sufficient, isolated rock", "Even in moments of crisis, the family standing on its own inner resilience and self-sufficiency, without support from outside."),
        6: ("Workers toiling in a gold mine", "Digging through the family's hardships to bring to light those hidden, priceless and noble treasures, the gold, within one another's character."),
        7: ("A diver above the depths of a deep lake", "Fearlessly diving into the dark and uneasy depths of feeling, and surfacing the karmic mysteries or wounds hidden there, for one another."),
        8: ("A lake reflecting the light of the moon", "The family being illuminated not by the sun's direct brilliance but by the soft, mystical and intuitive wisdom peculiar to the night; the souls conversing in the dark."),
        9: ("A giraffe admiring its own reflection", "That fine line between me and us within the family; the courage to see in your child's eyes not only your soul's beauty but also your own shortcomings."),
        10: ("A group of people rescued after a great disaster", "The miracle of surviving great karmic crises; being rescued by a divine hand even in the darkest moment when the family seemed about to collapse."),
        11: ("A bird waiting on a branch after a storm", "That absolute silence following crisis-ridden, stormy processes; the peaceful moment of waiting when fear has given way and you are, at last, safe."),
        12: ("A student searching for forbidden books in a great library", "The desire to courageously bring to the surface and confront the family's taboo, unspoken or deeply hidden feelings."),
        13: ("A giant ship taking shelter in a harbor during a storm", "Before the outer world's crises and social pressures, the power of the family to take refuge, protected, within its own unshakeable and safe harbor, in one another."),
        14: ("Deep forests of passion within a person", "The family's indescribable, uncontrollable and wild passion; using this fire not to burn one another but to conquer the world together."),
        15: ("A tribe celebrating rebirth", "After a great destruction or the fear of separation, the family being reborn far stronger, wiser and more sealed, rising from its ashes."),
        16: ("A girl dancing alone in a meadow", "Within the family, the ability to preserve your own spiritual joy apart from your child's world; the skill of remaining independent yet united in love."),
        17: ("An artist in search of himself", "Using the child as a mirror within the family, completing the missing fragments of your own soul and thus traveling toward wholeness."),
        18: ("A bridge over a quietly flowing river", "Emotional passages! Reaching one another across crisis-ridden waters by building a bridge of unshakeable logic and diplomacy."),
        19: ("A man talking to his own shadow", "Without judgment, using the dark sides your child reflects back to you as a means of making peace with your own shadow."),
        20: ("An old temple ceremonially burned", "Old beliefs, a finished way of life or a past karmic cycle being set alight and turned to ashes in a grand ritual, for the well-being of the family."),
        21: ("An architect building a giant city in his inner world", "That magnificent shared home the family builds not outward, but within the boundless, vast and rich world of one another's souls."),
        22: ("The phoenix rising from the flames", "Absolute destruction and resurrection! At the point where the family was said to be completely finished, by a miracle all pains turn into healing, and life is born again in a far higher form."),
        23: ("A dead crow lying in a field", "Fears, doubts and old dark thoughts, the crow, whose function has ended, departing from your family forever; a purification."),
        24: ("A man holding a glimmering sacred chalice", "The spiritual elixir distilled from the family's hardest crises; that karmic life-healing, drunk with absolute fidelity and love."),
        25: ("A flashlight sweeping back and forth between two poles", "Moving between emotional extremes, love and anger; yet, no matter what happens, the endeavor to light one another's path like a flashlight."),
        26: ("A mountaineer standing firm at the edge of a chasm", "At the family's most extreme, most dangerous and most crisis-ridden point, the mastery of holding that noble and unshakeable balance without falling or veering."),
        27: ("Lightning tearing the darkness of the night", "A very hidden, deeply concealed karmic truth of the family emerging in full clarity through an unexpected, shattering and illuminating event."),
        28: ("Waters boiling of their own accord in a river", "Anger or passion accumulating in the family's depths, seething within unnoticed from outside; the need to heal it before it erupts."),
        29: ("A group of people awaiting the sunrise", "Reaching the end of the darkest karmic cycle; patiently awaiting, with faith in one another, the beginning of a new and luminous era."),
        30: ("The two pans of a perfectly balanced scale", "From Scorpio's boundless crisis-ridden depths, arriving at last at an absolute spiritual balance and truth; that final karmic station.")
    },
    "Yay": {
        1: ("A dim star shining in the night sky suddenly exploding into a nova", "A potential or vision long dormant within the family suddenly exploding, and becoming a karmic guide that illuminates your child's entire life."),
        2: ("A white nun warming her face with her hands by a hot hearth", "Even in the family's most crisis-ridden, cold and uncertain moments, the miracle of a woman finding her own spiritual warmth in the presence of the child, with unshakeable faith."),
        3: ("Two people taking their first step into a new country", "Passage into an utterly undiscovered new dimension within the family; that first, brave karmic step of discovery, as old habits break and boundaries are crossed."),
        4: ("An immigrant preserving his traditions in a distant country", "While the family strives to adapt to the outer milieu, society or standards, its true struggle is to cling to its own roots and original philosophy."),
        5: ("A sage following his own inner light", "Regardless of what the outer world says, drawing the family's karmic course by trusting only that shared, divine guidance, that faith, between you."),
        6: ("A man begging at the door of an old church", "The family's test of faith and gratitude; the need to escape the trap of not valuing what you hold and ceaselessly focusing on lack."),
        7: ("A man on the seashore gazing at a vast ocean", "Perceiving the family's immense, boundless karmic potential; dissolving small problems within the vastness of the ocean."),
        8: ("An inscription carved on a stone, nearly effaced", "A karmic warning from the past or an ancient teaching being remembered again, in a message that will change the family's course."),
        9: ("A group of students traveling the world", "The family perceiving life as a realm of learning; traveling the world together, reading books, or embarking on a philosophical journey is your greatest shared bond."),
        10: ("Actors rehearsing on an old theater stage", "The family being in a constant state of growth and rehearsal on the stage of life; staging life with joy and mastery, without fretting over mistakes."),
        11: ("A ship guided at sea by a glowing lighthouse", "In dark, uncertain and stormy karmic passages, finding your way by one another's vision; love clarifying like a compass."),
        12: ("A golden sun shining upon a flag", "The family's success and strength springing entirely from devotion to that shared faith and divine vision; a victory sealed in light."),
        13: ("A child stroking the head of a lion sleeping in peace", "The strongest, wildest and most untamed aspects of the family, the lion, being domesticated by compassion, the child, and schooled in love."),
        14: ("A colossal pyramid suspended in the sky", "The family possessing a divine order, an ancient geometry; founded upon a planned and karmic structure beyond all coincidence."),
        15: ("A farmer sowing seeds in the earth", "The awareness that the family's present difficulties are, in truth, the preparation for a future harvest of peace and success; sowing with patience."),
        16: ("A radiant city rising above the seas", "The family's attempt to build a utopia detached from reality, idealistic and imaginary; the test of how you will bring these dreams down to earth and make them livable."),
        17: ("A dervish turning within himself", "The family withdrawing from the outer world's commotion, finding peace only in its own inner rhythm and shared meditations; love turning into an act of worship."),
        18: ("A knight on the battlefield laying down his sword and praying", "Giving up the battle to be right! Even in the family's fiercest crises, the wisdom of laying down the weapons of ego and criticism and returning to unity."),
        19: ("Watching the world from the summit of a high mountain", "The family casting a distant, wise and serene gaze upon daily problems, trivial arguments and jealousies, as though looking from a mountain peak."),
        20: ("A missile rising into the sky", "The family, wholly freed from earthly constraints, leaping swiftly and with great power into a higher karmic dimension to realize its dreams."),
        21: ("A self-sufficient hermit", "A noble togetherness within the family in which, free of dependency, each keeps their own spiritual center, yet enriches the other's soul."),
        22: ("Babies playing in a meadow", "The family's purest, most selfless, most joyful first karmic phase, savoring simply the delight of existing; love in its most unadorned form."),
        23: ("A swan gliding over a lake", "The serene beauty of grace, nobility and love; the family never breaking its noble stance and aesthetic, even in crisis-ridden moments."),
        24: ("A man rummaging through dusty shelves in a great library", "The necessity of seeking and finding the family's missing karmic knowledge in the dusty memories of the past or in an ancient teaching."),
        25: ("A star falling from the heights", "An unexpected divine intervention; a miraculous, celestial sign that changes the family's course in a single moment and rewrites destiny."),
        26: ("A soldier holding his flag upright in a storm", "However great the crisis, the vow of remaining faithful to the family's principal aim, its values, and the bond to one another."),
        27: ("An artist dissatisfied with his own work, destroying it", "The test of perfectionism! The courage to tear down utterly, and rebuild from zero, certain things or certain aspects of the family in order to create something better."),
        28: ("Red roses blooming in a garden, unfading even in winter", "The family, even under the most impossible conditions and in the most crisis-ridden of seasons, preserving and continuing to live its red, its passion and love."),
        29: ("The sun sinking and swallowing the sea at the horizon", "The closing of a karmic era; all the family's known forms being buried in darkness before a new and far brighter dawn."),
        30: ("Two angel-like people holding hands in the sky", "The Karmic Seal! Two souls, having completed their earthly roles, unite forever under a wholly divine contract, in a love that is timeless and beyond space.")
    },
    "Oglak": {
        1: ("An Indian chief governing his own tribe", "The family establishing a hierarchical order within itself; the skill of governing the responsibilities, roles and boundaries of shared life with a noble authority."),
        2: ("Three rose windows, one of them broken", "A crack or imperfection in the family's perfectionist structure! This flaw allowing the family to let even more light shine outward."),
        3: ("The human soul leaving its physical body for new experiences", "The exalted phase in which the family sheds the earthly constraints, material burdens and rigid responsibilities, uniting solely for the soul's higher purposes."),
        4: ("A man dancing in his own world amid a group celebration", "Within the family, fulfilling the social obligations of community and kin, yet remaining spiritually faithful to one's own karmic center and to the child."),
        5: ("Natives making a canoe", "Navigating the harsh, swiftly flowing crisis-ridden waters of life, without losing the rhythm, advancing toward the goal with trust in one another."),
        6: ("A black bird turning into a white bird", "Karmic alchemy! The family's dark, skeptical or fear-filled energies, purified through unshakeable fidelity and discipline, turning into a pure, white healing."),
        7: ("A very old man working in a library", "The family using all its accumulated experience, lived moments and karmic lessons as sources of wisdom with which to build the empire of the future."),
        8: ("A woman watching the sunrise in her home", "Each day, after every crisis, keeping alive the faith in the family's potential and in that clean, orderly, disciplined peace the new dawn brings."),
        9: ("An Indian warrior throwing a javelin", "The family's goals, dreams and shared projects being hurled at the target, the javelin, with sharp focus, full power and disciplined effort."),
        10: ("An old diamond set anew in a fresh surface", "The family's seasoned, experienced and storied worth being polished once more and presented in today's world, with a new status and a new form."),
        11: ("A group of people awaiting the sovereign in a great palace", "The high standards and authority the family establishes within itself; the outer world and the crises respecting this unshakeable authority."),
        12: ("A bird building its own nest", "The most fundamental responsibility! Weaving every straw and every detail of the family into a nest, with unshakeable trust, labor and a long-term plan."),
        13: ("A group of people singing", "The family's rules and responsibilities being fulfilled not merely as a duty but with joy and harmony, in song; discipline turning into art."),
        14: ("A fish standing upon a great rock", "The family uniting its emotional, fish-like nature with the unshakeable power of earth and discipline, the rock, and pouring emotions into a concrete achievement."),
        15: ("A seed awaiting its rebirth", "The family's winter, its crisis; in this frozen, silenced season, in truth, lies the hidden, strong and deep preparation of the roots."),
        16: ("An accountant working at a desk", "The family's honest accounting; who gives what, who takes what, what are the karmic debts? An honest reckoning and a rational ordering."),
        17: ("A beacon burning on a distant hill", "The duty of being an unshakeable direction, trust and steadiness, a beacon, to the family's surroundings, to others, or to one another in moments of crisis."),
        18: ("A sentry watching outward from within an old castle", "The discipline of guarding the family's values and privacy, around the clock, against every kind of danger that may come from without."),
        19: ("A self-sufficient, noble stance", "You are together not because you need the child, but because you have chosen one another. A noble companionship, free of ego dependency."),
        20: ("A granary stocked with provisions enough for the whole winter", "The family's planning for the future, for crisis; your trust in one another and your resources being solid enough to keep each other standing in hard days."),
        21: ("A colossal snow-clad mountain being climbed", "The family's most exalted, most magnificent, most arduous karmic goal; ascending without letting go of one another's hand, scorning every difficulty."),
        22: ("A soldier holding his flag upright in a storm", "The seal of fidelity! However great the crisis, the vow of remaining faithful to the family's principal aim, its values and the bond to one another."),
        23: ("A man rummaging through dusty shelves in a library", "The necessity of seeking and finding the family's missing karmic knowledge in the dusty memories of the past or in an ancient teaching."),
        24: ("A perpetual fire burning at a holy altar", "The continuity of the family's labor; not a love of a single day, but that sacred flame of service and devotion burning for a lifetime."),
        25: ("Two angel-like people holding hands in the sky", "The Karmic Seal! Two souls, having completed their earthly roles, unite forever under a wholly divine contract, in a love that is timeless and beyond space."),
        26: ("A man finding peace in a hut he built with his own hands", "The family drawing away from the outer world, the commotion and the hunger for status, and finding its peace only in the simple and honest home you have built together."),
        27: ("A man on a mountain peak illuminating the world with his torch", "The level of wisdom the family has attained; having found its own peace, at the same time becoming a karmic exemplar to other families."),
        28: ("Waters boiling of their own accord in a river", "Calm without, deep within; the family's deepest karmic sediments undergoing, silently yet with immense force, a process of purification and transformation."),
        29: ("A horizon line burning at sunset", "The closing of an era! That transition before one phase of the family ends and it moves to a new and entirely different status, an empire."),
        30: ("The two pans of a perfectly balanced scale", "From Capricorn's rigid, disciplined and worldly structure, arriving at last at an absolute spiritual balance and divine justice; the final station.")
    },
    "Kova": {
        1: ("An old mission chief telling the tribe his new visions", "Stepping outside the family's routine; together with the child, forging a radical, freedom-loving and boundary-pushing new vision of shared life for the future."),
        2: ("An umbrella sheltering from the storm, two people beneath it", "While the world's chaos, the storm, rages outside, the unshakeable mental trust you feel for one another within the family's own peculiar, independent and intellectual refuge."),
        3: ("A fresh waterfall spilling into a lake in the valley", "A current of electric passion that never lets feelings grow stagnant, that constantly renews, refreshes and keeps the mind alert."),
        4: ("A priest lighting a sacred fire for a holy ritual", "Turning the family's daily ordinariness into a ritual; using love not only as something physical but as an instrument of universal knowledge and service."),
        5: ("A man following his own inner voice", "Within the family, trusting neither what others say nor social patterns, but only that unique, extraordinary karmic voice, that instinct, between you."),
        6: ("An actor on stage playing a role in a white mask", "The family living not with social masks but with an entirely honest self; the phase in which the roles end and truth begins to be spoken."),
        7: ("A child sunbathing on the rocks by the sea", "Keeping joy, freedom and that childlike creativity even amid the difficulties, the rocks; the faculty of finding peace within the crises."),
        8: ("A man with dusty clothes sitting in a beautifully arranged garden", "Inner wealth having no need of outer appearance or status; the realization that the family's essence is far more precious than how it appears from without."),
        9: ("A flock of birds flying against the storm", "However great the obstacles, the family defying the storm with that independent spirit which acts on a group consciousness and rejects all boundaries."),
        10: ("A man walking on a balance beam blindfolded", "The family's unshakeable trust! Even with your eyes closed, in absolute surrender, the resolve to walk that balance within a world the child guides."),
        11: ("A studio where muses dance", "The family being not merely a shared life but a common center of creation; beautifying the world by producing, writing or drawing together."),
        12: ("A single page surviving a library where all the books burned", "Old teachings, traditional patterns of love or lived experiences collapsing; continuing onward with that one remaining, pure and true truth of love."),
        13: ("A scientist observing the stars through a telescope", "The family transcending worldly cares, and the desire to read one another's purpose in life and karmic course out to the farthest galaxies."),
        14: ("A colorful kite soaring in the sky", "The family's power to rise, to lighten and to remain flexible through every hardship; your bonds liberating you rather than nailing you to the world."),
        15: ("A beacon standing atop a high mountain", "The family illuminating both its own path and serving as a beacon of freedom and love to the other families around it, to society."),
        16: ("A choir singing in two different languages", "The family's harmony! That unusual wealth that emerges when the unique voice born of difference meets in a single karmic melody."),
        17: ("A puppy training itself", "The discipline within the family of learning from mistakes; that independent structure which, without anyone's external intervention, resolves its own crises by itself."),
        18: ("A watchmaker cleaning the inner workings of an old clock", "Repairing, with great meticulousness, the mechanical and mental frictions of the family, so that time and the karmic cycles function flawlessly."),
        19: ("An explorer discovering the ocean within himself", "The family being not merely a physical union but a journey of exploring the boundless, unknown and mysterious oceans within one another's subconscious."),
        20: ("A visionary shattering all boundaries", "The family utterly repudiating the patterns society imposes upon it, and founding its own karmic model of existing together."),
        21: ("A self-sufficient statue that speaks", "A noble, individual togetherness that has no need of the outer world's approval; able to create its own beauty, its own value and its own silence."),
        22: ("A giant cloud radiating light", "The family's passage from one form into another; shedding concrete and rigid responsibilities, becoming a pure field of energy and inspiration."),
        23: ("A full moon reflected upon a pond", "The family's reflection in the world being in flawless harmony with the karmic plan above, the moon; the union of intention and action."),
        24: ("A musician playing an instrument he fashioned with his own hands", "The family's music, its harmony, being produced not by anyone else but entirely by its own labor, its own rules and its own instruments."),
        25: ("Orchids blooming among the ruins of an old temple", "The family's old crises and destructions now being covered, healed, with life's joy and a rare beauty, the orchid."),
        26: ("Curiosity gleaming in a man's eyes", "Questioning and discovery never ending; the imperative to rediscover the family each day with the excitement of seeing the child for the very first time."),
        27: ("A flower wet under the rain", "Emotional purification; in the family's most intense and at times harsh, rainy processes, the truth that you are in fact cleansing one another and making each other more spiritually alive."),
        28: ("A man with only his own footprints in an endless snow", "The brand-new karmic path opened within the family, walked by no one before; a future entirely yours, entirely original, entirely undiscovered."),
        29: ("Colored lights dancing in the sky, the Northern Lights", "The family attaining spiritual maturity; the bond transcending earthly words, becoming a veritable symphony of energy."),
        30: ("A man walking the world stage with a method entirely his own", "The family becoming a school, an archetype; existing in the world with your own karmic rhythm, obeying no rule, no fashion and no social pressure.")
    },
    "Balik": {
        1: ("A public marketplace displaying a communal trading area", "The family's test of complete transparency instead of private secrets, and of existing honestly in the shared living space."),
        2: ("Squirrels playing with one another in a tree", "The virtue of living that first, pure and innocent joy within the family, simply delighting in one another's presence, without any karmic burden."),
        3: ("A petrified tree trunk", "The family's unshakeable resistance to the erosions of time; the bond having taken a form as enduring as if carved into history."),
        4: ("A sunny day on a small island", "That karmic refuge of the family, sealed off from the outer world, the commotion and the crises; filled only with your own peace and light."),
        5: ("A mysterious priest living within his inner world", "Accepting that you can never entirely fathom the child; respecting the mysterious and untouchable sacred realms in one another's soul."),
        6: ("A magician holding a magic wand", "The mastery of resolving the family's crises and blockages not by rational means, but only through the great spell of divine love, through compassion."),
        7: ("Fishermen on the seashore mending their nets", "Honestly repairing the family's emotional weariness, the nets; rather than lacerating one another, gently stitching and mending the wounded places."),
        8: ("Two lovers sitting silently on a bench at sunset", "That absolute peace and spiritual wholeness that requires no word and no deed; simply the serene fulfillment of existing side by side."),
        9: ("A jellyfish glowing with its own light", "Even in the family's dark and crisis-ridden karmic processes, the ability to ignite the pure, mystical light within itself and guide one another by it."),
        10: ("A child praying beneath the stars", "Entrusting the family's entire destiny, its future and one another to the universe's infinite compassion, to the Creator, with absolute trust in the divine flow."),
        11: ("The door of a radiant, mystical temple", "The family transcending being merely a family, and becoming a shrine in service of a divine purpose, a shared spiritual aim."),
        12: ("A seagull gliding over the seas", "Preserving freedom amid even the greatest crises; making of the family not a prison, but wings that carry one another's soul toward the sky."),
        13: ("The cleaning of an old painting", "Tenderly wiping away the dust and disappointments accumulated over the family's earlier phases, restoring the vibrant brilliance of its first days."),
        14: ("An astronomer observing the stars", "Charting the family's karmic course not by daily woes but by the immense and immutable guidance of the stars, the universal laws."),
        15: ("A group of people bathing in a river", "Emotional purification! The family washing away all its heaviness, its anger and the sediment of the past, immersed completely in one another's compassionate waters of love."),
        16: ("A girl dancing alone in a meadow", "Even within the family, preserving your own spiritual joy and independence, making love a source of delight rather than an obligation."),
        17: ("A sage conversing with his own shadow", "Within the family, accepting everything you see in the child as a reflection of your own shadow, and achieving wholeness through this mirroring."),
        18: ("A bridge over a quietly flowing river", "Emotional crossings; reaching one another across crisis-ridden waters by building a bridge of unshakeable logic and compassion."),
        19: ("An architect building a great city in his inner world", "The family dwelling far more in the boundless, rich and peaceful world of one another's soul than in the outer world."),
        20: ("The phoenix rising from the flames", "Absolute destruction and resurrection! At the point where the family was said to be finished, by a miracle all pains turn into healing, and life is born again in a far higher form."),
        21: ("A musician playing an instrument he made with his own hands", "The family's harmony being produced not by anyone else, but entirely from within, at that special, original frequency of its own."),
        22: ("Orchids blooming among the ruins of an old temple", "The family's old crises and destructions now being healed with a rare beauty."),
        23: ("Curiosity gleaming in a man's eyes", "Questioning and discovery never ending; the desire to rediscover the child anew each day."),
        24: ("A flower wet under the rain", "In the family's most intense and at times harsh, rainy processes, the truth that you are in fact cleansing one another and making each other more spiritually alive."),
        25: ("Only one's own footprints in an endless snow", "That original karmic path within the family which no one has walked; a future entirely yours, entirely undiscovered."),
        26: ("Colored lights dancing in the sky", "The family transcending earthly words, becoming a symphony of energy and light."),
        27: ("A man walking the world stage with a method completely his own", "The family becoming a school, an archetype; existing in the world with your own karmic rhythm, obeying no rules."),
        28: ("Waters boiling of their own accord in a river", "A deep emotional simmering within; anger or passion quietly yet powerfully turning into healing."),
        29: ("A horizon line burning at sunset", "The closing of an era! All the family's known forms now being buried in darkness before a far brighter dawn."),
        30: ("Two angel-like people holding hands in the sky", "The Karmic Seal! Two souls, having completed their earthly roles, unite forever under a wholly divine contract, in a love that is timeless and beyond space.")
    }
}