# -*- coding: utf-8 -*-
"""
Her gezegenin her burctaki ILISKI-DILLI yorumu (BAGIL HARITA baglamma).
Format: {("Gezegen", "Burc"): "Yorum metni"}

Bu yorumlar bagil harita analizinde kullanilir.
Her yorum kisiye ozel, somut, iliski odaklidir.
"Bu donemde" kalibi KULLANILMAZ (bagil harita olunecektir).
"""

FBST_YORUMLAR_BURC = {
    # === GUNES — Kisinin iliskideki kimligi, nasil parladigi ===
    ("Güneş", "Koç"): "Siz bu iliskide cesur ve oncu bir enerjiyle one cikiyorsunuz. Iliskinin yonunu siz belirliyor, ilk adimi atan hep siz oluyorsunuz. Partneriniz bu cesaretinizi hayranlikla izliyor ama bazen aceleci olmanizdan bunaliyor. Iliskideki en buyuk sinaviniz sabirli olmak — her seyi hemen simdi isteme egiliminiz partnerinizi yoruyor. Sabretmeyi ogrendiginizde ise bu iliskinin gercek motoru siz oluyorsunuz.",
    ("Güneş", "Boğa"): "Siz bu iliskide guvenilig saglam, guclu ve istikrarli bir temel olusturuyorsunuz. Sevginizi somut eylemlerle gosteriyorsunuz — yemek pisirmek, dokunmak, yaninda olmak. Partneriniz sizin guvenilirliginize hayran ama degisime direnmeniz zaman zaman gerilim yaratiyor. Iliskideki sinaviniz esnek ogrenmek — her seyin ayni kalmasini istemeniz iliskiyi bogabiliyor. Esneklastiginizde ise bu iliskinin en guclu limani siz oluyorsunuz.",
    ("Güneş", "İkizler"): "Siz bu iliskide zihninizi ve kelime yeteneginizi kullaniyorsunuz. Iliskiyi konusarak, tartisarak, fikir alisverisi yaparak yurutuyorsunuz. Partneriniz zekaniza ve espri anlayisiniza hayran ama bazen cok yuzeyel kaldiginizi dusunebiliyor. Iliskideki sinaviniz derinlesmek — konularin ustunu kosarak gecmeniz partnerinizi uzuyor. Derinlestiginizde ise bu iliskinin en parlak iletisim kaynagi siz oluyorsunuz.",
    ("Güneş", "Yengeç"): "Siz bu iliskide koruyucu, besleyici ve duygusal bir guc olusturuyorsunuz. Partnerinizi kucakliyor, evinizi yapiyorsunuz, sicak bir yuva kuruyorsunuz. Partneriniz sizi guvenli bir liman olarak goruyor ama bazen asiri korumaciliginizden bunaliyor. Iliskideki sinaviniz ozgur birakmak — her seyi kontrol etme ihtiyaciniz partnerinizi bunaltiyor. Ozgur biraktiginizda ise bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Güneş", "Aslan"): "Siz bu iliskide parildayan, dikkat ceken ve hayranlik uyandiran bir varliksiniz. Sevginizi buyuk, gosterisli ve tutkulu bir bicimde gosteriyorsunuz. Partneriniz bu enerjinize hayran ama bazen ego caprasmalarinda kaybolabiliyorsunuz. Iliskideki sinaviniz karsi tarafin da parlamaine izin vermek — iliskinin tek yildizi siz olma ısrarınız partnerinizi uzuyor. Alan tanidiginizda ise bu iliskinin en buyuk gucu oluyorsunuz.",
    ("Güneş", "Başak"): "Siz bu iliskide duzen kuran, analiz eden ve iyilestiren bir gucsunuz. Iliskiyi pratik adimlarla, kucuk dokunuslarla, hizmet ederek seviyorsunuz. Partneriniz sadakatinize ve caliskanliginiza hayran ama elestirilerinizin coklugundan yorulabiliyor. Iliskideki sinaviniz kendinizi de kabul etmek — kusursuzluk arayisiniz iliskiyi geriyor. Kusurlari guzel gordugunuzde ise bu iliskinin en ince guzelligini siz olusturuyorsunuz.",
    ("Güneş", "Terazi"): "Siz bu iliskide denge, uyum ve guzellik arayan bir ruhsunuz. Tartismalari bile zarif bir sekilde cozume ulastirabiliyorsunuz. Partneriniz zarafetinize ve adalet duygunuza hayran ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskideki sinaviniz net kararlar almak — her iki tarafin da gorusunu dinleme cabaniz sizi parcaliyor. Netlastiginizde ise bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Güneş", "Akrep"): "Siz bu iliskide derin, yogun ve donusturucu bir enerji tasiyorsunuz. Sevginizi tam veriyorsunuz — yari yolda birakmak yok. Partneriniz tutkunuza hayran ama kontrolculugunuzden korkabiliyor. Iliskideki sinaviniz guvenmek — her seyi denetim altinda tutma ihtiyaciniz iliskiyi boguyor. Guvenmeyi ogrendiginizde ise bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Güneş", "Yay"): "Siz bu iliskide ozgurluk, macera ve anlami temsil ediyorsunuz. Iliskiyi genis bir perspektiften goruyor, buyuk hayaller kuruyorsunuz. Partneriniz iyimserliginize ve hayata bakisiniza hayran ama taahhut vermekten kacinmaniz endise yaratiyor. Iliskideki sinaviniz somut adimlar atmak — surekli baska ufuklara bakmaniz partnerinizi güvensiz birakiyor. Topraklandiginizda ise bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Güneş", "Oğlak"): "Siz bu iliskide ciddi, sorumlu ve yapilandirici bir gucsunuz. Iliskiyi uzun vadeli planlarla, somut adimlarla, sabirla insa ediyorsunuz. Partneriniz kararliliginiza ve guvenilirliginize hayran ama duygularinizi gosterememeniz uzaklasma yaratiyor. Iliskideki sinaviniz acilmak — duvarlarinizin arkasina saklanmaniz partnerinizi uzuyor. Duygularinizi actiginizda ise bu iliskinin en saglam temelini siz kuruyorsunuz.",
    ("Güneş", "Kova"): "Siz bu iliskide ozgur, yenilikci ve vizyoner bir ruhsunuz. Iliskiyi esitlik, arkadaslik ve ozgurluk uzerine insa ediyorsunuz. Partneriniz vizyonunuza ve ozgunlugunuze hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskideki sinaviniz yakinlasmak — bagimsizlik ısrarınız partnerinizi uzaklastiriyor. Yakinlastiginizda ise bu iliskinin en ozel ve farkli bagini siz kuruyorsunuz.",
    ("Güneş", "Balık"): "Siz bu iliskide kosulsuz sevgi, merhamet ve manevi bir bag sunuyorsunuz. Sevginizi ruhsal bir boyutta yasiyor, karsinizdakini derinden anliyorsunuz. Partneriniz merhametinize ve sezgilerinize hayran ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskideki sinaviniz sinir koymak — kendinizi tamamen feda etme egiliminiz partnerinizi yoruyor. Sinir koydugunuzda ise bu iliskinin en guclu sevgi kaynagi siz oluyorsunuz.",

    # === AY — Duygusal ihtiyaclar, guvende hissettigi yer ===
    ("Ay", "Koç"): "Duygusal olarak hizli tepki veriyorsunuz — sevginizi de, ofkenizi de aninda gosteriyorsunuz. Partneriniz bu dogrudanlginizi seviyor ama bazen tepkilerinizin siddetinden sarsilabiliyor. Iliskide guvende hissetmeniz icin hizli cozumler ve net cevaplara ihtiyaciniz var. Uzun uzun bekleme sizi deli ediyor. Duygusal patlamalarinizi yonlendirmeyi ogrendiginizde bu iliskinin en guclu savascisi siz oluyorsunuz.",
    ("Ay", "Boğa"): "Duygusal olarak fiziksel dokunma, konfor ve istikrar uzerine kurulmus bir guvene ihtiyaciniz var. Sevginizi somut seylerle gosteriyorsunuz — yemek, sarilma, yaninda olma. Partneriniz size guvenebilmenin rahatligini yasatyor ama degisime karsi direnmeniz iliskiyi bogabiliyor. Iliskide guvende hissetmeniz icin rutin ve tekrar onemli. Degisimi kucuk adimlarla ogrendiginizde bu iliskinin en sicak yuvayi siz insa ediyorsunuz.",
    ("Ay", "İkizler"): "Duygusal olarak konusarak, paylasarak ve ogrenerek besleniyorsunuz. Ic dunyanizi kelimelerle ifade ediyorsunuz — duygularinizi yazarak, konusarak, tartisarak isliyorsunuz. Partneriniz zihinsel canliliginizi seviyor ama duygusal derinliginizin yuzeysel kalabildigini dusunebiliyor. Iliskide guvende hissetmeniz icin iletisim kesilmemeli. Duygularinizi da konustugunuzda bu iliskinin en parlak iletisim koprusunu siz kuruyorsunuz.",
    ("Ay", "Yengeç"): "Duygusal olarak ev, aile ve kokenleriniz uzerine kurulu bir guvene ihtiyaciniz var. Sevginizi evi isitmak, yemek pisirmek, sarilarak gosteriyorsunuz. Partneriniz sicakliginizi ve koruyuculugunuze hayran ama asiri duyarli olmaniz zaman zaman yorabiliyor. Iliskide guvende hissetmeniz icin guvenli bir yuvaya ihtiyaciniz var. Duygusal dalgalanmalarinizi yonlendirmeyi ogrendiginizde bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Ay", "Aslan"): "Duygusal olarak takdir edilmek, begenilmek ve goz onunde olmak istiyorsunuz. Sevginizi buyuk jestlerle, gosterisli sevgilerle sunuyorsunuz. Partneriniz tutkunuzu ve cimcirliginizi seviyor ama ilgiye olan acginiz bazen guvensizlik yaratiyor. Iliskide guvende hissetmeniz icin gozler uzerinizde olmali. Duygusal guveninizi icinizden beslediginizde bu iliskinin en parlayan yildizi siz oluyorsunuz.",
    ("Ay", "Başak"): "Duygusal olarak duzen, temizlik ve pratik cozumler uzerine kurulu bir guvene ihtiyaciniz var. Sevginizi hizmet ederek, duzenleyerek, yardimci olarak gosteriyorsunuz. Partneriniz caliskanliginizi ve sadakatinizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Iliskide guvende hissetmeniz icin her seyin yolunda olmasi gerekiyor. Kusurlari kabul ettiginizde bu iliskinin en ince guzelligini siz yaratiyorsunuz.",
    ("Ay", "Terazi"): "Duygusal olarak denge, uyum ve guzellik uzerine kurulu bir guvene ihtiyaciniz var. Herkesin mutlu oldugu, kimsenin kirmedigi bir iliski ariyorsunuz. Partneriniz zarafetinizi ve uyum yeteneginizi seviyor ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskide guvende hissetmeniz icin esitlik cok onemli. Kendi ihtiyaclarinizi da dillendirdiginizde bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Ay", "Akrep"): "Duygusal olarak derin, yogun ve mutlak bir bag ariyorsunuz. Sevginizi tam veriyorsunuz ama karsinizdakinden de aynisini bekliyorsunuz. Partneriniz sadakatinizi ve derinliginizi seviyor ama kontrolculugunuzden ve kiskancliginizdan yorulabiliyor. Iliskide guvende hissetmeniz icin derin guvene ihtiyaciniz var. Guvenmeyi ogrendiginizde bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Ay", "Yay"): "Duygusal olarak ozgurluk, genislik ve anlam uzerine kurulu bir guvene ihtiyaciniz var. Daralan, sinirlanan, rutine giren iliskiler sizi boguyor. Partneriniz iyimserliginizi ve hayata bakisinizi seviyor ama taahhut korkunuz endise yaratiyor. Iliskide guvende hissetmeniz icin buyuk resmi gormeniz gerekiyor. Topraklandiginizda bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Ay", "Oğlak"): "Duygusal olarak yapi, ciddiyet ve sorumluluk uzerine kurulu bir guvene ihtiyaciniz var. Duygularinizi gostermek size zor geliyor ama eylemleriniz konusuyor. Partneriniz guvenilirliginizi ve kararliliginizi seviyor ama duygusal mesafeniz uzaklasma yaratiyor. Iliskide guvende hissetmeniz icin somut adimlar onemli. Duygularinizi actiginizda bu iliskinin en saglam temelini siz insa ediyorsunuz.",
    ("Ay", "Kova"): "Duygusal olarak ozgurluk, esitlik ve arkadaslik uzerine kurulu bir guvene ihtiyaciniz var. Geleneksel iliski kaliplari size dar geliyor. Partneriniz ozgunlugunuzu ve vizyonunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskide guvende hissetmeniz icin arkadas gibi olmaniz gerekiyor. Yakinlastiginizda bu iliskinin en ozel bagini siz kuruyorsunuz.",
    ("Ay", "Balık"): "Duygusal olarak kosulsuz sevgi, fedakarlik ve manevi bag uzerine kurulu bir guvene ihtiyaciniz var. Sevginizi ruhsal bir boyutta yasiyorsunuz. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskide guvende hissetmeniz icin derin ruhsal bag onemli. Sinir koydugunuzda bu iliskinin en guclu sevgi kaynagi siz oluyorsunuz.",

    # === MERKUR — Iletisim dili, nasil anladigi/konusma bicimi ===
    ("Merkür", "Koç"): "Iletisimde hizli, dogrudan ve keskin bir dille konusuyorsunuz. Fikirlerinizi filtrelemeden soyluyorsunuz — bu durustulugunuz partnerinizi bazen urkutebiliyor. Iliskide tartismalar hizli baslayip hizli bitiyor. Partneriniz zekanizi ve cabuklugunuzu seviyor ama sert cikislarinizdan sarsilabiliyor. Kelimelerinizi secmeyi ogrendiginizde bu iliskinin en guclu iletisim motoru siz oluyorsunuz.",
    ("Merkür", "Boğa"): "Iletisimde yavas ama emin, somut ve guvenilir bir dille konusuyorsunuz. Her soylediginin arkasinda duran, bos konusmayan bir yapınız var. Partneriniz bu guvenilirliginize hayran ama konusma hizinizin yavasligi zaman zaman sabirsizlik yaratiyor. Iliskide somut konular, pratik cozumler onemli. Duygusal konulari da konusmayi ogrendiginizde bu iliskinin en saglam iletisim koprusunu siz kuruyorsunuz.",
    ("Merkür", "İkizler"): "Iletisimde cok yonlu, espirili ve zihinsel olarak canli bir dille konusuyorsunuz. Iliskiyi konusarak, ogrenerek, paylasarak yurutuyorsunuz. Partneriniz zekaniza ve esprilerinize hayran ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Iliskide bilgi alisverisi cok yuki. Dinlemeyi de ogrendiginizde bu iliskinin en parlak iletisim koprusunu siz kuruyorsunuz.",
    ("Merkür", "Yengeç"): "Iletisimde duygusal, empatik ve hassas bir dille konusuyorsunuz. Karsinizdakinin hislerini hemen anlıyorsunuz ama kendi duygularinizi acmakta zorlanabiliyorsunuz. Partneriniz empati yeteneginizi seviyor ama bazen cok kapali kalmanizdan sikayet edebiliyor. Iliskide gecmis konulari tekrar etme egiliminiz var. Gecmisi birakip bugune odaklandiginizda bu iliskinin en derin anlayis koprusunu siz kuruyorsunuz.",
    ("Merkür", "Aslan"): "Iletisimde gosterisli, etkileyici ve sahne aldiran bir dille konusuyorsunuz. Fikirlerinizi sunma biciminiz cok guclu — partnerinizi ikna etme kapasiteniz yuksek. Partneriniz hitabetinizi ve yaraticiliginizi seviyor ama her konuda hakli olma ısrarınız zaman zaman gerilim yaratiyor. Iliskide dinlemek de cok onemli. Karsi tarafin da fikrini onemsediginizde bu iliskinin en buyuk sahne sanatcisi siz oluyorsunuz.",
    ("Merkür", "Başak"): "Iletisimde analitik, detayci ve elestirel bir dille konusuyorsunuz. Her seyi ince ince analiz ediyorsunuz — bu durum iliskide hem guclu hem de yorucu olabiliyor. Partneriniz zekanizin derinligini seviyor ama elestirilerinizin cogunlugundan yorulabiliyor. Iliskide kucuk detaylari buyutme egiliminiz var. Ovgunuzu da ifade ettiginizde bu iliskinin en ince gozlemcisi siz oluyorsunuz.",
    ("Merkür", "Terazi"): "Iletisimde dengeli, zarif ve adil bir dille konusuyorsunuz. Her iki tarafin da gorusunu dinleyip dengelemeye calisiyorsunuz. Partneriniz adalet duygunuza ve zarafetinize hayran ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskide net kararlar almakta zorlanabiliyorsunuz. Netlastiginizde bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Merkür", "Akrep"): "Iletisimde derin, arastirici ve stratejik bir dille konusuyorsunuz. Yuzeyde kalmak size yetmiyor — her konuyu en derinine inecek sekilde analiz ediyorsunuz. Partneriniz zekanizin derinligini seviyor ama sirlar saklamaniz ve stratejik durusunuz zaman zaman guvensizlik yaratiyor. Iliskide acik ve seffaf olmak cok onemli. Sirlarini paylastiginizda bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Merkür", "Yay"): "Iletisimde genis, felsefi ve iyimser bir dille konusuyorsunuz. Buyuk resmi goruyor, detaylarda kaybolmuyorsunuz. Partneriniz iyimserliginizi ve genis perspektifinizi seviyor ama bazen cok genel kalmaniz somut cozumleri geciktiriyor. Iliskide buyuk hayaller kurmak onemli ama ayaklar yere de basmali. Somut adimlar attiginizda bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Merkür", "Oğlak"): "Iletisimde ciddi, stratejik ve yapilandirici bir dille konusuyorsunuz. Plan yapmayi, programlamayi, somut adimlar belirlemeyi seviyorsunuz. Partneriniz bu ciddiyetinizi ve kararliliginizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Iliskide duygulari da konusmak gerekiyor. Duygusal paylasimlari da arttirdiginizda bu iliskinin en guclu stratejisti siz oluyorsunuz.",
    ("Merkür", "Kova"): "Iletisimde ozgun, yenilikci ve siradisi bir dille konusuyorsunuz. Geleneksel dusunce kaliplarina uymuyorsunuz — fikirleriniz her zaman farkli ve ilginc. Partneriniz vizyonunuza ve ozgunlugunuza hayran ama mesafeli iletisim tarziniz sogukluk yaratabiliyor. Iliskide yakin iletisim de cok onemli. Sicaklastiginizda bu iliskinin en ozel ve farkli iletisim bagini siz kuruyorsunuz.",
    ("Merkür", "Balık"): "Iletisimde sezgisel, yaratici ve hayal gucu guclu bir dille konusuyorsunuz. Mantiksel analizden cok sezgisel kavrama gucunuz yuksek. Partneriniz hayal gucunuzu ve merhametinizi seviyor ama kelimelerinizi net secmekte zorlanmaniz anlasilmazlik yaratiyor. Iliskide net ve acik olmak cok onemli. Duygularinizi netlestirdiginizde bu iliskinin en derin ruhsal bagini siz kuruyorsunuz.",

    # === VENUS — Sevgi dili, nasil sevdigi ===
    ("Venüs", "Koç"): "Sevgiyi tutkuyla, cesurlukla ve eylemle gosteriyorsunuz. Kovalamak, elde etmek, yeni baslangiclar yapmak size zevk veriyor. Partneriniz bu tutkunuzu ve enerjinizi hayranlikla izliyor ama ilgiden dusmeniz endise yaratiyor. Iliskide monotonluk size gore degil — surekli canlilik, yenilik, aksiyon olmali. Sevginizi surekli taze tutmayi ogrendiginizde bu iliskinin en tutkulu sevgilisi siz oluyorsunuz.",
    ("Venüs", "Boğa"): "Sevgiyi somut eylemlerle, dokunarak, yemek yaparak, yaninda olarak gosteriyorsunuz. Guvenilir, istikrarli ve kalici iliskiler ariyorsunuz. Partneriniz sadakatinizi ve sicakliginizi seviyor ama sahipci olmaniz zaman zaman bogabiliyor. Iliskide guzel seylerin tadini cikarmak cok onemli — birlikte yemek, muzik, doga. Sevginizi paylastikca buyuyen bir iliski insa ediyorsunuz.",
    ("Venüs", "İkizler"): "Sevgiyi sohbet, espri ve zihinsel uyumla gosteriyorsunuz. Entelektuel bag sizin icin fiziksel cekim kadar onemli. Partneriniz zekanizi ve eglenceli iletisim tarzinizi seviyor ama cok degisken olmaniz guvensizlik yaratiyor. Iliskide monotonluk.size gore degil — surekli yenilik, ogrenme, paylasim olmali. Duygusal derinligi de kattiginizda bu iliskinin en eglenceli sevgilisi siz oluyorsunuz.",
    ("Venüs", "Yengeç"): "Sevgiyi koruyarak, besleyerek, kucaklayarak gosteriyorsunuz. Ev, sicaklik, yuva kavramlari cok onemli. Partneriniz sicakliginizi ve koruyuculugunuzu seviyor ama asiri baglanmaniz zaman zaman bunaltabiliyor. Iliskide guvenli bir liman olmak cok degerli. Sevginizi saglam bir temel uzerine kurduğunuzda bu iliskinin en guvenceli sevgilisi siz oluyorsunuz.",
    ("Venüs", "Aslan"): "Sevgiyi buyuk, gosterisli ve cimcirik bicimde gosteriyorsunuz. Hediye almak, surpriz yapmak, goz onunde olmak size zevk veriyor. Partneriniz cimcirliginizi ve tutkunuzu seviyor ama ilgiye olan acginiz guvensizlik yaratiyor. Iliskide gozler uzerinizde olmali — ama partnerinizin de parlamasi cok onemli. Alan tanidiginizda bu iliskinin en buyuk sevgi sahnini siz insa ediyorsunuz.",
    ("Venüs", "Başak"): "Sevgiyi hizmet ederek, duzenleyerek, yasamini kolaylastirarak gosteriyorsunuz. Pratik sevgi dili cok guclu. Partneriniz sadakatinizi ve caliskanliginizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Iliskide kusursuzluk arayisi iliskiyi bogabiliyor. Sevginizi kabul ettiginizde, kusurlari guzel gordugunuzde bu iliskinin en ince sevgilisi siz oluyorsunuz.",
    ("Venüs", "Terazi"): "Sevgiyi denge, zarafet ve guzellikle gosteriyorsunuz. Ilişkide esitlik, uyum, guzellik cok onemli. Partneriniz zarafetinizi ve adalet duygunuzu seviyor ama kararsizliginiz zaman zaman uzaklasma yaratiyor. Iliskide guzel seyler yasamak cok onemli — sanat, muzik, estetik. Sevginizi net bir sekilde ifade ettiginizde bu iliskinin en zarif sevgilisi siz oluyorsunuz.",
    ("Venüs", "Akrep"): "Sevgiyi derin, yogun ve mutlak bir bicimde gosteriyorsunuz. Sevginiz yari yolda birakmak yok — ya tam ya hic. Partneriniz tutkunuzu ve derinliginizi seviyor ama kiskancliginiz ve kontrolculugunuz zaman zaman bunaltabiliyor. Iliskide guven ve sadakat cok onemli. Guvenmeyi ogrendiginizde bu iliskinin en derin sevgilisi siz oluyorsunuz.",
    ("Venüs", "Yay"): "Sevgiyi ozgurluk, neşe ve macera ile gosteriyorsunuz. Iliskiyi eglenceli, genis ve anlamlı yasamak istiyorsunuz. Partneriniz iyimserliginizi ve cimcirliginizi seviyor ama taahhut korkunuz endise yaratiyor. Iliskide buyuk hayaller kurmak cok guzel ama topraklanmak da gerekir. Topraklandiginizda bu iliskinin en buyuk sevgi rehberi siz oluyorsunuz.",
    ("Venüs", "Oğlak"): "Sevgiyi eylemlerle, sorumlulukla ve pratik destekle gosteriyorsunuz. Sevginizi soyle degil, yaparak gosteriyorsunuz. Partneriniz guvenilirliginizi ve ciddiyetinizi seviyor ama duygusal acikliginizin eksikligi sogukluk yaratiyor. Iliskide duygusal paylasim da cok onemli. Duygularinizi actiginizda bu iliskinin en guvenilir sevgilisi siz oluyorsunuz.",
    ("Venüs", "Kova"): "Sevgiyi arkadaslik, esitlik ve ozgurluk uzerine insa ediyorsunuz. Geleneksel iliski kaliplari size dar geliyor. Partneriniz ozgunlugunuzu ve vizyonunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskide yakinlik da cok onemli. Sicaklastiginizda bu iliskinin en ozel sevgilisi siz oluyorsunuz.",
    ("Venüs", "Balık"): "Sevgiyi kosulsuz, fedakar ve manevi bir bicimde gosteriyorsunuz. Sevginizi ruhsal bir boyutta yasiyorsunuz. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskide sinir koymak cok onemli. Sinir koyabildiginizde bu iliskinin en guclu sevgi kaynagi siz oluyorsunuz.",

    # === MARS — Tutku bicimi, sinirlarini nasil korudugu ===
    ("Mars", "Koç"): "Tutkunuzu cesurca, dogrudan ve eylemseel bicimde ifade ediyorsunuz. Iliskide oncu sizsiniz — ilk adimi atan, sinirlari cizen, harekete gecen hep sizsiniz. Partneriniz bu enerjinizi ve cesaretinizi hayranlikla izliyor ama ofkenizin siddetinden sarsilabiliyor. Iliskide rekabet ve macera cok onemli. Enerjinizi yonlendirmeyi ogrendiginizde bu iliskinin en guclu savascisi siz oluyorsunuz.",
    ("Mars", "Boğa"): "Tutkunuzu sabirla, istikrarla ve somut eylemlerle ifade ediyorsunuz. Hizli degil, yavas ama emin adimlarla ilerliyorsunuz. Partneriniz guvenilirliginizi ve gucunuzu seviyor ama sahipci olmaniz zaman zaman sorun yaratiyor. Iliskide fiziksel dokunma cok onemli — sevginizi dokunarak, sarilarak, yaninda olarak ifade ediyorsunuz. Sabirli tutumunuz bu iliskinin en guclu temelini olusturuyor.",
    ("Mars", "İkizler"): "Tutkunuzu kelimelerle, tartismalarla ve zihinsel uyumla ifade ediyorsunuz. Iliskide konusmak, tartismak, fikir alisverisi yapmak cok onemli. Partneriniz zekanizi ve esprili iletisim tarzinizi seviyor ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Tartismalarda kelimelerinizi secmek cok onemli. Dengeli iletisim kurdugnuzda bu iliskinin en parlak iletisim savascisi siz oluyorsunuz.",
    ("Mars", "Yengeç"): "Tutkunuzu koruyarak, sahiplenerek ve duygusal bicimde ifade ediyorsunuz. Iliskide koruma, savunma, sahiplenme cok onemli. Partneriniz sadakatinizi ve sicakliginizi seviyor ama ofkenizi iceye dondurme egiliminiz zaman zaman sorun yaratiyor. Duygusal patlamalar yerine sagirim onemli. Duygularinizi saglikli ifade ettiginizde bu iliskinin en guclu koruyucusu siz oluyorsunuz.",
    ("Mars", "Aslan"): "Tutkunuzu gosterisli, tutkulu ve cesurca ifade ediyorsunuz. Iliskide goz onunde olmak, hayranlik uyandirmak cok onemli. Partneriniz cesaretinizi ve tutkunuzu seviyor ama ego caprasmalariniz zaman zaman gerilim yaratiyor. Iliskide partnerinizin de parlamasi cok onemli. Egonuzu yonlendirdiginizde bu iliskinin en buyuk tutku sahnesini siz insa ediyorsunuz.",
    ("Mars", "Başak"): "Tutkunuzu hizmet ederek, duzenleyerek ve pratik adimlarla ifade ediyorsunuz. Iliskide detaylara onem veriyorsunuz — her seyin yolunda olmasi cok onemli. Partneriniz caliskanliginizi ve sadakatinizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Ogrenme ve gelisme cok onemli. Kusurlari kabul ettiginizde bu iliskinin en ince gozlemcisi siz oluyorsunuz.",
    ("Mars", "Terazi"): "Tutkunuzu denge, uyum ve karsiliklilik uzerine insa ediyorsunuz. Iliskide esitlik cok onemli — her iki tarafin da esit sekilde katilmasi gerekiyor. Partneriniz zarafetinizi ve uyum yeteneginizi seviyor ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Cesur adimlar atmak cok onemli. Netlastiginizde bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Mars", "Akrep"): "Tutkunuzu derin, yogun ve mutlak bicimde ifade ediyorsunuz. Iliskide kontrol, guc ve derin bag cok onemli. Partneriniz tutkunuzu ve derinliginizi seviyor ama kontrolculugunuzden ve kiskancliginizdan yorulabiliyor. Guven ve sadakat cok onemli. Guvenmeyi ogrendiginizde bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Mars", "Yay"): "Tutkunuzu macera, ozgurluk ve anlami uzerine insa ediyorsunuz. Iliskide buyuk hayaller kurmak, yeni deneyimler yasamak cok onemli. Partneriniz iyimserliginizi ve cesaretinizi seviyor ama taahhut korkunuz endise yaratiyor. Topraklanmak da cok onemli. Somut adimlar attiginizda bu iliskinin en buyuk macera rehberi siz oluyorsunuz.",
    ("Mars", "Oğlak"): "Tutkunuzu sabirla, kararlilikla ve stratejik adimlarla ifade ediyorsunuz. Iliskide uzun vadeli hedefler cok onemli. Partneriniz kararliliginizi ve guvenilirliginizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Duygusal paylasim da cok onemli. Duygularinizi actiginizda bu iliskinin en guclu stratejisti siz oluyorsunuz.",
    ("Mars", "Kova"): "Tutkunuzu ozgurluk, yenilik ve toplumsal donusum uzerine insa ediyorsunuz. Geleneksel iliski kaliplari size dar geliyor. Partneriniz vizyonunuza ve ozgunlugunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Yakinlik da cok onemli. Sicaklastiginizda bu iliskinin en ozel bagini siz kuruyorsunuz.",
    ("Mars", "Balık"): "Tutkunuzu sezgisel, fedakar ve ruhsal bicimde ifade ediyorsunuz. Fiziksel mucadeleden cok manevi veya yaratici mucadele onemli. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Sinir koymak cok onemli. Sinir koydugunuzda bu iliskinin en guclu sevgi savascisi siz oluyorsunuz.",

    # === JUPITER — Iliskiye ne kattigi, genisleme alani ===
    ("Jüpiter", "Koç"): "Iliskiye cesaret, macera ve yenilik katmissiniz. Yeni baslangiclar, heyecan ve eylem enerjisi getiriyorsunuz. Partneriniz bu enerjinizi hayranlikla izliyor ama asiriya kacmaniz zaman zaman sorun yaratiyor. Iliskiyi genisleten, buyuten ve canli tutan sizsiniz. Bu genisleme enerjisini dengeli kullandiginizda bu iliskinin en buyuk sansi siz oluyorsunuz.",
    ("Jüpiter", "Boğa"): "Iliskiye bolluk, bereket ve somut degerler katmissiniz. Finans, guvenlik ve fiziksel konfor konularinda buyuk firsatlar getiriyorsunuz. Partneriniz guvenilirliginizi ve cimcirliginizi seviyor ama sahipci olmaniz zaman zaman sorun yaratiyor. Iliskiyi somut degerlerle buyuten sizsiniz. Bu bolluk enerjisini paylastikca bu iliskinin en buyuk bereket kaynagi siz oluyorsunuz.",
    ("Jüpiter", "İkizler"): "Iliskiye bilgi, iletisim ve zihinsel canlilik katmissiniz. Ogrenmek, ogretmek, paylasmak konularinda buyuk firsatlar getiriyorsunuz. Partneriniz zekanizi ve eglenceli iletisim tarzinizi seviyor ama cok konusup az dinlemeniz zaman zaman sorun yaratiyor. Iliskiyi zihinsel olarak buyuten sizsiniz. Dengeli iletisim kurduğunuzda bu iliskinin en parlak iletisim kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Yengeç"): "Iliskiye sicaklik, yuva ve aile degerleri katmissiniz. Evinizi buyutmek, aile kurmak, baglari guclendirmek konularinda buyuk firsatlar getiriyorsunuz. Partneriniz sicakliginizi ve koruyuculugunuzu seviyor ama asiri baglanmaniz zaman zaman bunaltabiliyor. Iliskiyi sicak bir yuvaya ceviren sizsiniz. Bu sicaklik enerjisini dengeli kullandiginizda bu iliskinin en buyuk guvenlik kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Aslan"): "Iliskiye tutku, eglence ve yaraticilik katmissiniz. Sanat, sahne ve eglence konularinda buyuk firsatlar getiriyorsunuz. Partneriniz cimcirliginizi ve enerjinizi seviyor ama ego caprasmalariniz zaman zaman gerilim yaratiyor. Iliskiyi eglenceli ve tutkulu kılan sizsiniz. Enerjinizi dengeli kullandiginizda bu iliskinin en buyuk eglence kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Başak"): "Iliskiye hizmet, pratik cozumler ve iyilestirme katmissiniz. Gundeşik hayati duzenlemek, sorunlari cozumlemek konularinda buyuk firsatlar getiriyorsunuz. Partneriniz caliskanliginizi ve sadakatinizi seviyor ama elestirel yaklasiminiz zaman zaman uzaklik yaratiyor. Iliskiyi pratik olarak buyuten sizsiniz. Ovgunuzu da ifade ettiginizde bu iliskinin en buyuk hizmet kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Terazi"): "Iliskiye denge, uyum ve guzellik katmissiniz. Iliskiler, ortakliklar ve estetik konularinda buyuk firsatlar getiriyorsunuz. Partneriniz zarafetinizi ve adalet duygusu seviyor ama kararsizliginiz zaman zaman sinir bozucu olabiliyor. Iliskiyi guzel ve dengeli kılan sizsiniz. Net kararlar aldiginda bu iliskinin en buyuk denge kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Akrep"): "Iliskiye donusum, derinlik ve buyuk kaynaklar katmissiniz. Cinsellik, ruhsal donusum ve ortak kaynaklar konularinda buyuk firsatlar getiriyorsunuz. Partneriniz derinliginizi ve tutkunuzu seviyor ama kontrolculugunuzden yorulabiliyor. Iliskiyi derinden donusturen sizsiniz. Guvenmeyi ogrendiginizde bu iliskinin en buyuk donusum kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Yay"): "Iliskiye ozgurluk, anlam ve macera katmissiniz. Felsefe, seyahat ve yuksek ogrenim konularinda buyuk firsatlar getiriyorsunuz. Partneriniz iyimserliginizi ve genis perspektifinizi seviyor ama taahhut korkunuz endise yaratiyor. Iliskiyi buyuk resimde buyuten sizsiniz. Topraklandiginizda bu iliskinin en buyuk rehber kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Oğlak"): "Iliskiye ciddiyet, sorumluluk ve uzun vadeli yapilandirma katmissiniz. Kariyer, statu ve uzun vadeli hedefler konularinda buyuk firsatlar getiriyorsunuz. Partneriniz kararliliginizi ve guvenilirliginizi seviyor ama cok is odakli kalmaniz duygusal baglari zayiflatabiliyor. Iliskiyi uzun vadede buyuten sizsiniz. Duygusal paylasimlari da arttirdiginizda bu iliskinin en buyuk guvence kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Kova"): "Iliskiye ozgurluk, yenilik ve toplumsal vizyon katmissiniz. Arkadaslik, sosyal projeler ve teknoloji konularinda buyuk firsatlar getiriyorsunuz. Partneriniz vizyonunuza ve ozgunlugunuza hayran ama mesafeli durusunuz sogukluk yaratabiliyor. Iliskiyi ozgurluk uzerine buyuten sizsiniz. Yakinlastiginizda bu iliskinin en ozel vizyon kaynagi siz oluyorsunuz.",
    ("Jüpiter", "Balık"): "Iliskiye maneviyat, sezgi ve kosulsuz sevgi katmissiniz. Sanat, muzik, meditasyon ve ruhsal pratikler konularinda buyuk firsatlar getiriyorsunuz. Partneriniz merhametinizi ve derinliginizi seviyor ama sinirlarinizin bulanik olmasi karisiklik yaratiyor. Iliskiyi ruhsal olarak buyuten sizsiniz. Sinir koydugunuzda bu iliskinin en buyuk manevi kaynagi siz oluyorsunuz.",

    # === SATURN — Iliskideki sinavi, nerede sinirlandigi ===
    ("Satürn", "Koç"): "Iliskide en buyuk sinaviniz sabirli olmak — hizli kararlar alma ve her seyi hemen isteme egiliminiz partnerinizi yoruyor. Cesaretiniz ve inisiyatif almaniz guclu ama sabirsizliginiz iliskiyi zedeleyebiliyor. Daha yavas, daha dusunceli adimlar attiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz sabretmeyi ogrenmek. Ogrendiginizde bu iliskinin en guclu motoru siz oluyorsunuz.",
    ("Satürn", "Boğa"): "Iliskide en buyuk sinaviniz degisime acilmak — surekli ayni seyleri yapma ısrarınız iliskiyi bogabiliyor. Istikrariniz ve guvenilirliginiz guclu ama esnek olmamaniz zaman zaman gerilim yaratiyor. Kucuk degisikliklere acildiginizda iliski cok daha canli bir hale geliyor. Sinaviniz esnek ogrenmek. Ogrendiginizde bu iliskinin en saglam temelini siz insa ediyorsunuz.",
    ("Satürn", "İkizler"): "Iliskide en buyuk sinaviniz derinlesmek — konularin ustunu kosarak gecme egiliminiz partnerinizi uzuyor. Zihinsel canliliginiz guclu ama yuzeyel kalmaniz zaman zaman uzaklik yaratiyor. Duygusal konularda da derinlestiginizde iliski cok daha guclu bir hale geliyor. Sinaviniz derinlesmeyi ogrenmek. Ogrendiginizde bu iliskinin en parlak iletisim koprusunu siz kuruyorsunuz.",
    ("Satürn", "Yengeç"): "Iliskide en buyuk sinaviniz ozgur birakmak — her seyi kontrol etme ihtiyaciniz partnerinizi bunaltiyor. Koruyuculugunuz ve sicakliginiz guclu ama asiri baglanmaniz zaman zaman sorun yaratiyor. Partnerinize alan tanidiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz guvenmeyi ogrenmek. Ogrendiginizde bu iliskinin en guvenli limanini siz insa ediyorsunuz.",
    ("Satürn", "Aslan"): "Iliskide en buyuk sinaviniz ego yonetimi — iliskinin tek yildizi siz olma ısrarınız partnerinizi uzuyor. Parildayan ve dikkat ceken bir yapınız var ama karsi tarafin da parlamaine izin vermeniz cok onemli. Partnerinizin guclerini onemsediginizde iliski cok daha guclu bir hale geliyor. Sinaviniz alan tanimak. Ogrendiginizde bu iliskinin en buyuk gucu oluyorsunuz.",
    ("Satürn", "Başak"): "Iliskide en buyuk sinaviniz kendinizi de kabul etmek — kusursuzluk arayisiniz hem sizi hem partnerinizi yoruyor. Analiz yeteneginiz guclu ama her seyi elestirme egiliminiz zaman zaman uzaklik yaratiyor. Ovgunuzu da ifade ettiginizde iliski cok daha guclu bir hale geliyor. Sinaviniz kabullenmeyi ogrenmek. Ogrendiginizde bu iliskinin en ince guzelligini siz olusturuyorsunuz.",
    ("Satürn", "Terazi"): "Iliskide en buyuk sinaviniz net kararlar almak — kararsizliginiz zaman zaman sinir bozucu olabiliyor. Denge ve uyum arayisiniz guclu ama her seyi erteleme egiliminiz iliskiyi yoruyor. Cesur adimlar attiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz netlesmeyi ogrenmek. Ogrendiginizde bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Satürn", "Akrep"): "Iliskide en buyuk sinaviniz guvenmek — her seyi denetim altinda tutma ihtiyaciniz iliskiyi boguyor. Derinliginiz ve tutkunuz guclu ama kontrolculugunuz zaman zaman sogukluk yaratiyor. Guvenmeyi ogrendiginizde iliski cok daha guclu bir hale geliyor. Sinaviniz birakmayi ogrenmek. Ogrendiginizde bu iliskinin en derin bagini siz kuruyorsunuz.",
    ("Satürn", "Yay"): "Iliskide en buyuk sinaviniz topraklanmak — surekli baska ufuklara bakma egiliminiz partnerinizi guvensiz birakiyor. Buyuk hayaller kurmaniz guclu ama somut adimlar atmamaniz zaman zaman sorun yaratiyor. Somut adimlar attiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz ayaklarinizi yere basmayi ogrenmek. Ogrendiginizde bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Satürn", "Oğlak"): "Iliskide en buyuk sinaviniz acilmak — duvarlarinizin arkasina saklanmaniz partnerinizi uzuyor. Ciddiyetiniz ve kararliliginiz guclu ama duygularinizi gosterememeniz zaman zaman sogukluk yaratiyor. Duygularinizi actiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz acilmayi ogrenmek. Ogrendiginizde bu iliskinin en saglam temelini siz insa ediyorsunuz.",
    ("Satürn", "Kova"): "Iliskide en buyuk sinaviniz yakinlasmak — bagimsizlik ısrarınız partnerinizi uzaklastiriyor. Ozgurlugunuz ve vizyonunuz guclu ama mesafeli durusunuz zaman zaman sogukluk yaratiyor. Yakinlastiginizda iliski cok daha guclu bir hale geliyor. Sinaviniz bag kurmayi ogrenmek. Ogrendiginizde bu iliskinin en ozel bagini siz kuruyorsunuz.",
    ("Satürn", "Balık"): "Iliskide en buyuk sinaviniz sinir koymak — kendinizi tamamen feda etme egiliminiz partnerinizi yoruyor. Merhametiniz ve derinliginiz guclu ama sinirlarinizin bulanik olmasi zaman zaman karisiklik yaratiyor. Sinir koydugunuzda iliski cok daha guclu bir hale geliyor. Sinaviniz sinirlari ogrenmek. Ogrendiginizde bu iliskinin en guclu sevgi kaynagi siz oluyorsunuz.",

    # === URANUS — OZGURLUK/SURPRIZ DINAMIGI ===
    ("Uranüs", "Koç"): "Iliskide ozgurluk ve bagimsizlik ısrarınız cok guclu. Ani degerisikikler, beklenmedik kararlar ve yenilikci yaklasimlar iliskinizi surekli canli tutuyor. Partneriniz bu enerjinizi hayranlikla izliyor ama ongorelemezliginiz zaman zaman endise yaratiyor. Iliskide yenilik ve macera cok onemli. Dengeli bir ozgurluk anlayisi ile bu iliskinin en yenilikci ruhu siz oluyorsunuz.",
    ("Uranüs", "Boğa"): "Iliskide deger ve guvenlik konularinda ani degisimler yasayabilirsiniz. Maddi konularda beklenmedik gelismeler, degerlerinizi yeniden tanimlama sureci iliskiyi etkiliyor. Partneriniz degisime acik olmanizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide yeni deger kaynaklari kefetmek cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci deger olusturucusu siz oluyorsunuz.",
    ("Uranüs", "İkizler"): "Iliskide iletisim ve dusunce tarzinizda ani devrimler yasayabilirsiniz. Yeni fikirler, siradisi yaklasimlar ve hizli iletisim iliskiyi surekli canli tutuyor. Partneriniz zihinsel canliliginizi seviyor ama daginikliginiz zaman zaman kafa karisikligi yaratiyor. Iliskide yenilikci fikirler cok onemli. Odaginizi korudugunuzda bu iliskinin en yenilikci iletisim kaynagi siz oluyorsunuz.",
    ("Uranüs", "Yengeç"): "Iliskide ev ve aile konularinda ani degisiklikler yasayabilirsiniz. Tasinma, ev degisikligi veya aile yapisinda beklenmedik gelismeler iliskiyi etkiliyor. Partneriniz yenilikci yaklasiminizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide guvenli bir yuva olusturmak cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci yuva kurucusu siz oluyorsunuz.",
    ("Uranüs", "Aslan"): "Iliskide yaraticilik ve eglence konularinda ani patlamalar yasayabilirsiniz. Sanat, eglence veya flortte ongorelemez gelismeler iliskiyi surekli canli tutuyor. Partneriniz yaraticiliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide surprizler ve yenilikler cok onemli. Duygusal baglari da guclendirdiginizde bu iliskinin en yenilikci ruhu siz oluyorsunuz.",
    ("Uranüs", "Başak"): "Iliskide gunluk hayati ve saglik konularinda ani degisiklikler yasayabilirsiniz. Calisma kosullarinda beklenmedik gelismeler, saglik konularinda ani farkindaliklar iliskiyi etkiliyor. Partneriniz yenilikci yaklasiminizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide pratik cozumler cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci cozum ureticisi siz oluyorsunuz.",
    ("Uranüs", "Terazi"): "Iliskide ani ozgurluk ve denge arayislari yasayabilirsiniz. Evlilik veya ortaklikta beklenmedik gelismeler, ozgurluk ve denge arasindaki catisma iliskiyi etkiliyor. Partneriniz ozgurlugunuza saygi duymani seviyor ama belirsizlik zaman zaman endise yaratiyor. Iliskide esitlik cok onemli. Dengeli bir ozgurluk anlayisi ile bu iliskinin en yenilikci hakemi siz oluyorsunuz.",
    ("Uranüs", "Akrep"): "Iliskide guc ve kontrol konularinda ani patlamalar yasayabilirsiniz. Gizli siralar aniden yuze cikabilir, kontrol kaybolabilir. Partneriniz derinliginizi seviyor ama ongorelemezliginiz zaman zaman korku yaratiyor. Iliskide derin donusum cok onemli. Kontrolu biraktiginizda bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Uranüs", "Yay"): "Iliskide inanç ve felsefe konularinda ani devrimler yasayabilirsiniz. Eski inanc sisteminiz sarsilabilir, yeni ve daha derin anlayislara acilabilirsiniz. Partneriniz vizyonunuza hayran ama belirsizlik zaman zaman endise yaratiyor. Iliskide buyuk resmi gormek cok onemli. Topraklandiginizda bu iliskinin en yenilikci rehberi siz oluyorsunuz.",
    ("Uranüs", "Oğlak"): "Iliskide kariyer ve statu konularinda ani degisiklikler yasayabilirsiniz. Is hayatinda beklenmedik gelismeler, kariyer yonunde degisiklikler iliskiyi etkiliyor. Partneriniz kararliliginizi seviyor ama ongorelemezliginiz zaman zaman tedirginlik yaratiyor. Iliskide uzun vadeli planlar cok onemli. Degisime uyum sagladiginizda bu iliskinin en yenilikci stratejisti siz oluyorsunuz.",
    ("Uranüs", "Kova"): "Iliskide ozgurluk ve yenilik konularinda ani patlamalar yasayabilirsiniz. Kisi donusumunuz cok hizli ve buyuk olabilir. Partneriniz ozgunlugunuzu seviyor ama mesafeli durusunuz zaman zaman sogukluk yaratabiliyor. Iliskide esitlik ve arkadaslik cok onemli. Yakinlastiginizda bu iliskinin en ozel ve farkli bagini siz kuruyorsunuz.",
    ("Uranüs", "Balık"): "Iliskide manevi dunyada ani donusumler yasayabilirsiniz. Sezgileriniz cok guclu ama belirsizlik de cok buyuk olabilir. Sanat veya muzikte ongorelemez ilham dalgalari gelebilir. Partneriniz derinliginizi seviyor ama ongorelemezliginiz zaman zaman kafa karisikligi yaratiyor. Iliskide sinirlar cok onemli. Sinirlarinizi netlestirdiginizde bu iliskinin en yenilikci ruhsal bagini siz kuruyorsunuz.",

    # === NEPTUN — IDEALIZMI, SEFFAFLIGI ===
    ("Neptün", "Koç"): "Iliskide kimlik ve hedefler konusunda bulaniklilar olabilir. Ne istediginiz konusunda belirsizlik yasayabilirsiniz ama sezgileriniz cok guclu. Partneriniz derinliginizi seviyor ama belirsizlik zaman zaman guvensizlik yaratiyor. Iliskide net olmak cok onemli. Netlestiginizde bu iliskinin en guclu sezgisel bagini siz kuruyorsunuz.",
    ("Neptün", "Boğa"): "Iliskide deger ve guvenlik konusunda belirsizlikler olabilir. Para konularinda net olmayan durumlar, degerler uzerine kafa karisikliklari yasayabilirsiniz. Partneriniz guvenilirliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide somut degerler cok onemli. Somutlastirdiginizda bu iliskinin en guvenli kaynagi siz oluyorsunuz.",
    ("Neptün", "İkizler"): "Iliskide iletisimde bulaniklilar olabilir. Soyledikleriniz ile kastettiginiz arasinda fark olabilir. Sezgisel iletisim cok guclu ama net olmamaniz zaman zaman anlasilmazlik yaratiyor. Iliskide acik ve net olmak cok onemli. Netlestiginizde bu iliskinin en derin anlayis koprusunu siz kuruyorsunuz.",
    ("Neptün", "Yengeç"): "Iliskide ev ve aile konularinda belirsizlikler olabilir. Aile yapisinda net olmayan dinamikler, gizli gercekler olabilir. Partneriniz sicakliginizi seviyor ama belirsizlik zaman zaman guvensizlik yaratiyor. Iliskide guvenli bir yuva cok onemli. Guvenli bir yuva olusturdugunuzda bu iliskinin en sicak limanini siz insa ediyorsunuz.",
    ("Neptün", "Aslan"): "Iliskide yaraticilik ve eglence konusunda ilham dalgalari yasayabilirsiniz. Sanat veya eglencede cok guclu sezgisel akis var ama somutlastirmakta zorlanabilirsiniz. Partneriniz yaraticiliginizi seviyor ama belirsizlik zaman zaman hayal kirikligi yaratiyor. Iliskide tutkuyu somutlastirmak cok onemli. Somutlastirdiginizda bu iliskinin en buyuk eglence kaynagi siz oluyorsunuz.",
    ("Neptün", "Başak"): "Iliskide gunluk hayat ve saglik konusunda belirsizlikler olabilir. Calisma kosullarinda net olmayan durumlar, saglik konularinda kafa karisikliklari yasayabilirsiniz. Partneriniz caliskanliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide pratik cozumler cok onemli. Pratiklastirdiginizda bu iliskinin en guvenli kaynagi siz oluyorsunuz.",
    ("Neptün", "Terazi"): "Iliskide idealizasyon ve hayal kirikligi riski cok yuksek. Partnerinizi oldugundan buyuk gorebilirsiniz ama kosulsuz sevgi potansiyeliniz de cok yuksek. Iliskide net gozlerle bakmak cok onemli. Net baktiginizda bu iliskinin en guclu sevgi bagini siz kuruyorsunuz.",
    ("Neptün", "Akrep"): "Iliskide guc ve kontrol konusunda belirsizlikler olabilir. Gizli guc dinamikleri devrede, derin bir donusum sureci yasayabilirsiniz. Partneriniz derinliginizi seviyor ama belirsizlik zaman zaman korku yaratiyor. Iliskide derin guven cok onemli. Guvenebildiginizde bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Neptün", "Yay"): "Iliskide inanç ve felsefe konusunda belirsizlikler olabilir. Eski inanc sisteminiz sarsilabilir ama yeni ve daha derin anlayislara da acilabilirsiniz. Partneriniz vizyonunuza hayran ama belirsizlik zaman zaman endise yaratiyor. Iliskide buyuk resmi gormek cok onemli. Topraklandiginizda bu iliskinin en buyuk manevi rehberi siz oluyorsunuz.",
    ("Neptün", "Oğlak"): "Iliskide kariyer ve statu konusunda belirsizlikler olabilir. Hedefleriniz veya kariyer yonunuz konusunda kafa karisikligi yasayabilirsiniz. Partneriniz kararliliginizi seviyor ama belirsizlik zaman zaman tedirginlik yaratiyor. Iliskide somut adimlar cok onemli. Somutlastirdiginizda bu iliskinin en guvenli stratejisti siz oluyorsunuz.",
    ("Neptün", "Kova"): "Iliskide arkadaslik ve toplumsal konularda belirsizlikler olabilir. Sosyal cevrenizde net olmayan dinamikler olabilir ama insani yardim icin cok guclu sezgisel baglar da kurabilirsiniz. Partneriniz vizyonunuza hayran ama belirsizlik zaman zaman endise yaratiyor. Iliskide netlik cok onemli. Netlestiginizde bu iliskinin en ozel vizyon bagini siz kuruyorsunuz.",
    ("Neptün", "Balık"): "Iliskide manevi dunyada belirsizlikler olabilir. Sezgileriniz cok guclu ama gerceklikle baginizi kaybetme riski de cok buyuk. Ruhunuz cok derin, sezgileriniz cok guclu. Iliskide sinirlar cok onemli. Sinirlarinizi netlestirdiginizde bu iliskinin en derin ruhsal bagini siz kuruyorsunuz.",

    # === PLUTON — GUC MUCADELESI, DONUSUM ===
    ("Plüton", "Koç"): "Iliskide guc ve kimlik donusumunun en yogun yasandigi yerdesiniz. Eski benliginizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz cesaretinizi ve donusum kapasitenizi seviyor ama kontrolculugunuzden korkabiliyor. Iliskide guc dengeleri surekli degisiyor. Kontrolu ogrendiginizde bu iliskinin en guclu donusum katalizoru siz oluyorsunuz.",
    ("Plüton", "Boğa"): "Iliskide deger ve guvenlik uzerinde derin bir donusum yasiyorsunuz. Eski degerlerinizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz guvenilirliginizi seviyor ama sahipci olmanizdan korkabiliyor. Iliskide deger catismalari cok yogun. Degerlerinizi paylastiginizda bu iliskinin en guclu deger ortagi siz oluyorsunuz.",
    ("Plüton", "İkizler"): "Iliskide iletisim ve dusunce tarzinizda derin bir donusum yasiyorsunuz. Eski iletisim kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz zekanizi seviyor ama manipulasyon riskine karsi dikkatli olmaniz gerekiyor. Iliskide acik ve seffaf iletisim cok onemli. Seffaf iletisim kurdugnuzda bu iliskinin en derin anlayis koprusunu siz kuruyorsunuz.",
    ("Plüton", "Yengeç"): "Iliskide ev, aile ve kokenler uzerinde derin bir donusum yasiyorsunuz. Eski aile kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz sicakliginizi seviyor ama asiri baglanmanizdan korkabiliyor. Iliskide guven ve baglanma cok yogun. Guvenli baglanti kurdugunuzda bu iliskinin en derin yuva kurucusu siz oluyorsunuz.",
    ("Plüton", "Aslan"): "Iliskide yaraticilik, ego ve dikkat cekme uzerinde derin bir donusum yasiyorsunuz. Eski ego kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz cesaretinizi seviyor ama ego caprasmalarindan korkabiliyor. Iliskide guc dengeleri cok yogun. Egonuzu yonlendirdiginizde bu iliskinin en buyuk sahne sahibi siz oluyorsunuz.",
    ("Plüton", "Başak"): "Iliskide gunluk hayat, saglik ve hizmet uzerinde derin bir donusum yasiyorsunuz. Eski calisma kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz caliskanliginizi seviyor ama elestirel yaklasiminizdan korkabiliyor. Iliskide hizmet ve kusursuzluk cok yogun. Kusurlari kabul ettiginizde bu iliskinin en ince gozlemcisi siz oluyorsunuz.",
    ("Plüton", "Terazi"): "Iliskide denge, uyum ve ortaklik uzerinde derin bir donusum yasiyorsunuz. Eski iliski kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz zarafetinizi seviyor ama guc mukavelesinden korkabiliyor. Iliskide denge ve esitlik cok yogun. Dengeyi buldugunuzda bu iliskinin en guclu hakemi siz oluyorsunuz.",
    ("Plüton", "Akrep"): "Iliskide guc, kontrol ve derin donusumun en yogun yasandigi yerdesiniz. Eski benliginizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz derinliginizi seviyor ama kontrolculugunuzden korkabiliyor. Iliskide guc mucadelesi cok yogun. Guvenmeyi ogrendiginizde bu iliskinin en derin donusum kaynagi siz oluyorsunuz.",
    ("Plüton", "Yay"): "Iliskide inanç, felsefe ve anlam uzerinde derin bir donusum yasiyorsunuz. Eski inanc sisteminizi birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz vizyonunuza hayran ama donusumun yogunlugundan korkabiliyor. Iliskide buyuk resim cok onemli. Somut adimlar attiginizda bu iliskinin en buyuk rehberi siz oluyorsunuz.",
    ("Plüton", "Oğlak"): "Iliskide kariyer, statu ve sorumluluklar uzerinde derin bir donusum yasiyorsunuz. Eski kariyer kaliplarini birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz kararliliginizi seviyor ama ciddiyetinizden korkabiliyor. Iliskide yapilandirma cok yogun. Duygusal acikligi da arttirdiginizda bu iliskinin en guvenilir destekcisi siz oluyorsunuz.",
    ("Plüton", "Kova"): "Iliskide ozgurluk, yenilik ve toplumsal donusum uzerinde derin bir donusum yasiyorsunuz. Eski toplumsal kaliplari birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz vizyonunuza hayran ama donusumun yogunlugundan korkabiliyor. Iliskide esitlik cok onemli. Yakinlastiginizda bu iliskinin en ozel vizyon bagini siz kuruyorsunuz.",
    ("Plüton", "Balık"): "Iliskide manevi dunya ve bilincdisi uzerinde derin bir donusum yasiyorsunuz. Eski ruhsal kaliplari birakip yenisini insa ediyorsunuz — bu surec iliskiyi de derinden etkiliyor. Partneriniz derinliginizi seviyor ama donusumun yogunlugundan korkabiliyor. Iliskide derin guven cok onemli. Guvenebildiginizde bu iliskinin en derin ruhsal bagini siz kuruyorsunuz.",

}
