# -*- coding: utf-8 -*-
"""
Versión en español de FBST_YORUMLAR_BURC.py.
Formato: {("Planeta", "Signo"): "Texto de comentario"} — mismas claves que el archivo TR.
Se carga a través de core/data.py (_load_es_dict); los valores faltantes se degradan a EN/TR.
"""

FBST_YORUMLAR_BURC = {
    # === SOL — La identidad en la relación, cómo brilla ===
    ("Güneş", "Koç"): "En esta relación te destacas con una energía valiente y pionera. Tú marcas el rumbo de la relación y siempre das el primer paso. Tu pareja admira tu valentía, aunque a veces se agota por tu impaciencia. Tu mayor desafío es la paciencia: tu tendencia a quererlo todo de inmediato cansa a tu pareja. Cuando aprendes a ser paciente, te conviertes en el verdadero motor de esta relación.",
    ("Güneş", "Boğa"): "En esta relación construyes una base segura, fuerte y estable. Muestras tu amor con acciones concretas: cocinar, tocar, estar presente. Tu pareja admira tu confiabilidad, aunque tu resistencia al cambio crea tensiones de vez en cuando. Tu desafío es aprender la flexibilidad: querer que todo siga igual puede asfixiar la relación. Cuando te vuelves flexible, eres el puerto más fuerte de esta relación.",
    ("Güneş", "İkizler"): "En esta relación usas tu mente y tu capacidad de palabra. Llevas la relación a través de la conversación, el debate y el intercambio de ideas. Tu pareja admira tu inteligencia y tu sentido del humor, aunque a veces puede percibirte como superficial. Tu desafío es profundizar: pasar de puntillas por los temas entristece a tu pareja. Cuando profundizas, te conviertes en la fuente de comunicación más brillante de esta relación.",
    ("Güneş", "Yengeç"): "En esta relación representas una fuerza protectora, nutritiva y emocional. Abrazas a tu pareja, construyes tu hogar y creas un refugio cálido. Tu pareja te ve como un puerto seguro, aunque a veces se siente agobiada por tu exceso de protección. Tu desafío es dejar ir: tu necesidad de controlarlo todo abruma a tu pareja. Cuando dejas ir, construyes el vínculo más profundo de esta relación.",
    ("Güneş", "Aslan"): "En esta relación eres una presencia radiante, que llama la atención y despierta admiración. Muestras tu amor de forma grande, vistosa y apasionada. Tu pareja admira tu energía, aunque a veces puedes perderte en choques de egos. Tu desafío es permitir que el otro también brille: tu insistencia en ser la única estrella entristece a tu pareja. Cuando concedes espacio, te conviertes en la mayor fortaleza de esta relación.",
    ("Güneş", "Başak"): "En esta relación eres una fuerza que ordena, analiza y sana. Amas con pasos prácticos, pequeños gestos y servicio. Tu pareja admira tu lealtad y tu diligencia, aunque puede cansarse de tantas críticas. Tu desafío es aceptarte a ti mismo: tu búsqueda de perfección tensa la relación. Cuando ves la belleza en las imperfecciones, creas la belleza más sutil de esta relación.",
    ("Güneş", "Terazi"): "En esta relación eres un alma que busca equilibrio, armonía y belleza. Puedes resolver hasta las discusiones con elegancia. Tu pareja admira tu refinamiento y tu sentido de la justicia, aunque tu indecisión puede resultar frustrante. Tu desafío es tomar decisiones claras: tu esfuerzo por escuchar a ambos lados te desgasta. Cuando te vuelves decidido, eres el árbitro más fuerte de esta relación.",
    ("Güneş", "Akrep"): "En esta relación portas una energía profunda, intensa y transformadora. Amas por completo: no hay medias tintas. Tu pareja admira tu pasión, aunque puede temer tu control. Tu desafío es confiar: tu necesidad de tenerlo todo bajo control asfixia la relación. Cuando aprendes a confiar, construyes el vínculo más profundo de esta relación.",
    ("Güneş", "Yay"): "En esta relación representas libertad, aventura y significado. Ves la relación desde una perspectiva amplia y sueñas en grande. Tu pareja admira tu optimismo y tu visión de la vida, aunque tu renuencia a comprometerte genera inquietud. Tu desafío es dar pasos concretos: mirar siempre otros horizontes deja insegura a tu pareja. Cuando te enraízas, eres el mayor guía de esta relación.",
    ("Güneş", "Oğlak"): "En esta relación eres una fuerza seria, responsable y constructiva. Construyes la relación con planes a largo plazo, pasos concretos y paciencia. Tu pareja admira tu determinación y tu confiabilidad, aunque tu incapacidad para mostrar emociones crea distancia. Tu desafío es abrirte: esconderte tras tus muros entristece a tu pareja. Cuando abres tus emociones, construyes la base más sólida de esta relación.",
    ("Güneş", "Kova"): "En esta relación eres un alma libre, innovadora y visionaria. Construyes la relación sobre la igualdad, la amistad y la libertad. Tu pareja admira tu visión y tu originalidad, aunque tu postura distante puede crear frialdad. Tu desafío es acercarte: tu insistencia en la independencia aleja a tu pareja. Cuando te acercas, construyes el vínculo más especial y diferente de esta relación.",
    ("Güneş", "Balık"): "En esta relación ofreces amor incondicional, compasión y un vínculo espiritual. Vives tu amor en una dimensión espiritual y comprendes profundamente a quien está frente a ti. Tu pareja admira tu compasión y tu intuición, aunque tus límites difusos crean confusión. Tu desafío es poner límites: tu tendencia a sacrificarte por completo cansa a tu pareja. Cuando pones límites, eres la fuente de amor más fuerte de esta relación.",

    # === LUNA — Necesidades emocionales, dónde se siente segura ===
    ("Ay", "Koç"): "Emocionalmente reaccionas con rapidez: muestras tanto tu amor como tu enfado al instante. A tu pareja le gusta tu franqueza, aunque a veces se siente sacudida por la intensidad de tus reacciones. Para sentirte segura en la relación necesitas soluciones rápidas y respuestas claras. Esperar mucho tiempo te vuelve loca. Cuando aprendes a canalizar tus estallidos emocionales, eres la guerrera más fuerte de esta relación.",
    ("Ay", "Boğa"): "Emocionalmente necesitas una confianza construida sobre el tacto físico, la comodidad y la estabilidad. Muestras tu amor con cosas concretas: comida, abrazos, estar presente. Tu pareja te da la comodidad de saber que puede confiar en ti, aunque tu resistencia al cambio puede asfixiar la relación. Para sentirte segura, la rutina y la repetición son importantes. Cuando aprendes el cambio en pequeños pasos, construyes el hogar más cálido de esta relación.",
    ("Ay", "İkizler"): "Emocionalmente te nutres hablando, compartiendo y aprendiendo. Expresas tu mundo interior con palabras: procesas tus emociones escribiendo, hablando y debatiendo. A tu pareja le gusta tu vitalidad mental, aunque puede percibir tu profundidad emocional como superficial. Para sentirte segura, la comunicación no debe cortarse. Cuando también hablas de tus emociones, construyes el puente de comunicación más brillante de esta relación.",
    ("Ay", "Yengeç"): "Emocionalmente necesitas una confianza construida sobre el hogar, la familia y tus raíces. Muestras tu amor calentando el hogar, cocinando y abrazando. Tu pareja admira tu calidez y tu protección, aunque tu excesiva sensibilidad a veces agota. Para sentirte segura necesitas un refugio seguro. Cuando aprendes a gestionar tus altibajos emocionales, construyes el vínculo más profundo de esta relación.",
    ("Ay", "Aslan"): "Emocionalmente quieres ser apreciada, admirada y estar en el centro de atención. Ofreces tu amor con grandes gestos y demostraciones vistosas. A tu pareja le gusta tu pasión y tu chispa, aunque tu hambre de atención a veces genera inseguridad. Para sentirte segura, las miradas deben estar sobre ti. Cuando nutres tu confianza desde dentro, eres la estrella más brillante de esta relación.",
    ("Ay", "Başak"): "Emocionalmente necesitas una confianza construida sobre el orden, la limpieza y las soluciones prácticas. Muestras tu amor sirviendo, organizando y ayudando. Tu pareja aprecia tu diligencia y tu lealtad, aunque tu actitud crítica a veces crea distancia. Para sentirte segura, todo debe estar en orden. Cuando aceptas las imperfecciones, creas la belleza más sutil de esta relación.",
    ("Ay", "Terazi"): "Emocionalmente necesitas una confianza construida sobre el equilibrio, la armonía y la belleza. Buscas una relación donde todos sean felices y nadie se sienta herido. Tu pareja aprecia tu elegancia y tu capacidad de armonía, aunque tu indecisión puede ser frustrante. Para sentirte segura, la igualdad es muy importante. Cuando también expresas tus propias necesidades, eres el árbitro más fuerte de esta relación.",
    ("Ay", "Akrep"): "Emocionalmente buscas un vínculo profundo, intenso y absoluto. Entregas tu amor por completo, pero esperas lo mismo de la otra persona. Tu pareja aprecia tu lealtad y tu profundidad, aunque puede cansarse de tu control y tus celos. Para sentirte segura necesitas una confianza profunda. Cuando aprendes a confiar, construyes el vínculo más profundo de esta relación.",
    ("Ay", "Yay"): "Emocionalmente necesitas una confianza construida sobre la libertad, la amplitud y el significado. Las relaciones que se estrechan, se limitan y entran en la rutina te asfixian. Tu pareja aprecia tu optimismo y tu visión de la vida, aunque tu miedo al compromiso genera inquietud. Para sentirte segura necesitas ver el panorama general. Cuando te enraízas, eres la mayor guía de esta relación.",
    ("Ay", "Oğlak"): "Emocionalmente necesitas una confianza construida sobre la estructura, la seriedad y la responsabilidad. Te cuesta mostrar tus emociones, pero tus acciones hablan por ti. Tu pareja aprecia tu confiabilidad y tu determinación, aunque tu distancia emocional crea alejamiento. Para sentirte segura, los pasos concretos son importantes. Cuando abres tus emociones, construyes la base más sólida de esta relación.",
    ("Ay", "Kova"): "Emocionalmente necesitas una confianza construida sobre la libertad, la igualdad y la amistad. Los patrones tradicionales de relación te quedan pequeños. Tu pareja admira tu originalidad y tu visión, aunque tu postura distante puede crear frialdad. Para sentirte segura necesitas sentirte como una amiga. Cuando te acercas, construyes el vínculo más especial de esta relación.",
    ("Ay", "Balık"): "Emocionalmente necesitas una confianza construida sobre el amor incondicional, el sacrificio y el vínculo espiritual. Vives tu amor en una dimensión espiritual. Tu pareja aprecia tu compasión y tu profundidad, aunque tus límites difusos crean confusión. Para sentirte segura, el vínculo espiritual profundo es importante. Cuando pones límites, eres la fuente de amor más fuerte de esta relación.",

    # === MERCURIO — Lenguaje de comunicación, cómo comprende/habla ===
    ("Merkür", "Koç"): "Hablas con un lenguaje rápido, directo y cortante. Dices tus ideas sin filtrarlas: esta honestidad puede asustar a veces a tu pareja. En la relación las discusiones empiezan y terminan rápido. Tu pareja aprecia tu inteligencia y tu rapidez, aunque tus salidas bruscas pueden sacudirla. Cuando aprendes a elegir tus palabras, eres el motor de comunicación más fuerte de esta relación.",
    ("Merkür", "Boğa"): "Hablas con un lenguaje lento pero seguro, concreto y confiable. Tienes una estructura que respalda lo que dices y no habla por hablar. Tu pareja admira esta confiabilidad, aunque la lentitud de tu habla a veces crea impaciencia. En la relación, los temas concretos y las soluciones prácticas son importantes. Cuando aprendes a hablar también de temas emocionales, construyes el puente de comunicación más sólido de esta relación.",
    ("Merkür", "İkizler"): "Hablas con un lenguaje versátil, divertido y mentalmente vivo. Llevas la relación conversando, aprendiendo y compartiendo. Tu pareja admira tu inteligencia y tus bromas, aunque hablar mucho y escuchar poco a veces crea problemas. En la relación, el intercambio de información es muy importante. Cuando aprendes también a escuchar, construyes el puente de comunicación más brillante de esta relación.",
    ("Merkür", "Yengeç"): "Hablas con un lenguaje emocional, empático y sensible. Captas de inmediato los sentimientos de quien está frente a ti, pero te cuesta abrir tus propias emociones. Tu pareja aprecia tu empatía, aunque a veces puede quejarse de que te cierras demasiado. En la relación tiendes a repetir los temas del pasado. Cuando dejas el pasado y te enfocas en el presente, construyes el puente de comprensión más profundo de esta relación.",
    ("Merkür", "Aslan"): "Hablas con un lenguaje vistoso, impactante y que roba el escenario. Tu forma de presentar tus ideas es muy poderosa: tu capacidad de convencer es alta. Tu pareja aprecia tu oratoria y tu creatividad, aunque tu insistencia en tener razón en todo a veces crea tensión. En la relación, escuchar también es muy importante. Cuando valoras también la opinión del otro, eres el mayor artista del escenario de esta relación.",
    ("Merkür", "Başak"): "Hablas con un lenguaje analítico, detallista y crítico. Analizas todo minuciosamente: esto puede ser tanto una fortaleza como un desgaste en la relación. Tu pareja aprecia la profundidad de tu inteligencia, aunque puede cansarse de tantas críticas. En la relación tiendes a agrandar los pequeños detalles. Cuando también expresas elogios, eres el observador más sutil de esta relación.",
    ("Merkür", "Terazi"): "Hablas con un lenguaje equilibrado, elegante y justo. Escuchas y tratas de equilibrar la opinión de ambos lados. Tu pareja admira tu sentido de la justicia y tu elegancia, aunque tu indecisión a veces resulta frustrante. En la relación te cuesta tomar decisiones claras. Cuando te vuelves decidido, eres el árbitro más fuerte de esta relación.",
    ("Merkür", "Akrep"): "Hablas con un lenguaje profundo, investigador y estratégico. Quedarte en la superficie no te basta: analizas cada tema hasta el fondo. Tu pareja aprecia la profundidad de tu inteligencia, aunque guardar secretos y tu postura estratégica a veces crea desconfianza. En la relación, ser abierto y transparente es muy importante. Cuando compartes tus secretos, construyes el vínculo más profundo de esta relación.",
    ("Merkür", "Yay"): "Hablas con un lenguaje amplio, filosófico y optimista. Ves el panorama general y no te pierdes en los detalles. Tu pareja aprecia tu optimismo y tu amplia perspectiva, aunque quedarte demasiado en lo general retrasa las soluciones concretas. En la relación soñar en grande es importante, pero los pies deben estar en la tierra. Cuando das pasos concretos, eres el mayor guía de esta relación.",
    ("Merkür", "Oğlak"): "Hablas con un lenguaje serio, estratégico y estructurado. Te gusta planificar, programar y definir pasos concretos. Tu pareja aprecia tu seriedad y tu determinación, aunque tu enfoque demasiado centrado en el trabajo puede debilitar los vínculos emocionales. En la relación también hay que hablar de emociones. Cuando aumentas los intercambios emocionales, eres el estratega más fuerte de esta relación.",
    ("Merkür", "Kova"): "Hablas con un lenguaje original, innovador y fuera de lo común. No sigues los patrones de pensamiento tradicionales: tus ideas siempre son diferentes e interesantes. Tu pareja admira tu visión y tu originalidad, aunque tu estilo de comunicación distante puede crear frialdad. En la relación, la comunicación cercana también es muy importante. Cuando te vuelves cálido, construyes el vínculo de comunicación más especial y diferente de esta relación.",
    ("Merkür", "Balık"): "Hablas con un lenguaje intuitivo, creativo y con gran imaginación. Tu capacidad de comprensión es más intuitiva que el análisis lógico. Tu pareja aprecia tu imaginación y tu compasión, aunque tu dificultad para elegir palabras claras crea malentendidos. En la relación, ser claro y abierto es muy importante. Cuando aclaras tus emociones, construyes el vínculo espiritual más profundo de esta relación.",

    # === VENUS — Lenguaje del amor, cómo ama ===
    ("Venüs", "Koç"): "Muestras tu amor con pasión, valentía y acción. Perseguir, conquistar, comenzar cosas nuevas te da placer. Tu pareja observa tu pasión y tu energía con admiración, aunque tu pérdida de interés genera inquietud. En la relación, la monotonía no es para ti: debe haber vitalidad, novedad y acción constantes. Cuando aprendes a mantener fresco tu amor, eres la amante más apasionada de esta relación.",
    ("Venüs", "Boğa"): "Muestras tu amor con acciones concretas, tocando, cocinando, estando presente. Buscas relaciones confiables, estables y duraderas. Tu pareja aprecia tu lealtad y tu calidez, aunque tu posesividad a veces asfixia. En la relación, disfrutar de las cosas bellas es muy importante: comer juntos, la música, la naturaleza. Construyes una relación que crece al compartir tu amor.",
    ("Venüs", "İkizler"): "Muestras tu amor con la conversación, el humor y la sintonía mental. Para ti, el vínculo intelectual es tan importante como la atracción física. Tu pareja aprecia tu inteligencia y tu estilo divertido de comunicación, aunque tu inconstancia genera inseguridad. La monotonía no es para ti: debe haber novedad, aprendizaje y compartir constantes. Cuando añades profundidad emocional, eres la amante más divertida de esta relación.",
    ("Venüs", "Yengeç"): "Muestras tu amor protegiendo, nutriendo y abrazando. Los conceptos de hogar, calidez y refugio son muy importantes. Tu pareja aprecia tu calidez y tu protección, aunque tu apego excesivo a veces abruma. En la relación, ser un puerto seguro es muy valioso. Cuando construyes tu amor sobre una base sólida, eres la amante más segura de esta relación.",
    ("Venüs", "Aslan"): "Muestras tu amor de forma grande, vistosa y chispeante. Dar regalos, hacer sorpresas y estar en el centro te da placer. Tu pareja aprecia tu chispa y tu pasión, aunque tu hambre de atención genera inseguridad. En la relación, las miradas deben estar sobre ti, pero es muy importante que tu pareja también brille. Cuando concedes espacio, construyes el gran escenario de amor de esta relación.",
    ("Venüs", "Başak"): "Muestras tu amor sirviendo, organizando y facilitando la vida. Tu lenguaje de amor práctico es muy fuerte. Tu pareja aprecia tu lealtad y tu diligencia, aunque tu actitud crítica a veces crea distancia. En la relación, la búsqueda de perfección puede asfixiar. Cuando aceptas tu amor y ves la belleza en las imperfecciones, eres la amante más delicada de esta relación.",
    ("Venüs", "Terazi"): "Muestras tu amor con equilibrio, elegancia y belleza. En la relación, la igualdad, la armonía y la belleza son muy importantes. Tu pareja aprecia tu elegancia y tu sentido de la justicia, aunque tu indecisión a veces crea distancia. En la relación, vivir cosas bellas es muy importante: arte, música, estética. Cuando expresas tu amor con claridad, eres la amante más elegante de esta relación.",
    ("Venüs", "Akrep"): "Muestras tu amor de forma profunda, intensa y absoluta. Tu amor no abandona a mitad de camino: todo o nada. Tu pareja aprecia tu pasión y tu profundidad, aunque tus celos y tu control a veces abruman. En la relación, la confianza y la lealtad son muy importantes. Cuando aprendes a confiar, eres la amante más profunda de esta relación.",
    ("Venüs", "Yay"): "Muestras tu amor con libertad, alegría y aventura. Quieres vivir la relación de forma divertida, amplia y con significado. Tu pareja aprecia tu optimismo y tu chispa, aunque tu miedo al compromiso genera inquietud. En la relación, soñar en grande es hermoso, pero también hay que enraizarse. Cuando te enraízas, eres la gran guía del amor de esta relación.",
    ("Venüs", "Oğlak"): "Muestras tu amor con acciones, responsabilidad y apoyo práctico. Muestras tu amor haciendo, no diciendo. Tu pareja aprecia tu confiabilidad y tu seriedad, aunque tu falta de apertura emocional crea frialdad. En la relación, el intercambio emocional también es muy importante. Cuando abres tus emociones, eres la amante más confiable de esta relación.",
    ("Venüs", "Kova"): "Construyes tu amor sobre la amistad, la igualdad y la libertad. Los patrones tradicionales de relación te quedan pequeños. Tu pareja admira tu originalidad y tu visión, aunque tu postura distante puede crear frialdad. En la relación, la cercanía también es muy importante. Cuando te vuelves cálido, eres la amante más especial de esta relación.",
    ("Venüs", "Balık"): "Muestras tu amor de forma incondicional, sacrificada y espiritual. Vives tu amor en una dimensión espiritual. Tu pareja aprecia tu compasión y tu profundidad, aunque tus límites difusos crean confusión. En la relación, poner límites es muy importante. Cuando puedes poner límites, eres la fuente de amor más fuerte de esta relación.",

    # === MARTE — Forma de pasión, cómo defiende sus límites ===
    ("Mars", "Koç"): "Expresas tu pasión con valentía, de forma directa y activa. En la relación eres el pionero: quien da el primer paso, marca los límites y pone las cosas en movimiento. Tu pareja observa tu energía y tu valor con admiración, aunque puede sacudirse por la intensidad de tu ira. En la relación, la competencia y la aventura son muy importantes. Cuando aprendes a canalizar tu energía, eres el guerrero más fuerte de esta relación.",
    ("Mars", "Boğa"): "Expresas tu pasión con paciencia, constancia y acciones concretas. Avanzas no rápido, sino lento pero seguro. Tu pareja aprecia tu confiabilidad y tu fuerza, aunque tu posesividad a veces crea problemas. En la relación, el tacto físico es muy importante: expresas tu amor tocando, abrazando y estando presente. Tu actitud paciente forma la base más fuerte de esta relación.",
    ("Mars", "İkizler"): "Expresas tu pasión con palabras, discusiones y sintonía mental. En la relación, hablar, debatir e intercambiar ideas es muy importante. Tu pareja aprecia tu inteligencia y tu estilo de comunicación divertido, aunque hablar mucho y escuchar poco a veces crea problemas. En las discusiones, elegir bien tus palabras es muy importante. Cuando estableces una comunicación equilibrada, eres el guerrero de comunicación más brillante de esta relación.",
    ("Mars", "Yengeç"): "Expresas tu pasión protegiendo, reclamando y de forma emocional. En la relación, la protección, la defensa y la posesión son muy importantes. Tu pareja aprecia tu lealtad y tu calidez, aunque tu tendencia a guardar tu ira hacia adentro a veces crea problemas. En lugar de estallidos emocionales, la expresión saludable es importante. Cuando expresas tus emociones de forma saludable, eres el protector más fuerte de esta relación.",
    ("Mars", "Aslan"): "Expresas tu pasión de forma vistosa, apasionada y valiente. En la relación, estar en el centro y despertar admiración es muy importante. Tu pareja aprecia tu valor y tu pasión, aunque tus choques de ego a veces crean tensión. En la relación, es muy importante que tu pareja también brille. Cuando diriges tu ego, construyes el gran escenario de pasión de esta relación.",
    ("Mars", "Başak"): "Expresas tu pasión sirviendo, organizando y con pasos prácticos. En la relación prestas atención a los detalles: que todo esté en orden es muy importante. Tu pareja aprecia tu diligencia y tu lealtad, aunque tu actitud crítica a veces crea distancia. Aprender y crecer es muy importante. Cuando aceptas las imperfecciones, eres el observador más sutil de esta relación.",
    ("Mars", "Terazi"): "Construyes tu pasión sobre el equilibrio, la armonía y la reciprocidad. En la relación, la igualdad es muy importante: ambos lados deben participar por igual. Tu pareja aprecia tu elegancia y tu capacidad de armonía, aunque tu indecisión puede resultar frustrante. Dar pasos valientes es muy importante. Cuando te vuelves decidido, eres el árbitro más fuerte de esta relación.",
    ("Mars", "Akrep"): "Expresas tu pasión de forma profunda, intensa y absoluta. En la relación, el control, el poder y el vínculo profundo son muy importantes. Tu pareja aprecia tu pasión y tu profundidad, aunque puede cansarse de tu control y tus celos. La confianza y la lealtad son muy importantes. Cuando aprendes a confiar, construyes el vínculo más profundo de esta relación.",
    ("Mars", "Yay"): "Construyes tu pasión sobre la aventura, la libertad y el significado. En la relación, soñar en grande y vivir nuevas experiencias es muy importante. Tu pareja aprecia tu optimismo y tu valor, aunque tu miedo al compromiso genera inquietud. Enraizarte también es muy importante. Cuando das pasos concretos, eres el gran guía de aventura de esta relación.",
    ("Mars", "Oğlak"): "Expresas tu pasión con paciencia, determinación y pasos estratégicos. En la relación, los objetivos a largo plazo son muy importantes. Tu pareja aprecia tu determinación y tu confiabilidad, aunque tu enfoque demasiado centrado en el trabajo puede debilitar los vínculos emocionales. El intercambio emocional también es muy importante. Cuando abres tus emociones, eres el estratega más fuerte de esta relación.",
    ("Mars", "Kova"): "Construyes tu pasión sobre la libertad, la innovación y la transformación social. Los patrones tradicionales de relación te quedan pequeños. Tu pareja admira tu visión y tu originalidad, aunque tu postura distante puede crear frialdad. La cercanía también es muy importante. Cuando te vuelves cálido, construyes el vínculo más especial de esta relación.",
    ("Mars", "Balık"): "Expresas tu pasión de forma intuitiva, sacrificada y espiritual. Más que el desafío físico, es importante el desafío espiritual o creativo. Tu pareja aprecia tu compasión y tu profundidad, aunque tus límites difusos crean confusión. Poner límites es muy importante. Cuando pones límites, eres el guerrero del amor más fuerte de esta relación.",

    # === JÚPITER — Qué aporta a la relación, área de expansión ===
    ("Jüpiter", "Koç"): "Has aportado valor, aventura e innovación a la relación. Traes nuevos comienzos, emoción y energía de acción. Tu pareja observa tu energía con admiración, aunque tus excesos a veces crean problemas. Eres quien expande, hace crecer y mantiene viva la relación. Cuando usas esta energía de expansión con equilibrio, eres la mayor suerte de esta relación.",
    ("Jüpiter", "Boğa"): "Has aportado abundancia, prosperidad y valores concretos a la relación. Traes grandes oportunidades en finanzas, seguridad y confort físico. Tu pareja aprecia tu confiabilidad y tu chispa, aunque tu posesividad a veces crea problemas. Eres quien hace crecer la relación con valores concretos. Cuando compartes esta energía de abundancia, eres la mayor fuente de prosperidad de esta relación.",
    ("Jüpiter", "İkizler"): "Has aportado conocimiento, comunicación y vitalidad mental a la relación. Traes grandes oportunidades para aprender, enseñar y compartir. Tu pareja aprecia tu inteligencia y tu estilo de comunicación divertido, aunque hablar mucho y escuchar poco a veces crea problemas. Eres quien hace crecer la relación mentalmente. Cuando estableces una comunicación equilibrada, eres la fuente de comunicación más brillante de esta relación.",
    ("Jüpiter", "Yengeç"): "Has aportado calidez, hogar y valores familiares a la relación. Traes grandes oportunidades para hacer crecer tu hogar, formar una familia y fortalecer los lazos. Tu pareja aprecia tu calidez y tu protección, aunque tu apego excesivo a veces abruma. Eres quien convierte la relación en un refugio cálido. Cuando usas esta energía de calidez con equilibrio, eres la mayor fuente de seguridad de esta relación.",
    ("Jüpiter", "Aslan"): "Has aportado pasión, diversión y creatividad a la relación. Traes grandes oportunidades en arte, escenario y entretenimiento. Tu pareja aprecia tu chispa y tu energía, aunque tus choques de ego a veces crean tensión. Eres quien hace la relación divertida y apasionada. Cuando usas tu energía con equilibrio, eres la mayor fuente de entretenimiento de esta relación.",
    ("Jüpiter", "Başak"): "Has aportado servicio, soluciones prácticas y sanación a la relación. Traes grandes oportunidades para organizar la vida cotidiana y resolver problemas. Tu pareja aprecia tu diligencia y tu lealtad, aunque tu actitud crítica a veces crea distancia. Eres quien hace crecer la relación de forma práctica. Cuando también expresas elogios, eres la mayor fuente de servicio de esta relación.",
    ("Jüpiter", "Terazi"): "Has aportado equilibrio, armonía y belleza a la relación. Traes grandes oportunidades en relaciones, sociedades y estética. Tu pareja aprecia tu elegancia y tu sentido de la justicia, aunque tu indecisión puede resultar frustrante. Eres quien hace la relación bella y equilibrada. Cuando tomas decisiones claras, eres la mayor fuente de equilibrio de esta relación.",
    ("Jüpiter", "Akrep"): "Has aportado transformación, profundidad y grandes recursos a la relación. Traes grandes oportunidades en sexualidad, transformación espiritual y recursos compartidos. Tu pareja aprecia tu profundidad y tu pasión, aunque puede cansarse de tu control. Eres quien transforma la relación desde lo profundo. Cuando aprendes a confiar, eres la mayor fuente de transformación de esta relación.",
    ("Jüpiter", "Yay"): "Has aportado libertad, significado y aventura a la relación. Traes grandes oportunidades en filosofía, viajes y estudios superiores. Tu pareja aprecia tu optimismo y tu amplia perspectiva, aunque tu miedo al compromiso genera inquietud. Eres quien hace crecer la relación en el panorama general. Cuando te enraízas, eres la mayor fuente de guía de esta relación.",
    ("Jüpiter", "Oğlak"): "Has aportado seriedad, responsabilidad y estructura a largo plazo a la relación. Traes grandes oportunidades en carrera, estatus y objetivos a largo plazo. Tu pareja aprecia tu determinación y tu confiabilidad, aunque tu enfoque demasiado centrado en el trabajo puede debilitar los vínculos emocionales. Eres quien hace crecer la relación a largo plazo. Cuando aumentas los intercambios emocionales, eres la mayor fuente de garantía de esta relación.",
    ("Jüpiter", "Kova"): "Has aportado libertad, innovación y visión social a la relación. Traes grandes oportunidades en amistad, proyectos sociales y tecnología. Tu pareja admira tu visión y tu originalidad, aunque tu postura distante puede crear frialdad. Eres quien hace crecer la relación sobre la libertad. Cuando te acercas, eres la fuente de visión más especial de esta relación.",
    ("Jüpiter", "Balık"): "Has aportado espiritualidad, intuición y amor incondicional a la relación. Traes grandes oportunidades en arte, música, meditación y prácticas espirituales. Tu pareja aprecia tu compasión y tu profundidad, aunque tus límites difusos crean confusión. Eres quien hace crecer la relación espiritualmente. Cuando pones límites, eres la mayor fuente espiritual de esta relación.",

    # === SATURNO — El desafío en la relación, dónde se limita ===
    ("Satürn", "Koç"): "Tu mayor desafío en la relación es ser paciente: tu tendencia a tomar decisiones rápidas y quererlo todo de inmediato cansa a tu pareja. Tu valor y tu iniciativa son fuertes, pero tu impaciencia puede dañar la relación. Cuando das pasos más lentos y más reflexivos, la relación se vuelve mucho más fuerte. Tu desafío es aprender a tener paciencia. Cuando lo aprendes, eres el motor más fuerte de esta relación.",
    ("Satürn", "Boğa"): "Tu mayor desafío en la relación es abrirte al cambio: tu insistencia en hacer siempre lo mismo puede asfixiar la relación. Tu constancia y tu confiabilidad son fuertes, pero tu falta de flexibilidad a veces crea tensión. Cuando te abres a pequeños cambios, la relación se vuelve mucho más viva. Tu desafío es aprender a ser flexible. Cuando lo aprendes, construyes la base más sólida de esta relación.",
    ("Satürn", "İkizler"): "Tu mayor desafío en la relación es profundizar: tu tendencia a pasar de puntillas por los temas entristece a tu pareja. Tu vitalidad mental es fuerte, pero quedarte en la superficie a veces crea distancia. Cuando profundizas también en los temas emocionales, la relación se vuelve mucho más fuerte. Tu desafío es aprender a profundizar. Cuando lo aprendes, construyes el puente de comunicación más brillante de esta relación.",
    ("Satürn", "Yengeç"): "Tu mayor desafío en la relación es dejar ir: tu necesidad de controlarlo todo abruma a tu pareja. Tu protección y tu calidez son fuertes, pero tu apego excesivo a veces crea problemas. Cuando das espacio a tu pareja, la relación se vuelve mucho más fuerte. Tu desafío es aprender a confiar. Cuando lo aprendes, construyes el puerto más seguro de esta relación.",
    ("Satürn", "Aslan"): "Tu mayor desafío en la relación es el manejo del ego: tu insistencia en ser la única estrella entristece a tu pareja. Tienes una estructura que brilla y llama la atención, pero es muy importante permitir que el otro también brille. Cuando valoras las fortalezas de tu pareja, la relación se vuelve mucho más fuerte. Tu desafío es conceder espacio. Cuando lo aprendes, te conviertes en la mayor fortaleza de esta relación.",
    ("Satürn", "Başak"): "Tu mayor desafío en la relación es aceptarte a ti mismo: tu búsqueda de perfección agota tanto a ti como a tu pareja. Tu capacidad de análisis es fuerte, pero tu tendencia a criticarlo todo a veces crea distancia. Cuando también expresas elogios, la relación se vuelve mucho más fuerte. Tu desafío es aprender a aceptar. Cuando lo aprendes, creas la belleza más sutil de esta relación.",
    ("Satürn", "Terazi"): "Tu mayor desafío en la relación es tomar decisiones claras: tu indecisión puede resultar frustrante. Tu búsqueda de equilibrio y armonía es fuerte, pero tu tendencia a posponerlo todo cansa la relación. Cuando das pasos valientes, la relación se vuelve mucho más fuerte. Tu desafío es aprender a decidir con claridad. Cuando lo aprendes, eres el árbitro más fuerte de esta relación.",
    ("Satürn", "Akrep"): "Tu mayor desafío en la relación es confiar: tu necesidad de tenerlo todo bajo control asfixia la relación. Tu profundidad y tu pasión son fuertes, pero tu control a veces crea frialdad. Cuando aprendes a confiar, la relación se vuelve mucho más fuerte. Tu desafío es aprender a soltar. Cuando lo aprendes, construyes el vínculo más profundo de esta relación.",
    ("Satürn", "Yay"): "Tu mayor desafío en la relación es enraizarte: tu tendencia a mirar siempre otros horizontes deja insegura a tu pareja. Soñar en grande es una fortaleza, pero no dar pasos concretos a veces crea problemas. Cuando das pasos concretos, la relación se vuelve mucho más fuerte. Tu desafío es aprender a mantener los pies en la tierra. Cuando lo aprendes, eres el mayor guía de esta relación.",
    ("Satürn", "Oğlak"): "Tu mayor desafío en la relación es abrirte: esconderte tras tus muros entristece a tu pareja. Tu seriedad y tu determinación son fuertes, pero tu incapacidad para mostrar emociones a veces crea frialdad. Cuando abres tus emociones, la relación se vuelve mucho más fuerte. Tu desafío es aprender a abrirte. Cuando lo aprendes, construyes la base más sólida de esta relación.",
    ("Satürn", "Kova"): "Tu mayor desafío en la relación es acercarte: tu insistencia en la independencia aleja a tu pareja. Tu libertad y tu visión son fuertes, pero tu postura distante a veces crea frialdad. Cuando te acercas, la relación se vuelve mucho más fuerte. Tu desafío es aprender a crear vínculos. Cuando lo aprendes, construyes el vínculo más especial de esta relación.",
    ("Satürn", "Balık"): "Tu mayor desafío en la relación es poner límites: tu tendencia a sacrificarte por completo cansa a tu pareja. Tu compasión y tu profundidad son fuertes, pero tus límites difusos a veces crean confusión. Cuando pones límites, la relación se vuelve mucho más fuerte. Tu desafío es aprender a poner límites. Cuando lo aprendes, eres la fuente de amor más fuerte de esta relación.",

    # === URANO — Dinámica de libertad/sorpresa ===
    ("Uranüs", "Koç"): "En la relación, tu insistencia en la libertad y la independencia es muy fuerte. Cambios repentinos, decisiones inesperadas y enfoques innovadores mantienen siempre viva la relación. Tu pareja observa tu energía con admiración, aunque tu imprevisibilidad a veces genera inquietud. En la relación, la novedad y la aventura son muy importantes. Con una comprensión equilibrada de la libertad, eres el espíritu más innovador de esta relación.",
    ("Uranüs", "Boğa"): "En la relación puedes experimentar cambios repentinos en temas de valores y seguridad. Desarrollos inesperados en lo material y un proceso de redefinir tus valores afectan la relación. Tu pareja aprecia tu apertura al cambio, aunque la incertidumbre a veces crea inquietud. En la relación, descubrir nuevas fuentes de valor es muy importante. Cuando te adaptas al cambio, eres el constructor de valores más innovador de esta relación.",
    ("Uranüs", "İkizler"): "En la relación puedes experimentar revoluciones repentinas en tu forma de comunicarte y pensar. Nuevas ideas, enfoques poco comunes y una comunicación veloz mantienen siempre viva la relación. Tu pareja aprecia tu vitalidad mental, aunque tu dispersión a veces crea confusión. En la relación, las ideas innovadoras son muy importantes. Cuando mantienes el enfoque, eres la fuente de comunicación más innovadora de esta relación.",
    ("Uranüs", "Yengeç"): "En la relación puedes experimentar cambios repentinos en temas de hogar y familia. Mudanzas, cambios de casa o desarrollos inesperados en la estructura familiar afectan la relación. Tu pareja aprecia tu enfoque innovador, aunque la incertidumbre a veces crea inquietud. En la relación, construir un refugio seguro es muy importante. Cuando te adaptas al cambio, eres el constructor de hogares más innovador de esta relación.",
    ("Uranüs", "Aslan"): "En la relación puedes experimentar explosiones repentinas en temas de creatividad y diversión. Desarrollos impredecibles en el arte, el entretenimiento o el romance mantienen siempre viva la relación. Tu pareja aprecia tu creatividad, aunque la incertidumbre a veces crea inquietud. En la relación, las sorpresas y novedades son muy importantes. Cuando también fortaleces los vínculos emocionales, eres el espíritu más innovador de esta relación.",
    ("Uranüs", "Başak"): "En la relación puedes experimentar cambios repentinos en temas de vida cotidiana y salud. Desarrollos inesperados en las condiciones de trabajo y despertares repentinos en temas de salud afectan la relación. Tu pareja aprecia tu enfoque innovador, aunque la incertidumbre a veces crea inquietud. En la relación, las soluciones prácticas son muy importantes. Cuando te adaptas al cambio, eres el generador de soluciones más innovador de esta relación.",
    ("Uranüs", "Terazi"): "En la relación puedes experimentar búsquedas repentinas de libertad y equilibrio. Desarrollos inesperados en el matrimonio o las sociedades y el conflicto entre libertad y equilibrio afectan la relación. Tu pareja aprecia que respetes su libertad, aunque la incertidumbre a veces genera inquietud. En la relación, la igualdad es muy importante. Con una comprensión equilibrada de la libertad, eres el árbitro más innovador de esta relación.",
    ("Uranüs", "Akrep"): "En la relación puedes experimentar explosiones repentinas en temas de poder y control. Secretos ocultos pueden salir a la luz de repente y el control puede perderse. Tu pareja aprecia tu profundidad, aunque tu imprevisibilidad a veces crea miedo. En la relación, la transformación profunda es muy importante. Cuando sueltas el control, eres la fuente de transformación más profunda de esta relación.",
    ("Uranüs", "Yay"): "En la relación puedes experimentar revoluciones repentinas en temas de creencia y filosofía. Tu antiguo sistema de creencias puede tambalearse y puedes abrirte a comprensiones nuevas y más profundas. Tu pareja admira tu visión, aunque la incertidumbre a veces genera inquietud. En la relación, ver el panorama general es muy importante. Cuando te enraízas, eres el guía más innovador de esta relación.",
    ("Uranüs", "Oğlak"): "En la relación puedes experimentar cambios repentinos en temas de carrera y estatus. Desarrollos inesperados en la vida laboral y cambios de dirección en la carrera afectan la relación. Tu pareja aprecia tu determinación, aunque tu imprevisibilidad a veces crea inquietud. En la relación, los planes a largo plazo son muy importantes. Cuando te adaptas al cambio, eres el estratega más innovador de esta relación.",
    ("Uranüs", "Kova"): "En la relación puedes experimentar explosiones repentinas en temas de libertad e innovación. Tu transformación personal puede ser muy rápida y grande. Tu pareja aprecia tu originalidad, aunque tu postura distante a veces puede crear frialdad. En la relación, la igualdad y la amistad son muy importantes. Cuando te acercas, construyes el vínculo más especial y diferente de esta relación.",
    ("Uranüs", "Balık"): "En la relación puedes experimentar transformaciones repentinas en el mundo espiritual. Tus intuiciones son muy fuertes, pero la incertidumbre también puede ser muy grande. Pueden llegar olas de inspiración impredecibles en el arte o la música. Tu pareja aprecia tu profundidad, aunque tu imprevisibilidad a veces crea confusión. En la relación, los límites son muy importantes. Cuando aclaras tus límites, construyes el vínculo espiritual más innovador de esta relación.",

    # === NEPTUNO — Idealismo, transparencia ===
    ("Neptün", "Koç"): "En la relación puede haber confusión sobre la identidad y los objetivos. Puedes experimentar incertidumbre sobre lo que quieres, pero tus intuiciones son muy fuertes. Tu pareja aprecia tu profundidad, aunque la incertidumbre a veces genera desconfianza. En la relación, ser claro es muy importante. Cuando te aclaras, construyes el vínculo intuitivo más fuerte de esta relación.",
    ("Neptün", "Boğa"): "En la relación puede haber incertidumbre sobre los valores y la seguridad. Puedes experimentar situaciones poco claras en el dinero y confusión sobre tus valores. Tu pareja aprecia tu confiabilidad, aunque la incertidumbre a veces crea inquietud. En la relación, los valores concretos son muy importantes. Cuando los vuelves concretos, eres la fuente más segura de esta relación.",
    ("Neptün", "İkizler"): "En la relación puede haber confusión en la comunicación. Puede haber una diferencia entre lo que dices y lo que quieres decir. Tu comunicación intuitiva es muy fuerte, pero tu falta de claridad a veces crea malentendidos. En la relación, ser abierto y claro es muy importante. Cuando te aclaras, construyes el puente de comprensión más profundo de esta relación.",
    ("Neptün", "Yengeç"): "En la relación puede haber incertidumbre en temas de hogar y familia. Puede haber dinámicas poco claras en la estructura familiar y verdades ocultas. Tu pareja aprecia tu calidez, aunque la incertidumbre a veces genera desconfianza. En la relación, un refugio seguro es muy importante. Cuando construyes un refugio seguro, creas el puerto más cálido de esta relación.",
    ("Neptün", "Aslan"): "En la relación puedes experimentar olas de inspiración en temas de creatividad y diversión. Hay un flujo intuitivo muy fuerte en el arte o el entretenimiento, pero puedes tener dificultad para concretarlo. Tu pareja aprecia tu creatividad, aunque la incertidumbre a veces crea decepción. En la relación, concretar la pasión es muy importante. Cuando la concretas, eres la mayor fuente de entretenimiento de esta relación.",
    ("Neptün", "Başak"): "En la relación puede haber incertidumbre en temas de vida cotidiana y salud. Puedes experimentar situaciones poco claras en las condiciones de trabajo y confusión en temas de salud. Tu pareja aprecia tu diligencia, aunque la incertidumbre a veces crea inquietud. En la relación, las soluciones prácticas son muy importantes. Cuando las vuelves prácticas, eres la fuente más segura de esta relación.",
    ("Neptün", "Terazi"): "En la relación, el riesgo de idealización y decepción es muy alto. Puedes ver a tu pareja más grande de lo que es, pero tu potencial de amor incondicional también es muy alto. En la relación, mirar con ojos claros es muy importante. Cuando miras con claridad, construyes el vínculo de amor más fuerte de esta relación.",
    ("Neptün", "Akrep"): "En la relación puede haber incertidumbre en temas de poder y control. Hay dinámicas de poder ocultas en juego y puedes experimentar un proceso de transformación profunda. Tu pareja aprecia tu profundidad, aunque la incertidumbre a veces crea miedo. En la relación, la confianza profunda es muy importante. Cuando puedes confiar, eres la fuente de transformación más profunda de esta relación.",
    ("Neptün", "Yay"): "En la relación puede haber incertidumbre en temas de creencia y filosofía. Tu antiguo sistema de creencias puede tambalearse, pero también puedes abrirte a comprensiones nuevas y más profundas. Tu pareja admira tu visión, aunque la incertidumbre a veces genera inquietud. En la relación, ver el panorama general es muy importante. Cuando te enraízas, eres el mayor guía espiritual de esta relación.",
    ("Neptün", "Oğlak"): "En la relación puede haber incertidumbre en temas de carrera y estatus. Puedes experimentar confusión sobre tus objetivos o la dirección de tu carrera. Tu pareja aprecia tu determinación, aunque la incertidumbre a veces crea inquietud. En la relación, los pasos concretos son muy importantes. Cuando los vuelves concretos, eres el estratega más seguro de esta relación.",
    ("Neptün", "Kova"): "En la relación puede haber incertidumbre en temas de amistad y comunidad. Puede haber dinámicas poco claras en tu círculo social, pero también puedes crear vínculos intuitivos muy fuertes para ayudar a las personas. Tu pareja admira tu visión, aunque la incertidumbre a veces genera inquietud. En la relación, la claridad es muy importante. Cuando te aclaras, construyes el vínculo de visión más especial de esta relación.",
    ("Neptün", "Balık"): "En la relación puede haber incertidumbre en el mundo espiritual. Tus intuiciones son muy fuertes, pero también es muy grande el riesgo de perder el contacto con la realidad. Tu alma es muy profunda y tus intuiciones son muy fuertes. En la relación, los límites son muy importantes. Cuando aclaras tus límites, construyes el vínculo espiritual más profundo de esta relación.",

    # === PLUTÓN — Lucha de poder, transformación ===
    ("Plüton", "Koç"): "Estás en el lugar donde la transformación de poder e identidad se vive con mayor intensidad. Dejas atrás tu antiguo yo y construyes uno nuevo: este proceso también afecta profundamente la relación. Tu pareja aprecia tu valor y tu capacidad de transformación, aunque puede temer tu control. En la relación, los equilibrios de poder cambian constantemente. Cuando aprendes sobre el control, eres el catalizador de transformación más fuerte de esta relación.",
    ("Plüton", "Boğa"): "Vives una transformación profunda sobre los valores y la seguridad. Dejas atrás tus valores antiguos y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu confiabilidad, aunque puede temer tu posesividad. En la relación, los conflictos de valores son muy intensos. Cuando compartes tus valores, eres el socio de valores más fuerte de esta relación.",
    ("Plüton", "İkizler"): "Vives una transformación profunda en tu forma de comunicarte y pensar. Dejas atrás los patrones antiguos de comunicación y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu inteligencia, pero debes tener cuidado con el riesgo de manipulación. En la relación, la comunicación abierta y transparente es muy importante. Cuando estableces una comunicación transparente, construyes el puente de comprensión más profundo de esta relación.",
    ("Plüton", "Yengeç"): "Vives una transformación profunda sobre el hogar, la familia y las raíces. Dejas atrás los patrones familiares antiguos y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu calidez, aunque puede temer tu apego excesivo. En la relación, la confianza y el apego son muy intensos. Cuando estableces un vínculo seguro, eres el constructor de hogares más profundo de esta relación.",
    ("Plüton", "Aslan"): "Vives una transformación profunda sobre la creatividad, el ego y la necesidad de atención. Dejas atrás los patrones antiguos del ego y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu valor, aunque puede temer tus choques de ego. En la relación, los equilibrios de poder son muy intensos. Cuando diriges tu ego, eres el mayor dueño del escenario de esta relación.",
    ("Plüton", "Başak"): "Vives una transformación profunda sobre la vida cotidiana, la salud y el servicio. Dejas atrás los patrones antiguos de trabajo y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu diligencia, aunque puede temer tu actitud crítica. En la relación, el servicio y la perfección son muy intensos. Cuando aceptas las imperfecciones, eres el observador más sutil de esta relación.",
    ("Plüton", "Terazi"): "Vives una transformación profunda sobre el equilibrio, la armonía y las sociedades. Dejas atrás los patrones antiguos de relación y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu elegancia, aunque puede temer la lucha de poder. En la relación, el equilibrio y la igualdad son muy intensos. Cuando encuentras el equilibrio, eres el árbitro más fuerte de esta relación.",
    ("Plüton", "Akrep"): "Estás en el lugar donde la transformación de poder, control y profundidad se vive con mayor intensidad. Dejas atrás tu antiguo yo y construyes uno nuevo: este proceso también afecta profundamente la relación. Tu pareja aprecia tu profundidad, aunque puede temer tu control. En la relación, la lucha de poder es muy intensa. Cuando aprendes a confiar, eres la fuente de transformación más profunda de esta relación.",
    ("Plüton", "Yay"): "Vives una transformación profunda sobre la creencia, la filosofía y el significado. Dejas atrás tu antiguo sistema de creencias y construyes uno nuevo: este proceso también afecta profundamente la relación. Tu pareja admira tu visión, aunque puede temer la intensidad de la transformación. En la relación, el panorama general es muy importante. Cuando das pasos concretos, eres el mayor guía de esta relación.",
    ("Plüton", "Oğlak"): "Vives una transformación profunda sobre la carrera, el estatus y las responsabilidades. Dejas atrás los patrones antiguos de carrera y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu determinación, aunque puede temer tu seriedad. En la relación, la estructura es muy intensa. Cuando también aumentas tu apertura emocional, eres el apoyo más confiable de esta relación.",
    ("Plüton", "Kova"): "Vives una transformación profunda sobre la libertad, la innovación y la transformación social. Dejas atrás los patrones sociales antiguos y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja admira tu visión, aunque puede temer la intensidad de la transformación. En la relación, la igualdad es muy importante. Cuando te acercas, construyes el vínculo de visión más especial de esta relación.",
    ("Plüton", "Balık"): "Vives una transformación profunda sobre el mundo espiritual y el inconsciente. Dejas atrás los patrones espirituales antiguos y construyes otros nuevos: este proceso también afecta profundamente la relación. Tu pareja aprecia tu profundidad, aunque puede temer la intensidad de la transformación. En la relación, la confianza profunda es muy importante. Cuando puedes confiar, construyes el vínculo espiritual más profundo de esta relación.",

}
