fbst_gezegen_ev_ebeveyn = {
    ("Güneş", 1): "{ebeveyn_iyelik} identity and will shine powerfully, making the child the radiant center of {ebeveyn_iyelik} life. {ebeveyn_iyelik} own being becomes a guiding light along the child's path.",
    ("Güneş", 2): "{ebeveyn_iyelik} self-worth is affirmed through the material and emotional security {ebeveyn_iyelik} provides the child. Protecting the child and preparing a precious foundation for them gives {ebeveyn_iyelik} life deep meaning.",
    ("Güneş", 3): "{ebeveyn_iyelik} energy sparkles in warm, heartfelt conversations with the child. The stories {ebeveyn_iyelik} tells and the things {ebeveyn_iyelik} shares gently shape how the child comes to see the world.",
    ("Güneş", 4): "{ebeveyn_iyelik} identity is deeply bound to home and roots. Building a warm, secure, and lasting family nest for the child is {ebeveyn_iyelik} greatest purpose.",
    ("Güneş", 5): "{ebeveyn_iyelik} joy and creativity come alive in playful moments with the child. {ebeveyn_iyelik} proudly showcases the child's talents and opens a stage for their light to shine.",
    ("Güneş", 6): "{ebeveyn_iyelik} orderly, systematic nature brings quiet confidence to the child's daily life. Routine and structure help nurture the child's sense of responsibility.",
    ("Güneş", 7): "{ebeveyn_iyelik} identity shines brightest in the fair, respectful relationship {ebeveyn_iyelik} builds with the child. Approaching the child with equality and balance nourishes their self-assurance.",
    ("Güneş", 8): "{ebeveyn_iyelik} strength emerges in the challenging seasons shared with the child. The resilience {ebeveyn_iyelik} shows in times of crisis instills a deep sense of trust in the child.",
    ("Güneş", 9): "{ebeveyn_iyelik} horizons are wide, and {ebeveyn_iyelik} loves passing on values, wisdom, and fresh perspectives to the child. {ebeveyn_iyelik} wants the child to look out upon the world from a broad, open window.",
    ("Güneş", 10): "{ebeveyn_iyelik} professional success and depth of knowledge contribute to the child's growth and future. Guiding the child toward a respected place in society matters deeply to {ebeveyn_iyelik}.",
    ("Güneş", 11): "{ebeveyn_iyelik} vision looks toward the future as {ebeveyn_iyelik} supports and encourages the child's dreams. {ebeveyn_iyelik} circle of friends and sense of community play a role in the child's development.",
    ("Güneş", 12): "{ebeveyn_iyelik} inner world and intuition are strong; {ebeveyn_iyelik} shares with the child a bond deeper than words. Self-sacrifice and quiet protection are the very foundation of this connection.",

    ("Ay", 1): "{ebeveyn_iyelik} feelings are open and sincere, and {ebeveyn_iyelik} shows the child affection with genuine warmth. This emotional closeness nourishes the child's sense of security.",
    ("Ay", 2): "{ebeveyn_iyelik} love is expressed through the concrete kindness of touch and nurture. Wrapping the child in care lets them feel they are truly safe and held.",
    ("Ay", 3): "{ebeveyn_iyelik} emotional world takes shape through the verbal bond {ebeveyn_iyelik} shares with the child. Talking with the child and truly listening supports their emotional growth.",
    ("Ay", 4): "{ebeveyn_iyelik} emotional security is drawn from the warm home {ebeveyn_iyelik} has created. Being the safe harbor the child can always return to lives in {ebeveyn_iyelik} very nature.",
    ("Ay", 5): "{ebeveyn_iyelik} happiness springs from joyful, playful moments with the child. {ebeveyn_iyelik} cheerful, affectionate manner supports the child's inner peace.",
    ("Ay", 6): "{ebeveyn_iyelik} attentive care and devotion bring serenity into the child's everyday life. The care {ebeveyn_iyelik} gives to health and routine instills quiet confidence in the child.",
    ("Ay", 7): "{ebeveyn_iyelik} emotional mirror reflects most brightly in the balanced relationship {ebeveyn_iyelik} shares with the child. Honoring and understanding the child's feelings helps them come to know themselves.",
    ("Ay", 8): "{ebeveyn_iyelik} deep emotions intensify in difficult moments with the child. {ebeveyn_iyelik} powerful devotion gives the child trust and strength when times are hard.",
    ("Ay", 9): "{ebeveyn_iyelik} values and beliefs guide the child like an emotional compass. {ebeveyn_iyelik} outlook on life and inner peace gently shape the child's spiritual growth.",
    ("Ay", 10): "{ebeveyn_iyelik} sense of responsibility runs deep, and {ebeveyn_iyelik} strives for the child's future with quiet devotion. How {ebeveyn_iyelik} manages society's expectations shapes the child's confidence.",
    ("Ay", 11): "{ebeveyn_iyelik} friendships and social circle help the child open up to the world. The bonds {ebeveyn_iyelik} forms with trusted people become a living example for the child.",
    ("Ay", 12): "{ebeveyn_iyelik} intuition and inner voice are strong; {ebeveyn_iyelik} senses the child's mood without a single word. Quiet, deep tenderness brings the child a soothing peace.",

    ("Merkür", 1): "{ebeveyn_iyelik} communication skills and gift for teaching stand out, making {ebeveyn_iyelik} the child's very first teacher. Patient answers to every question keep the child's curiosity alive.",
    ("Merkür", 2): "{ebeveyn_iyelik} shares knowledge in concrete, practical ways, teaching the child to learn by doing. Through this gentle structure, the meaning of value finds its place in the child's mind.",
    ("Merkür", 3): "{ebeveyn_iyelik} quick, cheerful speech keeps the bond with the child lively. The bridge {ebeveyn_iyelik} builds with words develops the child's language and communication skills.",
    ("Merkür", 4): "{ebeveyn_iyelik} mind comes to life in the conversations and stories shared at home. The child's world of thought is shaped within these warm exchanges.",
    ("Merkür", 5): "{ebeveyn_iyelik} creative, playful storytelling awakens the child's imagination. {ebeveyn_iyelik} makes learning a delight, so the child grows while learning joyfully.",
    ("Merkür", 6): "{ebeveyn_iyelik} orderly, meticulous mind brings rhythm to the child's learning habits. {ebeveyn_iyelik} attention to detail teaches the child to think practically.",
    ("Merkür", 7): "{ebeveyn_iyelik} honors balance in communication, valuing both listening and compromise with the child. This approach gifts the child with healthy communication skills.",
    ("Merkür", 8): "{ebeveyn_iyelik} curiosity and inquiring spirit deepen the child's mental world. An interest in the mysterious helps the child come to love thinking.",
    ("Merkür", 9): "{ebeveyn_iyelik} philosophical conversations broaden the child's horizons. The love of exploring different ideas gives the child a wide and generous perspective.",
    ("Merkür", 10): "{ebeveyn_iyelik} professional success and knowledge contribute to the child's growth and future. {ebeveyn_iyelik} work ethic and goals serve as an example for the child.",
    ("Merkür", 11): "{ebeveyn_iyelik} innovative ideas and social network help the child make sense of the world. Technology and new ways of thinking support the child's intellectual development.",
    ("Merkür", 12): "{ebeveyn_iyelik} inner world and intuition run deep; {ebeveyn_iyelik} understands even what the child leaves unsaid. Quiet observation allows {ebeveyn_iyelik} to read the child's needs with accuracy.",

    ("Venüs", 1): "{ebeveyn_iyelik} love is open and heartfelt, offered to the child without condition. This warm acceptance becomes the child's first and most powerful experience of love.",
    ("Venüs", 2): "{ebeveyn_iyelik} shows love through thoughtful gifts and devoted attention. The sense of value the child feels forms the very foundation of their self-esteem.",
    ("Venüs", 3): "{ebeveyn_iyelik} loves expressing affection in words. Loving phrases and gentle compliments help the child feel deeply cherished.",
    ("Venüs", 4): "{ebeveyn_iyelik} love lives within the warm, beautiful home {ebeveyn_iyelik} has built. The home's peaceful atmosphere nourishes the child's sense of love and security.",
    ("Venüs", 5): "{ebeveyn_iyelik} expresses love through play and celebration. Joyful moments with the child strengthen the bond of love between them.",
    ("Venüs", 6): "{ebeveyn_iyelik} shows love through devoted care and service. The attentive tenderness {ebeveyn_iyelik} offers the child shapes their own language of love.",
    ("Venüs", 7): "{ebeveyn_iyelik} builds a fair, balanced relationship of love with the child. Mutual respect and harmony teach the child the art of healthy relationships.",
    ("Venüs", 8): "{ebeveyn_iyelik} love is deep and passionate, growing even stronger in hard times. The loyalty {ebeveyn_iyelik} shows the child gives them lasting trust.",
    ("Venüs", 9): "{ebeveyn_iyelik} generous heart and openness to difference offer the child a world warmed by love. {ebeveyn_iyelik} teaches the child to appreciate all that is beautiful.",
    ("Venüs", 10): "{ebeveyn_iyelik} grace and values help the child find their place in society. The dignified presence {ebeveyn_iyelik} carries becomes an example for the child.",
    ("Venüs", 11): "{ebeveyn_iyelik} friendships and social circle help the child grow within an embrace of love. Sharing love freely lets the child feel valued within the community.",
    ("Venüs", 12): "{ebeveyn_iyelik} love is quiet and self-giving. Knowing how to love without expecting anything back gives the child the purest love one can know.",

    ("Mars", 1): "{ebeveyn_iyelik} protective instinct and courage run deep; {ebeveyn_iyelik} steps forward to shield the child from every harm. {ebeveyn_iyelik} spirited manner fills the child with confidence.",
    ("Mars", 2): "{ebeveyn_iyelik} works to provide the child with material and emotional security. Every effort {ebeveyn_iyelik} pours in is offered with the aim of building the child a safe life.",
    ("Mars", 3): "{ebeveyn_iyelik} is direct and outspoken, placing honesty at the heart of communication with the child. {ebeveyn_iyelik} helps the child learn to stand up for themselves.",
    ("Mars", 4): "{ebeveyn_iyelik} is resolute in guarding home and family. Providing the child a peaceful and secure haven is the most important goal of all.",
    ("Mars", 5): "{ebeveyn_iyelik} channels their energy into playful, joyful time with the child. {ebeveyn_iyelik} encourages the child to be happy, lively, and full of life.",
    ("Mars", 6): "{ebeveyn_iyelik} energy and discipline in daily tasks cultivate the child's spirit of hard work. {ebeveyn_iyelik} teaches the child the strength of taking responsibility.",
    ("Mars", 7): "{ebeveyn_iyelik} balances courage and compromise in the relationship with the child. The fair way {ebeveyn_iyelik} resolves conflict teaches the child healthy communication.",
    ("Mars", 8): "{ebeveyn_iyelik} endurance through difficult periods lends strength to the child. The way {ebeveyn_iyelik} navigates crisis nourishes the child's inner power.",
    ("Mars", 9): "{ebeveyn_iyelik} adventurous spirit encourages the child to be brave and enterprising. {ebeveyn_iyelik} makes room for the child to experience life for themselves.",
    ("Mars", 10): "{ebeveyn_iyelik} determined, ambitious nature strengthens the child's drive to reach their goals. Perseverance and hard work are the most precious heritage {ebeveyn_iyelik} passes on.",
    ("Mars", 11): "{ebeveyn_iyelik} is active and bold in social life, uplifting the child's confidence. {ebeveyn_iyelik} presence among others becomes an example for the child.",
    ("Mars", 12): "{ebeveyn_iyelik} holds inner strength in quiet reserve, protecting the child with calm determination. A protection that is gentle yet powerful brings the child peace.",

    ("Jüpiter", 1): "{ebeveyn_iyelik} optimistic, generous spirit instills confidence in the child. {ebeveyn_iyelik} positive view of life lets the child grow up courageous and sure of themselves.",
    ("Jüpiter", 2): "{ebeveyn_iyelik} generosity and spirit of sharing enrich the child's understanding of value. The abundance {ebeveyn_iyelik} offers feeds the child's sense of security.",
    ("Jüpiter", 3): "{ebeveyn_iyelik} desire to teach and share knowledge is strong, and it nourishes the child's curiosity. {ebeveyn_iyelik} wide learning grows the child's love of discovery.",
    ("Jüpiter", 4): "{ebeveyn_iyelik} brings abundance and peace into the home, enriching the child's inner life. Family traditions and inherited wisdom help the child put down deep roots.",
    ("Jüpiter", 5): "{ebeveyn_iyelik} joy and enthusiasm shine through the moments shared with the child. {ebeveyn_iyelik} supports the child's creativity and self-belief.",
    ("Jüpiter", 6): "{ebeveyn_iyelik} care for health and order gifts the child with wholesome habits. The optimism {ebeveyn_iyelik} carries into daily life brings the child peace.",
    ("Jüpiter", 7): "{ebeveyn_iyelik} brings justice and understanding to the relationship with the child. Trusting the child and granting them room to grow builds their confidence.",
    ("Jüpiter", 8): "{ebeveyn_iyelik} optimism in the face of difficulty plants hope in the child. The wisdom of learning from crises supports the child's maturing.",
    ("Jüpiter", 9): "{ebeveyn_iyelik} horizons and beliefs give the child a broad worldview. Openness to other cultures and ideas expands the child's vision.",
    ("Jüpiter", 10): "{ebeveyn_iyelik} success and standing in society light the way for the child's future. Being a fine example shapes the child's career goals.",
    ("Jüpiter", 11): "{ebeveyn_iyelik} social circle and contribution to community let the child grow up in a wider world. {ebeveyn_iyelik} friendships and ideals inspire the child.",
    ("Jüpiter", 12): "{ebeveyn_iyelik} spiritual depth and intuition enrich the child's inner world. The trust and gratitude {ebeveyn_iyelik} holds toward life bring the child serenity.",

    ("Satürn", 1): "{ebeveyn_iyelik} disciplined, responsible nature gives the child a solid foundation. Rules and boundaries allow the child to grow in confidence and safety.",
    ("Satürn", 2): "{ebeveyn_iyelik} frugal, well-planned ways teach the child financial awareness. Through this discipline, the idea of value and effort settles firmly in the child's mind.",
    ("Satürn", 3): "{ebeveyn_iyelik} is a person of their word, consistent and true, a model the child can rely upon. {ebeveyn_iyelik} patient communication helps the child learn to think with maturity.",
    ("Satürn", 4): "{ebeveyn_iyelik} holds fast to family rules and traditions, offering the child a solid structure. Order within the home lets the child feel safe and secure.",
    ("Satürn", 5): "{ebeveyn_iyelik} honors discipline and responsibility even in play. While cultivating the child's sense of duty, {ebeveyn_iyelik} never withholds love.",
    ("Satürn", 6): "{ebeveyn_iyelik} orderly, disciplined life helps the child adopt healthy habits. A sense of responsibility is imparted to the child from a young age.",
    ("Satürn", 7): "{ebeveyn_iyelik} brings honesty and trust to the relationship with the child. Keeping promises strengthens the child's sense of security.",
    ("Satürn", 8): "{ebeveyn_iyelik} maturity in difficult periods teaches the child resilience. Managing crises with composure gives the child confidence.",
    ("Satürn", 9): "{ebeveyn_iyelik} principled, earnest nature helps the child distinguish right from wrong. {ebeveyn_iyelik} values contribute to the child's maturing.",
    ("Satürn", 10): "{ebeveyn_iyelik} understanding of responsibility and discipline shapes the child's career goals. A steadfast, determined example lends strength to the child.",
    ("Satürn", 11): "{ebeveyn_iyelik} trustworthy friendships and lasting relationships teach the child the value of enduring bonds. {ebeveyn_iyelik} sense of responsibility supports the child's social growth.",
    ("Satürn", 12): "{ebeveyn_iyelik} inner discipline and maturity become a quiet source of strength for the child. The ability to meet hardship serves as an example for the child.",

    ("Uranüs", 1): "{ebeveyn_iyelik} freedom-loving, independent nature encourages the child to stand on their own two feet. A stance that refuses to fit any mold inspires the child.",
    ("Uranüs", 2): "{ebeveyn_iyelik} views values with an innovative eye, giving the child a flexible understanding of worth. {ebeveyn_iyelik} openness to change strengthens the child's adaptability.",
    ("Uranüs", 3): "{ebeveyn_iyelik} free and unconventional way of thinking supports the child's mental independence. Ideas beyond the ordinary give the child courage.",
    ("Uranüs", 4): "{ebeveyn_iyelik} creates a flexible, innovative atmosphere at home where the child grows freely. Not accepting traditions without question, {ebeveyn_iyelik} teaches the child to think critically.",
    ("Uranüs", 5): "{ebeveyn_iyelik} creativity and uncommon tastes feed the child's imagination. {ebeveyn_iyelik} champions the child's originality and never forces them into a mold.",
    ("Uranüs", 6): "{ebeveyn_iyelik} finds innovative solutions in daily life, teaching the child to think practically and differently. An unusual view of routine builds the child's flexibility.",
    ("Uranüs", 7): "{ebeveyn_iyelik} builds an equal, friendly relationship with the child. Choosing to stand beside the child rather than above them strengthens their confidence.",
    ("Uranüs", 8): "{ebeveyn_iyelik} is flexible and inventive in the face of change, gifting the child adaptability. Greeting sudden shifts with calm gives the child confidence.",
    ("Uranüs", 9): "{ebeveyn_iyelik} open-minded nature lets the child enter different worlds. Curiosity for the new and different expands the child's vision.",
    ("Uranüs", 10): "{ebeveyn_iyelik} unconventional sense of career and lifestyle gives the child the courage to find their own way. Rather than place the child in a mold, {ebeveyn_iyelik} lets them remain free.",
    ("Uranüs", 11): "{ebeveyn_iyelik} wide social network and innovative circle allow the child to meet a great variety of people. {ebeveyn_iyelik} sense of community opens new horizons for the child.",
    ("Uranüs", 12): "{ebeveyn_iyelik} intuitive, heartfelt inventiveness enriches the child's inner world. {ebeveyn_iyelik} independent spirit gives the child the courage to discover their own truth.",

    ("Neptün", 1): "{ebeveyn_iyelik} intuition and compassion run deep; {ebeveyn_iyelik} understands the child without a word. The heartfelt, spiritual bond {ebeveyn_iyelik} shares lets the child feel safe and protected.",
    ("Neptün", 2): "{ebeveyn_iyelik} values spiritual wealth above material things, teaching the child inner richness. {ebeveyn_iyelik} generous, tender manner teaches the child the joy of sharing.",
    ("Neptün", 3): "{ebeveyn_iyelik} intuitive, sensitive communication lets the child express their feelings freely. Listening without judgment brings the child peace.",
    ("Neptün", 4): "{ebeveyn_iyelik} adds a spiritual, tranquil atmosphere to the home. The child's inner world grows safely within this calm space.",
    ("Neptün", 5): "{ebeveyn_iyelik} imagination and love of art nourish the child's creativity. Letting the child dream enriches their soul.",
    ("Neptün", 6): "{ebeveyn_iyelik} serves selflessly, meeting the child's needs with great care. The devotion {ebeveyn_iyelik} shows develops the child's sense of compassion.",
    ("Neptün", 7): "{ebeveyn_iyelik} shares an unconditional, tender relationship with the child. Accepting the child exactly as they are helps them feel their own worth.",
    ("Neptün", 8): "{ebeveyn_iyelik} deep feelings and intuition become healing for the child in troubled times. Understanding and wrapping the child in warmth deepens their trust.",
    ("Neptün", 9): "{ebeveyn_iyelik} spiritual depth and beliefs light the way for the child's soul. A wide and compassionate view of life inspires the child.",
    ("Neptün", 10): "{ebeveyn_iyelik} idealistic, caring nature helps the child grow into someone sensitive to others. The wish to be of use to society offers the child a noble purpose.",
    ("Neptün", 11): "{ebeveyn_iyelik} love for community and humanity encourages the child to be helpful and kind. {ebeveyn_iyelik} ideals and friendships become a source of inspiration.",
    ("Neptün", 12): "{ebeveyn_iyelik} deepest intuition and spirituality bring inner peace to the child. An unseen yet powerful bond gives the child unconditional trust.",

    ("Plüton", 1): "{ebeveyn_iyelik} powerful, transformative presence leaves a deep mark upon the child's life. Strengthening the child and preparing them for life matters deeply to {ebeveyn_iyelik}.",
    ("Plüton", 2): "{ebeveyn_iyelik} protective, devoted nature gives the child a profound sense of trust. {ebeveyn_iyelik} values putting every resource toward the child's future.",
    ("Plüton", 3): "{ebeveyn_iyelik} deep, influential communication shapes the child's world of thought. {ebeveyn_iyelik} words carry weight, raising the child's awareness of what truly matters.",
    ("Plüton", 4): "{ebeveyn_iyelik} is profoundly devoted to family bonds and roots. {ebeveyn_iyelik} instills in the child a strong sense of belonging and family consciousness.",
    ("Plüton", 5): "{ebeveyn_iyelik} passionate, resolute nature strengthens the child's determination. {ebeveyn_iyelik} supports the child in expressing themselves and discovering their strengths.",
    ("Plüton", 6): "{ebeveyn_iyelik} gift for solving problems at their source teaches the child to think effectively. {ebeveyn_iyelik} disciplined, decisive manner helps the child mature.",
    ("Plüton", 7): "{ebeveyn_iyelik} forms a deep, intense bond with the child. The powerful experiences they share shape the child's character.",
    ("Plüton", 8): "{ebeveyn_iyelik} strength and resolve in moments of crisis teach the child endurance. Emerging transformed from hardship inspires the child.",
    ("Plüton", 9): "{ebeveyn_iyelik} deep beliefs and inquiring mind lead the child to question life itself. {ebeveyn_iyelik} passion for seeking truth offers the child a precious lesson.",
    ("Plüton", 10): "{ebeveyn_iyelik} strong will and determination inspire the child to reach their goals. A resolute example shapes the child's career path.",
    ("Plüton", 11): "{ebeveyn_iyelik} influential circle and strong connections open doors of opportunity for the child. Interest in social change adds vision to the child.",
    ("Plüton", 12): "{ebeveyn_iyelik} inner strength and deep intuition become a hidden reservoir of power for the child. A quiet yet potent protection lets the child grow in peace.",

    ("Lilith", 1): "{ebeveyn_iyelik} original, authentic nature gives the child the courage to stay true to themselves. Refusing to fit the mold encourages the child to develop a free identity.",
    ("Lilith", 2): "{ebeveyn_iyelik} sets values by {ebeveyn_iyelik} own measure, teaching the child to think independently. An unconventional approach to material matters widens the child's horizons.",
    ("Lilith", 3): "{ebeveyn_iyelik} bold, frank communication lets the child express themselves freely. Teaching the child not to be crushed under pressure gives them true strength.",
    ("Lilith", 4): "{ebeveyn_iyelik} brings long-suppressed emotions to the surface within the family, and this teaches the child honesty. {ebeveyn_iyelik} takes care that the child is accepted exactly as they are.",
    ("Lilith", 5): "{ebeveyn_iyelik} creative, unconventional tastes feed the child's imagination. {ebeveyn_iyelik} supports the child's original side and never tries to change them.",
    ("Lilith", 6): "{ebeveyn_iyelik} sets {ebeveyn_iyelik} own rules in daily life and teaches the child to set their own boundaries as well. An unusual view of routine gives the child flexibility.",
    ("Lilith", 7): "{ebeveyn_iyelik} builds an honest, heartfelt relationship with the child. Choosing to understand rather than steer the child wins their trust.",
    ("Lilith", 8): "{ebeveyn_iyelik} deep, transformative experiences offer the child a chance to discover their inner strength. The courage to face one's shadows inspires the child.",
    ("Lilith", 9): "{ebeveyn_iyelik} uncommon beliefs and free philosophy teach the child to think widely. Standing against dogma gives the child independent thought.",
    ("Lilith", 10): "{ebeveyn_iyelik} refusal to bow to authority lets the child carve out their own path. The strength to resist social pressure gives the child courage.",
    ("Lilith", 11): "{ebeveyn_iyelik} uncommon friendships and free circle teach the child to understand people of many kinds. {ebeveyn_iyelik} teaches the child to respect difference.",
    ("Lilith", 12): "{ebeveyn_iyelik} hidden, powerful inner world lends the child a deep intuitiveness. The power to transform suppressed emotion gives the child maturity.",

    ("Chiron", 1): "{ebeveyn_iyelik} becomes a powerful example for the child through the wisdom gained from {ebeveyn_iyelik} own wounds. The experiences {ebeveyn_iyelik} has lived help the child understand themselves.",
    ("Chiron", 2): "{ebeveyn_iyelik} experiences with value and trust help the child build a healthy self-regard. Having learned from {ebeveyn_iyelik} own wounds, {ebeveyn_iyelik} stands beside the child with understanding.",
    ("Chiron", 3): "{ebeveyn_iyelik} experiences in communication give the child the courage to express themselves. Being a patient, understanding listener helps the child open their heart.",
    ("Chiron", 4): "{ebeveyn_iyelik} experiences with family and home let the child grow in a secure environment. Healing the wounds of the past brings the child peace.",
    ("Chiron", 5): "{ebeveyn_iyelik} experiences with creativity and self-expression help the child gain confidence. {ebeveyn_iyelik} supports the child in discovering their own talents.",
    ("Chiron", 6): "{ebeveyn_iyelik} experiences with health and service teach the child how to care for themselves. {ebeveyn_iyelik} is careful not to pass {ebeveyn_iyelik} own perfectionism on to the child.",
    ("Chiron", 7): "{ebeveyn_iyelik} experiences in relationships teach the child how to form healthy bonds. {ebeveyn_iyelik} understanding, compassionate approach nourishes the child's trust.",
    ("Chiron", 8): "{ebeveyn_iyelik} experiences with deep loss and transformation instill a powerful resilience in the child. The gift of transforming hardship inspires the child.",
    ("Chiron", 9): "{ebeveyn_iyelik} experiences in the search for meaning help the child develop their own beliefs. {ebeveyn_iyelik} deep wisdom about life guides the child along the way.",
    ("Chiron", 10): "{ebeveyn_iyelik} experiences with success and inadequacy help the child build a healthy confidence. {ebeveyn_iyelik} is careful to shield the child from pressure.",
    ("Chiron", 11): "{ebeveyn_iyelik} experiences within the community strengthen the child's sense of belonging. Facing the fear of exclusion gives the child courage.",
    ("Chiron", 12): "{ebeveyn_iyelik} has transformed {ebeveyn_iyelik} deepest wounds with wisdom, and this brings the child peace. An understanding, compassionate presence serves as the child's safe harbor.",

    ("Juno", 1): "{ebeveyn_iyelik} loyalty and devotion to the child give them a powerful sense of security. Feeling that {ebeveyn_iyelik} is always by their side means the world to the child.",
    ("Juno", 2): "{ebeveyn_iyelik} faithfully tends the child's material and emotional needs. Keeping every promise deepens the child's trust.",
    ("Juno", 3): "{ebeveyn_iyelik} is honest and consistent in communication with the child. The confidence {ebeveyn_iyelik} brings through words helps the child form healthy relationships.",
    ("Juno", 4): "{ebeveyn_iyelik} devotion to family and home instills in the child a strong sense of belonging. The importance {ebeveyn_iyelik} gives to family bonds is an example for the child.",
    ("Juno", 5): "{ebeveyn_iyelik} remains devoted to joyful time with the child and is careful never to neglect them. Time spent together gives the child lasting confidence.",
    ("Juno", 6): "{ebeveyn_iyelik} faithfully attends to the child's care and needs. Regular, dependable support strengthens the child's sense of security.",
    ("Juno", 7): "{ebeveyn_iyelik} honors loyalty and fairness in the relationship with the child. Building an equal and dependable bond raises the child's self-esteem.",
    ("Juno", 8): "{ebeveyn_iyelik} stands by the child in hard times and proves {ebeveyn_iyelik} loyalty. This steadfast devotion gives the child a deep and lasting trust.",
    ("Juno", 9): "{ebeveyn_iyelik} is loyal to values and beliefs, teaching the child to live by principle. This consistency helps the child grow into a trustworthy person.",
    ("Juno", 10): "{ebeveyn_iyelik} commitment to the child's future is strong, preparing them a solid foundation. {ebeveyn_iyelik} sense of responsibility supports the child's career path.",
    ("Juno", 11): "{ebeveyn_iyelik} is loyal to {ebeveyn_iyelik} friends and community, teaching the child the value of reliable bonds. The trust within {ebeveyn_iyelik} circle is an example for the child.",
    ("Juno", 12): "{ebeveyn_iyelik} shows devotion to the child quietly and from the depth of the heart. An unseen yet powerful loyalty lets the child grow in peace.",

    ("Ceres", 1): "{ebeveyn_iyelik} nurturing, tender nature supports the child's healthy growth. The attentive care {ebeveyn_iyelik} gives is the most tangible expression of {ebeveyn_iyelik} love.",
    ("Ceres", 2): "{ebeveyn_iyelik} carefully meets the child's physical and emotional needs. The secure environment {ebeveyn_iyelik} offers supports the child's development.",
    ("Ceres", 3): "{ebeveyn_iyelik} nurturing conversations with the child help them come to know the world. {ebeveyn_iyelik} caring words give the child confidence.",
    ("Ceres", 4): "{ebeveyn_iyelik} turns the home into a nurturing ground for the child's growth. The warmth of the house lets the child flourish in safety.",
    ("Ceres", 5): "{ebeveyn_iyelik} builds a nourishing bond with the child through play and delight. Cheerful moments enrich the child's spirit.",
    ("Ceres", 6): "{ebeveyn_iyelik} gives great attention to the child's daily care and health. Steady, devoted care lets the child grow in serenity.",
    ("Ceres", 7): "{ebeveyn_iyelik} mutually nurturing relationship with the child forms a powerful bond. Listening and understanding deepen the child's trust.",
    ("Ceres", 8): "{ebeveyn_iyelik} experiences with loss and separation teach {ebeveyn_iyelik} to approach the child with compassion. The patience {ebeveyn_iyelik} shows in hard times gives the child confidence.",
    ("Ceres", 9): "{ebeveyn_iyelik} helps the child come to know different cultures and values. {ebeveyn_iyelik} nurturing philosophy gives the child a broad worldview.",
    ("Ceres", 10): "{ebeveyn_iyelik} makes a nurturing plan for the child's future. Every effort {ebeveyn_iyelik} invests helps the child become a successful adult.",
    ("Ceres", 11): "{ebeveyn_iyelik} values community and friendship, teaching the child the strength of solidarity. {ebeveyn_iyelik} caring social circle supports the child's development.",
    ("Ceres", 12): "{ebeveyn_iyelik} nurtures the child's soul and inner world as well, cherishing spiritual fulfillment. An unseen yet powerful tenderness brings the child peace.",

    ("KAD", 1): "{ebeveyn_iyelik} life purpose is the most powerful experience that gives the child's life meaning. Guiding the child is an essential part of {ebeveyn_iyelik} destiny.",
    ("KAD", 2): "{ebeveyn_iyelik} aims to give the child firm values and a secure foundation. The reassurance {ebeveyn_iyelik} provides walks beside the child upon their journey of fate.",
    ("KAD", 3): "{ebeveyn_iyelik} considers it destiny to pass on knowledge and experience to the child. What {ebeveyn_iyelik} shares helps the child find their own way.",
    ("KAD", 4): "{ebeveyn_iyelik} is devoted to family roots and traditions and wishes to pass this heritage on to the child. A deep-rooted, secure home is the child's very foundation.",
    ("KAD", 5): "{ebeveyn_iyelik} aims to support the child's joy and creativity. Seeing the child happy and self-assured is part of {ebeveyn_iyelik} destiny.",
    ("KAD", 6): "{ebeveyn_iyelik} aims to teach the child a sense of responsibility and order. Wholesome habits ease the child's journey of destiny.",
    ("KAD", 7): "{ebeveyn_iyelik} balanced relationship with the child is an important step upon the path of destiny. Treating the child fairly and with understanding supports their development.",
    ("KAD", 8): "{ebeveyn_iyelik} experience of struggling through difficulty helps the child grow strong. The transformations {ebeveyn_iyelik} has lived become a source of inspiration.",
    ("KAD", 9): "{ebeveyn_iyelik} aims to give the child a broad worldview. {ebeveyn_iyelik} horizons and beliefs light the way as the child seeks their own path.",
    ("KAD", 10): "{ebeveyn_iyelik} hopes the child becomes a successful and respected person in society. The discipline and determination {ebeveyn_iyelik} passes on walk beside the child on the journey of fate.",
    ("KAD", 11): "{ebeveyn_iyelik} values the child forming friendships and finding their place in the community. The hope and vision {ebeveyn_iyelik} shares illuminate the child's future.",
    ("KAD", 12): "{ebeveyn_iyelik} fulfills {ebeveyn_iyelik} spiritual purpose by protecting and watching over the child. Quiet guidance leaves a deep mark upon the child's inner world.",

    ("GAD", 1): "{ebeveyn_iyelik} inherited patterns from the past shape the child's developing identity. Recognizing and transforming these cycles matters deeply for both {ebeveyn_iyelik} and the child.",
    ("GAD", 2): "{ebeveyn_iyelik} past experiences with value and security shape the child's self-esteem. A conscious approach keeps these patterns from being passed on to the child.",
    ("GAD", 3): "{ebeveyn_iyelik} communication habits influence the bond with the child. Noticing the patterns of the past lets {ebeveyn_iyelik} offer the child healthier communication.",
    ("GAD", 4): "{ebeveyn_iyelik} family patterns influence the home {ebeveyn_iyelik} builds and the child's sense of security. Transforming these cycles provides the child a more peaceful environment.",
    ("GAD", 5): "{ebeveyn_iyelik} inherited patterns around creativity and joy can affect the child's freedom. Overcoming them lets the child grow up in gladness.",
    ("GAD", 6): "{ebeveyn_iyelik} daily routines and health habits influence the child's development. A conscious approach lets {ebeveyn_iyelik} offer the child a healthy way of life.",
    ("GAD", 7): "{ebeveyn_iyelik} relationship patterns influence the bond with the child. Recognizing the echoes of the past gives the child a healthy language of love.",
    ("GAD", 8): "{ebeveyn_iyelik} patterns of loss and transformation shape the child's ability to cope with difficulty. {ebeveyn_iyelik} own transformation teaches the child resilience.",
    ("GAD", 9): "{ebeveyn_iyelik} patterns of belief and philosophy shape the child's worldview. Widening these patterns gives the child a liberating perspective.",
    ("GAD", 10): "{ebeveyn_iyelik} patterns of success and responsibility influence the child's idea of career. A conscious approach keeps {ebeveyn_iyelik} from raising the child under pressure.",
    ("GAD", 11): "{ebeveyn_iyelik} social patterns influence the child's place in society. Transforming them offers the child a free and open social life.",
    ("GAD", 12): "{ebeveyn_iyelik} subconscious patterns shape the child's inner world profoundly. Recognizing and transforming these deep patterns leaves the child a peaceful inheritance.",
}