fbst_sabian = {
    "Koc": {
        1: ("A woman emerging from the sea, embracing a seal", "New beginnings; the courage to rise from the waters of the past and be reborn in an entirely new form within this relationship."),
        2: ("A comedian performing his tricks in a valley far from prying eyes", "Discovering the joy and hidden potential within the relationship itself, without needing the approval of the outer world."),
        3: ("A man charting a map of his country", "The effort to define the relationship's own boundaries, its latent potential, and the future shared living space it will create."),
        4: ("Two lovers walking a lonely, secluded path", "The power to withdraw from the world's rush and build the relationship's own sacred privacy and intimate seclusion."),
        5: ("A winged triangle", "Spirit, body, and mind attaining wholeness, lifting the relationship beyond earthly limits into a divine dimension of power."),
        6: ("A square with one side brilliantly illuminated", "Universal light falling upon the relationship's steadfast structural foundations; it reveals the destined direction that deserves your focus."),
        7: ("A man who expresses himself in two different worlds at once", "By balancing both the material and spiritual realms, the relationship achieves a flawless harmony that transcends duality."),
        8: ("A large woman's hat with ribbons, waving in an eastern wind", "Forming an intuitive shield against the universal winds of change, and attuning to spiritual storms without resisting them."),
        9: ("A medium focused on a crystal ball", "The ability to look beyond appearances and telepathically read the silent calls and hidden wounds within your partner's inner world."),
        10: ("A teacher giving new forms to traditional images", "Breaking old habits and entrenched toxic relationship structures, recreating your bond with an entirely new vision."),
        11: ("A ruler of a country", "The time to declare the relationship's own kingdom, to take responsibility, and to establish the unshakable authority of this destined union."),
        12: ("A flock of wild geese flying in a triangle formation", "Flawless destined synchronization toward shared goals; the power of moving forward effortlessly, guided by a divine instinct."),
        13: ("An unexploded bomb; a failed social uprising", "The possibility that the anger and crises building within you dissolve rather than erupt destructively, transforming into spiritual wisdom."),
        14: ("A serpent coiling near a man and a woman", "Karmic wisdom; deep-rooted sexual energy (Kundalini) and the mysterious, transformative magnetism awakening from the relationship's deepest core."),
        15: ("A Native American weaving a ceremonial blanket", "The endeavor to weave every moment of the relationship with fine patience and labor, turning it into a sacred spiritual armor or haven against the outside."),
        16: ("Nature spirits (fairies) working at sunset", "Beyond daily efforts, invisible universal forces (destiny's shock absorbers) are at work to mend and support your relationship."),
        17: ("Two unmarried women sitting in dignified silence", "Overcoming the fear of loneliness; the virtue of accompanying one another in silence and spiritual stillness with immense peace."),
        18: ("An empty hammock strung between two trees", "That sacred moment when the relationship needs to set aside action and effort, surrendering to rest, idleness, and its natural flow."),
        19: ("A magic carpet", "The potential to reject worldly limits and logic, transcending boundaries through imagination and faith, and carrying your relationship into a fairytale dimension."),
        20: ("A young girl feeding birds in winter", "The miracle of nourishing each other's soul with compassion, mercy, and unconditional love even in the harshest, coldest, most critical moments."),
        21: ("A boxer entering the ring", "The relationship arming itself with courage and decisive power to battle external obstacles, difficulties, or inner shadows."),
        22: ("A gateway opening into a garden where all desires are fulfilled", "The promise of reaching the summit of spiritual and worldly fulfillment; standing at the threshold where obstacles fall away and destiny's rewards and abundance await."),
        23: ("A pregnant woman in a light summer dress", "A new vision grow within the relationship: a seed of creativity, fertility, or spiritual fruit preparing for birth."),
        24: ("Curtains swaying through an open window, taking the shape of a cornucopia", "When the relationship surrenders completely to the universal flow, cosmic fortune and spiritual abundance pour in unexpectedly."),
        25: ("The possibility of a human gaining experience on two different planes of being", "The grace of living love masterfully in both its most passionate physical dimension and its most sublime divine dimension, simultaneously."),
        26: ("A man bearing more talents than he can carry", "The relationship's potential overflowing; the test of focusing this intensely destined energy without scattering it, and managing it rightly."),
        27: ("A lost opportunity regained through imagination", "Past mistakes or missed chances being mended through great love and faith, redrawing the relationship's destined course."),
        28: ("A performance artist confronting a large, disappointed audience", "The collision of excessive expectations with reality; the test of masks falling away and accepting the naked truth as it is, with love."),
        29: ("The music of the celestial spheres (the planets)", "That divine, cosmic point of synchronization where your souls enter perfect harmony with the universal vibration, needing no words."),
        30: ("A duck pond and its ducklings", "Attaining serenity in this phase of the destined journey; completing a place of belonging, a peaceful home, and absolute protection.")
    },
    "Boga": {
        1: ("Gold dust carried by a clear mountain stream", "The time to notice the immense material and spiritual wealth hidden in the relationship's natural flow, and to accept this abundance with love."),
        2: ("An electric storm; nature's tremendous power beneath a dark sky", "Crises and sudden eruptions being, in truth, a cosmic healing and awakening that cleanses the stagnant energy between you."),
        3: ("Natural steps ascending to a meadow blooming with clover", "The relationship growing step by step, organically and without haste, along its path toward peace, abundance, and rootedness."),
        4: ("A golden cube at the end of a rainbow", "The great destined reward that follows stormy processes and trials; the spiritual and material fulfillment reached together."),
        5: ("A widow waiting beside an open grave", "The test of bidding farewell to past pain and exhausted karmic bonds, making full room for this new relationship through spiritual cleansing."),
        6: ("A suspension bridge built over a deep chasm", "The power to bridge the seemingly insurmountable differences between you with a strong, reliable bridge of communication and loyalty."),
        7: ("The Samaritan woman at the well", "The virtue of breaking old prejudices and worldly taboos, quenching the deepest thirst in your partner's soul with unconditional love."),
        8: ("A sled standing on snowless ground", "Understanding the importance of timing in plans for the future; the will to wait patiently until the right destined conditions arise."),
        9: ("A fully decorated Christmas tree", "Keeping hope alive even on the darkest or coldest days, and celebrating the inner values you offer each other."),
        10: ("A Red Cross nurse", "A covenant of unconditional compassion and sacrifice: to be your partner's greatest spiritual healer in their weakest, most wounded moment."),
        11: ("A woman watering the flowers in her garden", "The wisdom that love turns into an unshakable, lasting home only when it is nourished by daily, steady, practical care."),
        12: ("A young couple gazing into shop windows", "A phase of dreaming together, building the future side by side, and joyfully setting the relationship's worldly and material goals."),
        13: ("A porter bearing heavy loads", "Bravely shouldering the relationship's material or destined burdens; loyalty and responsibility becoming a heavy test of patience."),
        14: ("Children playing on the shore and seashells along the water's edge", "Enjoying joy safely within natural limits; surrendering to childlike, sheltered, pure feelings within a peaceful home space."),
        15: ("A man with his head wrapped in a thick scarf", "Protecting the relationship's privacy from the outer world's noise and toxic interference; the need to listen only to each other's inner voice."),
        16: ("An old teacher who cannot capture his students' attention", "The time to let go of old, ineffective patterns; the necessity of finding a new, inspiring shared language instead of stubborn rules."),
        17: ("A symbolic battle between swords and torches", "The test of choosing between mental enlightenment (the torch) and destructive criticism (the sword) in the relationship: choosing healing over being right."),
        18: ("A woman airing an old bag from an open window", "A cleansing that purges the old poisons, doubts, and burdens accumulated in the subconscious with love's fresh, healing wind."),
        19: ("A new continent rising from the ocean", "The miracle of the relationship creating an entirely new, unshakable, concrete foundation (a continent) after great crises and emotional upheaval."),
        20: ("Wing-like clouds drifting across the sky", "Spiritual inspiration, universal protection, and lightness seeping into the relationship; shedding excessive materialism and trusting the divine flow."),
        21: ("A finger pointing to a line in an open book", "The moment of recognizing a very clear sign, message, or synchronicity your destined contract offers you, and aligning yourself with it."),
        22: ("A white dove flying above stormy waters", "Even amid the greatest crises, quarrels, and fears, a universal peace, trust, and divine protection gliding above the relationship."),
        23: ("A jewel shop filled with precious stones", "The summit of realizing the relationship's high self-worth, its rare talents, and its radiant shared wealth."),
        24: ("A Native American warrior riding with enemy scalps at his belt", "The risk of the protective instinct or possessiveness turning into destructive jealousy or control; the test of taming the primitive ego."),
        25: ("A vast and magnificent public park", "Personal love transcending its own limits; the relationship becoming a collective space of peace, abundance, and tolerance that inspires the outer world."),
        26: ("A Spanish lover serenading his beloved", "Romance, courtship, and the aesthetic, courageous expression of love's language rekindling the relationship's magnetic power."),
        27: ("An old woman selling her tribe's handicrafts", "Adapting the ancient wisdom of traditions, roots, and the past so it serves the relationship's present material and spiritual construction."),
        28: ("A mature woman awakening to love anew", "Despite all of the past's disappointments, bravely opening the heart once more; realizing that love is timeless and the relationship can blossom anew at any moment."),
        29: ("Two shoe repairers working at one table", "Working shoulder to shoulder for a common purpose with zero ego; a seal of practical, balanced, flawless cooperation in turning visions into reality."),
        30: ("A peacock displaying itself on the terrace of an ancient castle", "The justifiable pride of achievements, nobility, and eternal trust that have passed time's tests; the relationship crowned in splendor upon a rooted empire.")
    },
    "Ikizler": {
        1: ("People in a glass-bottomed boat watching the ocean floor", "The desire to move beyond the superficial and, with mental curiosity, explore each other's deepest spiritual waters."),
        2: ("Santa Claus secretly filling stockings", "Destined gifts arriving at unexpected moments; your pure, childlike innocence being rewarded by an invisible hand."),
        3: ("The Tuileries Gardens in Paris", "Elegance in communication, mental order, and intellectual harmony built with flawless architecture: a shared language."),
        4: ("Holly and mistletoe", "Nostalgia, old memories, and deep-rooted traditions keeping the mental bond between you alive across a romantic bridge."),
        5: ("A radical magazine calling to action", "Mental rebellion! The need to break the relationship's monotony and routine, generating new, revolutionary ideas that ignite each other's minds."),
        6: ("Workers drilling for oil", "Going far beyond daily chatter and superficial communication to reach the rich, hidden power source deep within the relationship: the oil."),
        7: ("An old-fashioned water well", "Drawing from each other's minds as from an inexhaustible ancient spring of wisdom and inspiration; quenching spiritual thirst with words."),
        8: ("Angry strikers gathered around a factory", "Disagreements escalating into crisis; a shattering confrontation that demands mental justice and an equal voice in the relationship."),
        9: ("A quiver full of arrows", "Mental sharpness! Words locked on target; the test of using words to strike shared obstacles rather than to wound each other."),
        10: ("An airplane diving into a nosedive", "Dangerous maneuvers in communication; the courage to take great mental risks and face the great confrontation you have long feared in the relationship."),
        11: ("Virgin fields of experience offered in newly opened lands", "Expanding the mind's horizons; the relationship setting sail toward brand-new frontiers, shared studies, or subjects never yet discussed."),
        12: ("A Black slave girl demanding her rights from her mistress", "Hidden imbalances in communication exploding; one side rising in revolt against the other's mental domination, demanding freedom and respect."),
        13: ("A renowned musician giving a piano concert", "A flawless display of intellectual talent; inspiring and dazzling each other with your ideas, vision, and communication."),
        14: ("Two people living far apart communicating telepathically", "Despite distance or silence, minds connecting at a quantum level in a sublime telepathic transmission."),
        15: ("Two Dutch children talking with each other", "Setting complex philosophies aside; the miracle of establishing that pure, joyous, simple shared language only the two of you understand."),
        16: ("A woman activist making an impassioned speech", "Passionate advocacy for beliefs and shared goals; the relationship's mental energy becoming a shield against the outer world."),
        17: ("A strapping youth's head transforming into a mature thinker's head", "The relationship leveling up mentally; childish curiosity and impetuosity, tempered by experience, evolving into deep destined wisdom."),
        18: ("Two Chinese people speaking their mother tongue amid an American crowd", "Communicating in that secret mental vibration and private code only the two of you can decipher, amid the outer world's crowds and noise."),
        19: ("A great archaic volume (book) revealing traditional wisdom", "The moment of nourishing the relationship's roots with a great lesson drawn from the past or from ancient teachings, through philosophical enlightenment."),
        20: ("A cafeteria with a great many options", "The test of mental clutter and indecision; amid many ideas and choices, the power to select the relationship's destined course with a shared mind."),
        21: ("A noisy workers' demonstration", "The harsh clash of logic and emotion, right and wrong; a bottleneck where the relationship's accumulated mental pressure must be released."),
        22: ("Couples dancing at a harvest festival", "Reaping the fruits of mental harmony, productive ideas, and successful communication; the relationship turning into a joyful, exuberant celebration."),
        23: ("Three baby birds in a nest atop a tree", "The growth of mental seeds; shared ideas, plans, or projects still in gestation, needing the tender protection of incubation."),
        24: ("Children ice-skating on a frozen village pond", "The ability to overcome cold, crisis-ridden, or distant periods with agile wit, joy, and flexibility in communication."),
        25: ("A gardener pruning great palm trees", "Pruning the relationship's mental branches; cutting away needless details, toxic thoughts, and past obsessions to focus on the main trunk."),
        26: ("Frost-covered trees standing against a winter sky", "Even in times of emotional distance or silence, the unique, noble beauty of that solid mental bond between you, crystallized."),
        27: ("A gypsy emerging from the forest where his tribe is camped", "The pursuit of mental freedom; the courage to step out of habitual thought patterns and the relationship's comfort zone to try a new philosophy."),
        28: ("Society granting an opportunity for a fresh start through bankruptcy", "The complete collapse of old communication languages and mental structures; after the ruin, the chance to rebuild a far more honest and stronger mind from scratch."),
        29: ("The first nightingale of spring", "Rebirth, joyful news, and fresh ideas; communication between you emerging from winter, coming alive with spring's exuberance and a sweet melody."),
        30: ("A parade of beauties entering the sea", "Boldly displaying the relationship's mental and aesthetic harmony to the outside; the energy of shining with confidence in its social showcase.")
    },
    "Yengec": {
        1: ("Sailors aboard a ship lowering an old flag and raising a new one", "Old allegiances, family ties, or the past coming to an end; the courage to be born into an entirely new shared-home identity through this relationship."),
        2: ("A man surveying a broad landscape from a magic carpet", "The relationship's ability to rise above daily worldly cares and look upon each other's soul from a higher perspective, with objective compassion."),
        3: ("A fur-clad man guiding a feathered deer", "Even in the coldest, hardest, most critical times, the instinct to be an unshakable protective shield (the fur) for your partner's delicate soul (the deer)."),
        4: ("A cat arguing with a mouse", "Small power struggles within the shared living space; the test of whether emotional boundaries will be probed with love or with manipulation."),
        5: ("An automobile struck and shattered by a train on the tracks", "The destructiveness of stubbornly opposing destiny's unstoppable flow with personal ego; here, absolute surrender to the system and the divine plan is essential."),
        6: ("Game birds feathering their nests", "The time to invest emotionally and materially in marriage, shared life, and home; the virtue of building the safest, warmest corner in each other's heart."),
        7: ("Two nature spirits (fairies) dancing in moonlight", "The fairytale, childlike, magical emotional harmony that begins where logic ends; the relationship leaving the rational world to heal in the realm of dreams."),
        8: ("A parade of rabbits dressed in human clothing", "The danger of assuming false forms imposed on the relationship by the outer world, families, or society; a warning to flee artificiality and return to the essence."),
        9: ("A small naked girl trying to catch fish in a pond", "Returning to the relationship's purest, most innocent, most vulnerable moments to calmly catch and safeguard that first-day thrill (the fish)."),
        10: ("A large, unpolished diamond in its first cutting stage", "Raw and primitive love being worked over time, through crises and patience, into an invaluable, eternal diamond of loyalty."),
        11: ("A clown imitating celebrities", "The ability to soften egos, tensions, and conflicts in the relationship with immense humor and affectionate mockery, adding joy to the home."),
        12: ("A woman nursing a baby recognized by its aura as a reincarnated sage", "That great, sacred awareness that while tending each other's naive, childlike wounds, you are in fact nourishing a very ancient, destined soul."),
        13: ("A hand with a prominent thumb extended for examination", "Will, character, and concrete actions (the hand) being laid honestly and unmasked on the table in the relationship, to be confronted."),
        14: ("A very old man looking into a dark, bottomless void in the northeast", "The unshakable spiritual wisdom developed together against the unknown, the future, and old age; the courage to walk hand in hand into eternity."),
        15: ("Guests resting in a luxurious dining hall after a great feast", "Surviving the difficult days to reach the peak of material and spiritual satisfaction, fullness, and domestic peace; that great spiritual harvest moment."),
        16: ("A man studying a mandala before him with the aid of an ancient book", "The desire to solve this deep, complex destined structure between you (the mandala) not with a superficial mind but with universal laws and spiritual wisdom."),
        17: ("A seed transforming into knowledge and life", "The divine omen that a tiny seed of love and compassion, once rooted, grows into a vast living space: a whole family."),
        18: ("A hen scratching the earth to feed her chicks", "That endless, selfless, sacred maternal and paternal labor poured into protecting family, children, and the relationship's shared future."),
        19: ("A priest officiating a wedding ceremony", "The relationship being sealed with a destined contract; loyalty crowned not merely by a worldly signature but by divine approval and a universal covenant."),
        20: ("Venetian gondoliers serenading", "The power to float over emotional waves, crises, and waters (the gondola) with immense grace and romance, celebrating love."),
        21: ("A famous singer displaying her skill at the opera", "Living the apex of your deep love, sacrifice, and belonging, and presenting it to the world with dignified poise."),
        22: ("A young woman waiting for the sailboat", "Waiting with unshakable faith, loyalty, and patience for the destined partner, the hoped-for spiritual savior, or the relationship's peaceful days to come."),
        23: ("The meeting of a literary club", "Not only emotional, but shared intellectual values, cultural roots, and ideals strengthening the bed and roof of the relationship."),
        24: ("A woman and two men marooned on a small island in the South Seas", "Destined isolation in the relationship, tests of jealousy, or the boundaries of belonging and loyalty being tried through crises at the extreme limits."),
        25: ("The shadow of a superior power falling over a man of will", "Personal egos and obstinacy being crushed before the relationship's divine destiny (the superior power); being compelled into total surrender to the universe and this love."),
        26: ("Guests reading in the library of a luxurious home", "Finding immense peace in a rich spiritual and mental home; arguments giving way to shared wisdom and silent harmony."),
        27: ("A violent storm over a canyon filled with luxury homes", "A destined crisis striking the comfort zone and the home! The relationship's unshakable roots passing the test of material and spiritual endurance."),
        28: ("A Native American girl introducing her white lover to her tribe", "Uniting two different roots, families, traditions, or pasts across a single bridge of love; the great test of harmony that rootedness brings."),
        29: ("A Greek Muse weighing newborn twins on a golden scale", "That golden seal where inner duality (logic and feeling, you and me) is placed in perfect, divine, untiring balance within the relationship."),
        30: ("A Daughter of the American Revolution", "Deep honor for roots, the past, and each other; the relationship drawing its worldly power and revolutionary force from this unshakable belonging.")
    },
    "Aslan": {
        1: ("Blood splashing onto the head of a man whose vital energy is roused by ambition", "Ego and passion suddenly flaring in the relationship; an awakening that locks onto a shared goal and moves to action with unstoppable force."),
        2: ("An epidemic of mumps", "The danger of a crisis or contagious pessimism spreading rapidly within the relationship; the test of isolating toxic energies before they contaminate others."),
        3: ("A middle-aged woman in youthful dress with her hair flowing over her shoulders", "The relationship defying time and age; shedding routine's tedium and donning again that fresh, rebellious, free spirit of the first days."),
        4: ("An elderly man in formal attire standing beside the spoils of a hunting expedition", "The test of ego and pride! Boasting of past successes or the relationship's social status; a warning to see your partner as a spouse, not a trophy."),
        5: ("Majestic rock formations rising over a deep canyon", "The seal of unshakability! The relationship standing tall, noble, and unbreakable as a tower against all the erosion of time and even the deepest crises around it."),
        6: ("An old-fashioned, conservative woman confronting a modern girl of today", "The collision of deep-rooted past values with the future's longing for liberation; lovingly breaking old taboos to find a modern shared language."),
        7: ("Constellations shining brilliantly in the night sky", "Realizing that your souls are guarded by universal guidance (destiny's compass) even in the darkest times, and that the relationship serves a divine plan."),
        8: ("An activist spreading revolutionary ideals", "The passion to radically change and rebuild things in the relationship; yet this revolt must free the bond, not destroy the partner."),
        9: ("Glassblowers shaping glass that glows with their breath", "Karmic alchemy! By touching each other's soul (the breath), mastering the transformation of this originally unformed bond into magnificent, lasting art."),
        10: ("Glistening morning dew shining as sunlight fills the field", "A fresh spiritual awakening after a dark period; the relationship washed anew each morning with hope and divine optimism."),
        11: ("Children swinging on a swing suspended from the branches of a giant oak", "The grace of fearlessly living the relationship's most innocent, playful, childlike side in the shade of very deep-rooted, sheltered, unshakable trust (the oak)."),
        12: ("An evening party of adults on a lawn lit by ornate lanterns", "The time to shine in the relationship's social showcase; stepping onto the stage with pride, aesthetics, and a harmony the outer world will approve of and admire."),
        13: ("An old sea captain rocking on the porch of his cottage", "That peaceful, settling moment when a relationship that has weathered great storms, crises, and tests of patience now smiles back at the past with experience and wisdom."),
        14: ("A human soul seeking opportunities for expression", "Love that once dwelled only in hearts now bursting with the need to become a concrete creation, a marriage, or a lasting shared work in the material world."),
        15: ("A magnificent procession moving down a crowded street met with cheers", "The relationship declaring its own kingdom; a showy, bold, noble destined summit that receives high approval (applause) from all around."),
        16: ("Nature's joy under brilliant sunshine once the storm has passed", "That immense relief after a very heavy crisis or power struggle; tears giving way to a washed, immaculate love."),
        17: ("A volunteer church choir singing hymns", "Different voices (egos) harmonizing for one exalted purpose; the relationship transcending the earthly dimension, integrating through spiritual devotion."),
        18: ("A chemist performing experiments for his students", "The time to solve the relationship's mathematics and chemistry! Mastering how formulas, elements, and emotions react, through lived experience."),
        19: ("A boat party (a houseboat)", "Seeing commitment not as a shackle but as a fun, free voyage sailed together; flexing the relationship's boundaries and focusing on joy."),
        20: ("Zuni Indians performing a sun ritual", "Feeling deep gratitude toward the source (the Sun, the Creator) of your existence and this immense love; setting the ego to zero and connecting reverently to divine power."),
        21: ("Drunken chickens, dizzy and flapping their wings, trying to fly", "A warning against giving in to expectations beyond capacity or inflated egos in the relationship; the risk of falling into comical or critical plights while trying to fly."),
        22: ("A carrier pigeon fulfilling its duty", "The seal of loyalty! The virtue of keeping your destined word to each other even in the hardest conditions, delivering love's sacred message to its goal."),
        23: ("A bareback rider at the circus enchanting an excited crowd", "The relationship's dangerous, risky yet hypnotic power of poise; defying obstacles and rules to perform bravely, and succeeding."),
        24: ("A man who, utterly neglecting his physical appearance, focuses on spiritual enlightenment", "The show, ego, and aesthetics of the outer world losing their meaning; the relationship focusing entirely on subconscious, mystical, and underworld alchemy."),
        25: ("A great camel crossing a vast and merciless desert", "A colossal test of endurance! Drawing on your inner reserves of water (love) to walk toward the goal patiently and stubbornly through the relationship's arid, crisis-ridden passages."),
        26: ("A rainbow appearing after a heavy storm", "A destined promise! After the pain endured and the tears shed, the divine bridge of hope, repair, and healing that the universe offers your relationship."),
        27: ("The glow of dawn in the eastern sky", "A dark cycle closing forever; with this love, the soul opening its eyes to a new consciousness, hope, and sun (awakening)."),
        28: ("Many small birds chirping on the branch of a great tree", "The shared circle, friendships, and small joys nourishing the relationship; moving away from heavy drama toward simple, playful, lively communication."),
        29: ("A mermaid emerging from ocean waves to be reborn in human form", "The Great Alchemical Evolution! Unconscious emotions and jealousies (the water) left behind; the relationship becoming fully conscious, mature, and concrete (human)."),
        30: ("A letter whose seal is broken (unsealed)", "Absolute transparency! An utterly free phase in which secrets, masks, and hidden agendas vanish, and hearts open to be read by each other honestly and without censorship.")
    },
    "Basak": {
        1: ("The pelt of an animal on a man's head", "The ability to tame one's own primitive, animalistic drives and raw energy through discipline, work, and practical intelligence, employing them in a higher form."),
        2: ("A white cross on a broad plain", "Realizing that sacrifice and service in the relationship are not a burden but the foundational pillar that sustains its lasting peace, its sacred dimension."),
        3: ("Two angels ready to help", "In the crisis moments when you feel most stuck while trying to perfect things together, the universe opening a door with a practical solution and intuitive help."),
        4: ("A young man's imagination turning into a real dimension", "The relationship's dreams and flights of fancy being transformed into concrete works (a home, a success) through work, attention to detail, and practical steps."),
        5: ("A man holding a book of fairytales filled with dreams", "The art of living without forgetting love's fairytale and divine origin (the fairytale) even while lost in the practicality of daily life (Virgo)."),
        6: ("A ballroom filled with decorations", "Aesthetics in detail; succeeding in running the relationship's daily order meticulously and flawlessly, as if it were a work of art or a dance."),
        7: ("A table set with two glasses of wine", "The destined value of those small but quality moments of sharing you give each other when pausing amid the practical rush of daily life."),
        8: ("A girl feeding her pet birds", "The small, vulnerable, needful parts of the relationship (your childlike side, your weak spots) being fed and protected with tenderness and order."),
        9: ("A painter painting himself", "The endeavor to observe the relationship and yourselves with an outsider's eye, with an artist's precision, instantly revising flaws to reach perfection."),
        10: ("A two-headed man looking at life", "Using logic and intuition at once; the faculty of focusing simultaneously on practical matters and on the relationship's future spiritual needs."),
        11: ("An untouched valley gleaming with the birth of a new day", "Old crises and mistakes in the relationship dissolving through Virgo's analytical cleansing; the clarity of beginning each morning completely fresh."),
        12: ("A man searching for his treasure", "Realizing that amid the relationship's daily chores (home, work, routine) lies hidden the great destined treasure you seek: spiritual maturity."),
        13: ("A statesman addressing the public", "Representing the relationship's order, rules, or vision before the outer world; a disciplined, respectable union, like a system or school."),
        14: ("A family album being photographed", "Standing against the flow of time; recording with discipline every phase, memory, and lesson of the relationship, carrying it into the future as a legacy of lived experience."),
        15: ("A little girl playing with dolls", "Solving the relationship's responsibilities, roles, and crises with playful gravity: without judging, without blaming, experiencing them like a simulation."),
        16: ("Fertile soil forming after a volcanic eruption", "The greatest crises (the eruption), once worked with Virgo's analytic power, actually forming the most fertile soil (experience) that will nourish the relationship in the future."),
        17: ("A clergyman praying for his people", "Daily service in the relationship turning into worship; the awareness that covering each other's lacks and maintaining order is, in truth, blessing each other's soul."),
        18: ("A researcher working in a great library", "The desire to decode the relationship's destined codes; researching each other's past, psychology, and the 'why' of this relationship with scientific, analytic precision."),
        19: ("A pomegranate tree in bloom", "Beneath the practical, plain exterior, countless fertile seeds and life energy lie hidden; the relationship's potential overflowing."),
        20: ("A peasant harvesting his field", "The day every destined labor given, planned, and woven stitch by stitch is repaid in due season and abundance."),
        21: ("A girls' basketball team", "Coordinated work toward a shared goal; being a well-oiled team where each person performs their role flawlessly and no ego conflicts arise."),
        22: ("A royal guard bearing the royal coat of arms", "Unshakable loyalty and guardianship of the system; guarding the relationship's values, order, and private world against external dangers with steel discipline."),
        23: ("A man cleaning the cages in a zoo", "The wild, uncontrolled, or animalistic instincts in the relationship being tamed through meticulous cleaning and discipline, so they can do no harm to the system."),
        24: ("A guard waiting at the gate of a great palace", "Controlling entry into and exit from the relationship's Sacred Home; firm, secure boundaries over who (or which energies) may join this space."),
        25: ("A man weeding his garden", "Cleansing the relationship's spiritual soil of 'weeds' (toxic thoughts, anxieties); feeding the bond only with what is pure and functional."),
        26: ("Unripe fruits hanging from a tree", "The relationship's plans or dreams are not yet ripe; the discipline of waiting patiently and orderly for their maturity (harvest) without haste."),
        27: ("A teapot gleaming in the sunlight", "Sanctifying the relationship's daily routine (tea, ritual); the mastery of transforming even an ordinary tea moment into one of immense peace and healing."),
        28: ("A monk bowing his bald head", "Ego withdrawing completely from the relationship; mental arrogance replaced by silent service and deep humility."),
        29: ("A human emerging from a hidden door", "The ability to overcome the relationship's problems, crises, and blockages through a practical, ingenious, hidden exit (method) that no one else has noticed."),
        30: ("A star broom sweeping the sky", "The relationship's destined cleansing! Virgo's meticulous, detailed discipline has now swept even the cosmic dust and karmic sediment from the sky, making the bond as clear as crystal.")
    },
    "Terazi": {
        1: ("An arrow sign with an arrow upon the wing of a butterfly", "Determining the emotional or mental orientation (the arrow) in the relationship; realizing toward which destined goal your interaction flies."),
        2: ("Six gleaming globes of light held in a man's hands", "The faculty of holding life's fundamental forces (the light globes) in balance within the relationship, and governing them with shared aesthetics."),
        3: ("A newborn day in the forest at dawn", "A fresh beginning that sweeps away all the past's weight; the discipline of starting each new day with a clean page and with hope."),
        4: ("A man leaving a group to walk his own path", "Preserving individual freedom and original character while becoming 'we' in the relationship; the art of being attached, not dependent."),
        5: ("A brilliant ring containing a drinking glass", "The sacred inner wholeness that companionship brings; enfolding each other like a complete ring and savoring this bond."),
        6: ("A small statue with the figure of a man inside", "Leaving a lasting, noble, aesthetic imprint on each other's lives; the relationship being remembered in the world like a concrete work of art."),
        7: ("A sky standing still and silent before a storm", "That critical, quiet, serene moment of observation before crises; sensing the approaching destined change intuitively, without argument, and taking precautions."),
        8: ("A group of people warming themselves by a fireplace", "Even in the coldest crises, keeping the relationship's inner warmth, trust, and homeliness alive through each other's presence."),
        9: ("Three master artists working in their own studios", "Each side independently but harmoniously producing its own talents, intellect, and labor for the relationship's shared vision."),
        10: ("A group of people building a canoe", "Everyone rowing to the same rhythm in the relationship's flow; calming conflicts and moving in sync toward a single destined direction (the goal)."),
        11: ("A man with a light in his eyes", "Inner enlightenment! Seeing the relationship's problems, the other's intention, and the universal message with a vision far deeper than what is visible."),
        12: ("A diamond freshly hewn from the mine", "The relationship's raw, unpolished potential being burnished through difficulties into true, priceless, enduring value."),
        13: ("A man standing in the sun with his hat removed", "Egos stepping entirely aside; that deep, unmasked, humble surrender to each other and to your destined course."),
        14: ("Two angels racing toward each other in the sky", "Those moments when the relationship is supported by a divine hand; crises being resolved through miraculous aids that appear merely as coincidence."),
        15: ("Baby birds gathered in a nest", "That phase when the relationship is most vulnerable, most childlike, most in need of protection; cradling the 'child' within each other and nurturing it safely."),
        16: ("A compass held in a man's hand", "The skill of charting the relationship's destined course without deviation, keeping in line with the universal compass (conscience and truth)."),
        17: ("A man lost in a dense forest", "A period of turmoil and uncertainty in the relationship! The risk of drifting from your destined center, swayed by the outer world (others' opinions)."),
        18: ("Empty armor hung on the walls of an ancient castle", "The past's defense mechanisms becoming unnecessary; the courage to remain vulnerable (unmasked) toward each other."),
        19: ("A group of people examining a work of art", "Awareness of how the relationship appears from outside; objectively evaluating the relationship's worth, aesthetics, and success."),
        20: ("A season in which all flowers bloom", "The zenith of creativity, love, and sharing in the relationship; everything humming along, beauty and plenty overflowing."),
        21: ("A pine tree standing firm in the midst of a storm", "Even amid the most shaking external influences, your bond to each other bends but never breaks; the unshakable strength of your roots."),
        22: ("A sacred fire burning on a hilltop", "The relationship's destined purpose being clear and elevated enough for everyone to see; the power to warm the world with a shared faith."),
        23: ("A cat observing itself in a mirror", "Clarifying the 'I' and 'you' distinction in the relationship; the awareness of seeing not only the beauty of your soul but also your own flaws in your partner's eyes."),
        24: ("An old key in a man's hand", "Attaining that very special, ancient wisdom or method that unlocks all of the relationship's locked destined doors (FBST's own key)."),
        25: ("An eagle soaring across the sky", "The relationship rising far above worldly cares; seeing perspective, far-sightedness, and destined wholeness with a godlike gaze from above."),
        26: ("A snake in an eagle's talons", "Crisis, manipulation, or fear (the snake) being neutralized and transformed into healing by the relationship's highest vision (the eagle)."),
        27: ("The laughter of children playing in a garden", "Amid seriousness and responsibilities, the necessity of preserving the relationship's purest, most joyful childlike delight; happiness is a choice."),
        28: ("A man arranging library shelves with great care", "Setting the relationship's past, memories, and learned lessons into mental order; keeping memories as accumulated wisdom."),
        29: ("The horizon line burning at sunset", "The close of an era! That mysterious transition interval before one phase of the relationship ends and an entirely different level begins."),
        30: ("An actor playing his role on the world's stage", "The relationship's destined role in the universal theater; as everyone has a part, honestly playing the divine message your relationship 'represents' in the world.")
    },
    "Akrep": {
        1: ("A watchful eye shining in the midnight sky", "Every moment of the relationship under universal observation; that vigilant stance where loyalty and intention are tested at the deepest layers."),
        2: ("The scent of an essence leaking from a broken bottle", "A past pain or a repressed emotion being set free, utterly changing the relationship's atmosphere; the beginning of the healing process."),
        3: ("A wild house cat being tamed", "The rebellious, uncontrollable, free-spirited sides of the relationship being brought into the home and system through tenderness and patience; a test."),
        4: ("A young man reading papers by candlelight", "The ability to read the relationship's destined contracts, hidden intentions, and each other's spiritual map with clarity even in the darkness."),
        5: ("A jellyfish on an isolated rock, self-sufficient", "Even in crisis, the relationship standing firm on its own inner resilience and self-sufficiency, without needing external support."),
        6: ("Workers laboring in a gold mine", "Digging through the relationship's difficulties (the earth) to bring to light each other's hidden, priceless, noble treasures of character (the gold)."),
        7: ("A diver over a deep lake", "Plunging fearlessly into the dark, uncanny depths of emotion and bringing up the destined mysteries (or wounds) hidden there, for each other."),
        8: ("A lake reflecting the moon's light", "The relationship being illumined not by the sun's direct brightness but by the soft, mystical, intuitive wisdom peculiar to the night; souls speaking under darkness."),
        9: ("A giraffe admiring its own reflection", "That fine line between 'me' and 'us' in the relationship; the courage to see not only the beauty of your own soul but also your shortcomings in your partner's eyes."),
        10: ("A group of people rescued after a great accident", "The miracle of surviving great destined crises; being saved by a divine hand even at the darkest moments when the relationship seemed about to collapse."),
        11: ("A bird waiting on a tree branch after a storm", "That absolute stillness following stormy, crisis-ridden processes; the peaceful waiting moment, replacing fear, when you know you are safe."),
        12: ("A student searching for forbidden books in a great library", "The desire to courageously bring to light and face the relationship's taboo, unspoken, deeply hidden 'forbidden' feelings."),
        13: ("A huge ship seeking shelter in a harbor during a storm", "Faced with the outer world's crises and social pressures, the power of the relationship to take refuge in its own unshakable, safe harbor (each other)."),
        14: ("Deep forests of passion within a human being", "The relationship's indescribable, uncontrollable, wild passion; using this fire not to burn each other but to conquer the world together."),
        15: ("A tribe celebrating rebirth", "After a great destruction or a fear of separation, the relationship being reborn from its ashes far stronger, wiser, and more sealed."),
        16: ("A girl dancing alone in a meadow", "Preserving your own spiritual joy in the relationship, independent of your partner's world; the skill of remaining independent yet united in love."),
        17: ("An artist seeking himself", "Using the partner as a mirror to complete the missing pieces within your own soul: the journey of integration (individuation)."),
        18: ("A bridge over a silently flowing river", "Emotional transitions! Reaching each other by building an unshakable bridge of logic and diplomacy across crisis-ridden waters."),
        19: ("A man talking to his own shadow", "In the relationship, not judging the 'dark' sides your partner reflects to you, but using them as a means of making peace with your own shadow."),
        20: ("An old temple being ritually burned down", "Old beliefs, a finished way of life, or a past destined cycle being consumed in flames through a great ritual, reduced to ash for the relationship's well-being."),
        21: ("An architect raising a giant city in his inner world", "The magnificent shared home you build not outward, but within each other's vast, colossal, rich soul-worlds."),
        22: ("The phoenix emerging from flames", "Absolute destruction and resurrection! At the point where the relationship is declared over, all pain turning into healing by a miracle, rekindled in a far more sublime form."),
        23: ("A dead crow lying in a field", "Fears, doubts, or old 'dark' thoughts (the crow) whose function has ended departing forever from your relationship; purification."),
        24: ("A sacred chalice gleaming in a man's hands", "The spiritual elixir distilled from the relationship's hardest crises; the destined elixir of life, drunk with absolute loyalty and love."),
        25: ("A flashlight oscillating between two poles", "Vacillating between emotional extremes (love and anger); yet whatever happens, the purpose of illuminating each other's path like a flashlight."),
        26: ("A mountaineer standing firm at the edge of a cliff", "The mastery of holding that noble, unshakable balance at the relationship's most extreme, dangerous, crisis-ridden point, without falling or veering."),
        27: ("A lightning bolt tearing through the darkness of night", "A very secret, deeply hidden destined truth in the relationship being revealed in full clarity by an unexpected, shaking, illuminating event."),
        28: ("Waters bubbling and seething by themselves in a river", "Anger or passion accumulated in the relationship's depths seething unseen from outside; the need to heal it before it explodes."),
        29: ("A group of people waiting for the sunrise", "Reaching the end of the darkest destined cycle; waiting patiently, with faith in each other, for a new and luminous era to begin."),
        30: ("The two perfectly balanced pans of a scale", "From Scorpio's boundless depths of crisis, the final destined station where absolute spiritual balance and truth are now attained.")
    },
    "Yay": {
        1: ("A dim star shining in the night sky suddenly exploding into a nova", "A long-dormant potential or vision in the relationship suddenly exploding, becoming a destined guide that illuminates your entire life."),
        2: ("A white nun warming her face with her hands by a hot stove", "Even in the relationship's most critical, cold, uncertain moments; the miracle of finding your own spiritual warmth in each other's presence, with unshakable faith."),
        3: ("Two people taking their first step into a new country", "A transition into an entirely undiscovered new dimension in the relationship; that first, bold destined step of discovery as habits break and limits are crossed."),
        4: ("An immigrant in a far country preserving their own traditions", "The relationship's effort to cling to its own roots and original philosophy while trying to adapt to the outer environment, society, or standards."),
        5: ("A sage following his own inner light", "Whatever the outer world says, charting the relationship's destined course by trusting only the shared, divine guidance (faith) between you."),
        6: ("A man begging at the door of an old church", "The test of faith and gratitude in the relationship; the need to escape the trap of not valuing what you already have while fixating on what is lacking."),
        7: ("A man on the seashore gazing out at the vast ocean", "Realizing the relationship's boundless destined potential; dissolving small problems within the immensity of the ocean."),
        8: ("An inscription carved on a stone, nearly effaced", "A destined warning from the past or an ancient teaching being remembered anew, carrying a message that will change the relationship's course."),
        9: ("A group of students traveling the world", "The relationship seeing life as a field of learning; traveling the world together, reading books, or embarking on a philosophical journey being your greatest shared bond."),
        10: ("Actors rehearsing on an old theater stage", "The relationship being in constant growth and rehearsal on life's stage; staging life with joy and mastery, without fretting over mistakes."),
        11: ("A ship guided by a lighthouse shining across the sea", "Finding your way through dark, uncertain, stormy destined processes with each other's vision; love crystallizing like a clear compass."),
        12: ("A golden sun shining upon the flag", "The relationship's success and power deriving entirely from devotion to that shared faith and divine vision; a victory sealed with light."),
        13: ("A child stroking the head of a lion sleeping peacefully", "The strongest, wildest, most uncontrolled aspects in the relationship (Leo) being gentled with tenderness (the child) and disciplined with love."),
        14: ("A colossal pyramid suspended in the sky", "The relationship possessing a divine order, an ancient geometry; built not upon coincidence but upon a planned, destined structure."),
        15: ("A farmer sowing seed in the earth", "The awareness that the hardships the relationship faces now are the preparation for a great future harvest (peace, success); sowing patiently."),
        16: ("A radiant city rising above the seas", "The relationship's attempt to build an idealistic utopia detached from reality; the test of grounding these dreams and making them livable."),
        17: ("A dervish revolving within himself", "The relationship withdrawing from the outer world's turmoil to find peace through its own inner rhythm and shared meditations; love becoming a form of worship."),
        18: ("A knight on the battlefield laying down his sword and praying", "Giving up the battle of being right! Even in the relationship's fiercest crises, the wisdom of laying down the weapons (ego, criticism) and returning to unity."),
        19: ("Watching the world from the summit of a high mountain", "The relationship gazing at daily problems, petty arguments, and jealousies with a distant, wise, peaceful perspective, as if from a mountaintop."),
        20: ("A rocket ascending into the sky", "The relationship freeing itself completely from earthly constraints and, with speed and great momentum, leaping into a higher destined realm to fulfill its dreams."),
        21: ("A self-sufficient monk", "Freeing the relationship from dependence; a noble companionship in which each preserves their own spiritual center while enriching the other's soul."),
        22: ("Babies playing in a meadow", "The relationship's purest, most selfless, most joyful first destined phase, savoring simply 'being'; love in its plainest form."),
        23: ("A swan gliding over a lake", "The serene beauty of grace, nobility, and love; even in crisis, the relationship never breaking its noble poise and its aesthetics."),
        24: ("A man rifling through dusty shelves in a great library", "The necessity of finding the relationship's missing destined knowledge in the dusty memories of the past or in some ancient teaching."),
        25: ("A star falling from great heights", "An unexpected divine intervention; that celestial sign which changes the relationship's course in a single moment, miraculously rewriting fate."),
        26: ("A soldier holding his flag upright in a storm", "However great the crisis, the vow to remain faithful to the relationship's central goal, its values, and your devotion to each other."),
        27: ("An artist disliking his own work and destroying it", "The test of perfectionism! The courage to tear down and rebuild from scratch certain things, or certain sides of yourselves, in order to create something better."),
        28: ("Red roses blooming in a garden, never fading even in winter", "The relationship preserving its 'red' (passion and love) through the most impossible conditions, living on through the most critical seasons."),
        29: ("The sun swallowing the sea as it sets on the horizon", "The close of a destined era; every form of the relationship you have known sinking into darkness before a new, far more radiant dawn."),
        30: ("Two angel-like people holding hands in the sky", "The Destined Seal! Two souls, having finished their earthly roles, now united eternally by a fully divine contract, in a love beyond time and space.")
    },
    "Oglak": {
        1: ("An Indian chief governing his own tribe", "The relationship establishing its own hierarchical order; governing the responsibilities, roles, and boundaries of shared life with noble authority."),
        2: ("Three rose windows, one of them shattered", "A crack or deficiency in the relationship's perfectionist structure! This very flaw allowing the relationship to 'leak more light' (new perspectives) outward."),
        3: ("The human soul leaving its physical body for new experiences", "The relationship shedding earthly constraints, material burdens, and rigid responsibilities to unite for the soul's lofty purposes: that ascended phase."),
        4: ("A man dancing in his own world amid a group celebration", "While fulfilling social responsibilities (society, family) in the relationship, remaining spiritually faithful to your own destined center and to your partner."),
        5: ("Natives paddling a canoe", "Amid life's harsh, fast-moving crisis waters, advancing toward the goal with trust in each other (the same rhythm), without losing the relationship's pace."),
        6: ("A black bird transforming into a white bird", "Destined alchemy! Dark, doubtful, or fearful energies in the relationship being purified through unshakable loyalty and discipline into pure, white healing."),
        7: ("A very old man working in a library", "Using all the relationship's past experiences, memories, and destined lessons as sources of wisdom with which to build the future's 'empire'."),
        8: ("A woman at home watching the sunrise", "Each day, and after every crisis, keeping alive faith in the relationship's potential and in the clean, orderly, disciplined peace that a new dawn brings."),
        9: ("A Native American warrior throwing a spear", "The goals, dreams, and shared projects in the relationship being hurled toward the target with sharp focus, complete determination, and disciplined effort (the spear)."),
        10: ("An aged diamond being set into a new surface", "The relationship's seasoned, experienced, deep-rooted value being polished and presented anew, with new status and new form, in today's world."),
        11: ("A group of people awaiting the sovereign in a great palace", "The high standards and authority the relationship establishes within itself; the outer world (or crises) respecting this unshakable authority."),
        12: ("A bird building its own nest", "The most fundamental responsibility! Weaving every twig and every detail of the relationship with unshakable trust, labor, and a long-term plan (the nest)."),
        13: ("A group of people singing", "The relationship's rules and responsibilities being fulfilled not merely as duty but in joy and harmony (song); discipline becoming art."),
        14: ("A fish standing on a great rock", "The relationship merging its emotional (fish) nature with the unshakable (rock) strength of earth and discipline, pouring feeling into concrete achievement."),
        15: ("A seed awaiting its rebirth", "The winter (crisis) period in the relationship; in this frozen, silent time, the hidden, strong, deep preparation taking place in the roots."),
        16: ("An accountant working at a desk", "The relationship's realistic accounting: who gives what, who takes what, what destined debts remain? Honest confrontation and rational ordering."),
        17: ("A beacon burning on a distant hill", "The relationship's duty to its surroundings, to other people, or to each other: being an unshakable point of direction, trust, and stability (a beacon) in crisis."),
        18: ("A sentry inside an old castle watching the outside", "Guarding the relationship's values and privacy around the clock against every kind of danger from outside (gossip, interference)."),
        19: ("A self-sufficient, noble bearing", "You are together not because you need your partner but because you choose each other. A noble companionship, free from ego-dependence."),
        20: ("A granary stocked with enough provisions for the whole winter", "The relationship's future (crisis) planning; trust in each other and your resources being strong enough to keep you standing through hard days."),
        21: ("A colossal snowy mountain being climbed", "The relationship's most supreme, most splendid, most arduous destined goal; braving the difficulties up that peak without letting go of each other's hand."),
        22: ("A soldier holding his flag upright in a storm", "The seal of loyalty! However great the crisis, the vow to remain faithful to the relationship's central goal, its values, and your devotion to each other."),
        23: ("A man rifling through dusty shelves in a great library", "The necessity of finding the relationship's missing destined knowledge in the dusty memories of the past or in some ancient teaching."),
        24: ("A perpetual fire burning on a sacred altar", "The continuity of labor in the relationship; not a one-day love, but that holy fire of service and devotion burning through a lifetime."),
        25: ("Two angel-like people holding hands in the sky", "The Destined Seal! Two souls, having finished their earthly roles, now united eternally by a fully divine contract, in a love beyond time and space."),
        26: ("A man finding peace in a cabin he built with his own hands", "The relationship withdrawing from the outer world, chaos, and status ambition to find peace in that simple, honest home the two of you built."),
        27: ("A man on a mountaintop lighting the world with his torch", "The level of wisdom the relationship has reached; having found its own peace, it also becomes a destined guide and example to other couples."),
        28: ("Waters bubbling and seething by themselves in a river", "Still without, deep within; the relationship's deepest destined sediments undergoing a quiet yet very powerful process of purification and transformation."),
        29: ("The horizon line burning at sunset", "The close of an era! The transition interval before one phase of the relationship ends and an entirely different status (empire) begins."),
        30: ("The two perfectly balanced pans of a scale", "From Capricorn's rigid, disciplined, earthly structure, the final station where absolute spiritual balance and divine justice are attained.")
    },
    "Kova": {
        1: ("An old mission chief telling the tribe people of new visions", "Stepping outside the relationship's routine; crafting radical, libertarian, boundary-pushing new shared-life visions for the future together with your partner."),
        2: ("An umbrella sheltering two people from a storm", "While the world's chaos (the storm) rages outside, that unshakable mental trust you hold for each other within the relationship's own distinctive, independent intellectual refuge."),
        3: ("A fresh waterfall pouring into a valley lake", "That electric flow of passion that never lets emotions stagnate, endlessly renewing, refreshing, and keeping the mind alert."),
        4: ("A priest lighting a fire for a sacred ritual", "Turning the relationship's daily ordinariness into a ritual; using love not only physically but as an instrument of universal knowledge and service."),
        5: ("A man following his own inner voice", "In the relationship, trusting not what others say or social conventions, but only that unique, extraordinary destined voice (instinct) between you."),
        6: ("An actor on stage wearing a white mask", "The relationship being lived not through social masks but in complete honest 'selfhood'; the phase when roles end and truth begins to speak."),
        7: ("A child sunbathing on the cliffs by the sea", "Preserving joy, freedom, and childlike creativity amid difficulties (the cliffs); finding peace within the crises."),
        8: ("A dust-covered man sitting in a beautifully arranged garden", "Inner wealth needing no outward show or status; realizing that the relationship's essence is far more precious than how it appears."),
        9: ("A flock of birds flying into a storm-wind", "However great the obstacles; the relationship defying the storm with its independent, group-conscious, boundary-rejecting free spirit."),
        10: ("A man walking a tightrope with his eyes blindfolded", "Unshakable trust in the relationship! The resolve to walk that line of balance with total surrender, even with eyes closed, in a world your partner navigates."),
        11: ("A studio where the muses dance", "The relationship being not merely a union but a shared 'creation center'; beautifying the world by producing, writing, or drawing together."),
        12: ("A single page saved from a library in which all the books burned", "The collapse of old teachings, traditional love patterns, or lived experiences; continuing on with that one pure, true 'truth of love' that remains."),
        13: ("A scientist watching the stars through a telescope", "The relationship transcending worldly cares; the desire to read each other's life purpose and destined course out to the farthest galaxies (the macro vision)."),
        14: ("A colorful kite soaring in the sky", "The relationship's power to rise, lighten, and remain flexible through every difficulty; your bonds liberating you rather than pinning you to the world."),
        15: ("A lighthouse erected atop a high mountain", "The relationship illuminating its own path while also serving as a guide of freedom and love to the couples (the community) around it."),
        16: ("A choir singing in two different languages", "The relationship's harmony! That extraordinary richness born when unique voices of difference meet in a single destined melody."),
        17: ("A puppy educating itself", "The discipline of learning from mistakes in the relationship; that independent structure which solves its own crises without anyone's external interference."),
        18: ("A watchmaker cleaning the inner gears of an old clock", "Repairing with great precision the mechanical and mental faults of the relationship so that time and its destined cycles run flawlessly."),
        19: ("An explorer discovering the ocean within himself", "The relationship being not only physical union; a journey of exploring the vast, unknown, mysterious oceans of each other's subconscious."),
        20: ("A visionary breaking all boundaries", "The relationship outright rejecting the patterns society imposes: 'boy-girl', 'husband-wife', or 'love'; and building its own destined model of 'coexistence'."),
        21: ("A self-sufficient, speaking statue", "A noble, individual union that needs no outer world's approval; able to create its own beauty, its own value, and its own silence."),
        22: ("A giant cloud radiating light", "The relationship's transition from one form to another; shedding concrete, rigid responsibilities to become a pure field of energy and inspiration."),
        23: ("A full moon reflected on a pond", "The relationship's reflection in the world being in perfect alignment with the destined plan above (the moon); intention and action uniting."),
        24: ("A musician playing an instrument he built with his own hands", "The relationship's music (harmony) being produced not by anyone else but entirely by your own handiwork, your own rules, and your own instruments."),
        25: ("Orchids blooming among the ruins of an old temple", "The relationship's old crises and destructions being healed, now overgrown with the joy of life and a rare beauty (the orchid)."),
        26: ("Curiosity shining in a man's eyes", "Questioning and discovering never ending; the necessity of rediscovering the relationship each day with the excitement of seeing your partner for the first time."),
        27: ("A flower getting wet under the rain", "Emotional cleansing; the truth that in the relationship's most intense, sometimes harsh (rainy) processes, you are in fact cleansing each other and keeping one another spiritually more alive."),
        28: ("A man in a boundless snowfield with only his own footprints", "That brand-new, untrodden destined path opened in the relationship; a future entirely yours, entirely original, entirely undiscovered."),
        29: ("Colorful lights dancing in the sky (the Northern Lights)", "The relationship attaining spiritual maturity; the bond transcending worldly words to become, as it were, a festival of energy."),
        30: ("A man walking the world's stage in his own distinctive manner", "The relationship becoming a 'school'; existing in the world by your own destined rhythm, obedient to no rule, no fashion, and no social pressure.")
    },
    "Balik": {
        1: ("A public trading area displayed in an open market", "The test of existing honestly, with full transparency and within a 'shared life' space, in place of individual secrets in the relationship."),
        2: ("Squirrels playing with each other in a tree", "The virtue of living the relationship's first, pure, innocent joy simply by delighting in each other's presence, carrying no destined burden at all."),
        3: ("A petrified tree trunk", "The relationship's unshakable resistance to the destructiveness of time; your devotion to each other now taking a form as lasting as though engraved in history."),
        4: ("A sunny day on a small island", "The relationship's destined refuge, insulated from the outer world, from chaos, and from crises, filled only with your shared peace and light."),
        5: ("A mysterious priest living in his own inner world", "Accepting that you can never fully 'solve' your partner; respecting the mysterious, untouchable sacred spaces within each other's soul."),
        6: ("A sorcerer wielding a magic wand", "The mastery of resolving the relationship's crises or blockages not by rational means, but through that great, divine 'love magic' (compassion) you hold for each other."),
        7: ("Fishermen on the shore mending their nets", "Honestly repairing the relationship's emotional wear (the nets); rather than bruising each other, lovingly stitching and mending the wounded parts."),
        8: ("A bench where two lovers sit silently at sunset", "That absolute peace and spiritual wholeness of simply existing side by side, needing no word and no act."),
        9: ("A jellyfish glowing with its own light", "Even in dark, crisis-ridden destined processes; the faculty of kindling the relationship's own pure, mystical light to guide each other."),
        10: ("A child praying beneath the stars", "Entrusting the relationship's entire fate, future, and each other to the universe's infinite compassion (the Creator), trusting absolutely in the divine flow."),
        11: ("The door of a radiant, mystical temple", "The relationship transcending mere coupledom to become a sanctuary that serves a divine purpose or a shared spiritual aim."),
        12: ("A seagull gliding over the seas", "Preserving freedom even through the greatest crises; making the relationship not a prison but a wing that carries each other's soul into the sky."),
        13: ("The cleaning of an old painting", "Tenderly wiping away the dust and disappointments accumulated over the relationship's earlier phases, restoring it to the vibrancy of its first days."),
        14: ("An astronomer observing the stars", "Charting the relationship's destined course not by daily worries but by the immense, unchanging guidance of the stars (the universal laws)."),
        15: ("A group of people bathing in a river", "Emotional cleansing! Washing away entirely, in each other's compassionate waters (love), all the relationship's weight, anger, and past sediment."),
        16: ("A girl dancing alone in a meadow", "Even within the relationship, preserving your own spiritual joy and independence, making love a source of delight rather than obligation."),
        17: ("A sage talking to his own shadow", "In the relationship, accepting everything you see in your partner as a reflection of your own shadow, and integrating through that mirrored truth."),
        18: ("A bridge over a silently flowing river", "Emotional transitions; reaching each other by building an unshakable bridge of logic and compassion across crisis-ridden waters."),
        19: ("An architect raising a giant city in his inner world", "The relationship existing less in the outer world and more within the vast, rich, peaceful world of each other's soul."),
        20: ("The phoenix emerging from flames", "Absolute destruction and resurrection! At the point where the relationship is said to be over, all pain turning into healing by a miracle, rekindled in a far more sublime form."),
        21: ("A musician playing an instrument he made with his own hands", "The relationship's harmony being produced not by anyone else but by that special vibration from within you, in its own original way."),
        22: ("Orchids blooming among the ruins of an old temple", "The relationship's old crises and destructions being healed with a rare and precious beauty."),
        23: ("Curiosity shining in a man's eyes", "Questioning and discovering never ending; the desire to rediscover your partner anew each day."),
        24: ("A flower getting wet under the rain", "The truth that in the relationship's most intense, sometimes harsh (rainy) processes, you are in fact cleansing each other and keeping one another spiritually more alive."),
        25: ("Footprints in a boundless snowfield", "That original destined path in the relationship no one has walked; a future entirely yours, entirely undiscovered."),
        26: ("Colorful lights dancing in the sky", "The relationship transcending worldly words to become a festival of energy and light."),
        27: ("A man walking the world's stage in his own distinctive manner", "The relationship becoming a 'school'; existing in the world by your own destined rhythm, obedient to no rule."),
        28: ("Waters bubbling and seething by themselves in a river", "Emotional seething in the depths; anger or passion quietly yet powerfully transforming into healing."),
        29: ("The horizon line burning at sunset", "The close of an era! Every form of the relationship you have known sinking into darkness before a far more radiant dawn."),
        30: ("Two angel-like people holding hands in the sky", "The Destined Seal! Two souls, having finished their earthly roles, now united eternally by a fully divine contract, in a love beyond time and space.")
    }
}