# -*- coding: utf-8 -*-
"""
English (EN) translation of FBST_YORUMLAR_BURC.
Keys are identical to the Turkish dict; only the value strings are translated.
Used when the active language is "en" (i18n.LangDict serves these values).
"""

FBST_YORUMLAR_BURC = {
    # === SUN - identity in the relationship, how it shines ===
    ("Güneş", "Koç"): "In this relationship you come forward with a bold, pioneering energy. You set the direction and you are always the one who takes the first step. Your partner admires your courage but sometimes feels drained by your haste. Your greatest test in this relationship is patience - your tendency to want everything right now tires your partner. When you learn to be patient, you become the true engine of this relationship.",
    ("Güneş", "Boğa"): "In this relationship you create a secure, solid, powerful and stable foundation. You show your love through concrete actions - cooking, touching, being there. Your partner admires your reliability, but your resistance to change sometimes creates tension. Your test in this relationship is learning to be flexible - wanting everything to stay the same can suffocate the relationship. When you become flexible, you are the strongest harbor of this relationship.",
    ("Güneş", "İkizler"): "In this relationship you use your mind and your gift with words. You run the relationship through talking, debating and exchanging ideas. Your partner admires your intellect and sense of humor but may sometimes feel you stay too superficial. Your test in this relationship is going deeper - skimming over topics hurts your partner. When you deepen, you become the brightest source of communication in this relationship.",
    ("Güneş", "Yengeç"): "In this relationship you create a protective, nurturing and emotional force. You embrace your partner, you build your home and create a warm nest. Your partner sees you as a safe harbor but sometimes feels overwhelmed by your over-protectiveness. Your test is letting go - your need to control everything suffocates your partner. When you let go, you build the deepest bond in this relationship.",
    ("Güneş", "Aslan"): "In this relationship you are a radiant, attention-drawing and admirable presence. You express your love in a grand, showy and passionate way. Your partner admires this energy but sometimes you get lost in ego clashes. Your test is allowing the other to shine too - insisting on being the only star of the relationship hurts your partner. When you give space, you become the greatest strength of this relationship.",
    ("Güneş", "Başak"): "In this relationship you are a force that organizes, analyzes and heals. You love through practical steps, small touches and service. Your partner admires your loyalty and diligence but can grow tired of your many critiques. Your test is accepting yourself too - your search for perfection strains the relationship. When you see flaws as beautiful, you create the finest beauty of this relationship.",
    ("Güneş", "Terazi"): "In this relationship you are a soul seeking balance, harmony and beauty. You can even resolve arguments gracefully. Your partner admires your elegance and sense of justice, but your indecisiveness can sometimes be frustrating. Your test is making clear decisions - your effort to hear both sides can tear you apart. When you become clear, you are the strongest referee of this relationship.",
    ("Güneş", "Akrep"): "In this relationship you carry a deep, intense and transformative energy. You give your love completely - no halfway. Your partner admires your passion but can fear your controlling nature. Your test is trusting - your need to keep everything under control suffocates the relationship. When you learn to trust, you build the deepest bond of this relationship.",
    ("Güneş", "Yay"): "In this relationship you represent freedom, adventure and meaning. You see the relationship from a broad perspective and dream big. Your partner admires your optimism and your outlook on life but your avoidance of commitment creates anxiety. Your test is taking concrete steps - constantly gazing at other horizons leaves your partner feeling insecure. When you get grounded, you become the greatest guide of this relationship.",
    ("Güneş", "Oğlak"): "In this relationship you are a serious, responsible and constructive force. You build the relationship with long-term plans, concrete steps and patience. Your partner admires your determination and reliability, but your difficulty showing emotions creates distance. Your test is opening up - hiding behind your walls hurts your partner. When you open your emotions, you build the strongest foundation of this relationship.",
    ("Güneş", "Kova"): "In this relationship you are a free, innovative and visionary spirit. You build the relationship on equality, friendship and freedom. Your partner admires your vision and originality, but your reserved stance can create coldness. Your test is drawing closer - your insistence on independence pushes your partner away. When you draw close, you build the most special and unique bond of this relationship.",
    ("Güneş", "Balık"): "In this relationship you offer unconditional love, compassion and a spiritual bond. You experience your love on a soul level and understand the other deeply. Your partner admires your compassion and intuition, but your blurred boundaries create confusion. Your test is setting boundaries - your tendency to sacrifice yourself completely tires your partner. When you set boundaries, you become the strongest source of love in this relationship.",

    # === MOON - emotional needs, where it feels safe ===
    ("Ay", "Koç"): "Emotionally you react quickly - you show both your love and your anger instantly. Your partner loves this directness but can be shaken by the intensity of your reactions. To feel secure in this relationship you need quick solutions and clear answers. Waiting for a long time drives you crazy. When you learn to channel your emotional outbursts, you become the strongest warrior of this relationship.",
    ("Ay", "Boğa"): "Emotionally your security is built on physical touch, comfort and stability. You show love with concrete things - food, hugs, presence. Your partner gives you the comfort of being able to trust you, but your resistance to change can suffocate the relationship. Routine and repetition matter for you to feel safe. When you learn change in small steps, you build the warmest home in this relationship.",
    ("Ay", "İkizler"): "Emotionally you are nourished by talking, sharing and learning. You express your inner world with words - you process your feelings by writing, speaking and debating. Your partner loves your mental liveliness but may feel your emotional depth can remain shallow. Communication must never stop for you to feel safe. When you also talk about your feelings, you build the brightest bridge of communication in this relationship.",
    ("Ay", "Yengeç"): "Emotionally your security is built on home, family and your roots. You show love by warming the home, cooking and hugging. Your partner admires your warmth and protectiveness, but your extreme sensitivity can sometimes be tiring. To feel safe in this relationship you need a secure home. When you learn to navigate your emotional waves, you build the deepest bond of this relationship.",
    ("Ay", "Aslan"): "Emotionally you want to be appreciated, admired and in the spotlight. You offer your love through grand gestures and showy affection. Your partner loves your passion and vivacity, but your hunger for attention sometimes creates insecurity. To feel safe, eyes must be on you. When you feed your emotional security from within, you become the brightest star of this relationship.",
    ("Ay", "Başak"): "Emotionally your security is built on order, cleanliness and practical solutions. You show love by serving, organizing and helping. Your partner loves your diligence and loyalty, but your critical approach sometimes creates distance. Everything must be in order for you to feel safe. When you accept flaws, you create the finest beauty of this relationship.",
    ("Ay", "Terazi"): "Emotionally your security is built on balance, harmony and beauty. You seek a relationship where everyone is happy and no one is hurt. Your partner loves your elegance and your ability to harmonize, but your indecisiveness can sometimes be frustrating. Equality is very important for you to feel safe. When you voice your own needs too, you become the strongest referee of this relationship.",
    ("Ay", "Akrep"): "Emotionally you seek a deep, intense and absolute bond. You give your love completely but expect the same in return. Your partner loves your loyalty and depth but can grow tired of your control and jealousy. Deep trust is what you need to feel safe. When you learn to trust, you build the deepest bond of this relationship.",
    ("Ay", "Yay"): "Emotionally your security is built on freedom, spaciousness and meaning. Relationships that constrict, limit or fall into routine suffocate you. Your partner loves your optimism and your outlook on life, but your fear of commitment creates anxiety. You need to see the big picture to feel safe. When you get grounded, you become the greatest guide of this relationship.",
    ("Ay", "Oğlak"): "Emotionally your security is built on structure, seriousness and responsibility. Showing emotions is hard for you, but your actions speak. Your partner loves your reliability and determination, but your emotional distance creates alienation. Concrete steps matter for you to feel safe. When you open your emotions, you build the strongest foundation of this relationship.",
    ("Ay", "Kova"): "Emotionally your security is built on freedom, equality and friendship. Traditional relationship molds feel too narrow for you. Your partner admires your originality and vision, but your reserved stance can create coldness. Being like friends is what you need to feel safe. When you draw close, you build the most unique bond of this relationship.",
    ("Ay", "Balık"): "Emotionally your security is built on unconditional love, self-sacrifice and a spiritual bond. You live your love on a soul level. Your partner loves your compassion and depth, but your blurred boundaries create confusion. Deep spiritual connection matters for you to feel safe. When you set boundaries, you become the strongest source of love in this relationship.",

    # === MERCURY - communication style, how it understands/speaks ===
    ("Merkür", "Koç"): "You speak with a fast, direct and sharp tongue. You say your ideas without filtering - your honesty can sometimes startle your partner. Arguments in the relationship start and end quickly. Your partner loves your intelligence and quickness but can be shaken by your harsh outbursts. When you learn to choose your words, you become the strongest communication engine of this relationship.",
    ("Merkür", "Boğa"): "You speak with a slow but sure, concrete and reliable language. You stand behind everything you say and never speak empty words. Your partner admires your reliability, but the slowness of your words can sometimes cause impatience. Concrete topics and practical solutions matter in this relationship. When you learn to talk about emotional topics too, you build the sturdiest bridge of communication in this relationship.",
    ("Merkür", "İkizler"): "You speak with a versatile, witty and mentally alive language. You run the relationship by talking, learning and sharing. Your partner admires your intellect and jokes, but talking too much and listening too little can create problems. Information exchange is very valuable in this relationship. When you learn to listen too, you build the brightest bridge of communication in this relationship.",
    ("Merkür", "Yengeç"): "You speak with an emotional, empathetic and sensitive language. You instantly read the other's feelings but struggle to open up your own. Your partner loves your empathy but can complain that you stay too closed. You have a tendency to repeat past topics. When you let go of the past and focus on today, you build the deepest bridge of understanding in this relationship.",
    ("Merkür", "Aslan"): "You speak with a showy, impressive language that commands the stage. The way you present your ideas is very powerful - your ability to convince is high. Your partner loves your eloquence and creativity, but your insistence on being right about everything can create tension. Listening matters too in this relationship. When you value the other's ideas, you become the greatest stage artist of this relationship.",
    ("Merkür", "Başak"): "You speak with an analytical, detail-oriented and critical language. You analyze everything in fine detail - this can be both a strength and exhausting in the relationship. Your partner loves the depth of your mind but can grow tired of your many critiques. You have a tendency to magnify small details. When you express praise too, you become the finest observer of this relationship.",
    ("Merkür", "Terazi"): "You speak with a balanced, elegant and fair language. You listen to both sides and try to balance them. Your partner admires your sense of justice and elegance, but your indecisiveness can sometimes be frustrating. You can struggle to make clear decisions. When you become clear, you are the strongest referee of this relationship.",
    ("Merkür", "Akrep"): "You speak with a deep, investigative and strategic language. Staying on the surface is never enough for you - you analyze every topic down to its core. Your partner loves the depth of your mind, but your secrecy and strategic stance can create distrust. Being open and transparent is very important in this relationship. When you share your secrets, you build the deepest bond of this relationship.",
    ("Merkür", "Yay"): "You speak with a broad, philosophical and optimistic language. You see the big picture and do not get lost in details. Your partner loves your optimism and broad perspective, but being too general can delay concrete solutions. Dreaming big matters in this relationship, but feet must stay on the ground. When you take concrete steps, you become the greatest guide of this relationship.",
    ("Merkür", "Oğlak"): "You speak with a serious, strategic and constructive language. You love planning, scheduling and setting concrete steps. Your partner loves this seriousness and determination, but staying too task-focused can weaken emotional bonds. Emotions must also be spoken about in this relationship. When you increase emotional sharing, you become the strongest strategist of this relationship.",
    ("Merkür", "Kova"): "You speak with an original, innovative and unconventional language. You do not fit traditional thought patterns - your ideas are always different and interesting. Your partner admires your vision and originality, but your distant communication style can create coldness. Close communication matters in this relationship. When you warm up, you build the most special and unique bond of this relationship.",
    ("Merkür", "Balık"): "You speak with an intuitive, creative language with strong imagination. Your grasp is intuitive rather than logical analysis. Your partner loves your imagination and compassion, but struggling to choose clear words creates misunderstanding. Being clear and open matters in this relationship. When you clarify your emotions, you build the deepest spiritual bond of this relationship.",

    # === VENUS - love language, how it loves ===
    ("Venüs", "Koç"): "You show love with passion, boldness and action. Chasing, conquering and making new beginnings give you pleasure. Your partner watches your passion and energy with admiration, but your waning interest creates anxiety. Monotony is not for you - there must always be liveliness, novelty, action. When you learn to keep your love constantly fresh, you become the most passionate lover of this relationship.",
    ("Venüs", "Boğa"): "You show love through concrete actions - touching, cooking, being there. You seek reliable, stable and lasting relationships. Your partner loves your loyalty and warmth, but your possessiveness can sometimes suffocate. Enjoying beautiful things matters - shared meals, music, nature. You build a love that grows as you share it.",
    ("Venüs", "İkizler"): "You show love through conversation, humor and mental harmony. Intellectual connection matters to you as much as physical attraction. Your partner loves your wit and fun communication style, but being too changeable creates insecurity. Monotony is not for you - there must always be novelty, learning and sharing. When you add emotional depth, you become the most fun lover of this relationship.",
    ("Venüs", "Yengeç"): "You show love by protecting, nurturing and embracing. Home, warmth and the concept of a nest are very important. Your partner loves your warmth and protectiveness, but being overly attached can sometimes feel overwhelming. Being a safe harbor is very valuable. When you build your love on a solid foundation, you become the most reassuring lover of this relationship.",
    ("Venüs", "Aslan"): "You show love in a big, grand and lively way. Buying gifts, surprising and being in the spotlight give you pleasure. Your partner loves your liveliness and passion, but your hunger for attention creates insecurity. Eyes must be on you - but your partner shining too is very important. When you give space, you build the greatest stage of love in this relationship.",
    ("Venüs", "Başak"): "You show love by serving, organizing and making your partner's life easier. Your practical love language is very strong. Your partner loves your loyalty and diligence, but your critical approach can create distance. The search for perfection can suffocate the relationship. When you accept your love and see flaws as beautiful, you become the most refined lover of this relationship.",
    ("Venüs", "Terazi"): "You show love with balance, elegance and beauty. Equality, harmony and beauty are very important in a relationship. Your partner loves your elegance and sense of justice, but your indecisiveness can create distance. Experiencing beautiful things matters - art, music, aesthetics. When you express your love clearly, you become the most elegant lover of this relationship.",
    ("Venüs", "Akrep"): "You show love in a deep, intense and absolute way. No halfway - it is all or nothing. Your partner loves your passion and depth, but your jealousy and control can feel overwhelming. Trust and loyalty matter deeply in this relationship. When you learn to trust, you become the deepest lover of this relationship.",
    ("Venüs", "Yay"): "You show love through freedom, joy and adventure. You want to live the relationship in a fun, spacious and meaningful way. Your partner loves your optimism and liveliness, but your fear of commitment creates anxiety. Dreaming big is beautiful, but grounding is also needed. When you get grounded, you become the greatest guide of love in this relationship.",
    ("Venüs", "Oğlak"): "You show love through actions, responsibility and practical support. You show your love by doing, not saying. Your partner loves your reliability and seriousness, but the lack of emotional openness creates coldness. Emotional sharing matters too. When you open your emotions, you become the most reliable lover of this relationship.",
    ("Venüs", "Kova"): "You build love on friendship, equality and freedom. Traditional relationship molds feel too narrow for you. Your partner admires your originality and vision, but your reserved stance can create coldness. Closeness matters too. When you warm up, you become the most unique lover of this relationship.",
    ("Venüs", "Balık"): "You show love unconditionally, selflessly and spiritually. You live your love on a soul level. Your partner loves your compassion and depth, but your blurred boundaries create confusion. Setting boundaries is very important. When you can set boundaries, you become the strongest source of love in this relationship.",

    # === MARS - style of passion, how it defends its boundaries ===
    ("Mars", "Koç"): "You express your passion boldly, directly and through action. You are the pioneer - the one who takes the first step, sets the boundaries, and gets things moving. Your partner watches your energy and courage with admiration but can be shaken by the intensity of your anger. Competition and adventure matter deeply in the relationship. When you learn to channel your energy, you become the strongest warrior of this relationship.",
    ("Mars", "Boğa"): "You express your passion with patience, steadiness and concrete actions. You move slowly but surely. Your partner loves your reliability and strength, but your possessiveness can create problems. Physical touch matters deeply - you express love by touching, hugging, being there. Your patient attitude forms the strongest foundation of this relationship.",
    ("Mars", "İkizler"): "You express your passion through words, debates and mental harmony. Talking, debating and exchanging ideas matter deeply in the relationship. Your partner loves your wit and playful communication style, but talking too much and listening too little can create problems. Choosing your words carefully matters in arguments. When you communicate in balance, you become the brightest communication warrior of this relationship.",
    ("Mars", "Yengeç"): "You express your passion by protecting, claiming and emotionally. Protection, defense and ownership matter deeply in the relationship. Your partner loves your loyalty and warmth, but your habit of turning your anger inward can create problems. Healthy expression matters instead of emotional outbursts. When you express your feelings healthily, you become the strongest protector of this relationship.",
    ("Mars", "Aslan"): "You express your passion grandly, passionately and boldly. Being in the spotlight and inspiring admiration matter deeply. Your partner loves your courage and passion, but your ego clashes can create tension. Your partner shining too is very important. When you channel your ego, you build the greatest stage of passion in this relationship.",
    ("Mars", "Başak"): "You express your passion by serving, organizing and taking practical steps. You value details - everything being in order is very important. Your partner loves your diligence and loyalty, but your critical approach can create distance. Learning and growth matter deeply. When you accept flaws, you become the finest observer of this relationship.",
    ("Mars", "Terazi"): "You build your passion on balance, harmony and mutuality. Equality is very important - both sides must participate equally. Your partner loves your elegance and your ability to harmonize, but your indecisiveness can be frustrating. Taking bold steps matters. When you become clear, you are the strongest referee of this relationship.",
    ("Mars", "Akrep"): "You express your passion deeply, intensely and absolutely. Control, power and deep connection matter deeply in the relationship. Your partner loves your passion and depth but can grow tired of your control and jealousy. Trust and loyalty matter deeply. When you learn to trust, you build the deepest bond of this relationship.",
    ("Mars", "Yay"): "You build your passion on adventure, freedom and meaning. Dreaming big and experiencing new things matter deeply in the relationship. Your partner loves your optimism and courage, but your fear of commitment creates anxiety. Grounding matters too. When you take concrete steps, you become the greatest adventure guide of this relationship.",
    ("Mars", "Oğlak"): "You express your passion with patience, determination and strategic steps. Long-term goals matter deeply. Your partner loves your determination and reliability, but staying too task-focused can weaken emotional bonds. Emotional sharing matters too. When you open your emotions, you become the strongest strategist of this relationship.",
    ("Mars", "Kova"): "You build your passion on freedom, innovation and social transformation. Traditional relationship molds feel too narrow for you. Your partner admires your vision and originality, but your reserved stance can create coldness. Closeness matters too. When you warm up, you build the most unique bond of this relationship.",
    ("Mars", "Balık"): "You express your passion intuitively, selflessly and spiritually. Spiritual or creative struggle matters more than physical struggle. Your partner loves your compassion and depth, but your blurred boundaries create confusion. Setting boundaries is very important. When you set boundaries, you become the strongest warrior of love in this relationship.",

    # === JUPITER - what it brings to the relationship, expansion area ===
    ("Jüpiter", "Koç"): "You bring courage, adventure and novelty to the relationship. You bring new beginnings, excitement and action energy. Your partner watches your energy with admiration, but going overboard can create problems. You are the one who expands, grows and keeps the relationship alive. When you use this expansion energy in balance, you become the greatest fortune of this relationship.",
    ("Jüpiter", "Boğa"): "You bring abundance, prosperity and tangible values to the relationship. You bring great opportunities in finances, security and physical comfort. Your partner loves your reliability and vivacity, but your possessiveness can create problems. You are the one who grows the relationship with tangible values. As you share this abundance energy, you become the greatest source of plenty in this relationship.",
    ("Jüpiter", "İkizler"): "You bring knowledge, communication and mental liveliness to the relationship. You bring great opportunities in learning, teaching and sharing. Your partner loves your wit and fun communication style, but talking too much and listening too little can create problems. You are the one who grows the relationship mentally. When you communicate in balance, you become the brightest source of communication in this relationship.",
    ("Jüpiter", "Yengeç"): "You bring warmth, home and family values to the relationship. You bring great opportunities in growing your home, building a family and strengthening bonds. Your partner loves your warmth and protectiveness, but being overly attached can feel overwhelming. You are the one who turns the relationship into a warm nest. When you use this warmth energy in balance, you become the greatest source of security in this relationship.",
    ("Jüpiter", "Aslan"): "You bring passion, fun and creativity to the relationship. You bring great opportunities in art, stage and entertainment. Your partner loves your vivacity and energy, but your ego clashes can create tension. You are the one who keeps the relationship fun and passionate. When you use your energy in balance, you become the greatest source of joy in this relationship.",
    ("Jüpiter", "Başak"): "You bring service, practical solutions and healing to the relationship. You bring great opportunities in organizing daily life and solving problems. Your partner loves your diligence and loyalty, but your critical approach can create distance. You are the one who grows the relationship practically. When you express praise too, you become the greatest source of service in this relationship.",
    ("Jüpiter", "Terazi"): "You bring balance, harmony and beauty to the relationship. You bring great opportunities in relationships, partnership and aesthetics. Your partner loves your elegance and sense of justice, but your indecisiveness can be frustrating. You are the one who keeps the relationship beautiful and balanced. When you make clear decisions, you become the greatest source of balance in this relationship.",
    ("Jüpiter", "Akrep"): "You bring transformation, depth and great resources to the relationship. You bring great opportunities in sexuality, spiritual transformation and shared resources. Your partner loves your depth and passion but can grow tired of your control. You are the one who transforms the relationship deeply. When you learn to trust, you become the greatest source of transformation in this relationship.",
    ("Jüpiter", "Yay"): "You bring freedom, meaning and adventure to the relationship. You bring great opportunities in philosophy, travel and higher learning. Your partner loves your optimism and broad perspective, but your fear of commitment creates anxiety. You are the one who grows the relationship on the big picture. When you get grounded, you become the greatest source of guidance in this relationship.",
    ("Jüpiter", "Oğlak"): "You bring seriousness, responsibility and long-term structuring to the relationship. You bring great opportunities in career, status and long-term goals. Your partner loves your determination and reliability, but staying too task-focused can weaken emotional bonds. You are the one who grows the relationship long-term. When you increase emotional sharing, you become the greatest source of assurance in this relationship.",
    ("Jüpiter", "Kova"): "You bring freedom, innovation and a social vision to the relationship. You bring great opportunities in friendship, social projects and technology. Your partner admires your vision and originality, but your reserved stance can create coldness. You are the one who grows the relationship through freedom. When you draw close, you become the most unique source of vision in this relationship.",
    ("Jüpiter", "Balık"): "You bring spirituality, intuition and unconditional love to the relationship. You bring great opportunities in art, music, meditation and spiritual practices. Your partner loves your compassion and depth, but your blurred boundaries create confusion. You are the one who grows the relationship spiritually. When you set boundaries, you become the greatest spiritual source of this relationship.",

    # === SATURN - the lesson in the relationship, where it is limited ===
    ("Satürn", "Koç"): "Your greatest test in this relationship is being patient - your tendency to make fast decisions and want everything now tires your partner. Your courage and initiative are strong, but your impatience can damage the relationship. When you take slower, more thoughtful steps, the relationship becomes much stronger. Your lesson is learning to be patient. When you learn it, you become the strongest engine of this relationship.",
    ("Satürn", "Boğa"): "Your greatest test in this relationship is opening to change - your insistence on always doing the same things can suffocate the relationship. Your steadiness and reliability are strong, but being inflexible can create tension. When you open to small changes, the relationship becomes much more alive. Your lesson is learning flexibility. When you learn it, you build the sturdiest foundation of this relationship.",
    ("Satürn", "İkizler"): "Your greatest test in this relationship is going deeper - your habit of skimming over topics hurts your partner. Your mental liveliness is strong, but staying shallow can create distance. When you deepen in emotional topics too, the relationship becomes much stronger. Your lesson is learning to deepen. When you learn it, you build the brightest bridge of communication in this relationship.",
    ("Satürn", "Yengeç"): "Your greatest test in this relationship is letting go - your need to control everything overwhelms your partner. Your protectiveness and warmth are strong, but being overly attached can create problems. When you give your partner space, the relationship becomes much stronger. Your lesson is learning to trust. When you learn it, you build the safest harbor of this relationship.",
    ("Satürn", "Aslan"): "Your greatest test in this relationship is ego management - your insistence on being the only star hurts your partner. You have a radiant, attention-drawing nature, but letting the other shine is very important. When you value your partner's strengths, the relationship becomes much stronger. Your lesson is giving space. When you learn it, you become the greatest strength of this relationship.",
    ("Satürn", "Başak"): "Your greatest test in this relationship is accepting yourself too - your search for perfection tires both you and your partner. Your analytical ability is strong, but your habit of criticizing everything can create distance. When you express praise too, the relationship becomes much stronger. Your lesson is learning acceptance. When you learn it, you create the finest beauty of this relationship.",
    ("Satürn", "Terazi"): "Your greatest test in this relationship is making clear decisions - your indecisiveness can be frustrating. Your search for balance and harmony is strong, but your habit of postponing everything tires the relationship. When you take bold steps, the relationship becomes much stronger. Your lesson is learning clarity. When you learn it, you become the strongest referee of this relationship.",
    ("Satürn", "Akrep"): "Your greatest test in this relationship is trusting - your need to keep everything under control suffocates the relationship. Your depth and passion are strong, but your control can create coldness. When you learn to trust, the relationship becomes much stronger. Your lesson is learning to let go. When you learn it, you build the deepest bond of this relationship.",
    ("Satürn", "Yay"): "Your greatest test in this relationship is getting grounded - your habit of always gazing at other horizons leaves your partner insecure. Dreaming big is strong in you, but not taking concrete steps can create problems. When you take concrete steps, the relationship becomes much stronger. Your lesson is learning to keep your feet on the ground. When you learn it, you become the greatest guide of this relationship.",
    ("Satürn", "Oğlak"): "Your greatest test in this relationship is opening up - hiding behind your walls hurts your partner. Your seriousness and determination are strong, but failing to show your emotions can create coldness. When you open your emotions, the relationship becomes much stronger. Your lesson is learning to open up. When you learn it, you build the sturdiest foundation of this relationship.",
    ("Satürn", "Kova"): "Your greatest test in this relationship is drawing close - your insistence on independence pushes your partner away. Your freedom and vision are strong, but your reserved stance can create coldness. When you draw close, the relationship becomes much stronger. Your lesson is learning to bond. When you learn it, you build the most unique bond of this relationship.",
    ("Satürn", "Balık"): "Your greatest test in this relationship is setting boundaries - your tendency to sacrifice yourself completely tires your partner. Your compassion and depth are strong, but your blurred boundaries can create confusion. When you set boundaries, the relationship becomes much stronger. Your lesson is learning boundaries. When you learn it, you become the strongest source of love in this relationship.",

    # === URANUS - freedom/surprise dynamic ===
    ("Uranüs", "Koç"): "Your insistence on freedom and independence in the relationship is very strong. Sudden changes, unexpected decisions and innovative approaches keep your relationship constantly alive. Your partner watches this energy with admiration, but your unpredictability can create anxiety. Novelty and adventure matter deeply. With a balanced sense of freedom, you become the most innovative spirit of this relationship.",
    ("Uranüs", "Boğa"): "You can experience sudden changes in values and security. Unexpected developments in finances and the process of redefining your values affect the relationship. Your partner loves your openness to change, but uncertainty can create unease. Discovering new sources of value matters deeply. When you adapt to change, you become the most innovative creator of value in this relationship.",
    ("Uranüs", "İkizler"): "You can experience sudden revolutions in your communication and thought style. New ideas, unconventional approaches and quick communication keep the relationship constantly alive. Your partner loves your mental liveliness, but your scatteredness can create confusion. Innovative ideas matter deeply. When you keep your focus, you become the most innovative source of communication in this relationship.",
    ("Uranüs", "Yengeç"): "You can experience sudden changes regarding home and family. Moving, changing homes or unexpected developments in the family structure affect the relationship. Your partner loves your innovative approach, but uncertainty can create unease. Creating a secure home matters deeply. When you adapt to change, you become the most innovative builder of home in this relationship.",
    ("Uranüs", "Aslan"): "You can experience sudden eruptions in creativity and fun. Unpredictable developments in art, entertainment or romance keep the relationship constantly alive. Your partner loves your creativity, but uncertainty can create unease. Surprises and innovations matter deeply. When you also strengthen emotional bonds, you become the most innovative spirit of this relationship.",
    ("Uranüs", "Başak"): "You can experience sudden changes in daily life and health. Unexpected developments in working conditions and sudden awareness about health affect the relationship. Your partner loves your innovative approach, but uncertainty can create unease. Practical solutions matter deeply. When you adapt to change, you become the most innovative problem-solver of this relationship.",
    ("Uranüs", "Terazi"): "You can experience sudden searches for freedom and balance. Unexpected developments in marriage or partnership and the conflict between freedom and balance affect the relationship. Your partner loves your respect for freedom, but uncertainty can create anxiety. Equality matters deeply. With a balanced sense of freedom, you become the most innovative referee of this relationship.",
    ("Uranüs", "Akrep"): "You can experience sudden eruptions around power and control. Hidden secrets can suddenly surface, control can be lost. Your partner loves your depth, but your unpredictability can create fear. Deep transformation matters deeply. When you release control, you become the deepest source of transformation in this relationship.",
    ("Uranüs", "Yay"): "You can experience sudden revolutions in belief and philosophy. Your old belief system can be shaken, and you can open to new, deeper understandings. Your partner admires your vision, but uncertainty can create anxiety. Seeing the big picture matters deeply. When you get grounded, you become the most innovative guide of this relationship.",
    ("Uranüs", "Oğlak"): "You can experience sudden changes in career and status. Unexpected developments in work life and changes in career direction affect the relationship. Your partner loves your determination, but your unpredictability can create unease. Long-term plans matter deeply. When you adapt to change, you become the most innovative strategist of this relationship.",
    ("Uranüs", "Kova"): "You can experience sudden eruptions around freedom and innovation. Your personal transformation can be very fast and great. Your partner loves your originality, but your reserved stance can create coldness. Equality and friendship matter deeply. When you draw close, you build the most special and unique bond of this relationship.",
    ("Uranüs", "Balık"): "You can experience sudden transformations in the spiritual world. Your intuition is very strong but uncertainty can be great too. Unpredictable waves of inspiration can come in art or music. Your partner loves your depth, but your unpredictability can create confusion. Boundaries matter deeply. When you clarify your boundaries, you build the most innovative spiritual bond of this relationship.",

    # === NEPTUNE - idealism, dissolution ===
    ("Neptün", "Koç"): "There can be blurriness regarding identity and goals in the relationship. You can experience uncertainty about what you want, but your intuition is very strong. Your partner loves your depth, but uncertainty can create distrust. Being clear matters deeply. When you become clear, you build the strongest intuitive bond of this relationship.",
    ("Neptün", "Boğa"): "There can be uncertainties regarding values and security. Unclear situations with money and confusion over values can arise. Your partner loves your reliability, but uncertainty can create unease. Tangible values matter deeply. When you make things concrete, you become the safest source of this relationship.",
    ("Neptün", "İkizler"): "There can be blurriness in communication. There can be a gap between what you say and what you mean. Intuitive communication is very strong, but being unclear can create misunderstanding. Being open and clear matters deeply. When you become clear, you build the deepest bridge of understanding in this relationship.",
    ("Neptün", "Yengeç"): "There can be uncertainties regarding home and family. There can be unclear dynamics or hidden truths in the family structure. Your partner loves your warmth, but uncertainty can create distrust. A secure home matters deeply. When you build a secure home, you build the warmest harbor of this relationship.",
    ("Neptün", "Aslan"): "You can experience waves of inspiration in creativity and fun. There is a very strong intuitive flow in art or entertainment, but you can struggle to make it concrete. Your partner loves your creativity, but uncertainty can create disappointment. Making passion concrete matters deeply. When you make it concrete, you become the greatest source of joy in this relationship.",
    ("Neptün", "Başak"): "There can be uncertainties in daily life and health. Unclear situations in working conditions and confusion over health can arise. Your partner loves your diligence, but uncertainty can create unease. Practical solutions matter deeply. When you make things practical, you become the safest source of this relationship.",
    ("Neptün", "Terazi"): "The risk of idealization and disappointment is very high. You can see your partner as larger than they are, but your potential for unconditional love is also very high. Looking with clear eyes matters deeply. When you look clearly, you build the strongest bond of love in this relationship.",
    ("Neptün", "Akrep"): "There can be uncertainties around power and control. Hidden power dynamics are at play, and you can experience a deep transformation process. Your partner loves your depth, but uncertainty can create fear. Deep trust matters deeply. When you can trust, you become the deepest source of transformation in this relationship.",
    ("Neptün", "Yay"): "There can be uncertainties in belief and philosophy. Your old belief system can be shaken, but you can also open to new, deeper understandings. Your partner admires your vision, but uncertainty can create anxiety. Seeing the big picture matters deeply. When you get grounded, you become the greatest spiritual guide of this relationship.",
    ("Neptün", "Oğlak"): "There can be uncertainties in career and status. You can experience confusion about your goals or career direction. Your partner loves your determination, but uncertainty can create unease. Concrete steps matter deeply. When you make things concrete, you become the safest strategist of this relationship.",
    ("Neptün", "Kova"): "There can be uncertainties in friendship and social matters. There can be unclear dynamics in your social circle, but you can also form very strong intuitive bonds for humanistic help. Your partner admires your vision, but uncertainty can create anxiety. Clarity matters deeply. When you become clear, you build the most unique vision bond of this relationship.",
    ("Neptün", "Balık"): "There can be uncertainties in the spiritual world. Your intuition is very strong but the risk of losing touch with reality is also great. Your soul is very deep, your intuition very strong. Boundaries matter deeply. When you clarify your boundaries, you build the deepest spiritual bond of this relationship.",

    # === PLUTO - power struggle, transformation ===
    ("Plüton", "Koç"): "You are in the most intense place of power and identity transformation. You are releasing your old self and building a new one - this process deeply affects the relationship too. Your partner loves your courage and capacity for transformation, but can fear your controlling nature. Power dynamics constantly shift. When you learn control, you become the strongest catalyst of transformation in this relationship.",
    ("Plüton", "Boğa"): "You experience deep transformation around values and security. You are releasing your old values and building new ones - this process deeply affects the relationship too. Your partner loves your reliability but can fear your possessiveness. Value conflicts are very intense. When you share your values, you become the strongest partner of value in this relationship.",
    ("Plüton", "İkizler"): "You experience deep transformation in your communication and thought style. You are releasing old communication patterns and building new ones - this process deeply affects the relationship too. Your partner loves your intellect, but you must be careful against the risk of manipulation. Open and transparent communication matters deeply. When you communicate transparently, you build the deepest bridge of understanding in this relationship.",
    ("Plüton", "Yengeç"): "You experience deep transformation around home, family and roots. You are releasing old family patterns and building new ones - this process deeply affects the relationship too. Your partner loves your warmth but can fear your over-attachment. Trust and bonding are very intense. When you form secure bonds, you become the deepest builder of home in this relationship.",
    ("Plüton", "Aslan"): "You experience deep transformation around creativity, ego and attention-seeking. You are releasing old ego patterns and building new ones - this process deeply affects the relationship too. Your partner loves your courage but can fear your ego clashes. Power dynamics are very intense. When you channel your ego, you become the greatest master of the stage in this relationship.",
    ("Plüton", "Başak"): "You experience deep transformation around daily life, health and service. You are releasing old work patterns and building new ones - this process deeply affects the relationship too. Your partner loves your diligence but can fear your critical approach. Service and perfectionism are very intense. When you accept flaws, you become the finest observer of this relationship.",
    ("Plüton", "Terazi"): "You experience deep transformation around balance, harmony and partnership. You are releasing old relationship patterns and building new ones - this process deeply affects the relationship too. Your partner loves your elegance but can fear power struggles. Balance and equality are very intense. When you find balance, you become the strongest referee of this relationship.",
    ("Plüton", "Akrep"): "You are in the most intense place of power, control and deep transformation. You are releasing your old self and building a new one - this process deeply affects the relationship too. Your partner loves your depth but can fear your controlling nature. Power struggle is very intense. When you learn to trust, you become the deepest source of transformation in this relationship.",
    ("Plüton", "Yay"): "You experience deep transformation around belief, philosophy and meaning. You are releasing your old belief system and building a new one - this process deeply affects the relationship too. Your partner admires your vision but can fear the intensity of transformation. The big picture matters deeply. When you take concrete steps, you become the greatest guide of this relationship.",
    ("Plüton", "Oğlak"): "You experience deep transformation around career, status and responsibilities. You are releasing old career patterns and building new ones - this process deeply affects the relationship too. Your partner loves your determination but can fear your seriousness. Structuring is very intense. When you increase emotional openness, you become the most reliable supporter of this relationship.",
    ("Plüton", "Kova"): "You experience deep transformation around freedom, innovation and social transformation. You are releasing old social patterns and building new ones - this process deeply affects the relationship too. Your partner admires your vision but can fear the intensity of transformation. Equality matters deeply. When you draw close, you build the most unique vision bond of this relationship.",
    ("Plüton", "Balık"): "You experience deep transformation around the spiritual world and the unconscious. You are releasing old spiritual patterns and building new ones - this process deeply affects the relationship too. Your partner loves your depth but can fear the intensity of transformation. Deep trust matters deeply. When you can trust, you build the deepest spiritual bond of this relationship.",

}