# -*- coding: utf-8 -*-
# fbst_sabian_ebeveyn.py
# Cocuk-ebeveyn iliskisi baglaminda Sabian yorumlari

fbst_sabian_ebeveyn = {
    "Koc": {
        1: ("Denizden yeni çıkmış, fok balığına sarılan bir kadın", "Ebeveynlige ilk adimi atmanin verdigi cabalilik ve ham duygularla, cocugunuzun size olan kosulsuz bagliligini sizi tamamen yeni bir role donusturmesi."),
        2: ("Gözlerden uzak bir vadide, yeteneklerini sergileyen bir komedyen", "Cocugunuzun kendi ic dunyasadaki yetenekleri ve neseyi, dis dunyanin beklentilerinden bagimsiz olarak kesfetme ve destekleme firsati."),
        3: ("Ülkesinin haritasını çıkaran bir adam", "Cocugunuzun gelisim yolunu, guclu ve zayif yonlerini haritalandirarak ona en uygun rehberligi saglama sorumlulugu."),
        4: ("Gözlerden uzak, tenha bir yolda yürüyen iki aşık", "Anne-baba ile cocuk arasindaki o benzersiz, dis dunyanin mudahalesinden uzak derin bag; birlikte buyumenin sessiz ve kutsal yolculugu."),
        5: ("Kanatlı bir üçgen", "Ebeveyn ile cocuk arasindaki zihin, duygu ve ruh butunlugunun; cocugun potansiyelini yucelterek onu hayata tasima gucu."),
        6: ("Bir kenarı parlak şekilde aydınlatılmış bir kare", "Cocugunuzun hayatindaki saglam temellerin uzerine dusen aydinlatici rehberlik; onun kadersel yonunu netlestirmek icin odaklanmasi gereken noktalar."),
        7: ("Aynı anda iki farklı dünyada kendini ifade edebilen bir adam", "Hem cocuklun hem yetiskinligin dilini ayni anda konusarak, cocugunuzla hem oyun hem derinlik duzeyinde bag kurabilme becerisi."),
        8: ("Doğu rüzgarında dalgalanan kurdeleli büyük bir kadın şapkası", "Cocugunuzun duygusal firtinalarina karsi sezgisel bir koruma kalkani olusturmak; onu sarsmadan, uyumlayarak destekleme sanati."),
        9: ("Kristal küreye odaklanmış bir medyum", "Cocugunuzun henuz dile getiremedigi icsel ihtiyaclarini, sessiz cagrisini ve duygusal yaralarini sezgisel olarak okuma yetenegi."),
        10: ("Geleneksel imgelere yeni formlar veren bir öğretmen", "Eski yetistirme kaliblari ve toksik ebeveynlik oruntulerini yikarak, cocugunuzla yepyeni ve saglikli bir iletisim dili yaratma firsati."),
        11: ("Bir ülkenin yöneticisi", "Ebeveyn rolu-nuzu tam anlamiyla sahiplenme; ailenin duzenini ve cocugunuzun guvenli yasam alanini sorumlulukla kurma vakti."),
        12: ("Üçgen şeklinde uçan yaban kazları sürüsü", "Anne-baba ve cocuk olarak ortak hedeflere dogru kusursuz bir uyum ve icgudusel isbirligiyle yol alma gucu."),
        13: ("Patlamamış bir bomba; başarısız bir sosyal isyan", "Cocugunuzda biriken ofke veya davranis problemlerinin yikici bir sekilde patlamak yerine, sabirla ve anlayisla sonumlenerek gelisim firsatina donusmesi."),
        14: ("Bir adam ve kadının yakınında kıvrılan bir yılan", "Ebeveyn ile cocuk arasindaki karmik bag; nesiller arasi aktarilan bilgelik ve cocugun derinlerinden uyanan donusturucu potansiyel."),
        15: ("Törensel bir battaniye dokuyan bir Kızılderili", "Cocugunuzun her bir gelisim anini sabirla ve emekle dokuyarak ona guvenli, kutsal bir yuva ve ruhsal zirh insa etme cabasi."),
        16: ("Gün batımında çalışan doğa ruhları (periler)", "Ebeveyn cabalarinizin otesinde, cocugunuzun gelisimini destekleyen gorunmez evrensel guclerin ve dogal koruyucu enerjilerin devrede olmasi."),
        17: ("Sessizlik içinde onurlu bir şekilde oturan iki bekar kadın", "Anne-baba ile cocuk arasindaki sessiz anlarin da derin bir sevgi ve huzur tasiydigini; soze gerek kalmadan var olabilmenin kutsalligini fark etme."),
        18: ("İki ağaç arasına gerilmiş boş bir hamak", "Surekli yetistirme cabasini birakip, cocugunuzun ve kendinizin dogal akisa dinlenmeye ihtiyac duydugu o kutsal an."),
        19: ("Sihirli bir halı", "Cocugunuzla birlikte hayal gucunun sinirlarini asarak, onun dunyasini masalsi ve ilham verici bir sekilde zenginlestirme potansiyeli."),
        20: ("Kışın kuşları besleyen genç bir kız", "En zor ve krizli donemlerde bile; sefkat, sabir ve kosulsuz sevgiyle cocugunuzun ruhsal beslenmesini saglayabilme mucizesi."),
        21: ("Ringe giren bir boksör", "Ebeveyn olarak cocugunuzun hakettigi degerler ve gelecek icin dissal engellere karsi savasmak uzere cesaretle ve kararlilikla donanma."),
        22: ("Tüm arzuların gerçekleştiği bahçeye açılan kapı", "Cocugunuzun potansiyeline ulastigini gormenin verdigi buyuk mutluluk; onun ozunu, yetenegi ve kadersel yolunu tam destekleme firsati."),
        23: ("Hafif bir yazlık elbise içinde hamile bir kadın", "Cocugunuzun kendi icinde buyuttugu yeni bir vizyonun, yaraticiliginin veya ruhsal bir meyvenin doguma hazirlanmasi."),
        24: ("Açık bir pencereden içeri savrulan perdelerin bereket boynuzu şeklini alması", "Evrensel akisa tam teslim olundugunda, kozmik sansin ve ruhsal bereketin beklenmedik bir sekilde ailenize dolmasi."),
        25: ("İnsanın iki farklı varlık seviyesinde deneyim kazanma ihtimali", "Ebeveynligi hem en derin fiziksel baglilikta hem de en yukse ilahi boyutta ayni anda, ustalikla yasayabilme lutfu."),
        26: ("Taşıyabileceğinden daha fazla yeteneğe sahip olan bir adam", "Cocugunuzun potansiyelinin tasmasi; bu yogun kadersel enerjiyi dagitmadan odaklayip dogru yonetme sinavi."),
        27: ("Hayal gücü sayesinde kaybedilmiş bir fırsatın yeniden kazanılması", "Gecmiste yapilmis hatalarin veya kacirilan sanslarin, guclu bir sevgi ve inanciyla onarilarak kadersel rotanin yeniden cizilmesi."),
        28: ("Hayal kırıklığına uğramış büyük bir izleyici kitlesiyle yüzleşen performans sanatçısı", "Cocugunuzla iliskideki asiri beklentilerin gerceklikle carpismasi; maskelerin duserek ciplak gercegin sevgiyle, oldugu gibi kabul edilmesi sinavi."),
        29: ("Göksel kürelerin (gezegenlerin) müziği", "Ruhlarinizin evrensel frekansla tam bir rezonansa girdigi, kelimelere ihtiyaç duyulmayan o ilahi ve kozmik senkronizasyon noktasi."),
        30: ("Bir ördek göleti ve yavruları", "Kadersel yolculugun bu fazinda sukunete erme; ait olma, huzurlu bir yuva kurma ve mutlak bir korunma alanimin tamamlanmasi.")
    },
    "Boga": {
        1: ("Berrak bir dağ deresinin taşıdığı altın tozları", "Ailesinin dogal akisinda sakli olan muazzam maddi ve manevi zenginligi fark etme ve bu bereketi sevgiyle kabul etme zamanı."),
        2: ("Elektrik fırtınası; doğanın karanlık gökyüzündeki muazzam gücü", "Aile icindeki krizlerin ve ani patlamalarin aslinda, Bu durumda size dusen, sabir ve anlayisla bu enerjileri temizleme firsatini gostermesidir."),
        3: ("Yoncalarla açan bir çimenliğe çıkan doğal basamaklar", "Cocugunuzun huzura, berekete ve koklenmeye giden yolda acele etmeden, adim adim ve organik bir sekilde buyumesi."),
        4: ("Gökkuşağının sonundaki altın küpü", "Firtinali sureclerin ve sinavlarin ardindan gelen o buyuk kadersel odul; birlikte ulasilan ruhsal ve maddi tatmin."),
        5: ("Açık bir mezarın başında bekleyen dul bir kadın", "Gecmisin acilarina ve bitmis karmik baglara veda ederek, ruhsal bir arinmayla bu yeni aile iliskisine tamamen yer acma sinavi."),
        6: ("Derin bir uçurumun üzerine kurulan asma köprü", "Anne-baba ile cocuk arasindaki en asilimaz gibi gorunen farkliliklari, saglam ve guvenilir bir iletisim koprusuyle asma gucu."),
        7: ("Kuyunun başındaki Samiriyeli kadın", "Eski onyargilari ve dunyevi tabulari yikarak, cocugunuzun ruhundaki en derin susuzlugu kosulsuz sevgiyle giderme erdemi."),
        8: ("Karsız bir zeminde duran kızak", "Gelecek icin yapilan planlarda zamanlamanin onemini anlama; dogru kosullar olusana kadar sabirla bekleme iradesi."),
        9: ("Tamamen süslenmiş bir Noel ağacı", "Ailenin en karanlik veya soguk gunlerinde bile umudu canli tutmasi ve birbirinize sundugunuz icsel degerlerin kutlamasi."),
        10: ("Bir Kızılhaç hemşiresi", "Kosulsuz sefkat, fedakarlik ve cocugunuzun en zayif, yarali aninda onun en buyuk ruhsal sifacisi olma kontrati."),
        11: ("Bahçesindeki çiçekleri sulayan bir kadın", "Sevginin ancak gunluk, istikrarli ve pratik bir emekle beslendiginde yikilmaz ve kalici bir yuvaya donusecegi bilgeligi."),
        12: ("Vitrinlere bakan genç bir çift", "Ortak hayaller kurma, gelecegi birlikte insa etme ve ailenin dunyevi/maddi hedeflerini neyseyle belirleme fazi."),
        13: ("Ağır yükler taşıyan bir hamal", "Ailenin maddi veya kadersel yuklerini cesaretle omuzlama; sadakatin ve sorumlulugun agir bir tork testine donusmesi."),
        14: ("Sahilde oynayan çocuklar ve suyun kenarındaki deniz kabukluları", "Dogal sinirlar icinde guvenle neseyi yasama; huzurlu bir yuva aliminda cocuksu, korunakli ve saf duygulara teslimiyet."),
        15: ("Kafasını kalın bir atkıyla sarmış adam", "Dis dunyanin gurultusu ve toksik mudahalelerine karsi ailenin mahremiyetini koruma; sadece birbirinizin ic sesini dinleme ihtiyaci."),
        16: ("Öğrencilerinin ilgisini çekemeyen yaşlı bir öğretmen", "Aile iliskisinde eski, ise yaramayan kaliplari birakma vakti; inatlasilan kurallar yerine yeni ve ilham verici bir ortak dil bulma zorunlulugu."),
        17: ("Kılıçlar ve meşaleler arasındaki sembolik savaş", "Iletisimde zihinsel aydinlanma (mesele) ile yikici elestiri (kilic) arasinda secim yapma; hakli olmayi degil sifayi secme sinavi."),
        18: ("Eski bir çantayı açık pencereden havalandıran kadın", "Bilincaltinda birikmis eski zehirleri, supheleri ve yukleri sevginin o taze ve sifali ruzgariyla temizleme arinmasi."),
        19: ("Okyanusun içinden yükselen yeni bir kıta", "Buyuk krizlerin ve duygusal calkantilarin ardindan ailenin yepyeni, sarsilmaz ve somut bir temel yaratma mucizesi."),
        20: ("Gökyüzünde uçuşan kanat benzeri bulutlar", "Manevi bir ilhamin, evrensel korumanin ve hafifligin aileye sigmasi; asiri maddiyatciligdan sirilip ilahi akisa guvenme."),
        21: ("Açık bir kitaptaki satırı gösteren parmak", "Kadersel kontratin size sundugu cok net bir isareti, mesaji veya senkronizasyonu fark edip ona gore hizalanma ani."),
        22: ("Fırtınalı suların üzerinde uçan beyaz güvercin", "En buyuk krizlerin, kavgalarin ve korkularin ortasinda bile; evrensel bir barisin, guvenin ve ilahi korumanin ailenin uzerinde suzulmesi."),
        23: ("Değerli taşlarla dolu bir mücevher dükkanı", "Ailenin sahip oldugu o yuksek oздegi, nadir bulunan yetenekleri ve parlayan ortak zenginligi idrak etme zirvesi."),
        24: ("Belinde düşman kafa derileriyle at süren Kızılderili savaşçı", "Koruma icgudusunun veya sahiplenmenin yikici bir kiskancliga/kontrolculuge donusme riski; ilkel egoyu ehillestirme sinavi."),
        25: ("Geniş ve muazzam bir halk parkı", "Kisisel sevginin sinirlarini asip, ailenin dis dunyaya da ilham veren kolektif bir huzur, bereket ve hosgoru alanna donusmesi."),
        26: ("Sevgilisine serenat yapan İspanyol aşık", "Sevgi dilini estetik bir sekilde, cesurca ifade etmenin ailenin manyetik torkunu yeniden alemlendirmesi."),
        27: ("Kabilesinin el sanatlarını satan yaşlı bir kadın", "Geleneklerin, koklerin ve gecmisin kadim bilgeligini; ailenizin bugunku maddi ve manevi insasina faydali olacak sekilde uyarlama."),
        28: ("Aşka yeniden uyanan olgun bir kadın", "Gecmisin tum hayal kirikliklarina ragmen kalbi cesurca yeniden acma; askin zamansiz oldugunu ve ailenin her an yeniden filizlenebilecegini idrak etme."),
        29: ("Bir masada çalışan iki ayakkabı tamircisi", "Ortak bir amac icin omuz omuza, sifir ego ile calisma; vizyonlari gercege donusturmek icin pratik, dengeli ve kusursuz bir isbirligi muhru."),
        30: ("Eski bir kalenin terasında gösteriş yapan tavus kuşu", "Zamanin testlerinden gecmis basarilarin, asaletin ve ebedi guvenin hakli gururu; ailenin koklu bir imparatorluk uzerine ihtişamla tacilmasi.")
    },
    "Ikizler": {
        1: ("Cam tabanlı bir teknede okyanusun dibini izleyen insanlar", "Yuzeysel olanin otesine gecip, zihinsel merakla cocugunuzun en derin ruhsal sularini kesfetme arzusu."),
        2: ("Noel Baba'nın gizlice çorapları doldurması", "Beklenmedik anda gelen kadersel hediyeler ve aile icindeki saf, cocuksu masumiyetin gorunmez bir el tarafindan odullendirilmesi."),
        3: ("Paris'teki Tuileries Bahçeleri", "Iletisimde zarafetin, zihinsel duzenin ve entelektuel uyumun kusursuz bir mimariyle (ortak bir dille) insa edilmesi."),
        4: ("Çobanpüskülü ve ökse otu", "Nostaljinin, eski anilarin ve koklu geleneklerin aile icindeki zihinsel bagi canli tutmasi."),
        5: ("Eyleme çağıran radikal bir dergi", "Zihinsel isyan! Ailededki siradanligi ve rutini kirarak, cocugunuzun zihnini atesecek yeni ve devrimsel fikirler uretme ihtiyaci."),
        6: ("Petrol sondajı yapan işçiler", "Gunluk sohbetlerin ve yuzeysel iletisimin cok otesine gecip, ailenin en derinindeki o zengin, gizli guc kaynagina ulasma cabasi."),
        7: ("Eski moda bir su kuyusu", "Birbirinizin zihninden, tukunmeyen kadim bir bilgelik ve ilham kaynagi gibi faydalanma; ruhsal susuzlugu kelimelerle giderme."),
        8: ("Fabrikanın etrafında toplanmış öfkeli grevciler", "Fikir ayiriliklarinin krize donusmesi; zihinsel adalet arayisi ve ailede esit soz hakki talep eden sarsici bir yuzelesme."),
        9: ("Oklarla dolu bir sadak", "Zihinsel keskinlik! Hedefe kilitlenmis sozler; kelimeleri birbirinizi yaralamak icin degil, ortak engelleri vurmak icin kullanma sinavi."),
        10: ("Burun dalışı yapan bir uçak", "Iletisimde tehlikeli manevralar; buyuk zihinsel riskler alarak ailede korkulan o buyuk yuzelesmeyi cesaretle gerceklestirme."),
        11: ("Yeni açılmış topraklarda sunulan bakir deneyim alanları", "Zihnin sinirlarini genisletme; ailenin yepyeni ufuklara, ortak egitimlere veya daha once hic konusulmamis konulara yelken acmasi."),
        12: ("Siyahi bir köle kızın, hanımından haklarını talep etmesi", "Iletisimdeki gizli dengesizliklerin patlamasi; bir tarafin zihinsel tahakkumune karsi digerinin ozgurluk ve saygi talebiyle ayaklanmasi."),
        13: ("Piyano konseri veren ünlü bir müzisyen", "Entelektuel yeteneklerin kusursuz sergilenisi; fikirlerinizle, vizyonunuzla ve iletisiminizle birbirinize ilham verip hayran birakma hali."),
        14: ("Uzaklarda yaşayan iki insanın telepatik iletişimi", "Mekansal mesafelere veya sessizliklere ragmen, zihinlerin kuantum seviyesinde birbirine baglanarak muazzam bir telepatik aktarim yapmasi."),
        15: ("Kendi aralarında konuşan iki Hollandalı çocuk", "Karmaşık felsefeleri bir kenara birakip, ailenin en saf, en neseli ve sadece sizin anladiginiz o basit ortak dili kurabilme mucizesi."),
        16: ("Duygusal bir konuşma yapan kadın aktivist", "Inanclar ve ortak hedefler ugruna tutkulu bir savunma; ailenin zihinsel enerjisinin dis dunyaya karsi bir kalkana donusmesi."),
        17: ("Gürbüz bir gencin kafasının olgun bir düşünürün kafasına dönüşmesi", "Ailenin zihinsel olarak seviye atlamasi; cocuksu merakin ve fevriligin, deneyimle harmanlanarak derin bir kadersel bilgelige evrilmesi."),
        18: ("Amerikan kalabalığı içinde kendi anadillerinde konuşan iki Çinli", "Dis dunyanin kalabaligi ve gurultusu icinde, sadece sizin cozebildiginiz o gizli zihinsel frekans ve ozel sifrelerle iletisim kurma."),
        19: ("Geleneksel bilgeliği ortaya çıkaran büyük arkaik bir cilt (kitap)", "Ailenin koklerini, gecmisten veya kadim ogretilerden alinan buyuk bir dersle, felsefi bir aydinlanmayla besleme ani."),
        20: ("Çok sayıda seçeneğin bulunduğu bir kafeterya", "Zihinsel daginiklik veya kararsizlik sinavi; bircok fikir veya secenek arasindan ailenin kadersel rotasini ortak bir aklla secebile gucu."),
        21: ("Gürültülü bir işçi gösterisi", "Mantik ve duygularin, haklilik ve haksizligin sert catismasi; ailede birikmis zihinsel basinclarin tahliye edilmesi gereken darboğaz."),
        22: ("Hasat festivalinde dans eden çiftler", "Zihinsel uyumun, uretken fikirlerin ve basarili iletisimin meyvelerini toplama; ailenin neseli ve coskulu bir kutlamaya donusmesi."),
        23: ("Ağacın tepesindeki bir yuvada bulunan üç yavru kuş", "Zihinsel tohumlarin buyumesi; ortak fikirlerin, planlarin veya projelerin henuz kuluçka asamasinda olup sefkatle korunmaya ihtiyac duymasi."),
        24: ("Donmuş köy göletinde buz pateni yapan çocuklar", "Soguk, krizli veya mesafeli donemlerin ustesinden, iletisimdeki kivrak bir zeka, nese ve esneklikle gelebilme yetenegi."),
        25: ("Büyük palmiye ağaçlarını budayan bir bahçıvan", "Ailenin zihinsel dallarini temizleme; gereksiz detaylari, toksik dusunceleri ve gecmis takintilari budayarak ana hedefe (govdeye) odaklanma."),
        26: ("Kış gökyüzüne karşı duran kırağı kaplı ağaçlar", "Duygusal mesafenin veya sessizligin oldugu donemlerde bile, aradaki o saglam zihinsel bagin kristalize olmus o essiz, asil guzelligi."),
        27: ("Kabilesinin kamp kurduğu ormandan çıkan bir çingene", "Zihinsel ozgurluk arayisi; alisilmis dusunce kaliplarindan ve ailenin konfor alanindan cikarak disarida yeni bir felsefe deneme cesareti."),
        28: ("İflas yoluyla toplumun yeniden başlama fırsatı vermesi", "Eski iletisim dilinin veya zihinsel yapilarin tamamen copmesi; bu yikimin ardindan sifirdan, cok daha durust ve guclu bir zihin insasi sansi."),
        29: ("İlkbaharın ilk bülbülü", "Yeniden dogus, neseli haberler ve taze fikirler; aile icindeki iletisimin kistin cikarak bahar coskusuyla ve tatli bir melodiyle canlanmasi."),
        30: ("Denize giren güzellerin geçit töreni", "Zihinsel ve estetik uyumun disariya cesurca sergilenmesi; ailenin sosyal vitrininde ozguvenle, parildayarak boy gosterme enerjisi.")
    },
    "Yengec": {
        1: ("Aboard a ship sailors lower an old flag and raise a new one (Yelkenlide eski bayrağın inip yenisinin çekilmesi)", "Eski aidiyetlerin, ailevi baglarin veya gecmisin sona erip, bu aile iliskisiyle yepyeni bir ortak yuva kimligine dogma cesareti."),
        2: ("Sihirli bir halı üzerinde geniş bir araziyi izleyen adam", "Ailenin, gunluk dunyevi dertlerden soyutlanip, birbirinizin ruhuna ust bir perspektiften ve objektif bir sefkatle bakabilme yetenegi."),
        3: ("Kürklere bürünmüş bir adamın tüylü bir geyiği yönlendirmesi", "En soguk, zor ve krizli zamanlarda bile, cocugunuzun o hassas ruhuna sarsilmaz bir koruyucu kalkan olma icgudusu."),
        4: ("Fareyle tartışan bir kedi", "Ortak yasam aliminda (yuvada) yasanan ufak tefek guc savaslari; duygusal sinirlarin sevgiyle mi yoksa manipulasyonla mi test edileceginin sinavi."),
        5: ("Tren yolunda trenin çarpıp parçaladığı bir otomobil", "Kaderin o durdurulamaz akisina karsi kisisel egoyla inatlasmanin yikiciligi; bu ailede sisteme ve ilahi plana mutlak teslimiyetin sart olmasi."),
        6: ("Yuvalarını tüylendiren oyun kuşları", "Evlilige, ortak yasama ve yuvaya duygusal/maddi yatirim yapma vakti; birbirinizin kalbinde o en guvenli ve sicak koseyi insa etme erdemi."),
        7: ("Ay ışığında dans eden iki doğa ruhu (peri)", "Mantigin bittigi yerde baslayan masalsi, cocuksu ve sihirli duygusal uyum; iliskinin rasyonel dunyadan cikip ruya aleminde sifalanmasi."),
        8: ("İnsan kıyafetleri giymiş bir grup tavşanın geçit töreni", "Dis dunyanin, ailelerin veya toplumun iliskiye dayattigi sahte formlara burunme tehlikesi; yapayliktan kacip oze donme uyarisi."),
        9: ("Gölette balık yakalamaya çalışan küçük, çıplak bir kız çocuğu", "Ailenin en saf, en masum, en savunmasiz anlarina geri donerek o ilk gun heycanini telsizsizca yakalama ve koruma cabasi."),
        10: ("İlk kesim aşamasındaki büyük ve işlenmemiş bir elmas", "Ham ve ilkel sevginin zamanla, krizlerle ve sabirla islentarak paha bicilemez, ebedi bir sadakat pirlantasina donusme sureci."),
        11: ("Ünlüleri taklit eden bir palyaço", "Ailedeki egolari, gerginlikleri ve catismalari muazzam bir mizahla, sefkatli bir alayla yumusatarak yuvaya nese katma yetenegi."),
        12: ("Aurasından reenkarne bir bilge olduğu anlaşılan bebeği emziren kadın", "Birbirinizin o naif, cocuksu yaralarini sararken aslinda cok kadim ve kadersel bir ruhu beslediginizin buyuk, kutsal farkindaligi."),
        13: ("İncelenmek üzere uzatılan, belirgin başparmaklı bir el", "Ailede iradenin, karakterin ve somut eylemlerin maskesiz bir sekilde durustce masaya yatirilmasi ve yuzlesilmesi."),
        14: ("Kuzeydoğudaki karanlık ve dipsiz boşluğa bakan çok yaşlı bir adam", "Bilinmeyene, gelecege ve yasliliga karsi birlikte gelistirilen sarsilmaz bir ruhsal bilgelik; ebediyete el ele yurume cesareti."),
        15: ("Büyük bir ziyafet sonrası lüks bir yemek salonunda dinlenen konuklar", "Ailenin zor gunlerini atlatip maddi/manevi tatminin, doygunlugun ve yuva huzurunun doruguna ulasma; o buyuk ruhsal hasat ani."),
        16: ("Kadim bir kitap yardımıyla önündeki mandalayı inceleyen bir adam", "Aranizdaki bu derin ve karmaşık kadersel yapiyi, yuzeysel aklla degil, evrensel yasalar ve ruhsal bilgelikle cozme arzusu."),
        17: ("Bilgiye ve hayata dönüşen tohum", "Atilan ufacik bir sevgi ve sefkat tohumunun, koklenerek muazzam bir yasam alimina (koca bir aileye) donusmesinin ilahi mujdesi."),
        18: ("Yavrularını beslemek için toprağı eşeleyen bir tavuk", "Aileyi, cocuklari veya ailenin ortak gelecegini korumak icin gosterilen o bitmek bilmeyen, fedakar ve kutsal anaç/emek."),
        19: ("Evlilik töreni yöneten bir rahip", "Ailenin kadersel bir akitle muhurlenmesi; sadakatin sadece dunyevi bir imza degil, ilahi bir onayla ve evrensel bir sozlesmeyle tacilmasi."),
        20: ("Serenat yapan Venedik gondolcuları", "Duygusal dalgalanmalarin, krizlerin ve sularin uzerinde muazzam bir zarafetle, aski kutlama gucu."),
        21: ("Operada hünerini sergileyen ünlü bir şarkıcı", "Birbirinize olan derin sevginizin, fedakarliginizin ve aidiyetinizin doruk noktasini yasama ve bunu dunyada saygin bir durusla sunma."),
        22: ("Yelkenliyi bekleyen genç kadın", "Kadersel partneri, beklenen ruhsal kurtariciyi veya ailenin gelecekteki o huzurlu gunlerini sarsilmaz bir inanc, sadakat ve sabirla bekleme."),
        23: ("Bir edebiyat kulübünün toplantısı", "Sadece duygusal degil, ortak entelektuel degerlerin, kulturel koklerin ve paylasilan ideallerin ailenin yatakini ve catisini guclendirmesi."),
        24: ("Güney denizlerinde küçük bir adada mahsur kalan kadın ve iki erkek", "Ailede kadersel bir izolasyon, kiskanclik testleri veya aidiyetin, sadakatin sinirlarinin en uc noktalarda, krizlerle sinanmasi."),
        25: ("İrade sahibi bir adamın üzerine inen üstün bir gücün gölgesi", "Kisisel egolarin ve inatlasmanin, ailenin ilahi kaderi karsisinda ezilmesi; evrene ve bu aska tam teslimiyete zorlanma."),
        26: ("Lüks bir evin kütüphanesinde okuyan misafirler", "Zengin bir ruhsal ve zihinsel yuvada muazzam bir huzur bulma; tartismalarin yerini ortak bilgeligin ve sessiz bir ahengin almasi."),
        27: ("Lüks evlerin olduğu kanyonda şiddetli fırtına", "Konfor alimini ve yuvayi vuran kadersel kriz! Ailenin sarsilmaz koklerinin, maddi ve manevi olarak dayaniklilik testinden gecmesi."),
        28: ("Beyaz sevgilisini kabilesiyle tanıştıran Kızılderili kız", "Iki farkli kokun, ailenin, gelenegin veya gecmisin tek bir sevgi koprusuyle birlestirilmesi; koklenmenin getirdigi buyuk uyum sinavi."),
        29: ("Yenidoğan ikizleri altın terazide tartan Yunan ilham perisi", "Icsel dualitenin (mantik ve duygu, sen ve ben) aile icinde kusursuz, ilahi ve yorulmaz bir dengeye oturtuldugu o altin muhur."),
        30: ("Amerikan Devrimi'nin kızı", "Koklere, gecmise ve birbirinize duyulan derin onur; ailenin dunyadaki gucunu ve devrimsel torkunu bu sarsilmaz aidiyetten almasi.")
    },
    "Aslan": {
        1: ("Hırslarının dürtüsüyle hayati enerjisi harekete geçen bir adamın başına kan sıçraması", "Ailede egonun ve tutkunun aniden alevlenmesi; ortak bir hedefe kilitlenip durdurulamaz bir gucle eyleme gecme uyanisi."),
        2: ("Bir kabakulak salgını", "Aile icindeki bir krizin veya bulasic bir karamsarligin hizla yayilmasi tehlikesi; toksik enerjileri baskalarina bulastirmadan izole etme sinavi."),
        3: ("Saçlarını omuzlarına dökmüş, gençlik kıyafetleri içindeki orta yaşlı bir kadın", "Ailenin zamana ve yasa meydan okumasi; rutinin sicakligindan sirilip, ilk gunki o taze, isyankar ve ozgur ruhu yeniden kusama."),
        4: ("Av seferinden getirdiği ganimetlerin yanında duran resmi giyimli yaşlı adam", "Ego ve gurur sinavi! Gecmis basarilariyla veya ailenin sosyal statusuyle ovunme; cocugunuzu bir ganimet gibi degil, bir birey gibi gorme uyarisi."),
        5: ("Derin bir kanyonun üzerinde yükselen heybetli kaya oluşumları", "Sarsilmazlik muhuru! Ailenizin, etrafindaki zamanin yipratciligina ve derin krizlere ragmen dimdik, asil ve yikilmaz bir kule gibi durmasi."),
        6: ("Eski moda, muhafazakar bir kadının, günümüzün modern bir kızıyla yüzleşmesi", "Gecmisin koklu degerleri ile gelecegin ozgurlesme arzusunun carpismasi; ailede eski tabulari sevgilerek modern bir ortak dil bulma."),
        7: ("Gece gökyüzünde ışıl ışıl parlayan takımyıldızlar", "Ruhlarinizin en karanlik zamanlarda bile evrensel bir rehberlikle korundugunu ve ailenizin ilahi bir plana hizmet ettigini idrak etme."),
        8: ("Devrimci ideallerini yayan bir aktivist", "Ailede bir seyleri kokeninden degistirme ve yeniden insa etme tutkusu; ancak bu isyanin cocugu yikmak icin degil, bagi ozgurlestirmek icin yapilmasi gerekliligi."),
        9: ("Nefesleriyle parlayan cama şekil veren cam üfleyicileri", "Karmik simya! Birbirinizin ruhuna dokunarak, baslangicta ham olan bu bagi muazzam bir estetige ve kalici bir esere donusturme ustaligi."),
        10: ("Güneş ışığı tarlayı doldururken parlayan sabah çiy damlaları", "Karanlik bir donemin ardindan gelen taptaze bir ruhsal uyanis; ailenin her sabah yeniden, umutla ve ilahi bir iyimserlikle yikanmasi."),
        11: ("Devasa bir meşe ağacının dallarından sarkan salıncakta sallanan çocuklar", "Cok koklu, korunakli ve sarsilmaz bir guvenin golgesinde; ailenin en masum, eglenceli ve cocuksu tarafini korkusuzca yasama lutfu."),
        12: ("Süslü fenerlerle aydınlatılmış bir çimenlikte yetişkinlerin akşam partisi", "Ailenin sosyal vitrinda parilama zamani; gururla, estetikle ve dis dunyanin da onaylayip hayran kalacagi bir uyumla sahneye cikma."),
        13: ("Kulübesinin verandasında sallanan yaşlı bir deniz kaptanı", "Buyuk firtinalari, krizleri ve tork testlerini atlatmis bir ailenin, artik deneyim ve bilgelikle gecmise gulumsedigi o huzurlu demlenme ani."),
        14: ("Dışavurum fırsatları arayan bir insan ruhu", "Sadece kalplerde gizli kalan sevginin artik somut dunyada bir esere, bir aile yasamina veya kalici bir ortak yaratima donusme ihtiyacinin patlamasi."),
        15: ("Tezahürat yapan kalabalık bir caddede ilerleyen görkemli bir geçit töreni", "Ailenin kendi kralligini ilan etmesi; gosterisli, cesur ve cevreden yuksek onay alan asil bir kadersel zirve noktasi."),
        16: ("Fırtına dindiğinde, doğanın parlak güneş ışığı altında sevinci", "Cok agir bir krizin veya guc savasinin ardindan gelen muazzam rahatlama; gozyaslarinin yerini yikanmis, tertemiz bir aska birakmasi."),
        17: ("Dini ilahiler söyleyen gönüllü bir kilise korosu", "Farkli seslerin (egolarin) tek bir yukse amac ugruna uyumlanmasi; ailenin dunyevi boyuttan cikip ruhsal bir adanmislikla butunlesmesi."),
        18: ("Öğrencileri için deney yapan bir kimyager", "Ailenin matematigini ve kimyasini cozme zamani! Formullerin, elementlerin ve duygularin nasil reaksiyon verdigini deneyimleyerek ustalasma."),
        19: ("Bir tekne partisi (yüzen ev)", "Bagliligi bir pranga olarak degil, birlikte seyredilen eglenceli ve ozgur bir yolculuk olarak gorme; ailenin sinirlarini esnetip neyseye odaklanma."),
        20: ("Güneş ritüeli yapan Zuni Kızılderilileri", "Varliginizin ve bu muazzam ailenin kaynagina derin sukran duyma; egoyu sifirlayip ilahi guce saygiyla baglanma."),
        21: ("Uçmaya çalışırken başları dönen ve kanat çırpan sarhoş tavuklar", "Ailede kapasitenin otesinde, gercek disi beklentilere veya abartili egolara kapilma uyarisi; ucmaya calisirken komik veya krizli durumlara dusme riski."),
        22: ("Görevini yerine getiren bir posta güvercini", "Sadakatin muhuru! En zor sartlarda bile birbirinize verdiginiz kadersel sozu tutma ve sevginin kutsal mesajini hedefine ulastirma erdemi."),
        23: ("Sirkte eyersiz ata binen bir binicinin heyecanlı kalabalığı büyülemesi", "Ailenin tehlikeli, riskli ama bir o kadar da hipnotik tork gucu; engelleri ve kurallari hic sayarak cesaretle basarma."),
        24: ("Fiziksel görünümünü tamamen ihmal edip ruhsal aydınlanmaya odaklanmış bir adam", "Dis dunyadaki gosterisin, egonun ve estetigin anlamini yitirip; ailenin tamamen bilincalti, mistik ve yeralti simyasina odaklanmasi."),
        25: ("Uçsuz bucaksız ve acımasız bir çölü geçen büyük bir deve", "Muazzam bir Tork ve Dayaniklilik testi! Ailenin kurak ve krizli sureclerinde, icsel su (sevgi) rezervlerinizi kullanarak sabirla ve inatla hedefe yurume."),
        26: ("Ağır bir fırtınanın ardından beliren gökkuşağı", "Kadersel bir soz! Cekilen acilarin ve dokulen gozyaslarinin ardindan evrenin ailenize sundugu o ilahi umut, onarim ve sifa koprusu."),
        27: ("Doğu gökyüzünde şafağın parıltısı", "Karanlik bir donemin sonsuza dek kapanmasi; bu aileyle birlikte ruhun yeni bir bilince, umuda ve gunese (uyanisa) gozlerini acmasi."),
        28: ("Büyük bir ağacın dalında cıvıldayan birçok küçük kuş", "Ortak cevrenin, dostluklarin ve ufak neselerin aileyi beslemesi; agir dramalardan uzaklasip basit, eglenceli ve hareketli bir iletisime gecis."),
        29: ("İnsan formunda yeniden doğmak üzere okyanus dalgalarından çıkan deniz kızı", "Buyuk Simyasal Evrim! Bilincsiz duygularin, kiskancliklarin geride birakilip, ailenin tam idrak sahibi, olgun ve somut bir yapiya donusmesi."),
        30: ("Mührü açılmış (mühürsüz) bir mektup", "Mutlak seffaflik! Sirlarin, maskelerin ve gizli ajandalarin tamamen ortadan kalktigi; kalplerin birbirine durustce, sansurzce okunmaya acildigi ozgur bir faz.")
    },
    "Basak": {
        1: ("Bir adamın başındaki hayvan postu", "Kendi ilkel, hayvansi durstulerini veya ham enerjini; disiplin, calisma ve pratik zeka ile ehillestirip ust bir formda kullanma yetenegi."),
        2: ("Geniş bir düzlükte yer alan, beyaz bir haç", "Ailedeki fedakarligin ve hizmetin bir yuk degil, ailenin kalici huzurunu (kutsal yonunu) ayakta tutan temel sutun oldugunu fark etme."),
        3: ("İki melek yardıma hazır", "Birlikte en cok tikandiginiz, kusursuzlastirmaya calistiginiz kriz anlarinda; evrenin size pratik bir cozumle, sezgisel bir yardimla kapi acmasi."),
        4: ("Genç bir adamın hayal gücü, gerçek bir boyuta dönüşüyor", "Ailededki hayallerin ve fikirlerin; calisma, detaylara odaklanma ve pratik adimlarla somut bir esere (yuvaya/basariya) donusmesi."),
        5: ("Bir adamın elinde rüya dolu bir peri masalı kitabı", "Gundelik hayatin pratikliginde kaybolurken, askin o masalsi ve ilahi kokununu (Peri masali) unutmadan yasama sanati."),
        6: ("Süslemelerle dolu bir dans salonu", "Detaylarda estetik; ailenin gundelik duzenini kurarken, bu duzeni adeta bir sanat eseri veya bir dans gibi ozenle, kusursuzca yonetme basarisi."),
        7: ("İki kadeh şarapla dolu bir masa", "Gundelik hayatin pratik kosturmacasinda, durup birbirinize ayirdiginiz o kucuk ama nitelikli paylasim anlarinin kadersel degeri."),
        8: ("Bir kız, evcil kuşları besliyor", "Ailedeki kucuk, savunmasiz ve ilgiye muhtac olan (cocuksu tarafiniz, zayif yanlariniz) parcalarin sefkatle ve duzenli beslenip korunmasi."),
        9: ("Kendi kendini boyayan bir ressam", "Aileyi ve kendinizi disaridan bir gozle, adeta bir sanatci titizligiyle gozleyip; hatalari aninda revize ederek kusursuzluga ulasma cabasi."),
        10: ("İki başlı bir adam, hayata bakıyor", "Mantik ve sezgiyi ayni anda kullanma; hem pratik islere hem de ailenin gelecekteki ruhsal ihtiyaclarina ayni anda odaklanabilme yetisi."),
        11: ("Yeni bir günün doğuşuyla parlayan, el değmemiş bir vadi", "Ailedeki eski krizlerin ve hatalarin, Basak'in analitik temizligiyle yok olmasi; her sabah taptaze bir baslangic yapma temizligi."),
        12: ("Hazinesini arayan bir adam", "Ailenin gundelik isleri (ev, is, rutin) icinde, aslinda aradiginiz buyuk kadersel hazinenin (ruhsal olgunluk) sakli oldugunu fark etme."),
        13: ("Halkın önünde konuşan devlet adamı", "Ailenin duzenini, kurallarini veya vizyonunu dis dunyaya karsi temsil etme; bir sistem/ekol gibi disiplinli ve saygin bir aile yasami."),
        14: ("Fotoğrafı çekilen bir aile albümü", "Zamanin akisina karsi durus; ailenin her evresini, hatirasini ve dersini bir disiplinle kayda alip gelecege bir yasanmislik mirasi olarak tasma."),
        15: ("Oyuncak bebeklerle oynayan bir kız çocuğu", "Ailedeki sorumluluklari, rolleri ve krizleri, bir oyun ciddiyetiyle; yargilamadan, suclamadan, adeta bir simulasyon gibi deneyimleyerek cozme."),
        16: ("Volkanik patlamanın ardından oluşan verimli topraklar", "En buyuk krizlerin (patlama), aslinda Basak'in analiz gucuyle islendiginde ailenizi gelecekte besleyecek en bereketli topraklari (tecrube) olusturmasi."),
        17: ("Halkı için dua eden bir din adamı", "Ailedeki gundelik hizmetin bir ibadete donusmesi; birbirinizin eksiklerini kapatmanin veya duzeni kurmanin, aslinda birbirinizin ruhunu kutsamak oldugu bilinci."),
        18: ("Büyük bir kütüphanede çalışan araştırmacı", "Ailenin kadersel kodlarini cozme arzusu; birbirinizin gecmisini, psikolojisini ve bu ailenin neden var oldugunu bilimsel/analitik bir titizlikle arastirma."),
        19: ("Çiçek açmış bir nar ağacı", "Pratik ve sade gorunumun altinda, cok sayida bereketli tohumun ve hayat enerjisinin sakli oldugu; ailenin potansiyelinin tasmasi."),
        20: ("Tarlasında hasat yapan bir köylü", "Emek verilen, planlanan ve ilmek ilmek islentigi her turlu kadersel calismanin, tam vaktinde ve bollukla karsiligini alma gunu."),
        21: ("Kızlar basketbol takımı", "Ortak bir hedef ugruna koordineli calisma; herkesin kendi rolunu kusursuz yaptigi, ego catismasi olmayan, tikir tikir isleyen bir ekip olma hali."),
        22: ("Kraliyet armasını taşıyan bir kraliyet muhafızı", "Sarsilmaz sadakat ve sistem koruyuculugu; ailenin degerlerini, duzenini ve ozel dunyasini dis tehlikelere karsi celik bir disiplinle muhafaza etme."),
        23: ("Bir hayvanat bahçesinde kafes temizleyen bir adam", "Ailedeki vahsi, kontrolsuz veya hayvansi icgudulerin; titiz bir temizlik ve disiplinle, sisteme zarar vermeyecek sekilde evcillestirilmesi."),
        24: ("Büyük bir sarayın kapısında bekleyen gardiyan", "Ailenin Kutsal Yuva'ya giris ve cikislarini kontrol etme; kimlerin (veya hangi enerjilerin) bu alana dahil olup olmayacagi konusunda katı ve guvenli sinirlar."),
        25: ("Bahçesindeki otları temizleyen bir adam", "Ailenin ruhsal topraklarini yabani otlardan (toksik dusunceler, vesveseler) arindirma; bagi sadece saf ve islevsel olanla besleme."),
        26: ("Bir ağaca asılı, henüz olgunlaşmamış meyveler", "Ailenin planlarinin veya hayallerinin henuz zamaninin gelmedigi; acele etmeden, sabirla ve duzenli olgunlasmasini (hasadini) bekleme disiplini."),
        27: ("Güneş ışığıyla parlayan bir çaydanlık", "Ailenin gundelik rutinini (cay/rituel) kutsallastirma; siradan bir cay anini bile muazzam bir huzur ve sifa anina dondurusturme ustaligi."),
        28: ("Kel başını öne eğmiş bir keşiş", "Ailede egonun tamamen geri cekilmesi; zihinsel kibrin yerini, sessiz bir hizmetin ve derin bir tevazunun almasi."),
        29: ("Gizli bir kapıdan çıkan bir insan", "Ailedeki sorunlari, krizleri ve tikanikliklari, kimsenin fark etmedigi pratik, dahice ve gizli bir cikis yoluyla (yontemle) asabilme."),
        30: ("Gökyüzünü süpüren bir yıldız süpürgesi", "Ailenin kadersel arinmasi! Artik Basak'in detayci disiplini, gokyuzundeki kadersel tozlari ve karmik tortulari bile temizleyerek, bagi kristal kadar berrak bir hale getirmistir.")
    },
    "Terazi": {
        1: ("Bir kelebek kanadının üzerinde, üzerinde bir ok olan bir ok işareti", "Ailedeki duygusal veya zihinsel yonelimin (ok) belirlenmesi; aranizdaki etkilesimin hangi kadersel hedefe dogru ustu oldugunu idrak etme."),
        2: ("Bir adamın elinde bulunan altı parıltılı ışık küresi", "Ailenin yasamin temel guclerini (isik kurelerini) dengede tutma ve bu gucleri ortak bir estetikle yonetebilme yetisi."),
        3: ("Şafak vakti ormanda yeni doğan bir gün", "Gecmisin tum agirliklarini silen taze bir baslangic; ailenin her yeni gune, temiz bir sayfayla ve umutla baslama disiplini."),
        4: ("Bir gruptan ayrılarak kendi yoluna giden bir adam", "Ailede biz olurken bireysel ozgurlugunu ve ozgun karakterini koruyabilme; bagimli degil, bagli olma sanati."),
        5: ("İçinde bir içki kadehi olan parlak bir halka", "Birlikteligin getirdigi o kutsal, icsel butunluk; birbirinizi tamamlanmis bir halka gibi sarip sarmalama ve bu bagin tadini cikarma."),
        6: ("İçinde bir adamın figürü olan küçük bir heykel", "Birbirinizin hayatinda kalici, asil ve estetik bir iz birakma; ailenin dunyada somut bir sanat eseri gibi hatirlanmasi."),
        7: ("Fırtına öncesi sessizce duran bir gökyüzü", "Krizlerden onceki o kritik, sessiz ve dingin gozlem ani; yaklasan kadersel degisimi, tartismadan, sadece sezgisel olarak hissedip onlem alma."),
        8: ("Bir şöminenin başında ısınan bir grup insan", "En soguk krizlerde bile ailenin ic sicakligini, guvenini ve yuva olma ozelligini, birbirinizin varligiyla diri tutma yetenegi."),
        9: ("Üç usta sanatçı kendi atölyelerinde çalışıyor", "Ailenin ortak vizyonu icin her iki tarafin da kendi yeteneklerini, zekasini ve emegini bagimsizca ama uyum icinde uretmesi."),
        10: ("Kano yapan bir grup insan", "Ailenin akisinda, herkesin ayni ritimle kurek cekmesi; catismalari dindirip, tek bir kadersel yone dogru (hedefe) senkronize hareket etme."),
        11: ("Gözlerinde bir ışık olan bir adam", "Icsel aydinlanma! Ailedeki sorunlari, karsidakinin niyetini ve evrensel mesaji, gorunur olandan cok daha derin bir vizyonla gorme."),
        12: ("Madenden yeni çıkarılmış bir elmas", "Ailenin ham ve islenmemis potansiyelinin, zorluklarla parlatilarak gercek, paha bicilemez ve dayanikli bir deger haline gelmesi."),
        13: ("Şapkasını çıkarmış, güneşin altında duran bir adam", "Egolarin tamamen aradan cekilmesi; birbirinize ve kadersel rotaniza karsi o derin, maskesiz ve tevazulu teslimiyet."),
        14: ("Gökyüzünde birbirine doğru koşan iki melek", "Ailenin ilahi bir el tarafindan desteklendigi o anlar; krizlerin, tesaduf gibi gorunen mucizevi yardimlarla cozume kavusmasi."),
        15: ("Bir yuvada toplanmış olan kuş yavruları", "Ailenin en savunmasiz, en cocuksu ve en korunmaya muhtac oldugu o evre; birbirinizin icindeki cocugu sarmalayip guvenle buyutme."),
        16: ("Bir adamın elinde tuttuğu bir pusula", "Ailenin kadersel rotasini sapmadan, evrensel pusulaya (vicdan ve hakikat) uygun sekilde cizme becerisi."),
        17: ("Sık ağaçlıklı bir ormanda kaybolmuş bir adam", "Ailede karmaşa ve belirsizlik donemi! Dis dunyadan (baskalarinin fikirlerinden) etkilenip kendi kadersel merkezinden sapma riski."),
        18: ("Eski bir kalenin surlarına asılı boş bir zırh", "Gecmisin savunma mekanizmalarinin artik gereksizlesmesi; birbirinize karsi savunmasiz (maskesiz) kalabilme cesareti."),
        19: ("Bir grup insan bir sanat eserini inceliyor", "Ailenin disariya nasil gorunugune dair farkindalik; ailenin degerini, estetigini ve basarisini objektif bir sekilde degerlendirme."),
        20: ("Tüm çiçeklerin açtığı bir mevsim", "Ailede yaraticiligin, askin ve paylasimin zirvesi; her seyin tikir tikir isledigi, guzelliklerin ve bereketin tasma noktasi."),
        21: ("Bir fırtınanın ortasında dimdik duran bir çam ağacı", "En sarsici dissal etkilerde bile, birbirinize olan baginizin esnemesi ama asla kirilmamasi; koklerinizin sarsilmaz gucu."),
        22: ("Bir tepenin zirvesinde yanan kutsal bir ateş", "Ailenin kadersel amacinin, herkesin gorebilecegi kadar net ve yuksek olmasi; ortak bir inanciyla dunyayi isitma gucu."),
        23: ("Bir aynada kendini izleyen bir kedi", "Ailedeki ben ve sen ayriminin netlesmesi; cocugunuzun gozlerinde kendi kusurlarinizi ve guzelliklerinizi gorebilme farkindaligi."),
        24: ("Bir adamın elinde bulunan eski bir anahtar", "Ailenin kilitli olan tum kadersel kapilarini acacak o cok ozel, kadim bilgelige veya yonteme erisme."),
        25: ("Gökyüzünde süzülen bir kartal", "Ailenin dunyevi dertlerin cok uzerine cikmasi; perspektif, uzak gorusluluk ve kadersel butunlugu yukaridan bir tanrisal bakisla gorme."),
        26: ("Bir kartalın pençelerinde bir yılan", "Krizin, manipulasyonun veya korkunun (yilan), ailenin en yuksek vizyonu (kartal) tarafindan etkisiz hale getirilip sifaya donusturulmesi."),
        27: ("Bir bahçede oynayan çocukların kahkahaları", "Ciddiyetin ve sorumluluklarin arasinda, ailenin o en saf, en neseli ve cocuksu neesesini koruma zorunlulugu; mutluluk bir secimdir."),
        28: ("Bir adamın büyük bir titizlikle kütüphane raflarını düzenlemesi", "Ailenin gecmisini, anilarini ve ogrendigi dersleri zihinsel bir duzene oturtma; hatiralarin birikim (bilgelik) olarak tutulmasi."),
        29: ("Güneşin batışında yanan ufuk çizgisi", "Bir devrin kapanisi! Artik ailenin bir asamasinin bitip, yeni ve bambaaska bir seviyeye gecmeden onceki o buyuleyici gecis araligi."),
        30: ("Dünya sahnesinde rolünü oynayan bir oyuncu", "Ailenin evrensel tiyatrodaki kadersel gorevi; herkesin bir roluu oldugu gibi, sizin ailenizin de dunyada temsil ettigi o ilahi mesaji durustce oynama.")
    },
    "Akrep": {
        1: ("Gece yarısı gökyüzünde parlayan, gözetleyen bir göz", "Ailenin her aninin evrensel bir gozlem altinda oldugu; sadakatin ve niyetin en derin katmanlarda test edildigi o uyanik durus."),
        2: ("Kırık bir şişeden sızan esansın kokusu", "Gecmisten gelen bir aci veya bastirilmis bir duyguyun serbest kalarak ailenin havasini tamamen degistirmesi; sifalanma surecinin baslangici."),
        3: ("Evcilleştirilmeye çalışılan vahşi bir ev kedisi", "Ailedeki asi, kontrol edilemez ve ozgur ruhlu yanlarin; sefkatle ve sabirla yuvaya/sisteme dahil edilme sinavi."),
        4: ("Bir mum ışığında elindeki kağıtları okuyan genç bir adam", "Ailenin kadersel kontratlarini, gizli niyetlerini ve birbirinizin ruhsal haritasini, o karanlikta bile net bir sekilde okuma/anlama yetenegi."),
        5: ("Kendi kendine yeten, izole bir kaya üzerindeki denizanası", "Kriz anlarinda bile disaridan destek almadan, ailenin kendi icsel dayanikliligiyla ve kendi kendine yetebilme gucuyle ayakta kalmasi."),
        6: ("Altın bir madeninde çalışan işçiler", "Ailenin zorluklarini (topragi) kazarak, birbirinizin karakterindeki o sakli, paha bicilemez ve asil hazineleri (altinlari) gun yuzune cikarma cabasi."),
        7: ("Derin gölün üzerindeki bir dalgıç", "Duygularin o karanlik ve tekinsiz derinliklerine korkusuzca dalip, orada saklanan kadersel gizemleri (veya yaralari) birbiriniz icin gun yuzune cikarma."),
        8: ("Ay'ın ışığını yansıtan bir göl", "Ailenin, dogrudan gunesin parlakligiyla degil, geceye ozgu o yumusak, mistik ve sezgisel bir bilgelikle aydinlanmasi; ruhlarin gece konusmasi."),
        9: ("Kendi yansımasını hayranlıkla izleyen bir zürafa", "Ailedeki ben ve biz arasindaki o ince cizgi; cocugunuzun gozlerinde kendi ruhunuzun guzelligini degil, kendi eksikliklerinizi de gorebilme cesareti."),
        10: ("Büyük bir kaza sonrasında kurtarılan bir grup insan", "Buyuk kadersel krizlerden sag kalma mucizesi; ailenin yikilacak gibi oldugu en karanlik anlarda bile ilahi bir elle kurtarilma."),
        11: ("Bir fırtına sonrasında ağacın dalında bekleyen bir kuş", "Krizli ve firtinali sureclerden sonra gelen o mutlak sessizlik; korkunun yerini alan, artik guvende oldugunuz o huzurlu bekleme ani."),
        12: ("Büyük bir kütüphanede yasaklı kitapları arayan bir öğrenci", "Ailenin tabu olan, konusulmayan veya derinlerde saklanan o yasak duygularini cesaretle ortaya cikarip yuzlesme arzusu."),
        13: ("Fırtınada limana sığınan dev bir gemi", "Dis dunyanin krizleri ve toplumsal baskilar karsisinda, ailenin kendi icindeki o sarsilmaz ve guvenli limana (birbirinize) siginip korunma gucu."),
        14: ("Bir insanın içindeki derin tutku ormanları", "Ailenin o tarif edilemez, kontrol edilemez ve vahsi tutku enerjisi; bu atesi birbirinizi yakmak yerine birlikte dunyayi fethetmek icin kullanma."),
        15: ("Yeniden doğuşu kutlayan bir kabile", "Buyuk bir yikimin veya ayrilik korkusunun ardindan, ailenin kulnerinden cok daha guclu, bilge ve muhururlu bir sekilde yeniden dogmasi."),
        16: ("Bir çayırda kendi başına dans eden bir kız", "Ailede, cocugunuzun dunyasindan bagimsiz olarak kendi ruhsal neesenizi koruyabilme; askta bagimsiz ama birlesik kalabilme becerisi."),
        17: ("Kendi kendini arayan bir sanatçı", "Ailede cocugunuzu bir ayna olarak kullanip, aslinda kendi ruhunuzdaki eksik parcalari tamamlayarak butunlesme yolculugu."),
        18: ("Sessizce akan bir nehrin üzerindeki köprü", "Duygusal gecisler! Krizli sulardan, sarsilmaz bir mantik ve diplomasi koprusu kurarak birbirinize ulasabilme."),
        19: ("Kendi gölgesiyle konuşan bir adam", "Ailede cocugunuzun size yansittigi karinlak yanlari yargilamadan, onlari kendi golgenizle barismanin bir araci olarak kullanma."),
        20: ("Törenle yakılan eski bir tapınak", "Eski inanclarin, bitmis bir yasantinin veya gecmis bir kadersel dongunun, ailenin selameti icin buyuk bir rituelle atese verilip kule donusturulmesi."),
        21: ("Kendi iç dünyasında dev bir şehir kuran bir mimar", "Ailenin disariya degil, birbirinizin ruhunun o ucsuz bucaksiz, devasa ve zengin dunyasina kurduugunuz o gorkemli ortak yuva."),
        22: ("Alevlerin içinden çıkan anka kuşu", "Mutlak yikim ve dirilis! Ailenin tamamen bittigi denilen noktasinda, bir mucizeyle tum acilarin sifaya donusup cok daha yuce bir formda canlanmasi."),
        23: ("Bir tarlada yatan ölü bir karga", "Artik islevi bitmis olan korkularin, suphelerin veya eski kara dusuncelerin (karga) ailenizden sonsuza dek uzaklasmasi, arinma."),
        24: ("Bir adamın elinde tuttuğu, parıldayan kutsal bir kadeh", "Ailenin o en zorlu krizlerinden suzulup elde edilen ruhsal iksir; mutlak sadakat ve askla icilen o kadersel yasam sifasi."),
        25: ("İki kutup arasında gidip gelen bir el feneri", "Duygusal uc noktalarda (sevgi ve ofke) gidip gelme; ancak her ne olursa olsun, bir el feneri gibi birbirinizin yolunu aydinlatma gayesi."),
        26: ("Bir uçurumun kenarında dimdik duran bir dağcı", "Ailenin en uc, en tehlikeli ve en krizli noktasinda bile, dusmeden, sapmadan, o asil ve sarsilmaz dengede durabilme ustaligi."),
        27: ("Gecenin karanlığını yırtan bir şimşek", "Ailedeki o cok gizli, cok sakli kalan kadersel bir gercegin; beklenmedik, sarsici ve aydinlatici bir olayla tum berrakligiyla ortaya cikmasi."),
        28: ("Bir nehirde kendi kendine kaynayan sular", "Ailenin derinlerinde biriken ofkenin veya tutkunun, disaridan fark edilmeden iceride fokur fokur kaynamasi; patlamadan once sifalandirma ihtiyaci."),
        29: ("Güneşin doğuşunu bekleyen bir grup insan", "En karanlik kadersel dongunun sonuna gelindigi; birbirinize olan inanciyla, yeni ve aydinlik bir donemin baslamasini sabirla bekleme."),
        30: ("Mükemmel bir şekilde dengelenmiş bir terazinin iki kefesi", "Akrep'in o ucsuz bucaksiz krizli derinliginden, artik mutlak bir ruhsal dengeye ve hakikate ulasiligi o son kadersel durak.")
    },
    "Yay": {
        1: ("Gece gökyüzünde parlayan sönük bir yıldızın aniden patlayarak nova'ya dönüşmesi", "Ailede uzun suredir durgun olan bir potansiyelin veya vizyonun, aniden patlayarak tum hayatini aydinlatan kadersel bir rehbere donusmesi."),
        2: ("Sıcak bir ocağın başında, elleriyle yüzünü ısıtan bir beyaz rahibe", "Ailenin en krizli, soguk ve belirsiz anlarinda bile; sarsilmaz bir inanciyla, kendi ruhsal isini cocugunuzun varliginda bulma mucizesi."),
        3: ("İki insan, yeni bir ülkeye ilk adımı atıyor", "Ailede kesfedilmemis yepyeni bir boyuta gecis; ezberlerin bozulup, sinirlarin asildigi o ilk, cesur kadersel kesif adimi."),
        4: ("Uzak bir ülkede, kendi geleneklerini sürdüren bir göçmen", "Ailenin dis cevreye, topluma veya standartlara uyum saglamaya calisirken, aslinda kendi koklerine ve ozgun felsefesine tutunma cabasi."),
        5: ("Kendi içsel ışığını takip eden bir bilge", "Dis dunyanin ne dedigine bakmadan, ailenin kadersel rotasini sadece aranizdaki o ortak, ilahi rehberlige (inanca) guvenerek cizme."),
        6: ("Eski bir kilisenin kapısında dilenen bir adam", "Ailedeki inanc ve sukur sinavi; elinizde olanin degerini bilmeyip surekli eksikliklere odaklanma tuzaqindan kurtulma ihtiyaci."),
        7: ("Deniz kıyısında, devasa okyanusa bakan bir adam", "Ailenin sahip oldugu o devasa, ucsuz bucaksiz kadersel potansiyeli idrak etme; kucuk sorunlari, okyanusun buyuklugu icinde eritme."),
        8: ("Bir taşın üzerine oyulmuş, silinmeye yüz tutmuş bir yazı", "Gecmisten gelen bir kadersel uyarinin veya kadim bir ogretinin, ailenizin rotasini degistirecek bir mesajla tekrar hatirlanmasi."),
        9: ("Dünyayı gezen bir grup öğrenci", "Ailenin hayati bir ogrenim alimi olarak gormesi; birlikte dunyayi gezmek, kitaplar okumak veya felsefi bir yolculuga cikmak en buyuk ortak baginizdir."),
        10: ("Eski bir tiyatro sahnesinde prova yapan oyuncular", "Ailenin yasam sahnesinde surekli bir gelisim ve prova halinde olmasi; hatalari dert etmeden, hayati bir nese ve ustalikla sahneleme."),
        11: ("Işıklı bir fenerin, denizde yol gösterdiği bir gemi", "Karanlik, belirsiz ve firtinali kadersel sureclerinde, birbirinizin vizyonuyla yolunuzu bulma; askin bir pusula gibi netlesmesi."),
        12: ("Bayrağın üzerinde parlayan altın bir güneş", "Ailenin basarisinin ve gucunun, tamamen o ortak inanca ve ilahi vizyona adanmisliktan gelmesi; isikla muhurlenmis zafer."),
        13: ("Huzur içinde uyuyan bir aslanın başını okşayan bir çocuk", "Ailedeki en guclu, vahsi ve kontrolsuz taraflarin (Aslan), sefkatle (cocuk) ehillestirilip sevgiyle terbiye edilmesi."),
        14: ("Gökyüzünde asılı kalmış, devasa bir piramit", "Ailenin ilahi bir duzene, kadim bir geometriye sahip olmasi; tesaduflerin otesinde, planli ve kadersel bir yapi uzerine kurulusu."),
        15: ("Toprağa tohum eken bir çiftçi", "Su an ailenin gordugu zorluklarin aslinda gelecekteki buyuk hasadin (huzurun/basarinin) hazirligi oldugu bilinci; sabirla ekmek."),
        16: ("Denizlerin üzerinde yükselen, ışık saçan bir şehir", "Ailenin gerceklikten kopuk, hayali ve idealist bir utopya kurma cabasi; bu hayalleri yere indirip nasil yasanabilir kilacaginizin sinavi."),
        17: ("Kendi içinde dönüp duran bir derviş", "Ailenin dis dunyadaki kargasadan sirilip, sadece kendi ic ritmi ve ortak meditasyonlari ile huzur bulma; askin bir ibadete donusmesi."),
        18: ("Savaş meydanında, kılıcını bırakıp dua eden bir şövalye", "Hakli olma savasini birakma! Ailenin en siddetli krizlerinde bile, silahlari (egoyu/elestiriyi) yere birakip birlige donme bilgeligi."),
        19: ("Yüksek bir dağın zirvesinden dünyayı izlemek", "Ailenin gunluk sorunlara, basit tartismalara ve kiskancliklara, sanki bir dag zirvesinden bakiyormus gibi mesafeli, bilge ve huzurlu bir bakis atmasi."),
        20: ("Gökyüzüne yükselen bir füze", "Ailenin dunyevi kisitlamalardan tamamen kurtulup, hizla ve buyuk bir Tork ile, hayalleri gerceklestirmek uzere yuksek bir kadersel boyuta sicramasi."),
        21: ("Kendi kendine yeten bir keşiş", "Ailede bagimliliktan kurtulup, herkesin kendi manevi merkezini korudugu; ancak birbirinin ruhunu zenginlestirdigi o asil beraberlik."),
        22: ("Bir çayırda oynayan bebekler", "Ailenin en saf, en cikarsiz, en neseli ve sadece var olmanin tadini cikaran o ilk kadersel evresi; sevginin en yalini hali."),
        23: ("Bir gölün üzerinde süzülen bir kuğu", "Zarafetin, asaletin ve sevginin duru guzelligi; krizli anlarda bile, ailenin kendi asil durusunu ve estetigini asla bozmamasi."),
        24: ("Büyük bir kütüphanede tozlu rafları karıştıran bir adam", "Ailenin eksik kalan kadersel bilgilerini, gecmisin tozlu hatiralarinda veya kadim bir ogretide arayip bulma zorunlulugu."),
        25: ("Yükseklerden düşen bir yıldız", "Beklenmedik bir ilahi mudahale; ailenin gidisatini tek bir anda degistiren, mucizevi ve kaderi yeniden yazan o goksel isaret."),
        26: ("Bir fırtınada bayrağını dik tutan bir asker", "Kriz ne kadar buyuk olursa olsun, ailenin ana hedefine, degerlerine ve birbirinize olan baglidlaga sadik kalma yemini."),
        27: ("Bir sanatçının kendi eserini beğenmeyip parçalaması", "Mukemmeliyetcilik sinavi! Ailedeki bazi seyleri veya bazi yonlerinizi, daha iyisini kurmak icin tamamen yikip sifirdan yapma cesareti."),
        28: ("Bir bahçede açan, kışın bile solmayan kırmızı güller", "Ailenin en imkansiz sartlarda, en krizli mevsimlerde bile o kirmizi (tutku ve ask) rengini koruyup yasamaya devam etmesi."),
        29: ("Ufukta batarken denizi yutan güneş", "Bir kadersel evrenin kapanisi; ailenin bildiginiz tum formlarinin, yeni ve cok daha parlak bir safak oncesi karinliga gomulmesi."),
        30: ("Gökyüzünde el ele tutuşan, melek gibi iki insan", "Kadersel Muhur! Iki ruhun, dunyevi rollerini bitirip, artik tamamen ilahi bir kontratla, zamansiz ve mekan disi bir askla ebediyen birlesmesi.")
    },
    "Oglak": {
        1: ("Hintli bir şef, kendi kabilesini yönetiyor", "Ailenin kendi icinde hiyerarsik bir duzen kurmasi; ortak yasamin sorumluluklarini, rollerini ve sinirlarini asil bir otoriteyle yonetme becerisi."),
        2: ("Üç gül penceresi, biri parçalanmış", "Ailenin mukemmeliyetci yapisinda bir catlak veya noksanlik! Bu kusurun, ailenin daha fazla disariya isik sizdirmasina izin vermesi."),
        3: ("İnsan ruhunun, yeni deneyimler için fiziksel bedenini terk etmesi", "Ailenin dunyevi kisitlamalardan, maddi yuklerden ve kati sorumluluklardan sirilip, sadece ruhun yukse amaclari icin birlestigi o yukselmis faz."),
        4: ("Grup kutlaması içinde, kendi dünyasında dans eden bir adam", "Ailede sosyal sorumluluklari (toplum/aile) yerine getirirken, aslinda ruhsal olarak kendi kadersel merkezine ve cocuguna sadik kalabilme."),
        5: ("Kano yapan yerliler", "Hayatin o sert ve hizli akan krizli sularinda, ailenin ritmini kaybetmeden, birbirinize olan guvenle hedefe dogru ilerleme."),
        6: ("Kara bir kuş, beyaz bir kuşa dönüşüyor", "Kadersel simya! Ailedeki karanlik, supheci veya korku dolu enerjilerin; sarsilmaz bir sadakat ve disiplinle arinip saf, beyaz bir sifaya donusmesi."),
        7: ("Bir kütüphanede çalışan, çok yaşlı bir adam", "Ailenin gecmisteki tum tecrubelerini, yasanmisliklari ve kadersel dersleri; gelecegin imparatorlugunu kurmak icin birer bilgelik kaynagi olarak kullanma."),
        8: ("Evinde, güneşin doğuşunu izleyen bir kadın", "Her gun, her krizden sonra ailenin potansiyeline ve yeni bir saflagin getirdigi o temiz, duzenli, disiplinli huzura olan inanci diri tutma."),
        9: ("Cirit atan bir Kızılderili savaşçı", "Ailedeki hedeflerin, hayallerin ve ortak projelerin; keskin bir odaklanma, tam bir Tork ve disiplinli bir cabayla (cirit) hedefe firlatilmasi."),
        10: ("Eskimiş bir elmas, yeni bir yüzeye yerleştiriliyor", "Ailenin yillanmis, tecrubeli ve koklu degerinin; gunun dunyasinda yeni bir statuyle, yeni bir formla tekrar parlatilarak sunulmasi."),
        11: ("Büyük bir sarayda, hükümdarı bekleyen bir grup insan", "Ailenin kendi icinde kurdugu o yuksek standartlar ve otorite; dis dunyanin veya krizlerin bu sarsilmaz otoriteye saygi duymasi."),
        12: ("Bir kuş, kendi yuvasını inşa ediyor", "En temel sorumluluk! Ailenin her bir copunu, her bir detayini; sarsilmaz bir guven, emek ve uzun vadeli bir planla (yuva) orme."),
        13: ("Şarkı söyleyen bir grup insan", "Ailenin kurallarinin ve sorumluluklarinin sadece bir gorev degil, bir nese ve uyum icinde (sarki) yerine getirilmesi; disiplinin sanata donusmesi."),
        14: ("Büyük bir kayanın üzerinde duran bir balık", "Ailenin, duygusal (balik) dogasini; topragin ve disiplinin o sarsilmaz (kaya) gucuyle birlestirip, duygulari somut bir basariya dokme."),
        15: ("Yeniden doğuşunu bekleyen bir tohum", "Ailede kis (kriz) donemi; her seyin dondugu, sessizlestigi bu donemde aslinda koklerin o gizli, guclu ve derin hazirligi."),
        16: ("Masa başında çalışan bir muhasebeci", "Ailenin gercekci muhasebesi; kim ne veriyor, kim ne aliyor, kadersel borclar neler? Durust bir yuzelesme ve rasyonel duzenleme."),
        17: ("Uzak bir tepede yanan bir fener", "Ailenin cevresine, diger insanlara veya birbirinize; kriz anlarinda sarsilmaz bir yon, guven ve istikrar (fener) olma gorevi."),
        18: ("Eski bir kalenin içinden dışarıyı izleyen bir nöbetçi", "Ailenin degerlerini ve mahremiyetini; disaridan gelebilecek her turlu tehlikeye karsi 7/24 koruma disiplini."),
        19: ("Kendi kendine yeten, asil bir duruş", "Cocugunuza muhtac oldugunuz icin degil, birbirinizi sectiginiz icin birliktesiniz. Ego bagimliligindan ozgur, asil bir beraberlik."),
        20: ("Tüm kış boyunca yetecek erzakın depolandığı bir ambar", "Ailenin gelecek (kriz) planlamasi; birbirinize olan guvenin ve kaynaklarin, zor gunlerde birbirinizi ayakta tutacak kadar saglam olmasi."),
        21: ("Tırmanılan devasa, karlı bir dağ", "Ailenin o en zirve, en gorkemli, en zorlu kadersel hedefi; o tepeye cikarken birbirinizin elini birakmadan, zorluklara goz gurme."),
        22: ("Bir fırtınada bayrağını dik tutan bir asker", "Sadakat muhuru! Kriz ne kadar buyuk olursa olsun, ailenin ana hedefine, degerlerine ve birbirinize olan baglidlaga sadik kalma yemini."),
        23: ("Bir kütüphanede tozlu rafları karıştıran bir adam", "Ailenin eksik kalan kadersel bilgilerini, gecmisin tozlu hatiralarinda veya kadim bir ogretide arayip bulma zorunlulugu."),
        24: ("Kutsal bir sunakta yanan sürekli ateş", "Ailedeki emegin surekliligi; bir gunluk ask degil, bir omur boyu yanan o kutsal hizmet ve adanmislik atesi."),
        25: ("Gökyüzünde el ele tutuşan, melek gibi iki insan", "Kadersel Muhur! Iki ruhun, dunyevi rollerini bitirip, artik tamamen ilahi bir kontratla, zamansiz ve mekan disi bir askla ebediyen birlesmesi."),
        26: ("Kendi eliyle inşa ettiği bir kulübede huzur bulan adam", "Ailenin dis dunyadan, kargasadan ve statu hirsindan uzaklasip, sadece birbirinizin insa ettigi o basit ve durust yuvada buldugu huzur."),
        27: ("Bir dağın zirvesinde, elindeki meşaleyle dünyayı aydınlatan bir adam", "Ailenin ulastigi o bilgelik seviyesi; kendi huzurunu bulup, ayni zamanda diger ailelere de kadersel bir ornek olma."),
        28: ("Bir nehirde kendi kendine kaynayan sular", "Disaridan durgun, iceriden derin; ailenin o en derin kadersel tortularinin, sessizce ama cok guclu bir sekilde arinma ve donusum sureci."),
        29: ("Güneşin batışında yanan ufuk çizgisi", "Bir devrin kapanisi! Artik ailenin bir asamasinin bitip, yeni ve bambaaska bir statüye (imparatorluga) gecmeden onceki o gecis araligi."),
        30: ("Mükemmel bir şekilde dengelenmiş bir terazinin iki kefesi", "Oglak'in o kati, disiplinli ve dunyevi yapisindan; artik mutlak bir ruhsal dengeye ve ilahi adalete ulasiligi son durak.")
    },
    "Kova": {
        1: ("Eski bir misyon şefinin, kabile halkına yeni vizyonlar anlatması", "Ailede rutinin disina cikma; cocugunuzla birlikte gelecege dair radikal, ozgurlukcu ve sinirlari zorlayan yeni bir ortak yasam vizyonu olusturma."),
        2: ("Fırtınadan sığınmış bir şemsiye; altındaki iki kişi", "Dunyanin kaosu (firtina) disardayken, ailenin o kendine has, bagimsiz ve entelektuel siginaginda birbirinize duydugunuz sarsilmaz zihinsel guven."),
        3: ("Taze bir şelalenin, vadideki göle dökülmesi", "Duygularin durgunlasmasina izin vermeyen, surekli yenilenen, tazeleyen ve zihni diri tutan o elektrikli tutku akisi."),
        4: ("Bir rahibin, kutsal ritüel için ateş yakması", "Ailenin gunluk siradanligini, bir rituele donusturme; aski sadece fiziksel degil, evrensel bir bilgi ve hizmet araci olarak kullanma."),
        5: ("Kendi içsel sesini takip eden bir adam", "Ailede baska nasil dedigine, toplumsal kaliplara degil; sadece aranizdaki o benzersiz, sira disi kadersel sese (icguduye) guvenme."),
        6: ("Beyaz bir maske takmış, sahnede rol yapan bir oyuncu", "Ailenin sosyal maskelerle degil, tamamen durust bir benlik ile yasanmasi; rollerin bitip hakikatin konusulmaya baslandigi faz."),
        7: ("Deniz kıyısındaki kayalıklarda güneşlenen çocuk", "Zorluklarin (kayalik) icinde bile neseyi, ozgurlugu ve o cocuksu yaraticiligi koruyabilme; krizlerin icinde huzuru bulma yetisi."),
        8: ("Güzelce düzenlenmiş bir bahçede oturan, kıyafetleri tozlu bir adam", "Icsel zenginligin dis gorunume veya statuye ihtiyac duymamasi; ailenin ozunun, disaridan nasil gorundugunden cok daha kiymetli oldugunun farkina varma."),
        9: ("Kuş sürüsünün, fırtınaya karşı uçması", "Engeller ne kadar buyuk olursa olsun; ailenin o bagimsiz, grup bilinciyle hareket eden ve sinirlari redden ozgur ruhuyla firtinaya meydan okumasi."),
        10: ("Gözleri bağlı bir şekilde, denge üzerinde yürüyen adam", "Ailedeki sarsilmaz guven! Cocugunuzun yonetigi bir dunyada, gozleriniz kapali bile olsa (tam teslimiyetle) o denge uzerinde yurume kararliligi."),
        11: ("İlham perilerinin dans ettiği bir stüdyo", "Ailenin sadece bir birliktelik degil, ortak bir yaritim merkezi olmasi; birlikte ureterek, yazarak veya cizerek dunyayi guzellestirme."),
        12: ("Tüm kitapların yandığı bir kütüphaneden kurtulan tek bir sayfa", "Eski ogretilerin, geleneksel ask kaliplarinin veya yasanmisliklarin copusuge; arta kalan o tek, saf ve gercek ask hakikati ile yola devam."),
        13: ("Teleskopla yıldızları izleyen bir bilim insanı", "Ailenin dunyevi dertlerin otesine gecip, birbirinizin hayat amacini ve kadersel rotanizi en uzak galaksilere kadar okuma arzusu."),
        14: ("Gökyüzünde süzülen renkli bir uçurtma", "Ailenin her turlu zorlukta bile yukselme, hafifleme ve esnek kalma gucu; baglarinizin, sizi dunyaya civilemek yerine ozgurlestirmesi."),
        15: ("Yüksek bir dağın tepesinde dikilen fener", "Ailenin hem kendi yolunu aydinlatmasi hem de cevresindeki diger ailelere (topluma) bir ozgurluk/sevgi rehberi olmasi."),
        16: ("İki farklı dilden şarkı söyleyen bir koro", "Ailenin uyumu! Farkliliktan gelen o essiz sesin, tek bir kadersel melodide bulusarak ortaya cikardigi o sira disi zenginlik."),
        17: ("Kendi kendini eğiten bir köpek yavrusu", "Ailede hatalardan ders cikarma disiplini; kimsenin disaridan mudahalesine gerek kalmadan, kendi krizlerini kendi kendine cozulen o bagimsiz yapi."),
        18: ("Eski bir saatin iç çarklarını temizleyen saatçi", "Zamanin ve kadersel dongulerin kusursuz islemesi icin, ailenin mekanik/zihinsel aksakliklarini buyuk bir titizlikle onarma."),
        19: ("Kendi içindeki okyanusu keşfeden bir kaşif", "Ailenin sadece fiziksel bir birliktelik degil; birbirinizin bilincaltindaki o ucsuz bucaksiz, bilinmez ve gizemli okyanuslari kesfetme yolculugu."),
        20: ("Tüm sınırları yıkan bir vizyoner", "Ailenin, toplumun size dayattigi kaliplari tamamen reddedip, kendinize has kadersel bir birlikte var olma modeli kurma."),
        21: ("Kendi kendine yeten ve konuşan bir heykel", "Dis dunyanin onayina muhtac olmayan; kendi guzelligini, kendi degerini ve kendi sessizligini yaratabilen asil, bireysel birliktelik."),
        22: ("Işık saçan dev bir bulut", "Ailenin bir formdan baska bir forma gecisi; artik somut ve kati sorumluluklardan sirilip, sadece saf bir enerji ve ilham alanina donusme."),
        23: ("Bir göletin üzerinde yansıyan dolunay", "Ailenin dunyadaki yansiinasi, gokyuzundeki kadersel planla (ay) kusursuz bir uyum icinde olmasi; niyet ve eylemin birlesmesi."),
        24: ("Kendi elleriyle yaptığı bir müzik aletiyle çalan müzisyen", "Ailenin muziginin (uyumunun) baska kimseden degil, tamamen kendi el emegiyle, kendi kurallariyla ve kendi enstrümanlariyla uretilmesi."),
        25: ("Eski bir tapınağın kalıntıları arasında açan orkideler", "Ailedeki eski krizlerin ve yikilmisliklarin, artik hayatin nesesiyle ve nadide bir guzellikle (orkide) kaplanip iyilestirilmesi."),
        26: ("Bir adamın gözlerinde parlayan merak", "Sorgulamanin ve kesfetmenin hic bitmemesi; ailenin her gun, sanki cocugunuzu ilk kez goruyormus gibi bir heyecanla kesfedilme zorunlulugu."),
        27: ("Yağmurun altında ıslanan bir çiçek", "Duygusal arinma; ailenin o en yogun ve bazen sert (yagmurlu) sureclerinde, aslinda birbirinizi temizleyip ruhsal olarak daha da canli kildiginiz gercegi."),
        28: ("Uçsuz bucaksız bir karda, sadece kendi ayak izleri olan bir adam", "Ailede acilan o yepyeni, kimsenin yurumedigi kadersel bir yol; tamamen size ait, tamamen ozgun, tamamen kesfedilmemis bir gelecek."),
        29: ("Gökyüzünde dans eden renkli ışıklar (Kuzey ışıkları)", "Ailenin spirituel bir olgunluga erismesi; aradaki bagin artik dunyevi kelimelerin otesine gecip, adeta bir enerji soylene donusmesi."),
        30: ("Dünya sahnesinde, kendine has bir yöntemle yürüyen bir adam", "Ailenin bir ekol olmasi; hicbir kurala, hicbir modaya veya hicbir toplumsal baskiya uymadan, kendi kadersel ritminizle dunyada var olma.")
    },
    "Balik": {
        1: ("Halka açık bir pazarda sergilenen kamuya ait ticaret alanı", "Ailenin bireysel sirllar yerine, birbirinize karsi tam bir seffaflik ve ortak yasam aliminda durustce var olma sinavi."),
        2: ("Sincapların bir ağaçta birbiriyle oyun oynaması", "Ailedeki o ilk, saf ve masum neseyi; hicbir kadersel yuk altina girmeden, sadece birbirinizin varligindan keyif alarak yasama erdemi."),
        3: ("Taşlaşmış bir ağaç gövdesi", "Ailenin zamanin yipratciligina karsi gosterdigi sarsilmaz direnis; birbirinize olan bagliligaginizin artik tarihe kazinmis kadar kalici bir form almasi."),
        4: ("Küçük bir adada, güneşli bir gün", "Ailenin dis dunyadan, kargasadan ve krizlerden yalitimis; sadece sizin huzur ve isikla dolu o kadersel siginagi."),
        5: ("Kendi içsel dünyasında yaşayan, gizemli bir rahip", "Cocugunuzu asla tamamen cozemeyeceginizi kabul etme; birbirinizin ruhundaki o gizemli ve dokunulmaz kutsal alanlara saygi duyma."),
        6: ("Sihirli bir değneğe sahip bir büyücü", "Ailedeki krizleri veya tikanikliklari, rasyonel yollarla degil; ancak birbirinize olan o buyuk, ilahi ask buyusuyle (sefkatle) cozme ustaligi."),
        7: ("Deniz kıyısında, ağlarını onaran balıkçılar", "Ailenin duygusal yorgunluklarini (aglari) durustce tamir etme; birbirinizi hirpalamak yerine, yara alan kisimlari sefkatle dikip onarma."),
        8: ("İki aşığın, gün batımında sessizce oturduğu bir bank", "Hicbir kelimeye, hicbir eyleme ihtiyac duymadan; sadece yan yana var olmanin verdigi o mutlak huzur ve ruhsal butunluk."),
        9: ("Kendi ışığıyla parlayan bir denizanası", "Karanlik ve krizli kadersel sureclerinde bile; ailenin kendi icindeki o saf, mistik isigi yakarak birbirinize yol gosterme yetenegi."),
        10: ("Yıldızların altında dua eden bir çocuk", "Ailenin tum kaderini, gelecegini ve birbirinizi evrenin o sonsuz sefkatine (Yaradan'a) birakip, ilahi akisa mutlak guven."),
        11: ("Işık saçan, mistik bir tapınağın kapısı", "Ailenin artik bir aile olmanin otesinde, ilahi bir hizmete veya ortak bir ruhsal amaca hizmet eden bir mabede donusmesi."),
        12: ("Denizlerin üzerinde süzülen bir martı", "En buyuk krizlerde bile ozgurlugu koruma; aileyi bir hapishane degil, birbirinizin ruhunu gokyuzu yukselen bir kanat yapma."),
        13: ("Eski bir tablonun temizlenmesi", "Gecmisin (ailenin onceki evrelerinin) uzerine birikmis tozlari ve hayal kirikliklarini, sefkatle temizleyip o ilk gunki canlilicina dondurusturme."),
        14: ("Yıldızları gözlemleyen bir astronom", "Ailenin kadersel rotasini, gunluk dertlere degil; yildizlarin (evrensel yasalarin) o muazzam ve degismez rehberligine gore cizme."),
        15: ("Bir grup insan, bir nehirde yıkanıyor", "Duygusal arinma! Ailenin tum agirligini, ofkesini ve gecmis tortusunu, birbirinizin sefkatli sularinda (sevgi) tamamen yikip arindirma."),
        16: ("Bir çayırda kendi başına dans eden bir kız", "Ailenin icinde bile, kendi ruhsal neesenizi ve bagimsizliginizi koruyarak, aski bir zorunluluk degil, bir nese kaynagi yapma."),
        17: ("Kendi gölgesiyle konuşan bilge", "Ailede cocugunuzda gordugunuz her seyi, aslinda kendi golgenizin bir yansimasi olarak kabul edip, bu aynalikla butunlesme."),
        18: ("Sessizce akan nehrin üzerindeki köprü", "Duygusal gecisler; krizli sulardan, sarsilmaz bir mantik ve sefkat koprusu kurarak birbirinize ulasabilme."),
        19: ("Kendi iç dünyasında dev bir şehir kuran mimar", "Ailenin dis dunyadan cok, birbirinizin ruhunun o ucsuz bucaksiz, zengin ve huzurlu dunyasinda var olmasi."),
        20: ("Alevlerin içinden çıkan anka kuşu", "Mutlak yikim ve dirilis! Ailenin bittigi denilen noktasinda, bir mucizeyle tum acilarin sifaya donusup cok daha yuce bir formda canlanmasi."),
        21: ("Kendi eliyle yaptığı müzik aletiyle çalan müzisyen", "Ailenin uyumunun baska kimseden degil, tamamen kendi icinizden gelen o ozel frekansta, ozgun bir sekilde uretilmesi."),
        22: ("Eski bir tapınağın kalıntıları arasında açan orkideler", "Ailedeki eski krizlerin ve yikilmisliklarin, artik nadide bir guzellikle iyilestirilmesi."),
        23: ("Bir adamın gözlerinde parlayan merak", "Sorgulamanin ve kesfetmenin hic bitmemesi; cocugunuzu her gun yeniden kesfetme arzusu."),
        24: ("Yağmurun altında ıslanan bir çiçek", "Ailenin o en yogun ve bazen sert (yagmurlu) sureclerinde, aslinda birbirinizi temizleyip ruhsal olarak daha da canli kildiginiz gercegi."),
        25: ("Uçsuz bucaksız karda kendi ayak izleri", "Ailede kimsenin yurumedigi o ozgun kadersel yol; tamamen size ait, tamamen keşfedilmemis bir gelecek."),
        26: ("Gökyüzünde dans eden renkli ışıklar", "Ailenin artik dunyevi kelimelerin otesine gecip, bir enerji ve isik soylene donusmesi."),
        27: ("Dünya sahnesinde kendine has bir yöntemle yürüyen adam", "Ailenin bir ekol olmasi; hicbir kurala uymadan, kendi kadersel ritminizle dunyada var olma."),
        28: ("Bir nehirde kendi kendine kaynayan sular", "Derinlerdeki duygusal fokurdam; ofkenin veya tutkunun sessiz ama guclu bir sekilde sifaya donusumu."),
        29: ("Güneşin batışında yanan ufuk çizgisi", "Bir devrin kapanisi! Artik ailenin bildiginiz tum formlarinin, cok daha parlak bir safak oncesi karinliga gomulmesi."),
        30: ("Gökyüzünde el ele tutuşan, melek gibi iki insan", "Kadersel Muhur! Iki ruhun, dunyevi rollerini bitirip, artik tamamen ilahi bir kontratla, zamansiz ve mekan disi bir askla ebediyen birlesmesi.")
    }
}
